/* Voltio · cada concepto tiene varias formas de explicarse.
   Si fallas un ejercicio, aparece la siguiente explicación y una pregunta para comprobarla. */
const mcq = (q, o, e, x = {}) => ({ t: 'mc', q, o, a: 0, e, ...x });
const CONCEPTS = {
  /* --- Curso base ampliado --- */
  engnum: { name: 'Notación de ingeniería', alts: [
    { title: 'Saltos de tres', text: 'La notación de ingeniería es la científica con una condición: el exponente siempre es múltiplo de 3. Así cada exponente tiene su prefijo: 10⁻⁶ es µ y 10³ es k.\n0,000 047 F = 47 × 10⁻⁶ F = <b>47 µF</b>.', q: mcq('¿Cómo se escribe 0,0022 A con prefijo?', ['2,2 mA', '2,2 µA', '22 mA', '0,22 mA'], '0,0022 = 2,2 × 10⁻³ → mili.') },
    { title: 'Cifras que significan algo', text: 'Las cifras significativas dicen cuánto te fías de un número. Si la resistencia es del 5 %, escribir 4,7123 kΩ es presumir de una precisión que no tienes. Regla práctica: da el resultado con tantas cifras como el dato menos preciso, normalmente 2 o 3.', q: mcq('Calculas 9 V / 470 Ω = 0,019148936 A. ¿Cómo lo escribes?', ['19 mA', '19,148936 mA', '0,019148936 A', '19 A'], 'Dos o tres cifras bastan: los datos no dan para más.') }
  ] },
  esafety: { name: 'Seguridad eléctrica', alts: [
    { title: 'Lo que hace daño es la corriente', text: 'El peligro lo marca la <b>corriente que atraviesa tu cuerpo</b>, y esa corriente la pone la tensión venciendo la resistencia de tu piel. Con la piel seca, 9 V apenas mueven unos microamperios. Con los 230 V de la red pueden pasar decenas de miliamperios por el pecho: suficiente para parar el corazón.', q: mcq('¿Por qué puedes tocar los dos polos de una pila de 9 V pero nunca los de un enchufe?', ['Con 9 V tu piel deja pasar una corriente mínima; con 230 V, una peligrosa', 'Porque la continua nunca hace daño', 'Porque el enchufe guarda más amperios', 'Porque la pila lleva fusible'], 'La tensión empuja, tu resistencia limita y la corriente hace el daño.') },
    { title: 'Energía guardada', text: 'No solo la red: una batería de litio en cortocircuito suelta decenas de amperios y puede arder, y un condensador grande de una fuente o de un flash puede seguir cargado con cientos de voltios después de desenchufar. Antes de tocar: desconecta, espera, mide y descarga con una resistencia.', q: mcq('Desenchufas una fuente de red para repararla. ¿Qué haces antes de meter la mano?', ['Medir y descargar los condensadores grandes con una resistencia', 'Nada: ya está desenchufada', 'Cortocircuitarlos con un destornillador', 'Esperar dos segundos'], 'Pueden guardar tensión peligrosa durante mucho rato. Se descargan de forma controlada.') }
  ] },
  network: { name: 'Thévenin, Norton y superposición', alts: [
    { title: 'Una caja negra', text: 'Vista desde dos bornes, cualquier red de pilas y resistencias se comporta como una pila con una resistencia en serie (Thévenin) o como una fuente de corriente con una resistencia en paralelo (Norton). Dos medidas la resumen: la tensión en vacío y la corriente en cortocircuito. <b>Rth = Vvacío / Icorto</b>.', q: mcq('Una salida da 6 V en vacío y 30 mA en cortocircuito. ¿Rth?', ['200 Ω', '180 Ω', '5 Ω', '0,2 Ω'], '6 / 0,03 = 200 Ω.') },
    { title: 'De una en una', text: 'Superposición: con varias fuentes, calcula el efecto de cada una con las demás “apagadas” (pila → cable; fuente de corriente → hueco abierto) y suma los resultados. Funciona porque las resistencias son lineales.', q: mcq('Al aplicar superposición, ¿qué haces con una pila que no estás analizando?', ['La sustituyes por un cable', 'La quitas y dejas el hueco abierto', 'La duplicas', 'La das la vuelta'], 'Una pila apagada da 0 V: es un cable.') }
  ] },
  scope: { name: 'Osciloscopio', alts: [
    { title: 'Una foto que necesita disparador', text: 'El osciloscopio dibuja la señal una y otra vez. Para que la imagen quede quieta, cada barrido debe empezar en el mismo punto de la onda: eso es el <b>disparo</b>. Eliges un nivel y un flanco; si el nivel queda fuera de la señal, no dispara y la imagen corre.', tune: { viz: 'scopeTrigger', params: { lvl: { label: 'Nivel de disparo', val: 3, min: -3, max: 3, step: 0.1, unit: 'V', dec: 1 }, tdiv: { label: 'Tiempo/div', val: 0.5, list: [0.05, 0.1, 0.2, 0.5, 1, 2], unit: 'ms', dec: 2 } } }, q: mcq('Una senoide de 2 V de pico corre sin parar por la pantalla. El nivel de disparo está en 3 V. ¿Qué haces?', ['Bajar el nivel dentro de la señal, por ejemplo a 0 V', 'Subir la escala de tiempo', 'Cambiar la sonda', 'Subir el nivel a 5 V'], 'Si la señal nunca cruza el nivel, no hay disparo.') },
    { title: 'La sonda también cuenta', text: 'Una sonda ×10 divide la señal entre 10 y carga mucho menos el circuito (unos 10 MΩ en vez de 1 MΩ, y menos capacidad). El osciloscopio tiene que saberlo: con el canal en ×1 y la sonda en ×10, todo marcará diez veces menos.', q: mcq('Esperas 5 V y el osciloscopio marca 0,5 V. Usas una sonda ×10. ¿Qué sospechas primero?', ['Que el canal está configurado como ×1', 'Que la señal está rota', 'Que el disparo está mal', 'Que el acoplo está en DC'], 'Revisa el factor de sonda del canal.') }
  ] },
  inductor: { name: 'Bobina', alts: [
    { title: 'Un volante de inercia', text: 'Una bobina es la inercia de la electricidad: cuesta arrancar la corriente y cuesta pararla. Su tensión depende de lo rápido que cambia la corriente: <b>V = L · ΔI / Δt</b>. Corriente constante → 0 V; cambio brusco → pico enorme.', tune: { viz: 'rlCurrent', params: { L: { label: 'L', val: 100, list: [1, 10, 47, 100, 470, 1000], unit: 'mH', dec: 0 }, R: { label: 'R', val: 100, list: [10, 22, 47, 100, 220, 470, 1000], fmt: 'R' }, V: { val: 5, fixed: true } } }, q: mcq('Por una bobina ideal pasa una corriente continua constante. ¿Qué tensión cae en ella?', ['Cero', 'Muchísima', 'La de la pila', 'Depende del color'], 'Sin cambio de corriente no hay tensión inducida.') },
    { title: 'Con números: τ = L / R', text: 'Al conectar una bobina y una resistencia a una pila, la corriente sube como la tensión de un condensador: 63 % tras τ y casi toda tras 5τ. Pero aquí <b>τ = L / R</b>: más resistencia, más rápido. Corriente final: I = V / R.', q: mcq('100 mH con 100 Ω. ¿τ?', ['1 ms', '10 s', '10 ms', '0,1 ms'], '0,1 / 100 = 0,001 s.') }
  ] },
  impedance: { name: 'Impedancia', alts: [
    { title: 'El triángulo', text: 'En alterna, una resistencia y una reactancia en serie no se suman sin más: sus tensiones están desfasadas 90°. Se combinan como los catetos de un triángulo rectángulo: <b>Z = √(R² + X²)</b>. El ángulo φ es el desfase entre tensión y corriente.', tune: { viz: 'zTriangle', params: { R: { label: 'R', val: 300, min: 0, max: 1000, step: 10, unit: 'Ω', dec: 0 }, X: { label: 'X (+ bobina, − condensador)', val: 400, min: -1000, max: 1000, step: 10, unit: 'Ω', dec: 0 } } }, q: mcq('R = 30 Ω y X = 40 Ω en serie. ¿Z?', ['50 Ω', '70 Ω', '10 Ω', '1200 Ω'], '√(900 + 1600) = 50.') },
    { title: 'Flechas que giran', text: 'Un fasor es una flecha que gira a la frecuencia de la señal; la senoide que ves en el osciloscopio es su sombra. En la bobina, la tensión va 90° por delante de la corriente; en el condensador, 90° por detrás. Sumar fasores es sumar flechas, no números.', q: mcq('En un condensador, la tensión respecto a la corriente va…', ['90° retrasada', '90° adelantada', 'En fase', 'A 180°'], 'Primero entra la corriente y después sube la tensión.') }
  ] },
  resonance: { name: 'Resonancia', alts: [
    { title: 'El columpio', text: 'Un columpio tiene su ritmo propio: si empujas justo a ese ritmo, sube mucho con poco esfuerzo. Un circuito LC también: la energía pasa del condensador a la bobina y vuelve, a <b>f₀ = 1 / (2π√(LC))</b>. Así se sintoniza una emisora.', tune: { viz: 'lcResonance', params: { L: { label: 'L', val: 220, list: [10, 22, 47, 100, 220, 470, 1000], unit: 'µH', dec: 0 }, C: { label: 'C (variable)', val: 120, min: 10, max: 1000, step: 5, unit: 'pF', dec: 0 }, R: { label: 'R', val: 47, list: [10, 22, 47, 100, 220, 470, 1000], fmt: 'R' } } }, q: mcq('Aumentas el condensador de un circuito LC. La frecuencia de resonancia…', ['Baja', 'Sube', 'No cambia', 'Se duplica'], 'Más L o más C: el vaivén es más lento.') },
    { title: 'Donde las reactancias se anulan', text: 'XL sube con la frecuencia y XC baja. A una frecuencia son iguales y, en serie, se cancelan: solo queda R y la corriente es máxima. <b>Q = XL / R</b> dice lo afilado del pico: ancho de banda = f₀ / Q.', q: mcq('En resonancia serie, la impedancia total es…', ['Solo R', 'Infinita', 'XL + XC', 'XL · XC'], 'XL y XC se cancelan.') }
  ] },
  thermal: { name: 'Calor y resistencia térmica', alts: [
    { title: 'Ohm, pero con calor', text: 'El calor fluye como la corriente: la potencia hace de corriente (W), la diferencia de temperatura de tensión (°C) y la resistencia térmica (°C/W) frena el paso. <b>ΔT = P · Rθ</b>. Las resistencias en serie (unión → cápsula → disipador → aire) se suman.', q: mcq('Rθ total de 20 °C/W y 3 W. ¿Cuánto sube la temperatura sobre la del ambiente?', ['60 °C', '6,7 °C', '23 °C', '0,15 °C'], '3 × 20 = 60 °C.') },
    { title: 'Para qué un disipador', text: 'Un TO-220 al aire tiene unos 50–65 °C/W según el fabricante: con 2 W subiría más de 100 °C. Un disipador ofrece al calor un camino más fácil (pocos °C/W). El límite lo pone la temperatura máxima de la unión, normalmente 125–150 °C.', q: mcq('¿Qué hace un disipador?', ['Baja la resistencia térmica hasta el aire', 'Reduce la potencia que disipa el chip', 'Sube la tensión de salida', 'Aísla del calor'], 'La potencia es la misma; sale con menos subida de temperatura.') }
  ] },
  mosfet: { name: 'MOSFET', alts: [
    { title: 'Umbral no es encendido', text: 'Con Vgs(th) el MOSFET apenas <b>empieza</b> a conducir (microamperios o pocos miliamperios). Para conducir de verdad necesita la tensión a la que la hoja de datos garantiza Rds(on): 10 V, 4,5 V o 2,5 V según el modelo.', q: mcq('Hoja de datos: Vgs(th) = 2 V y Rds(on) garantizada solo a 10 V. ¿Basta 3,3 V para 5 A?', ['No es seguro: no hay Rds(on) garantizada a esa tensión', 'Sí, supera el umbral', 'No, necesita exactamente 2 V', 'Sí, la puerta no importa'], 'El umbral es donde empieza a conducir, no donde conduce bien.') },
    { title: 'Un condensador que hay que llenar', text: 'La puerta es un condensador: para conmutar hay que meter y sacar su carga (Qg, en nC) deprisa. <b>I = Q / t</b>. Un pin débil tarda y el MOSFET pasa tiempo a medio conducir, calentándose. Un driver da amperios durante nanosegundos.', q: mcq('Un MOSFET se calienta con PWM rápido aunque su Rds(on) es bajísima. ¿Qué sospechas?', ['Que la puerta se carga despacio y pasa mucho tiempo a medias', 'Que Rds(on) es demasiado baja', 'Que la frecuencia es demasiado baja', 'Que la puerta consume mucha corriente en continua'], 'Pérdidas de conmutación: hace falta un driver.') }
  ] },
  hyst: { name: 'Histéresis', alts: [
    { title: 'Un termostato', text: 'Un termostato no enciende a 20,0 °C y apaga a 20,0 °C: estaría conmutando sin parar. Enciende a 19 °C y apaga a 21 °C. Un Schmitt trigger hace lo mismo con tensiones: un umbral para subir y otro para bajar.', tune: { viz: 'schmittHyst', params: { R1: { label: 'R1', val: 1000, list: [1000, 2200, 4700, 10000, 22000, 47000], fmt: 'R' }, R2: { label: 'R2', val: 100000, list: [10000, 22000, 47000, 100000, 220000], fmt: 'R' } } }, q: mcq('¿Para qué sirve la histéresis?', ['Para que el ruido cerca del umbral no haga oscilar la salida', 'Para amplificar más', 'Para ahorrar energía', 'Para invertir la señal'], 'La salida solo cambia si la entrada cruza con claridad.') },
    { title: 'Con números', text: 'En el Schmitt no inversor con Vref = Vcc / 2, la salida empuja a IN+ a través de R2: la histéresis vale <b>Vcc · R1 / R2</b>, centrada en Vref. Más R1 o menos R2, más separados los umbrales.', q: mcq('Vcc = 5 V, R1 = 10 kΩ y R2 = 100 kΩ. ¿Histéresis?', ['0,5 V', '5 V', '0,05 V', '50 V'], '5 × 10 / 100.') }
  ] },
  quant: { name: 'Cuantización', alts: [
    { title: 'Una escalera', text: 'Un ADC o un DAC trabajan en escalones: con n bits hay 2ⁿ escalones entre 0 y Vref. Un escalón (1 LSB) = Vref / 2ⁿ. Todo lo que cae dentro del mismo escalón da el mismo número: es el error de cuantización, de hasta medio escalón.', q: mcq('10 bits y 5 V de referencia. ¿Cuánto vale un escalón?', ['Unos 4,9 mV', '0,5 V', '10 mV', '1 mV'], '5 / 1024 ≈ 4,88 mV.') },
    { title: 'Más bits no es más exactitud', text: 'Los bits dan resolución (escalones finos), no exactitud: si la referencia se desvía un 1 %, todas las lecturas se desvían un 1 % aunque tengas 16 bits. Y el ruido puede comerse los últimos bits.', q: mcq('ADC de 12 bits con una referencia que puede variar un 2 %. Tus lecturas…', ['Pueden estar un 2 % desviadas aunque parezcan muy finas', 'Son exactas al 0,02 %', 'Son siempre correctas', 'Solo fallan con 8 bits'], 'Resolución y exactitud son cosas distintas.') }
  ] },
  smps: { name: 'Fuentes conmutadas', alts: [
    { title: 'Trocear y alisar', text: 'Un buck trocea la entrada con un transistor y la alisa con una bobina y un condensador. La media de la tensión troceada es Vent · D, así que <b>Vsal ≈ D · Vent</b>. La bobina mantiene la corriente mientras el transistor está abierto, a través de un diodo o de otro transistor.', q: mcq('Buck ideal de 12 V a 3 V. ¿Ciclo de trabajo?', ['25 %', '4 %', '75 %', '36 %'], '3 / 12.') },
    { title: 'El rizado se elige', text: 'La corriente de la bobina sube y baja en cada ciclo: <b>ΔI = (Vent − Vsal) · D / (L · f)</b>. Se suele elegir un ΔI del 20 al 40 % de la corriente de salida. Más frecuencia o más inductancia, menos rizado; y la bobina debe aguantar el pico sin saturarse.', q: mcq('Doblas la frecuencia de conmutación de un buck. El rizado de corriente…', ['Se reduce a la mitad', 'Se duplica', 'No cambia', 'Se cuadruplica'], 'ΔI es inversamente proporcional a f.') }
  ] },
  libat: { name: 'Baterías de litio', alts: [
    { title: 'Corriente y luego tensión', text: 'Una celda de litio se carga en dos fases: <b>corriente constante</b> (CC) hasta llegar a 4,2 V y luego <b>tensión constante</b> (CV) a 4,2 V mientras la corriente va bajando. Se termina cuando la corriente cae a una fracción (≈ 1/10). Pasar de 4,2 V la degrada y puede ser peligroso.', q: mcq('Durante la fase CV, la corriente de carga…', ['Va bajando', 'Sube', 'Es constante', 'Cambia de sentido'], 'La tensión está fija y la celda cada vez admite menos.') },
    { title: 'Cargar no es proteger', text: 'El cargador (como el TP4056) controla la carga. La protección (o BMS) corta si la tensión baja demasiado, si sube demasiado o si hay sobrecorriente o cortocircuito. Son cosas distintas: el cargador no te salva de vaciar la celda del todo.', q: mcq('Una celda sin protección alimenta un circuito hasta quedarse en 2 V. ¿Qué pasa?', ['Se daña por descarga profunda y recargarla puede ser peligroso', 'Nada: se recarga igual', 'Gana capacidad', 'Vuelve sola a 4,2 V'], 'Por eso se usa protección contra descarga profunda.') }
  ] },
  charge: { name: 'Carga eléctrica', alts: [
    { title: 'Como canicas en un tubo', text: 'Imagina un tubo lleno de canicas. Si empujas una por un extremo, sale otra casi al instante por el otro, aunque cada canica se mueva despacio. En un cable pasa igual: los electrones ya están ahí; la pila solo empuja la fila.', q: mcq('¿Por qué la luz se enciende al instante aunque los electrones se muevan despacio?', ['Porque el cable ya está lleno de electrones y el empuje se transmite por toda la fila', 'Porque los electrones viajan a la velocidad de la luz', 'Porque la pila lanza electrones muy rápidos', 'Porque la bombilla tiene electrones guardados'], 'Lo que viaja rápido es el empuje, no cada electrón.') },
    { title: 'Con números', text: 'La carga se mide en culombios (C). Un culombio son unos 6 trillones de electrones (6,24 × 10¹⁸). Un amperio es un culombio pasando cada segundo: <b>I = Q / t</b>.', q: mcq('Pasan 2 culombios por un cable en 1 segundo. ¿Corriente?', ['2 A', '0,5 A', '1 A', '2 V'], 'I = Q / t = 2 / 1 = 2 A.') }
  ] },
  current: { name: 'Corriente', alts: [
    { title: 'El caudal', text: 'La corriente es cuánta carga pasa por un punto cada segundo, como los litros por segundo de un río. No se “gasta”: la misma corriente que sale de la pila vuelve a ella.', q: mcq('En un circuito con una pila y una bombilla, la corriente que vuelve a la pila es…', ['La misma que sale', 'Menor, porque la bombilla la gasta', 'Cero', 'El doble'], 'La bombilla gasta energía, no corriente.') },
    { title: 'Contando coches', text: 'Si te pones en un puente de una autopista y cuentas coches por minuto, eso es “corriente de coches”. Da igual en qué punto de la carretera sin desvíos te pongas: pasan los mismos.', q: mcq('En un circuito en serie, ¿dónde es mayor la corriente?', ['Es igual en todos los puntos', 'Justo al salir de la pila', 'Antes de la resistencia', 'Después del LED'], 'Sin desvíos, por todos los puntos pasa lo mismo.') },
    { title: 'Sentido convencional', text: 'Por convenio, la corriente se dibuja saliendo del + y entrando por el −. Los electrones van al revés, pero eso no cambia ningún cálculo: todos los esquemas usan el sentido convencional.', q: mcq('En un esquema, la corriente se dibuja…', ['Del + al − por fuera de la pila', 'Del − al + por fuera de la pila', 'En ambos sentidos a la vez', 'Solo dentro de la pila'], 'Es el sentido convencional.') }
  ] },
  voltage: { name: 'Tensión', alts: [
    { title: 'Diferencia de altura', text: 'La tensión es como la diferencia de altura entre dos depósitos de agua: cuanta más diferencia, más empuje. Por eso siempre se mide <b>entre dos puntos</b>. Decir “este punto tiene 5 V” significa “5 V respecto a masa”.', q: mcq('¿Por qué un pájaro posado en un cable de alta tensión no se electrocuta?', ['Porque sus dos patas están al mismo potencial: no hay diferencia de tensión', 'Porque las plumas aíslan', 'Porque la corriente va demasiado rápido', 'Porque los pájaros no conducen'], 'Sin diferencia de tensión no hay empuje ni corriente.') },
    { title: 'Energía por carga', text: 'Un voltio significa que cada culombio que atraviesa la pila recibe un julio de energía. Una pila de 9 V da a cada carga 9 veces más energía que una de 1 V.', q: mcq('Una pila de 9 V y otra de 1,5 V. ¿Qué cambia?', ['La energía que recibe cada carga', 'El número de electrones del cable', 'La velocidad de la luz', 'El color de la corriente'], 'Tensión = energía por unidad de carga.') },
    { title: 'Masa como referencia', text: 'Igual que medimos la altura de una montaña desde el nivel del mar, en electrónica elegimos un punto de referencia llamado <b>masa</b> (GND) y le damos 0 V. Todas las demás tensiones se miden respecto a él.', q: mcq('Si un punto está a 5 V y otro a 2 V respecto a masa, ¿qué tensión hay entre ellos?', ['3 V', '7 V', '5 V', '2 V'], 'Diferencia: 5 − 2 = 3 V.') }
  ] },
  resistance: { name: 'Resistencia', alts: [
    { title: 'Tubería estrecha', text: 'Una resistencia es un estrechamiento en la tubería: con el mismo empuje, pasa menos agua. Los cables son tuberías anchas (casi sin resistencia) y la resistencia es el cuello de botella que controla el caudal.', q: mcq('Si sustituyes una resistencia por otra mayor, con la misma pila…', ['Pasa menos corriente', 'Pasa más corriente', 'Aumenta la tensión de la pila', 'Nada cambia'], 'Más estrechez, menos caudal.') },
    { title: 'Qué la determina', text: 'La resistencia de un hilo depende del material, de su longitud y de su grosor: <b>R = ρ · L / S</b>. El doble de largo, el doble de resistencia. El doble de sección, la mitad.', q: mcq('Un cable el doble de largo y del mismo grosor tiene…', ['El doble de resistencia', 'La mitad de resistencia', 'La misma resistencia', 'Cuatro veces menos'], 'R es proporcional a la longitud.') }
  ] },
  circuit: { name: 'Circuito cerrado', alts: [
    { title: 'Un camino en bucle', text: 'La corriente necesita un camino de ida y vuelta a la pila. Si se corta en cualquier punto (circuito abierto), se para en todas partes. Si encuentra un atajo sin resistencia (cortocircuito), circula muchísima corriente y algo se calienta.', q: mcq('Un cable une directamente el + y el − de una pila. ¿Qué pasa?', ['Cortocircuito: mucha corriente y calor', 'No pasa nada, no hay componentes', 'Circuito abierto', 'La pila se recarga'], 'Sin resistencia que limite, la corriente se dispara.') },
    { title: 'El interruptor', text: 'Un interruptor no “manda” la electricidad: simplemente abre o cierra el camino. Abierto = puente levantado; cerrado = puente bajado.', q: mcq('Un interruptor abierto en serie con un LED…', ['Corta el camino y el LED se apaga', 'Hace que el LED brille más', 'Provoca un cortocircuito', 'Solo afecta a la mitad del circuito'], 'En serie, cualquier corte apaga todo.') }
  ] },
  ohm: { name: 'Ley de Ohm', alts: [
    { title: 'El triángulo', text: 'Dibuja un triángulo con V arriba e I y R abajo. Tapa la magnitud que buscas: lo que queda te dice la operación. Tapando V queda I × R; tapando I queda V / R; tapando R queda V / I.', svg: '<svg viewBox="0 0 200 150" class="viz"><path d="M100 15L185 135H15Z" fill="none" stroke="currentColor" stroke-width="3"/><path d="M45 85H155M100 85V135" stroke="currentColor" stroke-width="3"/><text x="100" y="72" text-anchor="middle" font-size="30" font-weight="800" fill="currentColor">V</text><text x="70" y="122" text-anchor="middle" font-size="26" font-weight="800" fill="currentColor">I</text><text x="130" y="122" text-anchor="middle" font-size="26" font-weight="800" fill="currentColor">R</text></svg>', q: mcq('Tapando la R en el triángulo, ¿qué fórmula queda?', ['R = V / I', 'R = V × I', 'R = I / V', 'R = V − I'], 'V arriba, I abajo: V entre I.') },
    { title: 'Proporciones', text: 'Con la resistencia fija, tensión y corriente van juntas: doble de tensión, doble de corriente. Con la tensión fija, resistencia y corriente van al revés: doble de resistencia, mitad de corriente.', tune: { viz: 'ohm', params: { V: { label: 'Pila', val: 4, min: 1, max: 12, step: 1, unit: 'V', dec: 0 }, R: { label: 'Resistencia', val: 1000, fmt: 'R', min: 100, max: 10000 } } }, q: mcq('Con 1 kΩ circulan 3 mA. ¿Cuánto circula con 2 kΩ y la misma pila?', ['1,5 mA', '6 mA', '3 mA', '0,3 mA'], 'Doble resistencia, mitad de corriente.') },
    { title: 'Paso a paso con unidades', text: 'El error más común es mezclar prefijos. Receta: 1) pasa todo a V, A y Ω; 2) aplica la fórmula; 3) vuelve al prefijo cómodo. Ejemplo: 9 V entre 4,7 kΩ → 9 / 4700 = 0,0019 A = 1,9 mA.', q: mcq('5 V entre 2,2 kΩ. ¿Corriente?', ['2,27 mA', '2,27 A', '0,44 mA', '11 mA'], '5 / 2200 = 0,00227 A = 2,27 mA.') }
  ] },
  power: { name: 'Potencia', alts: [
    { title: 'Energía por segundo', text: 'La potencia es la rapidez con la que se transforma la energía. Un vatio es un julio cada segundo. Una resistencia convierte toda su potencia en calor: si es demasiada, se quema.', q: mcq('¿Qué indica la potencia nominal de una resistencia (por ejemplo ¼ W)?', ['El calor máximo que puede disipar sin dañarse', 'Su valor en ohmios', 'La tensión máxima de la pila', 'Cuánta corriente produce'], 'Por eso se elige con margen.') },
    { title: 'Tres caminos', text: 'P = V × I es la base. Si te dan I y R, sustituye V = I·R → P = I²·R. Si te dan V y R, sustituye I = V/R → P = V²/R. Elige la que use los datos que tienes.', q: mcq('Conoces la corriente y la resistencia. ¿Qué fórmula usas?', ['P = I² × R', 'P = V² / R', 'P = V / I', 'P = R / I'], 'La que solo necesita I y R.') }
  ] },
  series: { name: 'Serie', alts: [
    { title: 'Obstáculos en fila', text: 'Varias resistencias en serie son como varios estrechamientos seguidos en una tubería: el agua tiene que superarlos todos, así que se suman. Y como no hay desvíos, la corriente es la misma en todas.', q: mcq('Tres resistencias en serie de 100 Ω. ¿Total?', ['300 Ω', '33 Ω', '100 Ω', '1000 Ω'], 'Se suman.') },
    { title: 'Reparto de tensión', text: 'En serie, la tensión de la pila se reparte en proporción a cada resistencia: la más grande se queda con más voltios. Por eso un divisor de tensión funciona.', q: mcq('1 kΩ y 2 kΩ en serie con 9 V. ¿Cuál tiene más tensión?', ['La de 2 kΩ (6 V)', 'La de 1 kΩ (6 V)', 'Las dos igual', 'Ninguna'], 'La más grande se queda con la mayor parte.') }
  ] },
  parallel: { name: 'Paralelo', alts: [
    { title: 'Más carriles', text: 'Poner resistencias en paralelo es abrir más carriles en una autopista: el tráfico total fluye mejor, así que la resistencia total baja. Siempre queda por debajo de la más pequeña.', q: mcq('100 Ω en paralelo con 1 MΩ. ¿El total es…?', ['Un poco menos de 100 Ω', 'Más de 1 MΩ', 'Unos 500 kΩ', '1,0001 MΩ'], 'Por debajo de la menor.') },
    { title: 'Con conductancias', text: 'La conductancia (G = 1/R) mide lo fácil que es pasar. En paralelo, las facilidades se suman: G = G1 + G2. Luego vuelves: R = 1/G. Con dos resistencias queda el truco: R = (R1·R2) / (R1+R2).', q: mcq('200 Ω y 200 Ω en paralelo', ['100 Ω', '400 Ω', '200 Ω', '50 Ω'], 'Dos iguales: la mitad.') },
    { title: 'Misma tensión', text: 'Todo lo que está en paralelo comparte los mismos dos puntos, así que tiene la misma tensión. Por eso los enchufes de casa están en paralelo: todos reciben lo mismo.', q: mcq('Dos LEDs en paralelo conectados directamente a 3 V. ¿Qué tensión tiene cada uno?', ['3 V', '1,5 V', '6 V', 'Depende de la corriente'], 'Paralelo = misma tensión.') }
  ] },
  divider: { name: 'Divisor de tensión', alts: [
    { title: 'Una escalera', text: 'Imagina que la pila es una escalera de 9 escalones y las resistencias reparten los escalones según su tamaño. Con 2 kΩ arriba y 1 kΩ abajo, la de abajo se lleva 1 de cada 3 escalones: 3 V.', q: mcq('12 V, R1 = 3 kΩ arriba y R2 = 1 kΩ abajo. ¿Vsal?', ['3 V', '9 V', '4 V', '6 V'], 'R2 es 1/4 del total: 12/4 = 3 V.') },
    { title: 'Por qué no alimenta cosas', text: 'Si conectas una carga a la salida, queda en paralelo con R2 y la resistencia de abajo baja: la tensión cae. Un divisor sirve para dar una referencia o leer un sensor, no para alimentar.', q: mcq('Un divisor da 5 V en vacío. Le conectas un motor. ¿Qué pasa?', ['La tensión cae mucho', 'Sigue dando 5 V', 'Sube a 10 V', 'El motor gira al doble'], 'La carga cambia el divisor.') }
  ] },
  kcl: { name: 'Ley de nudos', alts: [
    { title: 'Un cruce de tuberías', text: 'En un cruce de tuberías, el agua que entra tiene que salir: no se acumula ni desaparece. Con la corriente pasa lo mismo en cualquier nudo.', q: mcq('Entran 50 mA en un nudo y salen 20 mA por una rama y 20 mA por otra. ¿Y por la tercera?', ['10 mA', '50 mA', '90 mA', '0 mA'], '50 − 20 − 20 = 10 mA.') },
    { title: 'Con signos', text: 'Cuenta como positivas las corrientes que entran y negativas las que salen: la suma siempre es cero. Si una incógnita sale negativa, es que va en sentido contrario al que supusiste.', q: mcq('Calculas una corriente de rama y te sale −5 mA. ¿Qué significa?', ['Que circula 5 mA en sentido contrario al supuesto', 'Que el circuito está mal', 'Que la corriente no existe', 'Que hay 5 mA de pérdidas'], 'El signo solo indica el sentido.') }
  ] },
  kvl: { name: 'Ley de mallas', alts: [
    { title: 'Subir y bajar una montaña', text: 'Si sales de casa, subes y bajas colinas y vuelves a casa, el desnivel total es cero. En una malla: la pila “sube” la tensión y cada componente la “baja”; al cerrar la vuelta, todo se compensa.', q: mcq('Pila de 5 V, una resistencia y un LED de 2 V. ¿Cuánto cae en la resistencia?', ['3 V', '5 V', '7 V', '2 V'], '5 − 2 = 3 V.') },
    { title: 'Compruébalo midiendo', text: 'Un truco práctico: mide la tensión de cada componente de la malla con el multímetro. Si las sumas no dan la pila, o hay un error de medida o un componente que no estás viendo (como un cable con mala conexión).', q: mcq('Mides 6 V + 2 V en una malla con una pila de 9 V. ¿Qué sospechas?', ['Que falta 1 V en alguna parte: una conexión con resistencia o un componente olvidado', 'Que Kirchhoff no se cumple aquí', 'Que la pila da 8 V exactos', 'Nada raro'], 'Kirchhoff siempre se cumple: busca dónde está el voltio que falta.') }
  ] },
  led: { name: 'LED y su resistencia', alts: [
    { title: 'Una presa que se desborda', text: 'Un LED es como una presa: por debajo de cierta tensión (≈2 V en rojo) no pasa nada; en cuanto la superas, el agua se desborda sin control. La resistencia en serie es la compuerta que limita el caudal.', q: mcq('¿Por qué no basta con dar al LED “exactamente” 2 V sin resistencia?', ['Porque un poco más de tensión dispara la corriente y lo quema', 'Porque necesita 9 V', 'Porque el LED no conduce sin resistencia', 'Sí basta'], 'Su curva es muy empinada: la resistencia lo estabiliza.') },
    { title: 'La receta en tres pasos', text: '1) Resta al voltaje de la fuente la tensión del LED: lo que queda cae en la resistencia. 2) Divide eso entre la corriente que quieres. 3) Elige el valor comercial superior.', q: mcq('5 V, LED verde de 2,1 V y 10 mA. ¿Qué resistencia comercial?', ['330 Ω', '220 Ω', '290 Ω', '510 kΩ'], '(5 − 2,1) / 0,01 = 290 Ω → 330 Ω.') }
  ] },
  rc: { name: 'Carga RC', alts: [
    { title: 'Llenar una piscina con una manguera', text: 'Un condensador es una piscina; la resistencia, el grosor de la manguera. Al principio entra mucha agua, pero cuanto más llena está, más presión hace en contra y entra más despacio. τ = R·C dice lo lento que es: manguera más fina o piscina más grande, más tiempo.', q: mcq('Si duplicas la capacidad con la misma resistencia, el tiempo de carga…', ['Se duplica', 'Se reduce a la mitad', 'No cambia', 'Se cuadruplica'], 'τ = R × C.') },
    { title: 'La regla de los 5τ', text: 'Tras 1τ está al 63 %, tras 3τ al 95 % y tras 5τ prácticamente lleno (99 %). Para calcular tiempos de retardo, piensa en múltiplos de τ.', q: mcq('τ = 0,2 s. ¿Cuánto tarda en cargarse casi del todo?', ['Alrededor de 1 s', '0,2 s', '0,04 s', '10 s'], '5 × 0,2 = 1 s.') }
  ] },
  diode: { name: 'Diodo', alts: [
    { title: 'Una válvula antirretorno', text: 'Un diodo es como la válvula de un neumático: deja entrar aire pero no salir. La flecha del símbolo indica el sentido permitido (convencional): de ánodo a cátodo.', q: mcq('En el símbolo del diodo, la corriente puede ir…', ['En el sentido de la flecha (ánodo → cátodo)', 'Contra la flecha', 'En ambos sentidos', 'En ninguno'], 'La barra es el “tope”.') },
    { title: 'El peaje de 0,7 V', text: 'Para conducir, un diodo de silicio “cobra” unos 0,6–0,7 V. Ese peaje se resta siempre de la tensión disponible para el resto del circuito.', q: mcq('Dos diodos de silicio en serie con una pila de 5 V. ¿Qué tensión queda para el resto?', ['Unos 3,6 V', '5 V', '4,3 V', '1,4 V'], '5 − 0,7 − 0,7 ≈ 3,6 V.') }
  ] },
  bjt: { name: 'Transistor', alts: [
    { title: 'Un grifo controlado', text: 'El transistor es un grifo: la corriente de base es la mano que lo abre y la de colector, el agua que pasa. Con poca mano mueves mucha agua; esa multiplicación es β.', q: mcq('β = 100. Si la base recibe 0,2 mA, ¿cuánta corriente puede pasar por el colector como mucho?', ['20 mA', '0,2 mA', '2 mA', '200 mA'], '100 × 0,2 mA.') },
    { title: 'Interruptor: cortado o saturado', text: 'Para usarlo como interruptor solo interesan dos estados: cortado (sin base, no pasa nada, Vce ≈ alimentación) y saturado (base de sobra, pasa todo lo que permite la carga, Vce ≈ 0,1–0,2 V).', q: mcq('Mides Vce = 8,9 V con una alimentación de 9 V. El transistor está…', ['Cortado', 'Saturado', 'Quemado seguro', 'En inversa'], 'Si apenas cae nada en la carga, no conduce.') }
  ] },
  binary: { name: 'Binario', alts: [
    { title: 'Como un cuentakilómetros', text: 'Un cuentakilómetros decimal pasa de 9 a 10 porque cada rueda tiene 10 cifras. En binario cada rueda solo tiene 0 y 1, así que pasa de 1 a 10 (que vale dos). Cada posición vale el doble que la de su derecha: 1, 2, 4, 8, 16…', q: mcq('¿Qué viene después de 0111 en binario?', ['1000', '0112', '1111', '0110'], '7 + 1 = 8 = 1000.') },
    { title: 'Pesos', text: 'Para leer un número binario, escribe debajo los pesos (… 8 4 2 1) y suma los de las posiciones con 1. 1010 = 8 + 2 = 10.', q: mcq('¿Cuánto vale 1100?', ['12', '3', '1100', '6'], '8 + 4.') }
  ] },
  prefix: { name: 'Prefijos', alts: [
    { title: 'La escalera de mil', text: 'Los prefijos son peldaños de 1000 en 1000: p → n → µ → m → (unidad) → k → M. Bajar un peldaño multiplica por 1000; subirlo divide entre 1000.', q: mcq('¿Cuántos µA hay en 1 mA?', ['1000', '10', '100', '0,001'], 'Un peldaño: ×1000.') },
    { title: 'Moviendo la coma', text: 'Cambiar de prefijo es mover la coma 3 posiciones: 4,7 kΩ → 4700 Ω (coma 3 a la derecha); 0,02 A → 20 mA (coma 3 a la derecha).', q: mcq('0,0047 A en mA es…', ['4,7 mA', '47 mA', '0,47 mA', '4700 mA'], 'Coma 3 posiciones a la derecha.') }
  ] },
  pow10: { name: 'Potencias de 10', alts: [
    { title: 'Contar ceros', text: '10³ = 1000 (tres ceros). 10⁻³ = 0,001 (la coma se mueve tres a la izquierda). Multiplicar potencias suma exponentes: 10³ × 10⁻⁶ = 10⁻³.', q: mcq('10⁶ × 10⁻³ = ?', ['10³', '10⁻¹⁸', '10⁹', '10⁻³'], '6 + (−3) = 3.') }
  ] },
  algebra: { name: 'Despejar', alts: [
    { title: 'La balanza', text: 'Una ecuación es una balanza equilibrada: lo que hagas a un lado, házselo al otro. Si V = I·R y quieres R, divide los dos lados entre I: V/I = R.', q: mcq('De P = V × I, despeja V', ['V = P / I', 'V = P × I', 'V = I / P', 'V = P − I'], 'Divide los dos lados entre I.') }
  ] },
  color: { name: 'Código de colores', alts: [
    { title: 'Una frase para recordarlo', text: 'Negro 0, marrón 1, rojo 2, naranja 3, amarillo 4, verde 5, azul 6, violeta 7, gris 8, blanco 9. Del oscuro al claro pasando por el arcoíris. La tercera banda dice cuántos ceros añadir.', q: mcq('Rojo, violeta, naranja', ['27 kΩ', '273 Ω', '2,7 kΩ', '270 kΩ'], '2, 7 y tres ceros: 27 000 Ω.') }
  ] },
  ac: { name: 'Corriente alterna', alts: [
    { title: 'Un columpio', text: 'La alterna es como un columpio: va y viene. La frecuencia es cuántas idas y vueltas completas hace por segundo (50 Hz en Europa). El valor eficaz (rms) es el de una continua que calentaría lo mismo: Vp/√2.', q: mcq('La red europea tiene 230 V eficaces. ¿Cuál es el pico aproximado?', ['325 V', '230 V', '163 V', '460 V'], '230 × √2 ≈ 325 V.') }
  ] },
  filter: { name: 'Filtro RC', alts: [
    { title: 'Un condensador elige frecuencias', text: 'El condensador deja pasar fácilmente las señales rápidas y bloquea las lentas. En un paso bajo RC, el condensador va a masa: “se come” lo rápido y deja pasar lo lento. La frontera es fc = 1/(2πRC).', q: mcq('En un paso bajo RC, si subes la frecuencia muy por encima de fc, la salida…', ['Baja mucho', 'Sube', 'No cambia', 'Se invierte'], 'Lo rápido se va a masa por el condensador.') }
  ] },
  log: { name: 'Logaritmos y dB', alts: [
    { title: 'Contar ceros otra vez', text: 'El logaritmo en base 10 responde a: ¿10 elevado a cuánto da este número? log(100) = 2. Los decibelios usan logaritmos porque el oído y muchos circuitos trabajan en proporciones: 20·log(×10) = 20 dB.', q: mcq('Una ganancia de ×100 en tensión son…', ['40 dB', '20 dB', '100 dB', '2 dB'], '20 · log(100) = 20 · 2.') }
  ] },
  opamp: { name: 'Amplificador operacional', alts: [
    { title: 'Las dos reglas de oro', text: 'Con realimentación negativa: 1) las entradas no consumen corriente; 2) la salida hace lo necesario para que las dos entradas tengan la misma tensión. Con eso se deducen todas las fórmulas.', q: mcq('En un seguidor de tensión (salida unida a la entrada −), si IN+ = 2 V, la salida es…', ['2 V', '0 V', 'La alimentación', '4 V'], 'La salida iguala las entradas.') }
  ] },
  ic555: { name: 'Temporizador 555', alts: [
    { title: 'Un condensador que sube y baja', text: 'Dentro del 555 hay dos comparadores que vigilan el condensador: cuando llega a 2/3 de la alimentación, lo descarga; cuando baja a 1/3, lo vuelve a cargar. La salida cambia en cada vuelta: eso es el parpadeo.', q: mcq('Si usas un condensador más grande en un 555 astable, el LED parpadea…', ['Más despacio', 'Más rápido', 'Igual', 'Deja de parpadear'], 'Más capacidad, más tiempo en cargar y descargar.') }
  ] },
  pullup: { name: 'Pull-up', alts: [
    { title: 'Un muelle', text: 'Una resistencia de pull-up es un muelle que mantiene la entrada arriba (HIGH) cuando nadie la toca. El pulsador, al cerrarse, la lleva a masa con más fuerza que el muelle: LOW.', q: mcq('Sin pull-up ni pull-down, una entrada sin conectar…', ['Lee valores al azar (flota)', 'Lee siempre LOW', 'Lee siempre HIGH', 'Se quema'], 'Por eso siempre hay que fijarla.') }
  ] },
  meter_v: { name: 'Medir tensión', alts: [
    { title: 'Mirar desde fuera', text: 'Para medir tensión no hay que tocar el circuito: el multímetro se apoya por fuera, una punta a cada lado del componente, como quien compara la altura de dos escalones. Por dentro tiene muchísima resistencia y apenas roba corriente.', q: mcq('¿Hay que abrir el circuito para medir tensión?', ['No: se mide en paralelo', 'Sí: se mide en serie', 'Solo con multímetro manual', 'Solo si es alterna'], 'Paralelo, sin desmontar nada.') }
  ] },
  meter_a: { name: 'Medir corriente', alts: [
    { title: 'Un contador en la tubería', text: 'Para contar el agua que pasa hay que cortar la tubería y meter el contador en medio: toda el agua lo atraviesa. Con la corriente igual: se abre el circuito y el multímetro va en serie, con la punta roja en mA.', q: mcq('¿Por qué es peligroso poner el multímetro en modo corriente en paralelo con una pila?', ['Porque por dentro es casi un cable y provoca un cortocircuito', 'Porque mide alterna', 'Porque marca negativo', 'No es peligroso'], 'El fusible está ahí por eso.') }
  ] },
  breadboard: { name: 'Protoboard', alts: [
    { title: 'Tiras ocultas', text: 'Debajo de cada columna de 5 agujeros hay una pinza metálica: todo lo que pinches en la misma columna (a–e) queda unido. La ranura central separa la mitad de arriba de la de abajo. Las filas largas de los bordes son la alimentación.', q: mcq('Pinchas un cable en b7 y otro en e7. ¿Están conectados?', ['Sí, misma columna y mismo lado', 'No, filas distintas', 'Solo si hay un puente', 'Depende del cable'], 'a–e de la misma columna = un solo nudo.') }
  ] },
  schematic: { name: 'Esquemas', alts: [
    { title: 'Un mapa de metro', text: 'Un esquema es como un mapa de metro: no respeta las distancias reales, solo qué está unido con qué. Dos dibujos muy distintos pueden ser el mismo circuito.', q: mcq('Dos esquemas tienen formas distintas pero las mismas conexiones. ¿Son el mismo circuito?', ['Sí', 'No', 'Solo si tienen el mismo tamaño', 'Solo si los colores coinciden'], 'Lo que importa son las conexiones.') }
  ] },
  cap: { name: 'Condensador', alts: [
    { title: 'Un depósito pequeño', text: 'Un condensador guarda carga entre dos placas. Se llena y se vacía muy rápido, y en continua, una vez lleno, no deja pasar corriente. Su capacidad (µF) es el tamaño del depósito.', q: mcq('En continua y ya cargado, un condensador se comporta como…', ['Un circuito abierto', 'Un cable', 'Una pila infinita', 'Una resistencia de 0 Ω'], 'Bloquea la continua.') }
  ] },
  logic: { name: 'Puertas lógicas', alts: [
    { title: 'Interruptores', text: 'AND son interruptores en serie (todos cerrados para que pase). OR son interruptores en paralelo (basta uno). NOT invierte. Todas las demás se construyen combinándolas.', q: mcq('Una alarma suena si la puerta está abierta O la ventana está abierta. ¿Qué puerta?', ['OR', 'AND', 'NOT', 'NAND'], 'Basta una condición.') }
  ] },
  pwm: { name: 'PWM', alts: [
    { title: 'Parpadeo muy rápido', text: 'Si enciendes y apagas una luz muy rápido, el ojo ve la media. PWM hace eso cientos de veces por segundo: con el 25 % del tiempo encendido, ves un 25 % de brillo.', q: mcq('analogWrite(pin, 255) equivale a…', ['Siempre encendido', 'Apagado', 'La mitad', '255 V'], '255 es el máximo: 100 %.') }
  ] },
  adc: { name: 'Conversión analógica', alts: [
    { title: 'Una regla con marcas', text: 'El ADC mide una tensión con una regla de marcas: la Uno tiene 1024 marcas entre 0 y 5 V (unos 4,9 mV cada una). El número que devuelve es la marca más cercana.', q: mcq('analogRead devuelve 512 en una Uno. ¿Tensión aproximada?', ['2,5 V', '5 V', '512 V', '1 V'], '512/1023 × 5 ≈ 2,5 V.') }
  ] },
  /* --- m12 Microcontroladores --- */
  mc_types: { name: 'Tipos y desbordamiento', alts: [
    { title: 'Cajas de distinto tamaño', text: 'Cada tipo es una caja de tamaño fijo. En un <b>byte</b> caben números de 0 a 255; en un <b>int</b> de la Uno, de −32 768 a 32 767. Si metes algo más grande no cabe, se queda solo la parte que entra y el número “da la vuelta”. No hay aviso: simplemente sale un valor equivocado.', q: mcq('¿Qué guarda un byte si le asignas 300?', ['44', '300', '255', '0'], '300 − 256 = 44: solo caben 8 bits.') },
    { title: 'El cuentakilómetros', text: 'Un cuentakilómetros de tres cifras pasa de 999 a 000. Un byte es un cuentakilómetros binario de 8 cifras: después de 255 viene 0. Y hacia atrás, en un tipo sin signo, 0 − 1 da el máximo.', q: mcq('byte b = 0; y luego b = b - 1; ¿Cuánto vale b?', ['255', '−1', '0', '1'], 'Sin signo no hay negativos: da la vuelta hasta arriba.') },
    { title: 'Bits y rangos', text: 'Con n bits hay 2ⁿ combinaciones. 8 bits: 256 valores. 16 bits: 65 536. 32 bits: más de 4000 millones. Si el tipo tiene signo, la mitad de las combinaciones son negativas. Por eso millis() usa unsigned long: 32 bits sin signo, unos 49,7 días de milisegundos.', q: mcq('¿Hasta qué número llega un unsigned int de 16 bits?', ['65 535', '32 767', '255', '65 536'], '2¹⁶ − 1 = 65 535 (el 0 también cuenta como combinación).') }
  ] },
  mc_intmath: { name: 'Aritmética entera', alts: [
    { title: 'Repartir caramelos', text: 'Reparte 17 caramelos entre 5 niños: cada uno recibe 3 (eso es <b>17 / 5</b> entre enteros) y sobran 2 (eso es <b>17 % 5</b>). Con enteros no se parten caramelos: no hay decimales y no se redondea.', q: mcq('¿Cuánto da 23 / 4 entre enteros?', ['5', '5,75', '6', '3'], '4 × 5 = 20 y sobran 3: el resultado es 5.') },
    { title: 'Que haya decimales', text: 'La cuenta se hace con el tipo de los números que intervienen. Si los dos son enteros, el resultado es entero aunque lo guardes en un float. Basta con que uno lleve decimales (5.0 o (float)x) para que toda la cuenta los tenga.', q: mcq('¿Qué guarda float f = 1 / 4;?', ['0', '0,25', '4', '1'], '1 / 4 entre enteros es 0. Con un número decimal en la cuenta (uno con punto en el código) saldría 0,25.') }
  ] },
  mc_flow: { name: 'Condicionales y bucles', alts: [
    { title: 'Sigue el programa con el dedo', text: 'Lee el código como el procesador: línea a línea, apuntando en un papel cuánto vale cada variable. En un if, comprueba la condición con esos valores. En un bucle, apunta cada vuelta hasta que la condición deje de cumplirse.', q: mcq('for (int i = 1; i < 4; i++) — ¿qué valores toma i dentro del bucle?', ['1, 2 y 3', '1, 2, 3 y 4', '0, 1, 2 y 3', 'Solo 4'], 'Cuando i llega a 4 la condición es falsa y el bucle termina.') },
    { title: '= frente a ==', text: 'Un igual (<b>=</b>) guarda: “x pasa a valer 5”. Dos iguales (<b>==</b>) preguntan: “¿x vale 5?”. Dentro de un if casi siempre quieres preguntar.', q: mcq('¿Qué línea pregunta si el botón está pulsado (con pull-up)?', ['if (digitalRead(2) == LOW)', 'if (digitalRead(2) = LOW)', 'digitalRead(2) = LOW;', 'if (LOW)'], 'Comparar es ==.') }
  ] },
  mc_func: { name: 'Funciones', alts: [
    { title: 'Una receta', text: 'Una función es una receta con nombre: los <b>parámetros</b> son los ingredientes que le das y el <b>return</b> es el plato que te devuelve. Puedes usar la misma receta muchas veces con ingredientes distintos.', q: mcq('Con int cuadrado(int x) { return x * x; }, ¿cuánto vale cuadrado(3) + 1?', ['10', '7', '9', '16'], 'cuadrado(3) devuelve 9; más 1, 10.') },
    { title: 'Copias, no originales', text: 'Al llamar a una función le pasas <b>copias</b> de los valores. Lo que haga con ellas no cambia tus variables. Si quieres un resultado, la función lo devuelve con return y tú lo guardas.', q: mcq('void poner(int x) { x = 0; } … int a = 7; poner(a); ¿Cuánto vale a?', ['7', '0', 'Indefinido', '1'], 'La función solo cambió su copia.') }
  ] },
  mc_array: { name: 'Arrays', alts: [
    { title: 'Una fila de taquillas', text: 'Un array es una fila de taquillas numeradas <b>empezando por 0</b>. En un array de 5, la última es la 4. Pedir la 5 es abrir la taquilla de otro: C++ no te lo impide y el fallo aparece donde menos lo esperas.', q: mcq('int v[3] = {7, 8, 9}; ¿Cuánto vale v[1]?', ['8', '7', '9', 'No existe'], 'Índices 0, 1 y 2: v[1] es el segundo.') },
    { title: 'Bucle y array, pareja inseparable', text: 'Para hacer lo mismo con todos los elementos: un for con i desde 0 mientras <b>i < N</b>, usando v[i]. Si mañana tienes 8 LEDs en vez de 5, solo cambias N y la lista.', q: mcq('Para recorrer un array de N elementos, la condición del for es…', ['i < N', 'i <= N', 'i < N + 1', 'i > N'], 'Con <= te sales una posición.') }
  ] },
  mc_serial: { name: 'Puerto serie y texto', alts: [
    { title: 'Un chivato en el programa', text: 'Serial.print es tu chivato: cuenta por dónde pasa el programa y cuánto valen las variables. Si algo falla, pon chivatos antes y después del punto sospechoso y compara lo que esperas con lo que sale.', q: mcq('El Monitor serie no muestra nada legible. ¿Qué compruebas primero?', ['Que haya Serial.begin() con los mismos baudios que el monitor', 'El color del cable', 'Que el LED 13 funcione', 'La EEPROM'], 'Sin begin() o con baudios distintos no verás nada útil.') },
    { title: 'Bits por segundo', text: 'Los baudios son bits por segundo. Cada carácter viaja como 10 bits, así que a 9600 baudios salen unos 960 caracteres por segundo, y a 115 200, unos 11 520. Si imprimes mucho a poca velocidad, Serial.print acaba esperando y frena el programa.', q: mcq('A 9600 baudios, ¿cuánto tarda en salir un mensaje de 96 caracteres?', ['Unos 100 ms', 'Unos 10 ms', '1 s', '9,6 s'], '96 × 10 bits / 9600 = 0,1 s.') },
    { title: 'Letras que son números', text: 'Por el puerto serie solo viajan bytes. Cada letra es un número según la tabla ASCII: \'A\' es 65 y \'0\' es 48. Las cifras van seguidas, así que para pasar el carácter \'7\' al número 7 se le resta \'0\'.', q: mcq('¿Cuánto vale \'9\' - \'0\'?', ['9', '57', '48', '0'], '57 − 48 = 9.') }
  ] },
  mc_debounce: { name: 'Rebotes y flancos', alts: [
    { title: 'Una pelota que bota', text: 'Al pulsar, las láminas del botón chocan y rebotan como una pelota antes de quedarse quietas. Son unos pocos milisegundos, pero el microcontrolador lee tan rápido que ve cada rebote como una pulsación. Solución: ignorar los cambios durante unos 20–50 ms tras aceptar uno.', tune: { viz: 'mc_bounce', params: { T: { label: 'Antirrebote', val: 30, min: 0, max: 120, step: 1, unit: 'ms', dec: 0 } } }, q: mcq('Un contador suma 3 o 4 por cada pulsación. ¿Qué le falta?', ['Antirrebote', 'Una pull-up más fuerte', 'Más velocidad de reloj', 'Un delay en setup()'], 'Cada rebote cuenta como una pulsación nueva.') },
    { title: 'Recordar el pasado', text: 'Para saber si un botón “se acaba de pulsar” no basta con mirar cómo está ahora: hay que compararlo con cómo estaba en la vuelta anterior. Si antes estaba suelto y ahora pulsado, es un <b>flanco</b>. Guarda siempre la lectura anterior en una variable.', q: mcq('Con pull-up: antes = HIGH y ahora = LOW. ¿Qué ha pasado?', ['Se acaba de pulsar', 'Se acaba de soltar', 'Sigue pulsado', 'Sigue suelto'], 'De HIGH a LOW: flanco de bajada, es decir, pulsación.') }
  ] },
  mc_millis: { name: 'Tiempo sin bloquear', alts: [
    { title: 'El reloj de la cocina', text: 'Cocinas tres cosas sin quedarte mirando ninguna: apuntas cuándo pusiste cada una y miras el reloj de vez en cuando. Cuando ha pasado su tiempo, la atiendes. Eso es <b>millis() − inicio >= tiempo</b>.', q: mcq('antes = 1000, ahora = 1600, intervalo = 500. ¿Toca ejecutar la tarea?', ['Sí: han pasado 600 ms', 'No: faltan 100 ms', 'No: 1600 no es múltiplo de 500', 'Solo si ahora fuera 1500'], '1600 − 1000 = 600, que es mayor o igual que 500.') },
    { title: 'delay() es quedarse mirando la olla', text: 'delay(1000) es quedarse un segundo mirando la olla sin hacer nada más: si suena el timbre, no te enteras. Con millis(), cada vuelta de loop() es un vistazo rápido a todo.', q: mcq('¿Qué deja de funcionar bien si pones delay(3000) en loop()?', ['Todo lo demás espera 3 s: botones, sensores y otras tareas', 'Solo el LED', 'Nada', 'millis() deja de contar'], 'delay() bloquea el programa entero.') }
  ] },
  mc_fsm: { name: 'Máquinas de estados', alts: [
    { title: 'Un juego de mesa', text: 'En un juego de mesa tu ficha está en una casilla y las reglas dicen a cuál pasa. En una máquina de estados, la variable <b>estado</b> es la ficha y cada <b>case</b> del switch es una casilla con sus reglas para salir de ella.', q: mcq('¿Qué decide qué código se ejecuta en cada vuelta de una máquina de estados?', ['El valor de la variable de estado', 'El orden en que se escribieron las funciones', 'El delay', 'El número de vueltas'], 'Solo se ejecuta el código del estado actual.') },
    { title: 'Dibújala primero', text: 'Dibuja un círculo por estado y una flecha por cada transición, con lo que la provoca escrito encima: un botón, un tiempo, un sensor. Si de un estado no sale ninguna flecha, el programa se quedará atascado ahí para siempre.', q: mcq('Un estado ALARMA no tiene ninguna transición de salida. ¿Qué pasará?', ['Una vez dentro, no saldrá nunca', 'Volverá solo al inicio', 'No compila', 'Se lo salta'], 'Toda situación necesita su salida, aunque sea un botón de reinicio.') }
  ] },
  mc_isr: { name: 'Interrupciones', alts: [
    { title: 'El timbre', text: 'Leer un pin en loop() es ir a mirar la puerta cada poco. Una interrupción es un timbre: haces otras cosas y, cuando suena, lo dejas todo, abres (la ISR) y vuelves. Si te entretienes en la puerta se quema la comida: por eso la ISR debe ser cortísima.', q: mcq('¿Qué debe hacer una buena ISR?', ['Lo mínimo: anotar el evento en una variable volatile', 'Imprimir un informe por Serial', 'Esperar con delay() a que pase el rebote', 'Llamar a loop()'], 'El trabajo pesado se hace luego, en loop().') },
    { title: 'Por qué volatile', text: 'El compilador optimiza: si ve que loop() nunca cambia una variable, puede leerla una vez y no volver a mirarla en memoria. <b>volatile</b> le dice: “esta variable puede cambiar sola en cualquier momento, léela siempre de verdad”.', q: mcq('Una variable que cambia la ISR y lee loop() debe declararse…', ['volatile', 'const', 'static', 'float'], 'Sin volatile, loop() puede no ver nunca el cambio.') }
  ] },
  mc_memory: { name: 'Memoria del microcontrolador', alts: [
    { title: 'Pizarra, libreta y libro', text: 'La <b>SRAM</b> es una pizarra: rápida, pero se borra al apagar. La <b>EEPROM</b> es una libreta: guarda sin corriente, pero se gasta si escribes y borras mucho. La <b>Flash</b> es el libro impreso con tu programa: no lo reescribes mientras funciona.', q: mcq('¿Dónde guardas la calibración de un sensor para que sobreviva a un apagado?', ['En la EEPROM', 'En la SRAM', 'En una variable local', 'En el Monitor serie'], 'La EEPROM no se borra al quitar la corriente.') },
    { title: 'Haz la cuenta de bytes', text: 'Suma lo que ocupan tus variables: cada int son 2 bytes en la Uno, cada float 4, cada carácter de un texto 1 (más el cero final). La Uno solo tiene 2048 bytes de RAM, y las funciones necesitan una parte libre para sus variables locales.', q: mcq('char buffer[200] y float datos[100] en la Uno. ¿Cuánta RAM ocupan?', ['600 bytes', '300 bytes', '1000 bytes', '200 bytes'], '200 × 1 + 100 × 4 = 600 bytes, casi un tercio de la RAM.') }
  ] },
  mc_lib: { name: 'Librerías y módulos', alts: [
    { title: 'Molde y galletas', text: 'Una <b>clase</b> es el molde y los <b>objetos</b> son las galletas. Servo es el molde; con Servo brazo; y Servo pinza; tienes dos galletas distintas. Cada una guarda sus datos (su pin, su ángulo) y responde a sus métodos: brazo.write(90).', q: mcq('Servo a, b; a.attach(9); b.attach(10); a.write(0); — ¿qué servo se mueve?', ['El del pin 9', 'El del pin 10', 'Los dos', 'Ninguno'], 'Cada objeto es independiente.') },
    { title: 'Empieza por el ejemplo', text: 'Cuando un módulo no funciona, separa el problema: abre un ejemplo de su librería, cámbialo lo mínimo (pin o dirección) y súbelo. Si el ejemplo funciona, el fallo está en tu programa; si no, en el cableado, la alimentación o la dirección.', q: mcq('El ejemplo de la librería tampoco encuentra el sensor. ¿Dónde buscas?', ['En el montaje, la alimentación o la dirección', 'En tu programa', 'En el IDE', 'En el Monitor serie'], 'El ejemplo ya está probado: tu código queda descartado.') },
    { title: 'Chip y módulo no son lo mismo', text: 'El chip tiene sus límites (por ejemplo, 3,6 V como máximo) y la plaquita del módulo puede añadir un regulador y adaptadores de nivel para aceptar 5 V. Mira las dos cosas: la hoja de datos del chip y la descripción de esa placa concreta.', q: mcq('Un chip admite como máximo 3,6 V. ¿Puede alimentarse su módulo con 5 V?', ['Solo si el módulo lleva regulador (y adaptación de niveles en los datos)', 'Siempre', 'Nunca', 'Solo con pilas'], 'Depende del módulo, no solo del chip.') }
  ] },
  mc_sleep: { name: 'Bajo consumo', alts: [
    { title: 'La media que cuenta', text: 'Si un aparato pasa 1 segundo despierto a 20 mA y 59 dormido gastando casi nada, su consumo medio es menos de medio miliamperio. Lo que manda es la <b>proporción de tiempo despierto</b>.', q: mcq('Despierto el 1 % del tiempo a 50 mA y dormido el resto a 0 mA. ¿Consumo medio?', ['0,5 mA', '50 mA', '5 mA', '25 mA'], '50 × 0,01 = 0,5 mA.') },
    { title: 'Lo que no se ve también gasta', text: 'Dormir el chip no basta si la placa tiene un LED de encendido, un regulador que gasta aunque no haya carga o un sensor siempre alimentado. Haz la lista de todo lo conectado y mide la corriente total con el multímetro en serie.', q: mcq('Duermes el chip y el multímetro sigue marcando 8 mA. ¿Qué buscas?', ['LEDs, reguladores y módulos que siguen alimentados', 'Un fallo del multímetro', 'Que el chip no sabe dormir', 'Nada: es normal e inevitable'], 'Suma el consumo de toda la placa.') }
  ] },
  mc_choose: { name: 'Elegir microcontrolador', alts: [
    { title: 'La herramienta justa', text: 'Elegir microcontrolador es como elegir herramienta: no usas un martillo neumático para colgar un cuadro. Empieza por lo que el proyecto necesita (radio, tensión, memoria, pines) y elige la placa más sencilla que lo cumpla.', q: mcq('Un juego de reflejos con dos botones y tres LEDs, alimentado por USB. ¿Qué basta?', ['Una Uno o una Nano', 'Un ESP32, obligatoriamente', 'Un ordenador con Linux', 'Un STM32 de gama alta'], 'Sin radio ni grandes cálculos, lo más sencillo vale.') },
    { title: 'Las tres preguntas', text: 'Antes de elegir: 1) ¿necesito WiFi o Bluetooth? 2) ¿mis módulos son de 5 V o de 3,3 V? 3) ¿cuánta RAM necesito? (la Uno solo tiene 2 KB). Con eso descartas la mayoría de opciones.', q: mcq('Necesitas tener en RAM una imagen de 20 KB. ¿Qué placa descartas?', ['La Uno: solo tiene 2 KB de RAM', 'El ESP32', 'La Pico', 'Ninguna'], 'El ESP32 y la Pico tienen cientos de KB de RAM.') }
  ] }
};
