/* Voltio · generadores de ejercicios. Cada uno devuelve un ejercicio nuevo
   (mc o num) con valores distintos y distractores sacados de errores típicos. */
const Gen = (() => {
  const pick = a => a[Math.floor(Math.random() * a.length)];
  const ri = (a, b) => a + Math.floor(Math.random() * (b - a + 1));
  const fmt = (x, d = 3) => { const r = Math.round(x * 10 ** d) / 10 ** d; return String(r).replace('.', ','); };
  const fR = r => r >= 1e6 ? fmt(r / 1e6) + ' MΩ' : r >= 1000 ? fmt(r / 1000) + ' kΩ' : fmt(r) + ' Ω';
  const fA = i => Math.abs(i) >= 1 ? fmt(i) + ' A' : fmt(i * 1000, 2) + ' mA';
  const fV = v => fmt(v, 2) + ' V';
  const sup = n => String(n).split('').map(c => '⁰¹²³⁴⁵⁶⁷⁸⁹'['0123456789'.indexOf(c)] || (c === '-' ? '⁻' : c)).join('');
  const uniq = (right, wrong) => { const s = new Set([right]); const o = [right]; for (const w of wrong) if (!s.has(w) && o.length < 4) { s.add(w); o.push(w); } return o; };
  const MC = (q, right, wrong, e, extra = {}) => ({ t: 'mc', q, o: uniq(right, wrong), a: 0, e, ...extra });
  const N = (q, a, u, e, tol) => ({ t: 'num', q, a, u, e, tol });
  const E = [10, 22, 33, 47, 68, 100, 150, 220, 330, 470, 680, 1000, 1500, 2200, 3300, 4700, 6800, 10000, 22000, 47000, 100000];
  const PREF = [['p', -12], ['n', -9], ['µ', -6], ['m', -3], ['', 0], ['k', 3], ['M', 6]];

  const G = {
    pow10: () => { const a = ri(-6, 6), b = ri(-6, 6); return MC(`¿Cuánto es 10${sup(a)} × 10${sup(b)}?`, '10' + sup(a + b), ['10' + sup(a * b), '10' + sup(a - b), '10' + sup(a + b + 1), '10' + sup(a + b - 1), '10' + sup(-(a + b) + 2)], 'Al multiplicar potencias de la misma base, los exponentes se suman.'); },
    pow10div: () => { const a = ri(-3, 6), b = ri(-6, 3); return MC(`¿Cuánto es 10${sup(a)} ÷ 10${sup(b)}?`, '10' + sup(a - b), ['10' + sup(a + b), '10' + sup(b - a), '10' + sup(a * b), '10' + sup(a - b + 1), '10' + sup(a - b - 1)], 'Al dividir, se resta el exponente de abajo al de arriba.'); },
    sci: () => { const m = pick([4.7, 2.2, 3.3, 1.5, 6.8]), e = pick([-6, -5, -4, -3, 3, 4, 5]); const val = m * 10 ** e; const s = val < 1 ? fmt(val, 8) : String(Math.round(val)); return MC(`¿Cómo se escribe ${s} en notación científica?`, `${fmt(m)} × 10${sup(e)}`, [`${fmt(m)} × 10${sup(-e)}`, `${fmt(m)} × 10${sup(e + 1)}`, `${fmt(m * 10)} × 10${sup(e + 1)}`], 'Mueve la coma hasta dejar una sola cifra delante; cada salto es una potencia de 10.'); },
    prefixName: () => { const [p, e] = pick(PREF.filter(x => x[0])); return MC(`¿Cuánto vale el prefijo “${p}”?`, '10' + sup(e), PREF.filter(x => x[0] && x[0] !== p).map(x => '10' + sup(x[1])).sort(() => Math.random() - .5), `${p} = 10${sup(e)}. Memoriza la escalera: p, n, µ, m, (unidad), k, M; cada peldaño son 1000.`); },
    prefixConv: () => {
      const cases = [
        () => { const v = pick([1.5, 2.2, 4.7, 10, 22, 0.33]); return N(`${fmt(v)} kΩ son… ¿cuántos ohmios?`, v * 1000, 'Ω', `k = ×1000 → ${fmt(v * 1000)} Ω.`); },
        () => { const v = pick([0.02, 0.015, 0.25, 0.005, 0.12]); return N(`${fmt(v, 4)} A son… ¿cuántos miliamperios?`, v * 1000, 'mA', `×1000 → ${fmt(v * 1000)} mA.`); },
        () => { const v = pick([20, 350, 4.5, 1200]); return N(`${fmt(v)} mA son… ¿cuántos amperios?`, v / 1000, 'A', `÷1000 → ${fmt(v / 1000, 4)} A.`); },
        () => { const v = pick([100, 470, 2200, 47]); return N(`${v} nF son… ¿cuántos microfaradios?`, v / 1000, 'µF', `De n a µ hay un salto de 1000: ÷1000 → ${fmt(v / 1000, 3)} µF.`); },
        () => { const v = pick([3300, 47000, 680, 220000]); return N(`${v} Ω son… ¿cuántos kiloohmios?`, v / 1000, 'kΩ', `÷1000 → ${fmt(v / 1000)} kΩ.`); },
        () => { const v = pick([0.1, 0.47, 2.2, 10]); return N(`${fmt(v)} µF son… ¿cuántos nanofaradios?`, v * 1000, 'nF', `×1000 → ${fmt(v * 1000)} nF.`); }
      ];
      return pick(cases)();
    },
    rearrange: () => { const c = pick([['V = I × R', 'R', 'R = V / I', ['R = I / V', 'R = V × I', 'R = I − V']], ['V = I × R', 'I', 'I = V / R', ['I = R / V', 'I = V × R', 'I = V − R']], ['P = V × I', 'I', 'I = P / V', ['I = V / P', 'I = P × V', 'I = P − V']], ['P = I² × R', 'R', 'R = P / I²', ['R = P × I²', 'R = I² / P', 'R = √P / I']], ['P = V² / R', 'R', 'R = V² / P', ['R = P / V²', 'R = V² × P', 'R = V / P']], ['τ = R × C', 'C', 'C = τ / R', ['C = R / τ', 'C = τ × R', 'C = τ − R']], ['f = 1 / T', 'T', 'T = 1 / f', ['T = f', 'T = f / 1', 'T = 1 × f']]]); return MC(`Despeja ${c[1]} de ${c[0]}`, c[2], c[3], 'Para despejar, haz la misma operación a los dos lados hasta dejar la incógnita sola.'); },
    proportion: () => { const a = pick([2, 3, 4, 5]), b = pick([10, 20, 30, 50]), k = pick([2, 3, 4, 6]); return N(`Si ${a} pilas iguales dan ${a * 1.5} V en serie, ¿cuántos voltios dan ${a * k}?`, a * k * 1.5, 'V', 'Es proporcional: el doble de pilas, el doble de tensión.'); },
    percent: () => { const v = pick([9, 5, 12, 3.3]), p = pick([10, 20, 25, 50]); return N(`¿Cuánto es el ${p} % de ${fmt(v)} V?`, v * p / 100, 'V', `${fmt(v)} × ${p} / 100 = ${fmt(v * p / 100)} V.`); },
    tolerance: () => { const r = pick([1000, 4700, 220, 10000, 330]), t = pick([5, 10, 1]); const lo = r * (1 - t / 100), hi = r * (1 + t / 100); return MC(`Una resistencia de ${fR(r)} con tolerancia ±${t} %. ¿Entre qué valores puede estar?`, `${fR(lo)} y ${fR(hi)}`, [`${fR(r - t)} y ${fR(r + t)}`, `${fR(r * (1 - t / 10))} y ${fR(r * (1 + t / 10))}`, `${fR(r)} y ${fR(hi)}`], `${t} % de ${fR(r)} es ${fR(r * t / 100)}: se resta y se suma.`); },
    estimate: () => { const V = pick([5, 9, 12]), R = pick([470, 1000, 2200, 10000, 100]); const I = V / R; return MC(`Sin calculadora: ${V} V entre ${fR(R)}, ¿qué orden de magnitud tiene la corriente?`, I >= 0.01 ? 'Decenas de mA' : I >= 0.001 ? 'Unos pocos mA' : 'Cientos de µA o menos', ['Decenas de mA', 'Unos pocos mA', 'Cientos de µA o menos', 'Amperios'], `${V} / ${R} ≈ ${fA(I)}. Estimar el orden de magnitud te salva de errores de prefijos.`); },
    ohmV: () => { const R = pick(E.slice(3, 15)), I = pick([0.002, 0.005, 0.01, 0.015, 0.02]); return N(`Por una resistencia de ${fR(R)} pasan ${fA(I)}. ¿Qué tensión cae en ella?`, R * I, 'V', `V = I × R = ${fmt(I, 4)} A × ${R} Ω = ${fmt(R * I)} V. Pasa siempre a unidades base antes de multiplicar.`); },
    ohmI: () => { const V = pick([3, 5, 9, 12]), R = pick([100, 220, 470, 1000, 2200]); return N(`${V} V aplicados a ${fR(R)}. ¿Qué corriente circula en mA?`, V / R * 1000, 'mA', `I = V / R = ${V} / ${R} = ${fmt(V / R, 5)} A = ${fmt(V / R * 1000)} mA.`, Math.max(0.05, V / R * 10)); },
    ohmR: () => { const V = pick([3, 5, 9, 12]), I = pick([0.01, 0.02, 0.05, 0.1]); return N(`Una carga consume ${fA(I)} con ${V} V. ¿Qué resistencia tiene?`, V / I, 'Ω', `R = V / I = ${V} / ${fmt(I, 3)} = ${fmt(V / I)} Ω.`); },
    ohmMC: () => { const V = pick([5, 9, 12]), R = pick([100, 470, 1000]); const I = V / R; return MC(`${V} V sobre ${fR(R)}. ¿Corriente?`, fA(I), [fA(R / V / 1000), fA(V * R / 1e6), fA(I * 10)], `I = V / R. Los otros resultados vienen de invertir la fórmula o equivocarse de prefijo.`); },
    power: () => { const c = pick(['VI', 'IR', 'VR']); if (c === 'VI') { const V = pick([5, 9, 12]), I = pick([0.1, 0.2, 0.5]); return N(`${V} V y ${fA(I)}. ¿Potencia?`, V * I, 'W', `P = V × I = ${fmt(V * I)} W.`); } if (c === 'IR') { const I = pick([0.01, 0.02, 0.05]), R = pick([100, 220, 470]); return N(`${fA(I)} por ${fR(R)}. ¿Potencia en mW?`, I * I * R * 1000, 'mW', `P = I² × R = ${fmt(I * I * R * 1000)} mW.`); } const V = pick([5, 9, 12]), R = pick([100, 220, 1000]); return N(`${V} V sobre ${fR(R)}. ¿Potencia en mW?`, V * V / R * 1000, 'mW', `P = V² / R = ${fmt(V * V / R * 1000)} mW.`); },
    rating: () => { const V = pick([9, 12]), R = pick([100, 220, 330, 470, 1000]); const P = V * V / R; const ok = P <= 0.25; return MC(`${V} V directamente sobre ${fR(R)}. ¿Vale una resistencia de ¼ W?`, ok ? `Sí: disipa ${fmt(P * 1000, 0)} mW` : `No: disipa ${fmt(P, 2)} W`, [ok ? `No: disipa ${fmt(P * 4, 2)} W` : `Sí: disipa ${fmt(P / 4 * 1000, 0)} mW`, 'Sí, la potencia no depende de la resistencia', 'Depende del color'], 'P = V² / R y compara con 0,25 W. En la práctica, deja al menos el doble de margen.'); },
    energy: () => { const P = pick([60, 100, 1000, 2000, 10]), h = pick([2, 5, 8, 24]), c = pick([0.15, 0.2, 0.25]); const kwh = P * h / 1000; return N(`Un aparato de ${P} W funciona ${h} h. Con la luz a ${fmt(c)} €/kWh, ¿cuánto cuesta (en €)?`, kwh * c, '€', `${P} W × ${h} h = ${fmt(kwh)} kWh × ${fmt(c)} € = ${fmt(kwh * c)} €.`, 0.01); },
    series: () => { const rs = [pick(E.slice(3, 14)), pick(E.slice(3, 14)), pick(E.slice(3, 14))]; return N(`${rs.map(fR).join(', ')} en serie. ¿Resistencia total en Ω?`, rs[0] + rs[1] + rs[2], 'Ω', 'En serie, se suman.'); },
    parallel2: () => { const [a, b] = pick([[100, 100], [1000, 1000], [100, 300], [600, 300], [2200, 2200], [1000, 1500], [470, 470], [60, 30]]); const r = a * b / (a + b); return N(`${fR(a)} y ${fR(b)} en paralelo. ¿Resistencia total en Ω?`, r, 'Ω', `(${a} × ${b}) / (${a} + ${b}) = ${fmt(r)} Ω. Siempre menor que la más pequeña.`); },
    parallelN: () => { const r = pick([1000, 2200, 330, 100]), n = pick([2, 3, 4, 5]); return N(`${n} resistencias iguales de ${fR(r)} en paralelo. ¿Total en Ω?`, r / n, 'Ω', `n iguales en paralelo: R / n = ${fmt(r / n)} Ω.`); },
    parallelMC: () => { const a = pick([100, 1000, 470]), b = pick([10000, 100000]); return MC(`${fR(a)} en paralelo con ${fR(b)}. ¿El total es aproximadamente…?`, `Un poco menos de ${fR(a)}`, [`Un poco más de ${fR(b)}`, `${fR(a + b)}`, `La mitad de ${fR(b)}`], 'Una resistencia muy grande en paralelo apenas cambia nada: casi toda la corriente va por la pequeña.'); },
    mixed: () => { const r1 = pick([100, 220, 470]), r = pick([200, 1000, 2200]); return N(`${fR(r1)} en serie con dos de ${fR(r)} que están en paralelo entre sí. ¿Total en Ω?`, r1 + r / 2, 'Ω', `Primero el paralelo: ${fR(r / 2)}. Luego suma la de serie: ${fmt(r1 + r / 2)} Ω.`); },
    divider: () => { const V = pick([5, 9, 12]), [a, b] = pick([[1000, 1000], [2000, 1000], [1000, 2000], [10000, 4700], [4700, 10000], [3300, 6800]]); const vo = V * b / (a + b); return N(`${V} V con R1 = ${fR(a)} (arriba) y R2 = ${fR(b)} (abajo). ¿Vsal?`, vo, 'V', `Vsal = ${V} × ${b} / (${a} + ${b}) = ${fmt(vo, 2)} V.`, 0.05); },
    currentDiv: () => { const I = pick([10, 30, 60]), [a, b] = pick([[100, 200], [1000, 1000], [300, 600]]); const i1 = I * b / (a + b); return N(`Entran ${I} mA en dos ramas en paralelo: R1 = ${fR(a)}, R2 = ${fR(b)}. ¿Corriente por R1 en mA?`, i1, 'mA', `Por la rama de menor resistencia va más: I1 = I × R2 / (R1 + R2) = ${fmt(i1)} mA.`, 0.2); },
    kcl: () => { const a = ri(5, 40), b = ri(2, a - 1); return N(`Entran ${a} mA en un nudo. Por una salida van ${b} mA. ¿Por la otra?`, a - b, 'mA', 'Lo que entra, sale.'); },
    kvl: () => { const V = pick([9, 12]), a = ri(2, 4), b = pick([1.8, 2]); return N(`Una pila de ${V} V con tres componentes en serie. En el primero caen ${a} V y en el segundo ${fmt(b)} V. ¿Y en el tercero?`, V - a - b, 'V', 'La suma de caídas en una malla iguala la tensión de la pila.'); },
    ledR: () => { const Vs = pick([5, 9, 12, 3.3]), [col, Vf] = pick([['rojo', 1.8], ['verde', 2.1], ['azul', 3.0], ['amarillo', 2.0]]), I = pick([0.01, 0.015, 0.02]); if (Vs <= Vf) return G.ledR(); return N(`Fuente de ${fmt(Vs)} V, LED ${col} (${fmt(Vf)} V) y ${fA(I)}. ¿Resistencia en Ω?`, (Vs - Vf) / I, 'Ω', `R = (${fmt(Vs)} − ${fmt(Vf)}) / ${fmt(I, 3)} = ${fmt((Vs - Vf) / I)} Ω. Luego eliges el valor comercial siguiente.`, 2); },
    colorRead: () => { const B = ['negro', 'marrón', 'rojo', 'naranja', 'amarillo', 'verde', 'azul', 'violeta', 'gris', 'blanco']; const r = pick([100, 150, 220, 330, 470, 680, 1000, 1500, 2200, 3300, 4700, 6800, 10000, 22000, 47000, 100000]); const s = String(r); const d = [+s[0], +s[1], s.length - 2]; const wrong = [r * 10, r / 10, (+s[0] * 10 + +s[1]) * 10 ** (s.length - 1) + 1].map(fR); return { t: 'res', bands: [B[d[0]], B[d[1]], B[d[2]], 'dorado'], o: uniq(fR(r), wrong), a: 0, e: `${d[0]}, ${d[1]} y ${d[2]} ceros → ${fR(r)}.` }; },
    colorBuild: () => { const r = pick([100, 220, 330, 470, 1000, 2200, 4700, 10000, 47000]); return { t: 'bands', q: `Pinta las bandas de ${fR(r)}.`, target: r, e: '' }; },
    eSeries: () => { const need = pick([300, 350, 195, 4300, 160, 900, 2000, 6000]); const E12 = [100, 120, 150, 180, 220, 270, 330, 390, 470, 560, 680, 820]; const all = E12.concat(E12.map(x => x * 10), E12.map(x => x * 100)); const up = all.find(x => x >= need), down = all.filter(x => x < need).pop(); return MC(`Te sale ${fR(need)} para limitar la corriente de un LED. ¿Qué valor comercial (serie E12) eliges?`, fR(up), [fR(down), fR(up * 10), fR(down / 10)], 'Redondea hacia arriba: algo menos de corriente es seguro; algo más, no.'); },
    tau: () => { const R = pick([1000, 4700, 10000, 47000, 100000]), C = pick([1, 10, 47, 100, 220, 470]); return N(`R = ${fR(R)} y C = ${C} µF. ¿Cuánto vale τ en segundos?`, R * C * 1e-6, 's', `τ = R × C = ${R} × ${C}·10⁻⁶ = ${fmt(R * C * 1e-6, 4)} s.`, Math.max(0.002, R * C * 1e-8)); },
    rcPct: () => { const n = pick([1, 2, 3, 5]); const p = { 1: '63 %', 2: '86 %', 3: '95 %', 5: '99 %' }[n]; return MC(`Un condensador se carga a través de una resistencia. ¿Qué porcentaje tiene tras ${n}τ?`, p, ['63 %', '86 %', '95 %', '99 %', '50 %'].filter(x => x !== p), 'Carga = 1 − e^(−t/τ): 63 %, 86 %, 95 %, 98 %, 99 %.'); },
    capSeries: () => { const a = pick([10, 22, 47, 100]), b = pick([10, 22, 47, 100]); return MC(`${a} µF y ${b} µF. ¿Capacidad en paralelo?`, `${a + b} µF`, [`${fmt(a * b / (a + b))} µF`, `${Math.max(a, b)} µF`, `${a * b} µF`], 'Los condensadores en paralelo suman (al revés que las resistencias).'); },
    capCode: () => { const c = pick([['104', '100 nF'], ['103', '10 nF'], ['105', '1 µF'], ['473', '47 nF'], ['222', '2,2 nF'], ['101', '100 pF']]); return MC(`Un condensador cerámico pone “${c[0]}”. ¿Cuánto vale?`, c[1], ['100 nF', '10 nF', '1 µF', '47 nF', '2,2 nF', '100 pF', '10 µF'].filter(x => x !== c[1]).sort(() => Math.random() - .5), 'Dos cifras y número de ceros, en picofaradios: 104 = 10 0000 pF = 100 nF.'); },
    bin2dec: () => { const n = ri(1, 255); const b = n.toString(2).padStart(8, '0'); return N(`¿Cuánto vale ${b} en decimal?`, n, '', `Suma los pesos de los unos: ${[...b].map((x, i) => x === '1' ? 2 ** (7 - i) : null).filter(Boolean).join(' + ')} = ${n}.`); },
    dec2bin: () => { const n = ri(1, 31); const r = n.toString(2).padStart(5, '0'); const w = [(n ^ 1), (n ^ 4), (n ^ 16)].map(x => x.toString(2).padStart(5, '0')); return MC(`¿Cómo se escribe ${n} en binario (5 bits)?`, r, w, `Descompón en potencias de 2: ${[16, 8, 4, 2, 1].filter(p => n & p).join(' + ')}.`); },
    hex: () => { const n = ri(16, 255); return N(`¿Cuánto vale 0x${n.toString(16).toUpperCase()} en decimal?`, n, '', `Cada cifra hexadecimal vale 16 veces la siguiente: ${Math.floor(n / 16)} × 16 + ${n % 16} = ${n}.`); },
    f555: () => { const R1 = pick([1000, 10000]), R2 = pick([10000, 47000, 68000, 100000]), C = pick([1, 10, 22]); const f = 1.44 / ((R1 + 2 * R2) * C * 1e-6); return N(`555 astable: R1 = ${fR(R1)}, R2 = ${fR(R2)}, C = ${C} µF. ¿Frecuencia en Hz?`, f, 'Hz', `f ≈ 1,44 / ((R1 + 2·R2)·C) = ${fmt(f, 2)} Hz.`, f * 0.03); },
    gainNI: () => { const Rf = pick([9000, 10000, 47000, 100000]), Rg = pick([1000, 10000, 4700]); return N(`Amplificador no inversor: Rf = ${fR(Rf)}, Rg = ${fR(Rg)}. ¿Ganancia?`, 1 + Rf / Rg, '', `G = 1 + Rf / Rg = ${fmt(1 + Rf / Rg, 2)}.`, 0.05); },
    gainInv: () => { const Rf = pick([10000, 47000, 100000]), Ri = pick([1000, 10000, 4700]); return N(`Amplificador inversor: Rf = ${fR(Rf)}, Rin = ${fR(Ri)}. ¿Ganancia (con signo)?`, -Rf / Ri, '', `G = −Rf / Rin = ${fmt(-Rf / Ri, 2)}.`, 0.05); },
    vrms: () => { const vp = pick([10, 14.1, 325, 5, 170]); return N(`Una senoide tiene ${fmt(vp)} V de pico. ¿Valor eficaz (Vrms)?`, vp / Math.SQRT2, 'V', `Vrms = Vp / √2 ≈ Vp × 0,707 = ${fmt(vp / Math.SQRT2, 1)} V.`, vp * 0.01); },
    period: () => { const f = pick([50, 60, 1000, 2, 440]); return N(`Una señal de ${f} Hz. ¿Periodo en milisegundos?`, 1000 / f, 'ms', `T = 1 / f = ${fmt(1000 / f, 3)} ms.`, 0.05); },
    xc: () => { const f = pick([50, 1000, 10000]), C = pick([0.1, 1, 10]); const x = 1 / (2 * Math.PI * f * C * 1e-6); return N(`Reactancia de ${C} µF a ${f} Hz, en Ω`, x, 'Ω', `Xc = 1 / (2π·f·C) ≈ ${fmt(x, 1)} Ω. A más frecuencia, menos reactancia.`, x * 0.03); },
    fc: () => { const R = pick([1000, 10000, 1600]), C = pick([0.1, 0.01, 1]); const f = 1 / (2 * Math.PI * R * C * 1e-6); return N(`Filtro RC con ${fR(R)} y ${C} µF. ¿Frecuencia de corte en Hz?`, f, 'Hz', `fc = 1 / (2π·R·C) ≈ ${fmt(f, 0)} Hz.`, f * 0.03); },
    db: () => { const [r, d] = pick([[10, 20], [100, 40], [2, 6], [0.5, -6], [0.1, -20], [1000, 60]]); return MC(`Una señal sale ${String(r).replace('.', ',')} veces más grande que entra (en tensión). ¿Cuántos dB son?`, `${d} dB`, [`${d / 2} dB`, `${d * 2} dB`, `${r} dB`], 'dB = 20 · log₁₀(Vsal / Vent). ×10 = 20 dB; ×2 ≈ 6 dB; ÷2 ≈ −6 dB.'); },
    exp: () => { const n = pick([1, 2, 3]); return MC(`¿Cuánto vale aproximadamente e^(−${n})?`, { 1: '0,37', 2: '0,14', 3: '0,05' }[n], ['0,37', '0,14', '0,05', '0,63', '0,5'].filter(x => x !== { 1: '0,37', 2: '0,14', 3: '0,05' }[n]), 'e ≈ 2,718. e^(−1) ≈ 0,37: lo que falta por cargar tras 1τ.'); },
    log10: () => { const n = pick([10, 100, 1000, 0.1, 0.01, 1]); return N(`¿Cuánto vale log₁₀(${String(n).replace('.', ',')})?`, Math.log10(n), '', 'El logaritmo en base 10 es el exponente: log(1000) = 3 porque 10³ = 1000.', 0.01); },
    battLife: () => { const c = pick([500, 1000, 2000, 2500]), i = pick([20, 50, 100, 250]); return N(`Batería de ${c} mAh y consumo de ${i} mA. ¿Horas aproximadas?`, c / i, 'h', `${c} / ${i} = ${fmt(c / i, 1)} h (en la práctica, algo menos).`, 0.1); },
    regLoss: () => { const vin = pick([7, 9, 12]), vo = pick([5, 3.3]), I = pick([0.1, 0.2, 0.5]); return N(`Regulador lineal: ${vin} V → ${fmt(vo)} V con ${fA(I)}. ¿Potencia perdida en calor (W)?`, (vin - vo) * I, 'W', `(${vin} − ${fmt(vo)}) × ${fmt(I)} = ${fmt((vin - vo) * I)} W.`, 0.01); },
    efficiency: () => { const vin = pick([9, 12]), vo = pick([5, 3.3]); return N(`Eficiencia máxima de un regulador lineal de ${vin} V a ${fmt(vo)} V, en %`, vo / vin * 100, '%', `Eficiencia ≈ Vsal / Vent = ${fmt(vo / vin * 100, 1)} %. Lo demás se pierde en calor.`, 1); },
    rb: () => { const vc = pick([5, 3.3]), ib = pick([0.5, 1, 2]); return N(`Pin de ${fmt(vc)} V, quieres ${ib} mA de base (Vbe = 0,7 V). ¿Rb en Ω?`, (vc - 0.7) / (ib / 1000), 'Ω', `Rb = (${fmt(vc)} − 0,7) / ${ib} mA = ${fmt((vc - 0.7) / (ib / 1000))} Ω.`, 20); },
    beta: () => { const b = pick([100, 150, 200]), ib = pick([0.05, 0.1, 0.2]); return N(`β = ${b} y una corriente de base de ${fmt(ib)} mA. ¿Corriente de colector máxima en mA?`, b * ib, 'mA', `Ic = β × Ib = ${fmt(b * ib)} mA (si la carga lo permite).`); },
    adc: () => { const esp = Math.random() < 0.4; const max = esp ? 4095 : 1023, vr = esp ? 3.3 : 5; const n = ri(50, max); return N(`${esp ? 'ESP32 (12 bits, 3,3 V)' : 'Arduino Uno (10 bits, 5 V)'}: analogRead devuelve ${n}. ¿Tensión aproximada en V?`, n / max * vr, 'V', `V = ${n} / ${max} × ${fmt(vr)} = ${fmt(n / max * vr, 2)} V.`, 0.03); },
    pwm: () => { const v = pick([64, 128, 191, 255, 25]); return N(`analogWrite(pin, ${v}) en una Uno. ¿Ciclo de trabajo en %?`, v / 255 * 100, '%', `${v} / 255 = ${fmt(v / 255 * 100, 1)} %.`, 0.6); },
    millis: () => { const ms = pick([500, 2000, 60000, 250]); return N(`¿Cuántos segundos son ${ms} ms?`, ms / 1000, 's', '1 s = 1000 ms.'); }
  };
  function make(key) { const e = G[key](); if (e.o === undefined && e.t === 'mc') delete e.o; return { ...e, _gen: key, c: e.c || CONCEPT_OF[key] }; }
  const CONCEPT_OF = { pow10: 'pow10', pow10div: 'pow10', sci: 'pow10', prefixName: 'prefix', prefixConv: 'prefix', rearrange: 'algebra', proportion: 'algebra', percent: 'algebra', tolerance: 'algebra', ohmV: 'ohm', ohmI: 'ohm', ohmR: 'ohm', ohmMC: 'ohm', power: 'power', rating: 'power', series: 'series', parallel2: 'parallel', parallelN: 'parallel', parallelMC: 'parallel', mixed: 'parallel', divider: 'divider', currentDiv: 'parallel', kcl: 'kcl', kvl: 'kvl', ledR: 'led', tau: 'rc', rcPct: 'rc', bin2dec: 'binary', dec2bin: 'binary', f555: 'ic555', gainNI: 'opamp', gainInv: 'opamp', vrms: 'ac', period: 'ac', xc: 'ac', fc: 'filter', db: 'log', log10: 'log', exp: 'log', rb: 'bjt', beta: 'bjt', adc: 'adc', pwm: 'pwm', colorRead: 'color', colorBuild: 'color', capCode: 'cap', capSeries: 'cap' };
  return { make, keys: Object.keys(G) };
})();
