/* Voltio · curso base, módulo 6: Análisis de circuitos
   Lote 3. VIZ propias: nodal, thevenin, norton, maxPower, bridge. Generadores m5_*.
   Los conceptos de este módulo solo los usa este módulo: aquí se amplían o se crean. */
(() => {
  const { num, fR, fI, fV, st, batt, flowPath, hbar } = Widgets.H;
  // Resistencia en zigzag de 42 de largo, centrada en (x, y); v = vertical
  const zz = (x, y, v) => v ? `<path d="M${x} ${y - 21}l-6 3l12 6l-12 6l12 6l-12 6l12 6l-12 6l6 3" ${st}/>` : `<path d="M${x - 21} ${y}l3 -6l6 12l6 -12l6 12l6 -12l6 12l6 -12l3 6" ${st}/>`;
  const fl = (d, I) => flowPath(d, Math.abs(I), 0.012);
  const rev = (fw, bw, I) => I >= 0 ? fw : bw;
  const isrc = (x, y) => `<circle cx="${x}" cy="${y}" r="16" ${st}/><path d="M${x} ${y + 10}V${y - 10}M${x - 6} ${y - 4}l6 -6l6 6" ${st}/>`;
  const gnd = (x, y) => `<path d="M${x - 10} ${y}h20M${x - 6} ${y + 5}h12M${x - 2} ${y + 10}h4" ${st}/>`;
  const oneOf = [0, 1];

  /* ================= VISUALIZACIONES ================= */
  Object.assign(Widgets.VIZ, {
    // Dos pilas que empujan hacia un nudo A; de A sale R3 a masa. on1/on2 = 0 cambia la pila por un cable.
    nodal: {
      calc: p => {
        const on1 = p.on1 ?? 1, on2 = p.on2 ?? 1, v1 = on1 ? p.V1 : 0, v2 = on2 ? p.V2 : 0;
        const VA = (v1 / p.R1 + v2 / p.R2) / (1 / p.R1 + 1 / p.R2 + 1 / p.R3);
        const I1 = (v1 - VA) / p.R1, I2 = (v2 - VA) / p.R2, I3 = VA / p.R3;
        return { VA, I1, I2, I3, I1mA: I1 * 1000, I2mA: I2 * 1000, I3mA: I3 * 1000, I2abs: Math.abs(I2) * 1000, cfg: on1 + 2 * on2 };
      },
      svg: (p, o) => {
        const on1 = p.on1 ?? 1, on2 = p.on2 ?? 1;
        const src = (x, on, V) => on ? batt(x, 110, V) : `<path d="M${x} 88V132" ${st}/><text x="${x + (x < 150 ? -6 : 6)}" y="114" text-anchor="${x < 150 ? 'end' : 'start'}" class="vizsm">cable</text>`;
        const a1 = o.I1 >= 0 ? '→' : '←', a2 = o.I2 >= 0 ? '←' : '→';
        return `<svg viewBox="0 0 300 190" class="viz">
          ${rev(fl('M45 88V40H74', o.I1) + fl('M116 40H150', o.I1), fl('M150 40H116', o.I1) + fl('M74 40H45V88', o.I1), o.I1)}
          ${rev(fl('M255 88V40H226', o.I2) + fl('M184 40H150', o.I2), fl('M150 40H184', o.I2) + fl('M226 40H255V88', o.I2), o.I2)}
          ${fl('M150 40V84', o.I3)}${fl('M150 126V165', o.I3)}
          <path d="M45 132V165H255V132" ${st}/>${zz(95, 40)}${zz(205, 40)}${zz(150, 105, 1)}${src(45, on1, p.V1)}${src(255, on2, p.V2)}
          <circle cx="150" cy="40" r="5" fill="var(--led)"/><circle cx="150" cy="165" r="3.5" fill="currentColor"/>${gnd(150, 172)}
          <text x="150" y="22" text-anchor="middle" class="vizlab">A = ${fV(o.VA)}</text>
          <text x="95" y="62" text-anchor="middle" class="vizsm">R1 ${fR(p.R1)}</text><text x="95" y="76" text-anchor="middle" class="vizsm">${fI(Math.abs(o.I1))} ${Math.abs(o.I1) < 1e-6 ? '' : a1}</text>
          <text x="205" y="62" text-anchor="middle" class="vizsm">R2 ${fR(p.R2)}</text><text x="205" y="76" text-anchor="middle" class="vizsm">${fI(Math.abs(o.I2))} ${Math.abs(o.I2) < 1e-6 ? '' : a2}</text>
          <text x="140" y="100" text-anchor="end" class="vizsm">R3 ${fR(p.R3)}</text><text x="140" y="116" text-anchor="end" class="vizsm">${fI(Math.abs(o.I3))} ↓</text>
          <text x="172" y="186" class="vizsm">masa = 0 V</text></svg>`;
      }
    },
    // Una «caja» (Vth en serie con Rth) alimentando una carga RL
    thevenin: {
      calc: p => { const IL = p.Vth / (p.Rth + p.RL), VL = IL * p.RL; return { IL, ILmA: IL * 1000, VL, drop: (1 - VL / p.Vth) * 100 }; },
      svg: (p, o) => `<svg viewBox="0 0 300 190" class="viz">
        <rect x="12" y="20" width="140" height="130" rx="10" fill="none" stroke="var(--muted)" stroke-dasharray="5 4"/><text x="18" y="15" class="vizsm">la caja: Vth + Rth</text>
        ${fl('M40 88V45H69', o.IL)}${fl('M111 45H215V74', o.IL)}${fl('M215 116V145H40V132', o.IL)}
        ${batt(40, 110, p.Vth)}${zz(90, 45)}${zz(215, 95, 1)}
        <circle cx="152" cy="45" r="4" fill="var(--bg)" stroke="currentColor" stroke-width="2"/><circle cx="152" cy="145" r="4" fill="var(--bg)" stroke="currentColor" stroke-width="2"/>
        <text x="90" y="68" text-anchor="middle" class="vizsm">Rth ${fR(p.Rth)}</text>
        <text x="228" y="90" class="vizsm">RL</text><text x="228" y="104" class="vizsm">${fR(p.RL)}</text>
        <text x="200" y="30" text-anchor="middle" class="vizlab">I = ${fI(o.IL)}</text>
        ${hbar(20, 180, 260, o.VL / p.Vth, o.drop < 10 ? 'var(--ok)' : 'var(--led)', `En la carga ${fV(o.VL)} (en vacío ${fV(p.Vth)}) · cae un ${num(o.drop, 0)} %`)}</svg>`
    },
    // Fuente de corriente IN con RN en paralelo, alimentando RL
    norton: {
      calc: p => {
        const IN = p.IN / 1000, Rp = p.RN * p.RL / (p.RN + p.RL), VL = IN * Rp, IL = VL / p.RL, IRN = VL / p.RN;
        return { VL, IL, IRN, ILmA: IL * 1000, share: IL / IN * 100, Vth: IN * p.RN };
      },
      svg: (p, o) => `<svg viewBox="0 0 300 190" class="viz">
        <rect x="12" y="22" width="130" height="140" rx="10" fill="none" stroke="var(--muted)" stroke-dasharray="5 4"/><text x="18" y="17" class="vizsm">la caja: IN ∥ RN</text>
        ${fl('M40 79V40H110', p.IN / 1000)}${fl('M110 40H230V74', o.IL)}${fl('M110 40V74', o.IRN)}${fl('M230 116V150H40V111', o.IL)}<path d="M110 116V150" ${st}/>
        ${isrc(40, 95)}${zz(110, 95, 1)}${zz(230, 95, 1)}<circle cx="110" cy="40" r="3.5" fill="currentColor"/><circle cx="110" cy="150" r="3.5" fill="currentColor"/>
        <text x="62" y="99" class="vizsm">${num(p.IN, 1)} mA</text><text x="120" y="128" class="vizsm">RN ${fR(p.RN)}</text><text x="240" y="128" class="vizsm">RL ${fR(p.RL)}</text>
        <text x="120" y="70" class="vizsm">${fI(o.IRN)}</text><text x="240" y="70" class="vizsm">${fI(o.IL)}</text>
        <text x="150" y="178" text-anchor="middle" class="vizlab">A la carga: ${num(o.share, 0)} % · VL = ${fV(o.VL)}</text>
        <text x="290" y="16" text-anchor="end" class="vizsm">= Thévenin de ${fV(o.Vth)} con ${fR(p.RN)}</text></svg>`
    },
    // Potencia en la carga según RL, con su curva (eje logarítmico de Rth/10 a 10·Rth)
    maxPower: {
      calc: p => { const I = p.V / (p.Rth + p.RL), PL = I * I * p.RL, Pmax = p.V * p.V / (4 * p.Rth); return { I, PL, Pmax, rel: PL / Pmax * 100, eta: p.RL / (p.Rth + p.RL) * 100 }; },
      svg: (p, o) => {
        const lo = Math.log10(p.Rth / 10), hi = Math.log10(p.Rth * 10), X = r => 40 + 240 * (Math.log10(r) - lo) / (hi - lo), Y = f => 130 - 95 * f;
        const pts = []; for (let i = 0; i <= 80; i++) { const r = 10 ** (lo + (hi - lo) * i / 80); pts.push(`${X(r).toFixed(1)},${Y(4 * p.Rth * r / (p.Rth + r) ** 2).toFixed(1)}`); }
        const xr = X(Math.min(Math.max(p.RL, p.Rth / 10), p.Rth * 10));
        return `<svg viewBox="0 0 300 190" class="viz"><path d="M40 30V130H285" ${st} stroke-width="1.5"/>
          <polyline points="${pts.join(' ')}" fill="none" stroke="var(--line)" stroke-width="2.5"/>
          <path d="M${X(p.Rth).toFixed(1)} 32V130" stroke="var(--muted)" stroke-dasharray="4 4"/><text x="${X(p.Rth).toFixed(1)}" y="143" text-anchor="middle" class="vizsm">RL = Rth</text>
          <circle cx="${xr.toFixed(1)}" cy="${Y(o.rel / 100).toFixed(1)}" r="7" fill="var(--led)"/>
          <text x="36" y="34" text-anchor="end" class="vizsm">máx.</text><text x="285" y="143" text-anchor="end" class="vizsm">RL →</text>
          <text x="40" y="20" class="vizlab">En la carga ${num(o.PL, 2)} W · I = ${fI(o.I)}</text>
          ${hbar(40, 176, 240, o.eta / 100, o.eta >= 80 ? 'var(--ok)' : 'var(--led)', `Rendimiento ${num(o.eta, 0)} %: el resto calienta la fuente`)}</svg>`;
      }
    },
    // Puente de Wheatstone: tres resistencias fijas y un sensor Rx
    bridge: {
      calc: p => { const R = p.R || 1000, VL = p.V / 2, VR = p.V * p.Rx / (R + p.Rx), Vd = (VR - VL) * 1000; return { VL, VR, Vd, absVd: Math.abs(Vd) }; },
      svg: (p, o) => {
        const ok = o.absVd < 1;
        return `<svg viewBox="0 0 300 190" class="viz"><path d="M50 88V20H200V34M110 20V34M110 76V104M200 76V104M110 146V170H200V146M50 132V170H110" ${st}/>
          ${batt(50, 110, p.V)}${zz(110, 55, 1)}${zz(110, 125, 1)}${zz(200, 55, 1)}<g style="color:var(--ice)">${zz(200, 125, 1)}</g>
          <circle cx="110" cy="90" r="3.5" fill="currentColor"/><circle cx="200" cy="90" r="3.5" fill="currentColor"/>
          <path d="M110 90H136M174 90H200" stroke="var(--muted)" stroke-width="2"/><circle cx="155" cy="90" r="19" fill="var(--bg)" stroke="${ok ? 'var(--ok)' : 'currentColor'}" stroke-width="2.5"/>
          <text x="155" y="94" text-anchor="middle" class="vizlab">${num(o.Vd, 1)}</text><text x="155" y="122" text-anchor="middle" class="vizsm">mV</text>
          <text x="96" y="58" text-anchor="end" class="vizsm">1 kΩ</text><text x="96" y="128" text-anchor="end" class="vizsm">1 kΩ</text><text x="214" y="58" class="vizsm">1 kΩ</text>
          <text x="214" y="122" class="vizsm" style="fill:var(--ice)">sensor</text><text x="214" y="136" class="vizsm" style="fill:var(--ice)">${num(p.Rx, 0)} Ω</text>
          <text x="20" y="186" class="vizlab" style="fill:${ok ? 'var(--ok)' : 'currentColor'}">${ok ? 'Equilibrado: los dos lados dan lo mismo' : `Izquierda ${num(o.VL, 3)} V · derecha ${num(o.VR, 3)} V`}</text></svg>`;
      }
    }
  });

  /* ================= ESQUEMAS ================= */
  Object.assign(SCH, {
    m5_nodal: { w: 300, h: 160, parts: [{ k: 'bat', x: 30, y: 85, rot: 90, lab: '12 V', lx: -18, ly: 4 }, { k: 'res', x: 100, y: 25, lab: 'R1 1 kΩ' }, { k: 'res', x: 200, y: 25, lab: 'R2 1 kΩ' }, { k: 'bat', x: 270, y: 85, rot: 90, lab: '6 V', lx: -18, ly: 4 }, { k: 'res', x: 150, y: 85, rot: 90, lab: 'R3 1 kΩ' }],
      wires: [[30, 55, 30, 25, 70, 25], [130, 25, 170, 25], [230, 25, 270, 25, 270, 55], [150, 25, 150, 55], [150, 115, 150, 145], [30, 115, 30, 145, 270, 145, 270, 115]], dots: [[150, 25], [150, 145]], text: [[145, 12, 'A']] },
    m5_div: { w: 260, h: 190, parts: [{ k: 'bat', x: 40, y: 95, rot: 90, lab: '9 V', lx: -18, ly: 4 }, { k: 'res', x: 150, y: 55, rot: 90, lab: 'R1 1 kΩ' }, { k: 'res', x: 150, y: 135, rot: 90, lab: 'R2 1 kΩ' }],
      wires: [[40, 65, 40, 20, 150, 20, 150, 25], [150, 85, 150, 105], [150, 95, 230, 95], [150, 165, 150, 180, 40, 180, 40, 125], [150, 180, 230, 180]], dots: [[150, 95], [150, 180]], text: [[236, 99, 'A'], [236, 184, 'B']] }
  });

  /* ================= GENERADORES (con pista) ================= */
  const { pick, ri, fmt, fR: gR, fV: gV, MC, N } = Gen.helpers;
  const mA = i => fmt(i * 1000, 2) + ' mA';
  Gen.add('m5_nodeCur', () => {
    let a, b; do { a = pick([2, 3, 5, 6, 7, 9, 10, 12]); b = pick([1, 2, 3, 4, 5, 6, 8]); } while (a === b);
    const R = pick([500, 1000, 2000, 4000, 5000]), I = Math.abs(a - b) / R, ab = a > b;
    const dir = x => x ? 'de A a B' : 'de B a A';
    return MC(`El nudo A está a ${a} V y el nudo B a ${b} V. Entre ellos hay ${gR(R)}. ¿Qué corriente pasa y hacia dónde?`, `${mA(I)}, ${dir(ab)}`, [`${mA(I)}, ${dir(!ab)}`, `${mA((a + b) / R)}, ${dir(ab)}`, `${mA(Math.max(a, b) / R)}, ${dir(ab)}`], `I = (VA − VB) / R = (${a} − ${b}) / ${R} = ${fmt((a - b) / R * 1000, 2)} mA. Va de la tensión alta a la baja.`, { h: 'Resta las dos tensiones de nudo y divide entre la resistencia que las une.' });
  }, 'ba_nodecur');
  Gen.add('m5_nodeV', () => {
    const [V1, V2] = pick([[9, 5], [12, 6], [10, 2], [5, 5], [12, 3], [9, 0]]), [R1, R2, R3] = pick([[1000, 1000, 1000], [1000, 2000, 2000], [2000, 1000, 2000], [1000, 1000, 2000], [2000, 2000, 1000]]);
    const Vn = (V1 / R1 + V2 / R2) / (1 / R1 + 1 / R2 + 1 / R3);
    return { ...N(`Nudo A: R1 = ${gR(R1)} lo une a una pila de ${V1} V, R2 = ${gR(R2)} a otra de ${V2} V y R3 = ${gR(R3)} a masa. ¿Tensión del nudo A, en V?`, Vn, 'V', `Lo que entra por R1 y R2 sale por R3: (${V1} − VA)/${R1} + (${V2} − VA)/${R2} = VA/${R3} → VA = ${fmt(Vn, 2)} V.`, 0.03), h: 'Escribe «lo que entra = lo que sale» en el nudo A usando (V − VA) / R en cada rama, y despeja VA.' };
  }, 'ba_nodal');
  Gen.add('m5_thev', () => {
    const V = pick([6, 9, 10, 12]), [R1, R2] = pick([[1000, 1000], [2000, 2000], [1000, 3000], [3000, 1000], [2000, 6000], [4000, 4000], [6000, 3000]]);
    const Vth = V * R2 / (R1 + R2), Rth = Math.round(R1 * R2 / (R1 + R2));
    return MC(`Divisor de ${V} V con R1 = ${gR(R1)} arriba y R2 = ${gR(R2)} abajo. ¿Equivalente de Thévenin visto desde la salida?`, `${gV(Vth)} y ${gR(Rth)}`, [`${gV(Vth)} y ${gR(R1 + R2)}`, `${gV(V)} y ${gR(Rth)}`, `${gV(V * R1 / (R1 + R2))} y ${gR(Rth)}`, `${gV(Vth)} y ${gR(R2)}`], `Vth es la salida en vacío: ${V} × ${R2} / (${R1} + ${R2}) = ${fmt(Vth, 2)} V. Rth: pila → cable, y R1 queda en paralelo con R2: ${gR(Rth)}.`, { h: 'Vth: la salida del divisor sin carga. Rth: cambia la pila por un cable y mira R1 y R2 desde la salida.' });
  }, 'ba_thev');
  Gen.add('m5_thevLoad', () => {
    const Vth = pick([3, 4.5, 5, 6, 9, 12]), Rth = pick([50, 100, 500, 1000, 2000]), RL = pick([100, 220, 470, 1000, 2200, 4700]);
    const VL = Vth * RL / (Rth + RL);
    return { ...N(`Una salida tiene Vth = ${gV(Vth)} y Rth = ${gR(Rth)}. Le conectas una carga de ${gR(RL)}. ¿Qué tensión queda en la carga, en V?`, VL, 'V', `Rth y la carga forman un divisor: VL = ${fmt(Vth, 2)} × ${RL} / (${Rth} + ${RL}) = ${fmt(VL, 2)} V.`, Math.max(0.02, VL * 0.02)), h: 'Dibuja Vth, Rth y la carga en serie: es un divisor de tensión.' };
  }, 'ba_thevload');
  Gen.add('m5_norton', () => {
    if (Math.random() < 0.5) {
      const Vth = pick([5, 6, 9, 10, 12]), Rth = pick([1000, 2000, 3000, 500]); const IN = Vth / Rth * 1000;
      return { ...N(`Pasas a Norton una salida con Vth = ${Vth} V y Rth = ${gR(Rth)}. ¿Cuánto vale IN, en mA?`, IN, 'mA', `IN es la corriente de cortocircuito: Vth / Rth = ${Vth} / ${Rth} = ${fmt(IN, 2)} mA, con RN = ${gR(Rth)} en paralelo.`, Math.max(0.02, IN * 0.02)), h: 'IN es lo que pasaría si unieras los dos bornes con un cable: Vth / Rth.' };
    }
    const IN = pick([1, 2, 3, 5, 10]), RN = pick([500, 1000, 2000, 4700]); const Vth = IN * RN / 1000;
    return { ...N(`Un equivalente Norton da ${IN} mA con ${gR(RN)} en paralelo. ¿Qué tensión hay entre sus bornes en vacío, en V?`, Vth, 'V', `Sin carga, toda la corriente pasa por RN: V = IN · RN = ${IN} mA × ${gR(RN)} = ${fmt(Vth, 2)} V. Es la Vth del equivalente de Thévenin.`, Math.max(0.02, Vth * 0.02)), h: 'Sin carga, toda la corriente de la fuente tiene que pasar por RN: aplica Ohm.' };
  }, 'ba_norton');
  Gen.add('m5_superpos', () => {
    if (Math.random() < 0.5) {
      const a = pick([2, 3, 4, 4.5, 6]), b = pick([-2, -1.5, 1, 1.5, 2.5, 3]);
      return { ...N(`Con solo la pila 1 encendida (la 2 cambiada por un cable), un nudo está a ${gV(a)}. Con solo la pila 2, a ${gV(b)}. ¿Tensión del nudo con las dos?`, a + b, 'V', `Superposición: se suman los efectos, con su signo: ${fmt(a, 2)} + (${fmt(b, 2)}) = ${fmt(a + b, 2)} V.`, 0.02), h: 'Suma las dos contribuciones respetando el signo de cada una.' };
    }
    const [V1, V2] = pick([[12, 6], [9, 3], [10, 5], [6, 6], [9, 9]]), R = pick([1000, 2000]), R3 = pick([1000, 2000]);
    const par = R * R3 / (R + R3), k = par / (R + par);
    return { ...N(`Dos pilas, de ${V1} V y ${V2} V, llegan a un nudo por ${gR(R)} cada una, y del nudo sale ${gR(R3)} a masa. Por superposición, ¿tensión del nudo, en V?`, (V1 + V2) * k, 'V', `Solo la de ${V1} V: la otra rama (${gR(R)}) queda en paralelo con ${gR(R3)} → ${gR(Math.round(par))}; divisor: ${fmt(V1 * k, 2)} V. Solo la de ${V2} V: ${fmt(V2 * k, 2)} V. Suma: ${fmt((V1 + V2) * k, 2)} V.`, 0.03), h: 'Con una pila sola, la rama de la otra (ya un cable) queda en paralelo con la resistencia a masa: calcula ese divisor.' };
  }, 'ba_superpos');
  Gen.add('m5_maxpow', () => {
    const V = pick([5, 6, 9, 10, 12]), R = pick([2, 4, 5, 8, 10, 50]);
    if (Math.random() < 0.5) { const P = V * V / (4 * R); return MC(`Fuente de ${V} V con resistencia interna de ${gR(R)}. ¿Potencia máxima que puede dar a una carga?`, fmt(P, 3) + ' W', [fmt(V * V / R, 3) + ' W', fmt(V * V / (2 * R), 3) + ' W', fmt(V / (4 * R), 3) + ' W'], `Máximo con RL = Rth = ${gR(R)}: I = ${V} / ${2 * R} A y la mitad de la tensión cae en la carga. P = V² / (4R) = ${fmt(P, 3)} W.`, { h: 'La máxima potencia sale con la carga igual a la resistencia interna: calcula la corriente y luego I² · RL.' }); }
    const RL = R * pick([0.25, 0.5, 2, 4]); const I = V / (R + RL), P = I * I * RL;
    return { ...N(`Fuente de ${V} V con ${gR(R)} internos y una carga de ${gR(RL)}. ¿Potencia en la carga, en W?`, P, 'W', `I = ${V} / (${fmt(R)} + ${fmt(RL)}) = ${fmt(I, 3)} A; P = I² · RL = ${fmt(P, 3)} W.`, Math.max(0.005, P * 0.02)), h: 'Primero la corriente con las dos resistencias en serie; después P = I² · RL.' };
  }, 'ba_maxpow');
  Gen.add('m5_bridge', () => {
    const V = pick([5, 9, 10, 12]), d = pick([-50, -20, -10, 5, 10, 20, 50]), Rx = 1000 + d;
    const Vd = (V * Rx / (1000 + Rx) - V / 2) * 1000;
    return { ...N(`Puente de ${V} V con tres resistencias de 1 kΩ y un sensor de ${Rx} Ω (abajo a la derecha). ¿Tensión entre los puntos medios (derecha − izquierda), en mV?`, Vd, 'mV', `Izquierda: ${fmt(V / 2, 2)} V. Derecha: ${V} × ${Rx} / ${1000 + Rx} = ${fmt(V * Rx / (1000 + Rx), 4)} V. Diferencia: ${fmt(Vd, 1)} mV.`, Math.max(0.3, Math.abs(Vd) * 0.03)), h: 'Calcula cada divisor por separado con varios decimales y resta: derecha menos izquierda.' };
  }, 'ba_bridgecalc');

  /* ================= CONCEPTOS ================= */
  const nodalP = (o = {}) => ({ V1: { label: 'Pila 1', val: 12, min: 0, max: 12, step: 0.5, unit: 'V', dec: 1 }, V2: { label: 'Pila 2', val: 3, min: 0, max: 12, step: 0.5, unit: 'V', dec: 1 }, R1: { val: 1000, fixed: true }, R2: { val: 1000, fixed: true }, R3: { val: 1000, fixed: true }, ...o });
  const thevP = (o = {}) => ({ Vth: { val: 9, fixed: true }, Rth: { label: 'Rth', val: 1000, fmt: 'R', min: 10, max: 10000 }, RL: { label: 'Carga RL', val: 220, fmt: 'R', min: 10, max: 10000 }, ...o });
  const tanks = '<svg viewBox="0 0 300 150" class="viz"><rect x="20" y="30" width="70" height="100" rx="6" fill="none" stroke="currentColor" stroke-width="2"/><rect x="22" y="50" width="66" height="78" fill="var(--ice)" opacity=".45"/><rect x="210" y="30" width="70" height="100" rx="6" fill="none" stroke="currentColor" stroke-width="2"/><rect x="212" y="100" width="66" height="28" fill="var(--ice)" opacity=".45"/><path d="M90 118H210" stroke="currentColor" stroke-width="8" opacity=".25"/><path d="M90 118H210" class="a-flow" stroke="var(--led)" stroke-width="3"/><rect x="132" y="108" width="36" height="20" rx="4" fill="var(--bg)" stroke="currentColor" stroke-width="2"/><text x="150" y="122" text-anchor="middle" class="vizsm">R</text><text x="55" y="22" text-anchor="middle" class="vizlab">A: 8 V</text><text x="245" y="22" text-anchor="middle" class="vizlab">B: 2 V</text><text x="150" y="146" text-anchor="middle" class="vizsm">del nivel alto al bajo: I = (VA − VB) / R</text></svg>';
  const base = k => CONCEPTS[k] ? CONCEPTS[k].alts : [];
  Object.assign(CONCEPTS, {
    ba_nodecur: { name: 'Corriente entre dos nudos', alts: [
      { title: 'Dos depósitos unidos', text: 'Piensa en cada nudo como un depósito de agua a cierta altura (su tensión). Si los unes con un tubo (la resistencia), el agua baja del alto al bajo, y pasa más cuanto mayor es la diferencia y más ancho el tubo: <b>I = (VA − VB) / R</b>.', svg: tanks, q: mcq('Nudo A a 2 V, nudo B a 8 V y 3 kΩ entre ellos. ¿Corriente?', ['2 mA, de B a A', '2 mA, de A a B', '3,3 mA, de B a A', '0,67 mA, de A a B'], '(8 − 2) / 3000 = 2 mA, de la tensión alta (B) a la baja (A).') },
      { title: 'El signo te lo dice', text: 'No hace falta adivinar el sentido. Escribe siempre (VA − VB) / R como si fuera de A a B. Si te sale positivo, acertaste; si sale <b>negativo</b>, la corriente va de B a A con ese mismo valor.', q: mcq('Supones que la corriente va de A a B y te sale −3 mA. ¿Qué significa?', ['Que van 3 mA de B a A', 'Que hay un error en el circuito', 'Que no pasa corriente', 'Que la resistencia es negativa'], 'El signo menos solo indica que el sentido real es el contrario.') }
    ] },
    ba_nodal: { name: 'Análisis nodal', alts: [
      { title: 'Pruébalo moviendo una pila', text: 'Dos pilas empujan hacia el nudo A y de A sale R3 a masa. Sube la pila 2 hasta que valga lo mismo que A: por R2 deja de pasar corriente. La ecuación del nudo dice justo eso: lo que entra por R1 y R2 sale por R3.', tune: { viz: 'nodal', params: nodalP() }, q: mcq('12 V → 1 kΩ → A; 6 V → 1 kΩ → A; y de A, 1 kΩ a masa. ¿VA?', ['6 V', '9 V', '4 V', '18 V'], '(12 − VA) + (6 − VA) = VA (todo entre 1 kΩ) → 18 = 3 · VA → VA = 6 V.') },
      ...base('ba_nodal')
    ] },
    ba_measdiff: { name: 'Cálculo frente a medida', alts: [
      { title: 'Una franja, no un punto', text: 'Con resistencias del ±5 %, un cálculo de 6 V se convierte en una franja de valores posibles, más o menos de 5,7 a 6,3 V. Si tu medida cae dentro, el circuito está bien.', svg: '<svg viewBox="0 0 300 120" class="viz"><path d="M20 70H280" stroke="currentColor" stroke-width="2"/><rect x="95" y="58" width="110" height="24" rx="5" fill="var(--ok)" opacity=".3"/><path d="M150 50V90" stroke="currentColor" stroke-width="2.5"/><circle cx="188" cy="70" r="7" fill="var(--led)" class="a-pulse"/><text x="150" y="42" text-anchor="middle" class="vizlab">cálculo 6 V</text><text x="95" y="102" text-anchor="middle" class="vizsm">5,7 V</text><text x="205" y="102" text-anchor="middle" class="vizsm">6,3 V</text><text x="188" y="118" text-anchor="middle" class="vizsm">medida 6,2 V ✓</text></svg>', q: mcq('Calculas 4,0 V con resistencias del ±5 % y mides 4,15 V. ¿Qué concluyes?', ['Que está dentro de lo esperable', 'Que el cálculo está mal', 'Que el multímetro está roto', 'Que una resistencia está quemada'], 'Un 4 % de diferencia encaja con resistencias del 5 %.') },
      { title: 'Busca primero lo pequeño', text: 'Si medida y cálculo no coinciden, antes de dudar de Kirchhoff repasa lo habitual: la tolerancia de las resistencias, que la pila no da exactamente lo que dice su etiqueta y que el voltímetro también carga un poco el circuito. Solo una diferencia grande (un 30 %, el doble…) indica un error de montaje o de cuentas.', q: mcq('Calculas 6 V y mides 3 V. ¿Qué es lo más probable?', ['Un error de montaje o de cálculo', 'La tolerancia de las resistencias', 'Que Kirchhoff no se cumple', 'Que es normal'], 'Un 50 % es demasiado para las tolerancias: revisa el montaje y las cuentas.') }
    ] },
    ba_thev: { name: 'Equivalente de Thévenin', alts: [
      { title: 'La caja negra', text: 'Desde dos bornes, cualquier red de pilas y resistencias se comporta como <b>una pila Vth con una resistencia Rth en serie</b>. Vth es lo que mides sin carga; Rth dice cuánto «se hunde» la salida al cargarla. Prueba: con Rth pequeña la salida apenas cae.', tune: { viz: 'thevenin', params: thevP() }, q: mcq('Una salida tiene Rth = 10 Ω y otra Rth = 10 kΩ, las dos con 5 V en vacío. ¿Cuál aguanta mejor una carga de 1 kΩ?', ['La de 10 Ω', 'La de 10 kΩ', 'Las dos igual', 'Ninguna da tensión'], 'Con Rth pequeña casi toda la tensión queda en la carga.') },
      { title: 'Receta con un divisor', text: '1) <b>Vth</b>: quita la carga y calcula la tensión entre los bornes (en un divisor, V · R2 / (R1 + R2)).\n2) <b>Rth</b>: cambia cada pila por un cable y calcula la resistencia que se ve desde los bornes. En un divisor, R1 y R2 quedan en paralelo.\nEjemplo: 12 V con 2 kΩ y 2 kΩ → 6 V y 1 kΩ.', q: mcq('Divisor de 10 V con R1 = 3 kΩ arriba y R2 = 6 kΩ abajo. ¿Thévenin?', ['6,67 V y 2 kΩ', '6,67 V y 9 kΩ', '3,33 V y 2 kΩ', '10 V y 2 kΩ'], 'Vth = 10 × 6/9 ≈ 6,67 V; Rth = 3 ∥ 6 = 2 kΩ.') }
    ] },
    ba_thevload: { name: 'Tensión con carga (Thévenin)', alts: [
      { title: 'Rth y la carga hacen un divisor', text: 'Con el equivalente ya hecho, conectar una carga es fácil: Vth, Rth y RL quedan en serie y forman un divisor. <b>VL = Vth · RL / (Rth + RL)</b>. Mueve RL y mira cómo cae la salida.', tune: { viz: 'thevenin', params: thevP({ Rth: { val: 500, fixed: true }, Vth: { val: 4.5, fixed: true } }) }, q: mcq('Vth = 4,5 V, Rth = 500 Ω y una carga de 500 Ω. ¿VL?', ['2,25 V', '4,5 V', '0 V', '9 V'], 'Rth = RL: la tensión se reparte a medias.') },
      { title: 'Con números', text: 'Vth = 12 V, Rth = 1 kΩ, carga de 3 kΩ. Corriente: 12 / 4000 = 3 mA. En la carga: 3 mA × 3 kΩ = 9 V. Se pierden 3 V dentro de la «caja». Atajo: la carga se lleva RL / (Rth + RL) = 3/4 de Vth.', q: mcq('Vth = 10 V, Rth = 1 kΩ, carga de 4 kΩ. ¿VL?', ['8 V', '10 V', '2 V', '2,5 V'], '10 × 4/5 = 8 V.') }
    ] },
    ba_intres: { name: 'Resistencia interna de una pila', alts: [
      { title: 'Una resistencia escondida', text: 'Una pila real es una pila ideal con una pequeña resistencia dentro: su Thévenin. Sin carga mides la tensión completa; al pedir corriente, parte de la tensión se queda dentro. <b>r = (Vvacío − Vcarga) / I</b>.', svg: '<svg viewBox="0 0 300 165" class="viz"><rect x="20" y="25" width="150" height="100" rx="12" fill="none" stroke="var(--muted)" stroke-dasharray="5 4"/><text x="28" y="20" class="vizsm">pila real</text><rect x="40" y="55" width="24" height="44" rx="4" fill="var(--board)"/><rect x="40" y="55" width="24" height="10" rx="3" fill="#E5484D"/><path d="M52 55V40H90M140 40H190V60M190 102V140H52V99" stroke="currentColor" stroke-width="2.2" fill="none"/><path d="M94 40l3 -6l6 12l6 -12l6 12l6 -12l6 12l3 -6" stroke="var(--err)" stroke-width="2.2" fill="none"/><text x="115" y="30" text-anchor="middle" class="vizsm" style="fill:var(--err)">r</text><rect x="178" y="60" width="24" height="42" rx="4" fill="none" stroke="currentColor" stroke-width="2"/><text x="214" y="86" class="vizsm">carga</text><path d="M52 40H190" class="a-flow-slow" stroke="var(--led)" stroke-width="2"/><text x="150" y="160" text-anchor="middle" class="vizsm">la tensión que se queda en r no llega fuera</text></svg>', q: mcq('Una pila da 1,6 V en vacío y 1,4 V dando 0,5 A. ¿Resistencia interna?', ['0,4 Ω', '2,8 Ω', '3,2 Ω', '0,1 Ω'], '0,2 V perdidos / 0,5 A = 0,4 Ω.') },
      { title: 'Con números', text: 'Una pila de 9 V marca 9,3 V sin nada conectado. Con una carga que pide 0,3 A, baja a 7,5 V. Se han perdido 1,8 V dentro: r = 1,8 / 0,3 = <b>6 Ω</b>. Por eso las pilas pequeñas no sirven para motores: con mucha corriente, casi toda la tensión se queda dentro.', q: mcq('Una pila tiene 2 Ω internos. ¿Cuánto baja su tensión al dar 0,5 A?', ['1 V', '0,25 V', '4 V', 'Nada'], 'Caída interna = I · r = 0,5 × 2 = 1 V.') }
    ] },
    ba_isource: { name: 'La fuente de corriente', alts: [
      { title: 'Una cinta transportadora', text: 'Una pila fija la <b>tensión</b> y deja que la corriente sea la que salga. Una fuente de corriente ideal hace lo contrario: fija la <b>corriente</b>, como una cinta que mueve siempre las mismas cajas por segundo, y su tensión sube o baja lo que haga falta. Se dibuja como un círculo con una flecha.', svg: '<svg viewBox="0 0 300 140" class="viz"><circle cx="60" cy="70" r="22" fill="none" stroke="currentColor" stroke-width="2.2"/><path d="M60 84V56M52 64l8 -8l8 8" stroke="currentColor" stroke-width="2.2" fill="none"/><text x="60" y="118" text-anchor="middle" class="vizlab">2 mA siempre</text><path d="M120 40h160M120 100h160" stroke="var(--line)"/><text x="200" y="34" text-anchor="middle" class="vizsm">con 1 kΩ → 2 V</text><text x="200" y="66" text-anchor="middle" class="vizsm">con 2 kΩ → 4 V</text><text x="200" y="98" text-anchor="middle" class="vizsm">con 5 kΩ → 10 V</text><text x="200" y="128" text-anchor="middle" class="vizsm">la tensión se adapta: V = I · R</text></svg>', q: mcq('Una fuente de corriente ideal de 3 mA alimenta 2 kΩ. ¿Tensión en la resistencia?', ['6 V', '3 V', '1,5 V', 'Depende de la pila'], 'La corriente está fijada: V = 3 mA × 2 kΩ = 6 V.') },
      { title: 'La tienes en la mesa', text: 'Tu fuente de laboratorio en modo de corriente constante (CC) se porta como una fuente de corriente: si la carga cambia, ajusta la tensión para mantener la corriente fijada, hasta el tope de tensión que le hayas puesto. Una fuente de corriente ideal tendría una resistencia interna infinita.', q: mcq('¿Qué hace una fuente de corriente ideal si la resistencia de carga se duplica?', ['Duplica su tensión para mantener la corriente', 'Reduce la corriente a la mitad', 'Mantiene la tensión', 'Se apaga'], 'La corriente no cambia; la tensión V = I · R sí.') }
    ] },
    ba_norton: { name: 'Norton y la conversión Thévenin ↔ Norton', alts: [
      { title: 'Compruébalo con la caja', text: 'La caja de Norton es una fuente de corriente IN con RN en paralelo. La corriente se reparte entre RN y la carga; cuanto mayor es RN frente a la carga, más corriente llega a la carga. Fíjate abajo: la misma caja vista como Thévenin da Vth = IN · RN con Rth = RN.', tune: { viz: 'norton', params: { IN: { label: 'IN', val: 3, min: 0.5, max: 10, step: 0.5, unit: 'mA', dec: 1 }, RN: { label: 'RN', val: 3000, list: [100, 1000, 3000, 10000, 100000], fmt: 'R' }, RL: { label: 'Carga RL', val: 1000, fmt: 'R', min: 100, max: 100000 } } }, q: mcq('Norton de 3 mA con 3 kΩ. ¿Thévenin equivalente?', ['9 V con 3 kΩ en serie', '1 V con 3 kΩ en serie', '9 V con 1 kΩ en serie', '3 V con 3 kΩ en serie'], 'Vth = IN · RN = 3 mA × 3 kΩ = 9 V; Rth = RN.') },
      ...base('ba_norton')
    ] },
    ba_rthmeas: { name: 'Medir la resistencia de Thévenin', alts: [
      { title: 'Dos medidas', text: 'Para medir Rth desde fuera, mide la tensión en vacío y luego con una carga conocida. Lo que «desaparece» se ha quedado en Rth: <b>Rth = (Vvacío − Vcarga) / Icarga</b>. Si cortocircuitar no daña nada, también vale Rth = Vvacío / Icorto.', svg: '<svg viewBox="0 0 300 130" class="viz"><rect x="15" y="25" width="90" height="80" rx="10" fill="none" stroke="var(--muted)" stroke-dasharray="5 4"/><text x="60" y="70" text-anchor="middle" class="vizlab">caja</text><path d="M105 45H135M105 85H135" stroke="currentColor" stroke-width="2"/><text x="145" y="36" class="vizsm">sin carga: 5 V</text><text x="145" y="58" class="vizsm">con 400 Ω: 4 V</text><text x="145" y="80" class="vizsm">I = 4 V / 400 Ω = 10 mA</text><text x="145" y="104" class="vizlab">Rth = 1 V / 10 mA</text><text x="145" y="122" class="vizlab">= 100 Ω</text></svg>', q: mcq('6 V en vacío y 5 V con una carga de 50 Ω. ¿Rth?', ['10 Ω', '50 Ω', '1 Ω', '60 Ω'], 'I = 5 / 50 = 0,1 A; Rth = 1 V / 0,1 A = 10 Ω.') },
      { title: 'Por qué no siempre cortocircuitar', text: 'Vvacío / Icorto es el atajo, pero un cortocircuito en una pila o una fuente potente puede calentar, quemar pistas o dañar algo. Con una carga conocida obtienes lo mismo sin riesgo: es un divisor entre Rth y tu carga.', q: mcq('Una salida da 12 V en vacío y 200 mA en cortocircuito. ¿Rth?', ['60 Ω', '2,4 Ω', '0,6 Ω', '600 Ω'], '12 / 0,2 = 60 Ω.') }
    ] },
    ba_superpos: { name: 'Superposición', alts: [
      { title: 'Enciende y apaga las pilas', text: 'Pon a 0 una pila (se cambia por un cable) y mira la tensión del nudo; luego al revés; y luego las dos. La tensión con las dos es la suma de las otras dos.', tune: { viz: 'nodal', params: nodalP({ V1: { val: 12, fixed: true }, V2: { val: 6, fixed: true }, on1: { label: 'Pila 1 (1 = puesta, 0 = cable)', val: 1, list: oneOf, dec: 0 }, on2: { label: 'Pila 2 (1 = puesta, 0 = cable)', val: 1, list: oneOf, dec: 0 } }) }, q: mcq('Solo la pila 1: VA = 4 V. Solo la pila 2: VA = 2 V. ¿Con las dos?', ['6 V', '4 V', '2 V', '8 V'], 'Se suman los efectos: 4 + 2.') },
      ...base('ba_superpos')
    ] },
    ba_linear: { name: 'Cuándo vale la superposición', alts: [
      { title: 'Recta sí, curva no', text: 'La superposición solo funciona si cada componente es <b>lineal</b>: su gráfica tensión–corriente es una recta, como la de una resistencia. El LED tiene un codo: con la mitad de tensión no da la mitad de corriente, así que sumar efectos por separado falla.', svg: '<svg viewBox="0 0 260 150" class="viz"><path d="M30 130H245M30 130V15" stroke="currentColor" stroke-width="2"/><path d="M30 130L230 40" stroke="var(--ice)" stroke-width="3"/><path d="M30 130C120 129 150 126 170 110S190 40 200 15" stroke="var(--err)" stroke-width="3" fill="none"/><text x="70" y="72" class="vizsm" style="fill:var(--ice)">resistencia: sí</text><text x="120" y="30" class="vizsm" style="fill:var(--err)">LED: no</text><text x="238" y="144" class="vizsm">V</text><text x="14" y="20" class="vizsm">I</text></svg>', q: mcq('¿En qué circuito puedes usar superposición?', ['Uno con dos pilas y solo resistencias', 'Uno con un LED', 'Cualquiera', 'Ninguno con dos pilas'], 'Hace falta que todo sea lineal.') },
      { title: 'Las potencias no se suman', text: 'Aunque el circuito sea lineal, la potencia va con el <b>cuadrado</b> de la corriente. Si una fuente sola da 3 mA por 1 kΩ (9 mW) y la otra 1 mA (1 mW), juntas dan 4 mA: 16 mW, no 10 mW. Suma corrientes o tensiones y calcula la potencia al final.', q: mcq('Una fuente sola hace pasar 2 mA por 1 kΩ y la otra, en el mismo sentido, 2 mA. ¿Potencia en la resistencia con las dos?', ['16 mW', '8 mW', '4 mW', '2 mW'], '4 mA juntas: 0,004² × 1000 = 16 mW.') }
    ] },
    ba_maxpow: { name: 'Máxima transferencia de potencia', alts: [
      { title: 'Busca el pico', text: 'Mueve la carga: con RL pequeña pasa mucha corriente pero la carga apenas tiene tensión; con RL grande hay tensión pero casi no hay corriente. El pico de potencia está justo en <b>RL = Rth</b>.', tune: { viz: 'maxPower', params: { V: { val: 10, fixed: true }, Rth: { val: 10, fixed: true }, RL: { label: 'Carga RL', val: 2.2, list: [1, 2.2, 4.7, 6.8, 10, 15, 22, 47, 100], unit: 'Ω', dec: 1 } } }, q: mcq('Una fuente tiene 4 Ω internos. ¿Con qué carga le sacas más potencia?', ['4 Ω', '0 Ω', 'La más grande posible', '2 Ω'], 'Máxima potencia con RL = Rth.') },
      ...base('ba_maxpow')
    ] },
    ba_adapt: { name: 'Rendimiento: adaptar o no', alts: [
      { title: 'Dónde se va la energía', text: 'En RL = Rth la carga recibe el máximo, pero la fuente calienta lo mismo por dentro: <b>rendimiento del 50 %</b>. Con RL mucho mayor que Rth la carga recibe algo menos que el máximo, pero casi nada se desperdicia. Para alimentar cosas se busca rendimiento; para señales débiles (antenas, micrófonos) se busca el máximo.', svg: '<svg viewBox="0 0 300 120" class="viz"><text x="20" y="22" class="vizlab">RL = Rth</text><rect x="20" y="30" width="130" height="18" rx="4" fill="var(--err)" opacity=".7"/><rect x="150" y="30" width="130" height="18" rx="4" fill="var(--ok)" opacity=".8"/><text x="85" y="62" text-anchor="middle" class="vizsm">calor dentro 50 %</text><text x="215" y="62" text-anchor="middle" class="vizsm">en la carga 50 %</text><text x="20" y="86" class="vizlab">RL = 9 · Rth</text><rect x="20" y="94" width="26" height="18" rx="4" fill="var(--err)" opacity=".7"/><rect x="46" y="94" width="234" height="18" rx="4" fill="var(--ok)" opacity=".8"/><text x="163" y="107" text-anchor="middle" class="vizsm" style="fill:#fff">en la carga 90 %</text></svg>', q: mcq('Rth = 1 Ω y RL = 9 Ω. ¿Rendimiento?', ['90 %', '50 %', '10 %', '100 %'], 'η = RL / (Rth + RL) = 9/10.') },
      { title: 'Ejemplos de la vida real', text: 'Una batería tiene Rth muy pequeña frente a lo que alimenta: buen rendimiento y poco calor. Un amplificador de audio también tiene Rth muy baja y pide una carga mínima (4 u 8 Ω): no busca adaptación. En cambio, una antena o un micrófono dan tan poca potencia que interesa aprovecharla toda: ahí sí se adapta.', q: mcq('¿En cuál interesa adaptar (RL = Rth)?', ['Una antena que entrega una señal muy débil', 'Una batería que alimenta un motor', 'Un cargador de móvil', 'Una linterna'], 'Con señales débiles importa sacar el máximo, no el rendimiento.') }
    ] },
    ba_bridge: { name: 'Puente de Wheatstone', alts: [
      { title: 'Equilíbralo tú', text: 'Tres resistencias de 1 kΩ y un sensor. Cuando el sensor vale lo mismo que su pareja, los dos divisores dan la misma tensión y el medidor marca 0. Un cambio pequeño del sensor aparece como unos milivoltios alrededor de cero, fáciles de ver.', tune: { viz: 'bridge', params: { V: { val: 10, fixed: true }, Rx: { label: 'Sensor Rx', val: 1030, min: 950, max: 1050, step: 1, unit: 'Ω', dec: 0 } } }, q: mcq('El puente está equilibrado. ¿Qué marca el medidor central?', ['0 V', 'La mitad de la pila', 'La pila entera', 'Depende del sensor'], 'Equilibrado = las dos mitades dan la misma tensión.') },
      ...base('ba_bridge')
    ] },
    ba_bridgecalc: { name: 'Calcular un puente', alts: [
      { title: 'Dos divisores y una resta', text: 'Calcula cada lado como un divisor normal y resta. 10 V; izquierda 1 kΩ/1 kΩ → 5 V. Derecha 1 kΩ arriba y sensor de 1020 Ω abajo → 10 × 1020 / 2020 = 5,0495 V. Diferencia: <b>49,5 mV</b>. Usa varios decimales: la resta se come las cifras.', svg: '<svg viewBox="0 0 300 110" class="viz"><rect x="20" y="20" width="110" height="34" rx="6" fill="none" stroke="currentColor" stroke-width="2"/><text x="75" y="42" text-anchor="middle" class="vizlab">5,0000 V</text><rect x="170" y="20" width="110" height="34" rx="6" fill="none" stroke="var(--ice)" stroke-width="2"/><text x="225" y="42" text-anchor="middle" class="vizlab">5,0495 V</text><text x="150" y="42" text-anchor="middle" class="vizlab">−</text><text x="150" y="86" text-anchor="middle" class="vizbig">= 49,5 mV</text></svg>', q: mcq('10 V, tres de 1 kΩ y un sensor de 980 Ω. ¿Diferencia aproximada (derecha − izquierda)?', ['Unos −50 mV', 'Unos +50 mV', '0 V', 'Unos −5 V'], 'Derecha: 10 × 980 / 1980 ≈ 4,949 V; menos 5 V: unos −51 mV.') },
      { title: 'La condición de equilibrio', text: 'El puente está en equilibrio cuando los dos divisores tienen la misma proporción: <b>R1 / R2 = R3 / Rx</b>. Así puedes medir una resistencia desconocida: ajustas una conocida hasta que el medidor marca 0 y despejas Rx = R3 · R2 / R1.', q: mcq('R1 = 1 kΩ, R2 = 2 kΩ, R3 = 3 kΩ. ¿Qué Rx equilibra el puente?', ['6 kΩ', '1,5 kΩ', '3 kΩ', '0,67 kΩ'], 'Rx = R3 · R2 / R1 = 3 × 2 / 1 = 6 kΩ.') }
    ] }
  });

  // Arregla frases de alternativas heredadas que nombraban cosas aún no vistas en esta parte del curso
  const fixAlt = (k, title, pairs) => { const a = CONCEPTS[k].alts.find(x => x.title === title); if (!a) return; const r = s => pairs.reduce((x, [f, t]) => x.split(f).join(t), s); a.text = r(a.text); if (a.q) { a.q.q = r(a.q.q); a.q.e = r(a.q.e); a.q.o = a.q.o.map(r); } };
  fixAlt('ba_norton', 'La fuente de corriente', [['Es el modelo natural de cosas como un fotodiodo o un transistor en zona activa.', 'Tu fuente de laboratorio en modo CC se porta así.']]);
  fixAlt('ba_superpos', 'De una en una', [['(no con LEDs ni transistores)', '(no con LEDs)']]);
  fixAlt('ba_superpos', 'Apagar fuentes', [['Con un diodo o un LED no funciona.', 'Con un LED no funciona.']]);
  /* ================= LECCIONES ================= */
  const nodalSVG = '<svg viewBox="0 0 300 150" class="viz"><path d="M30 60V25H75M117 25H183M225 25H270V60M150 25V55M150 97V125M30 100V125H270V100" stroke="currentColor" stroke-width="2.2" fill="none"/><path d="M75 25l3 -6l6 12l6 -12l6 12l6 -12l6 12l6 -12l3 6M183 25l3 -6l6 12l6 -12l6 12l6 -12l6 12l6 -12l3 6M150 55l-6 3l12 6l-12 6l12 6l-12 6l12 6l-12 6l6 3" stroke="currentColor" stroke-width="2.2" fill="none"/><rect x="18" y="60" width="24" height="40" rx="4" fill="var(--board)"/><rect x="258" y="60" width="24" height="40" rx="4" fill="var(--board)"/><circle cx="150" cy="25" r="7" fill="var(--led)" class="a-pulse"/><text x="160" y="16" class="vizlab">A = ?</text><circle cx="150" cy="125" r="4" fill="currentColor"/><text x="150" y="143" text-anchor="middle" class="vizsm">masa: 0 V (la eliges tú)</text><text x="48" y="84" class="vizlab">12 V</text><text x="252" y="84" text-anchor="end" class="vizlab">6 V</text></svg>';
  const kclSVG = '<svg viewBox="0 0 300 140" class="viz"><circle cx="150" cy="70" r="9" fill="var(--led)"/><path d="M30 70H140" stroke="currentColor" stroke-width="2"/><path d="M30 70H140" class="a-flow" stroke="var(--led)" stroke-width="3"/><path d="M270 70H160" stroke="currentColor" stroke-width="2"/><path d="M270 70H160" class="a-flow" stroke="var(--led)" stroke-width="3"/><path d="M150 80V130" stroke="currentColor" stroke-width="2"/><path d="M150 80V130" class="a-flow" stroke="var(--ice)" stroke-width="3"/><text x="70" y="60" class="vizsm">(12 − VA) / 1k</text><text x="185" y="60" class="vizsm">(6 − VA) / 1k</text><text x="160" y="118" class="vizsm">VA / 1k</text><text x="150" y="22" text-anchor="middle" class="vizlab">lo que entra = lo que sale</text></svg>';
  const boxSVG = '<svg viewBox="0 0 300 150" class="viz"><rect x="15" y="25" width="110" height="100" rx="10" fill="var(--board)"/><text x="70" y="70" text-anchor="middle" class="vizsm" style="fill:#fff">pilas y</text><text x="70" y="86" text-anchor="middle" class="vizsm" style="fill:#fff">resistencias</text><path d="M125 50H140M125 100H140" stroke="currentColor" stroke-width="2.2"/><circle cx="143" cy="50" r="3.5" fill="currentColor"/><circle cx="143" cy="100" r="3.5" fill="currentColor"/><text x="160" y="80" class="vizbig">=</text><rect x="180" y="25" width="110" height="100" rx="10" fill="none" stroke="var(--muted)" stroke-dasharray="5 4"/><rect x="195" y="62" width="20" height="34" rx="3" fill="var(--board)"/><path d="M205 62V45H225M255 45H290M205 96V110H290" stroke="currentColor" stroke-width="2.2" fill="none"/><path d="M225 45l3 -6l5 12l5 -12l5 12l5 -12l2 6" stroke="var(--led)" stroke-width="2.2" fill="none"/><text x="205" y="120" text-anchor="middle" class="vizsm">Vth</text><text x="240" y="64" text-anchor="middle" class="vizsm">Rth</text><circle cx="290" cy="45" r="3.5" fill="currentColor" class="a-pulse"/><circle cx="290" cy="110" r="3.5" fill="currentColor" class="a-pulse"/></svg>';
  const rthSVG = '<svg viewBox="0 0 300 170" class="viz"><path d="M40 30H150V39M150 81V111M150 153V160H40M150 96H240" stroke="currentColor" stroke-width="2.2" fill="none"/><path d="M40 30V160" stroke="var(--ok)" stroke-width="3.5"/><text x="48" y="100" class="vizsm" style="fill:var(--ok)">pila → cable</text><path d="M150 39l-6 3l12 6l-12 6l12 6l-12 6l12 6l-12 6l6 3M150 111l-6 3l12 6l-12 6l12 6l-12 6l12 6l-12 6l6 3" stroke="currentColor" stroke-width="2.2" fill="none"/><text x="140" y="64" text-anchor="end" class="vizsm">1 kΩ</text><text x="140" y="136" text-anchor="end" class="vizsm">1 kΩ</text><circle cx="150" cy="96" r="3.5" fill="currentColor"/><circle cx="244" cy="96" r="4" fill="var(--bg)" stroke="currentColor" stroke-width="2" class="a-pulse"/><text x="290" y="84" text-anchor="end" class="vizsm">mirando desde aquí</text><text x="225" y="140" text-anchor="middle" class="vizlab">1 kΩ ∥ 1 kΩ</text><text x="225" y="158" text-anchor="middle" class="vizlab">= 500 Ω</text></svg>';
  const twoBoxes = '<svg viewBox="0 0 300 150" class="viz"><rect x="10" y="20" width="125" height="105" rx="10" fill="none" stroke="var(--muted)" stroke-dasharray="5 4"/><text x="72" y="16" text-anchor="middle" class="vizsm">Thévenin</text><rect x="25" y="55" width="18" height="34" rx="3" fill="var(--board)"/><path d="M34 55V40H60M100 40H130M34 89V110H130" stroke="currentColor" stroke-width="2.2" fill="none"/><path d="M60 40l3 -6l5 12l5 -12l5 12l5 -12l5 12l5 -12l2 6" stroke="currentColor" stroke-width="2.2" fill="none"/><text x="34" y="122" text-anchor="middle" class="vizsm">9 V</text><text x="80" y="60" text-anchor="middle" class="vizsm">3 kΩ</text><rect x="165" y="20" width="125" height="105" rx="10" fill="none" stroke="var(--muted)" stroke-dasharray="5 4"/><text x="228" y="16" text-anchor="middle" class="vizsm">Norton</text><circle cx="195" cy="72" r="15" fill="none" stroke="currentColor" stroke-width="2.2"/><path d="M195 82V62M190 67l5 -5l5 5M195 57V40H290M195 87V110H290M250 40V55M250 89V110" stroke="currentColor" stroke-width="2.2" fill="none"/><path d="M250 55l-5 3l10 5l-10 5l10 5l-10 5l10 5l-5 2" stroke="currentColor" stroke-width="2.2" fill="none"/><text x="195" y="122" text-anchor="middle" class="vizsm">3 mA</text><text x="262" y="76" class="vizsm">3 kΩ</text><text x="150" y="80" text-anchor="middle" class="vizbig">⇄</text><text x="150" y="146" text-anchor="middle" class="vizsm">desde los bornes de la derecha no se distinguen</text></svg>';
  const offSVG = '<svg viewBox="0 0 300 130" class="viz"><rect x="25" y="25" width="22" height="40" rx="4" fill="var(--board)"/><text x="36" y="84" text-anchor="middle" class="vizsm">pila</text><text x="75" y="50" class="vizbig">→</text><path d="M120 25V65" stroke="var(--ok)" stroke-width="3.5"/><text x="120" y="84" text-anchor="middle" class="vizsm">cable (0 V)</text><circle cx="185" cy="45" r="16" fill="none" stroke="currentColor" stroke-width="2.2"/><path d="M185 55V35M179 41l6 -6l6 6" stroke="currentColor" stroke-width="2.2" fill="none"/><text x="185" y="84" text-anchor="middle" class="vizsm">f. de corriente</text><text x="214" y="50" class="vizbig">→</text><path d="M255 20V36M255 54V70" stroke="var(--ok)" stroke-width="3.5"/><text x="255" y="84" text-anchor="middle" class="vizsm">hueco (0 A)</text><text x="150" y="118" text-anchor="middle" class="vizsm">apagar = dejarla en 0, sin quitar su sitio</text></svg>';
  const peakSVG = '<svg viewBox="0 0 300 150" class="viz"><path d="M30 120H285M30 120V20" stroke="currentColor" stroke-width="2"/><path d="M30 118C80 70 120 30 150 28S230 70 285 100" stroke="var(--led)" stroke-width="3" fill="none" class="a-draw" style="--len:320"/><path d="M150 28V120" stroke="var(--muted)" stroke-dasharray="4 4"/><circle cx="150" cy="28" r="6" fill="var(--led)" class="a-pulse"/><text x="150" y="138" text-anchor="middle" class="vizsm">RL = Rth</text><text x="40" y="138" class="vizsm">RL pequeña</text><text x="285" y="138" text-anchor="end" class="vizsm">RL grande</text><text x="36" y="18" class="vizsm">potencia en la carga</text></svg>';
  const bridgeSVG = '<svg viewBox="0 0 300 160" class="viz"><path d="M150 20L80 80L150 140L220 80Z" stroke="currentColor" stroke-width="2.2" fill="none"/><path d="M80 80H128M172 80H220" stroke="var(--muted)" stroke-width="2"/><circle cx="150" cy="80" r="20" fill="var(--bg)" stroke="var(--ok)" stroke-width="2.5"/><text x="150" y="85" text-anchor="middle" class="vizlab">0 V</text><text x="102" y="44" text-anchor="end" class="vizsm">R1</text><text x="102" y="124" text-anchor="end" class="vizsm">R2</text><text x="198" y="44" class="vizsm">R3</text><text x="198" y="124" class="vizsm" style="fill:var(--ice)">sensor</text><text x="150" y="14" text-anchor="middle" class="vizsm">+ pila</text><text x="150" y="156" text-anchor="middle" class="vizsm">masa</text><circle cx="80" cy="80" r="4" fill="currentColor" class="a-pulse"/><circle cx="220" cy="80" r="4" fill="currentColor" class="a-pulse"/><text x="20" y="84" class="vizsm">4,5 V</text><text x="232" y="84" class="vizsm">4,5 V</text></svg>';
  const gaugeSVG = '<svg viewBox="0 0 300 130" class="viz"><rect x="40" y="40" width="220" height="16" rx="3" fill="var(--line)"/><path d="M60 48h20v-6h20v12h20v-12h20v12h20v-12h20v12h20v-6h20" stroke="var(--ice)" stroke-width="2" fill="none"/><path d="M150 60v30" stroke="currentColor" stroke-width="2"/><path d="M140 84l10 10l10 -10" stroke="currentColor" stroke-width="2" fill="none" class="a-bob"/><text x="150" y="110" text-anchor="middle" class="vizsm">al doblarse, el hilo se estira</text><text x="150" y="124" text-anchor="middle" class="vizsm">y su resistencia sube un poquito</text><text x="150" y="28" text-anchor="middle" class="vizlab">galga extensiométrica</text></svg>';

  UNITS.push({ id: 'm5', title: 'Análisis de circuitos', desc: 'Análisis nodal, Thévenin, Norton, superposición, máxima potencia y puente de Wheatstone.', nodes: [
    L('d12', 'Análisis nodal sencillo', 'node', ['ba_nodal', 'ba_nodecur', 'ba_measdiff'], [
      Q('Una pila de 12 V y otra de 6 V empujan, cada una por su resistencia, hacia el mismo punto, y de ahí sale una resistencia a masa. ¿Qué crees que hace la pila de 6 V?', ['Depende: puede dar corriente, recibirla o ninguna de las dos', 'Siempre da corriente', 'Siempre recibe corriente de la otra'], 'Depende de la tensión de ese punto. Si vale más de 6 V, la corriente entra en la pila pequeña; si vale menos, sale de ella; si vale justo 6 V, no pasa nada. Vamos a verlo.', { predict: true, c: 'ba_nodal', h: 'Compara la tensión de ese punto con los 6 V de la pila pequeña.' }),
      I('Con serie, paralelo y Kirchhoff ya resuelves muchos circuitos. Pero con <b>dos pilas</b> que empujan hacia el mismo punto no hay ni serie ni paralelo puros. Para eso está el <b>análisis nodal</b>: averiguar la tensión de cada nudo.', { svg: nodalSVG, more: 'Un nudo es un punto donde se unen dos o más componentes. Si conoces la tensión de todos los nudos, con la ley de Ohm sacas cualquier corriente.\nEs el método que usan los simuladores de circuitos: escala a circuitos de miles de componentes.' }),
      { t: 'explore', text: 'Dos pilas empujan hacia el nudo A; de A sale R3 a masa. Las tres resistencias son de 1 kΩ. Mueve las pilas y mira las corrientes y sus flechas.', viz: 'nodal', params: nodalP(),
        tasks: [
          { q: 'I2abs', min: 0, max: 0.05, text: 'Haz que por R2 no pase corriente', done: 'Con la pila 2 a 6 V, A también vale 6 V: sin diferencia de tensión no hay corriente.', hint: 'Sube la pila 2 poco a poco y mira la flecha de R2.' },
          { q: 'VA', min: 3.95, max: 4.05, text: 'Ahora consigue que A valga 4 V', done: 'Con la pila 2 a 0 V, A queda en 4 V… y la corriente entra en la pila 2 (flecha hacia la derecha).', hint: 'Baja la pila 2 del todo.' },
          { q: 'I3mA', min: 7.9, max: 8.1, text: 'Consigue 8 mA por R3', done: 'A 8 V: las dos pilas a 12 V dan 4 mA cada una y se juntan en R3.', hint: 'Por R3 pasa VA / 1 kΩ: necesitas A = 8 V.' }
        ] },
      I('<b>Receta, paso 1</b>: elige un nudo como <b>masa</b> (0 V); suele ser el negativo de las pilas. Luego da un nombre (A, B…) a cada nudo cuya tensión no conoces. Los demás ya los sabes: el + de una pila de 12 V está a 12 V.', { svg: nodalSVG }),
      I('<b>Paso 2</b>: la corriente por una resistencia que une dos nudos es <b>(VA − VB) / R</b> y va del nudo de más tensión al de menos. Si al calcular sale negativa, simplemente iba al revés.', { svg: tanks }),
      Q('Entre un nudo a 7 V y otro a 3 V hay 2 kΩ. ¿Qué corriente pasa?', ['2 mA, del de 7 V al de 3 V', '5 mA, del de 7 V al de 3 V', '2 mA, del de 3 V al de 7 V', '3,5 mA'], '(7 − 3) / 2000 = 2 mA, de la tensión alta a la baja.', { c: 'ba_nodecur', h: 'Resta las dos tensiones y divide entre la resistencia.' }),
      I('<b>Paso 3</b>: en cada nudo desconocido, <b>lo que entra = lo que sale</b> (la ley de nudos). Escribe cada corriente con (V − VA) / R y despeja VA.', { svg: kclSVG }),
      { t: 'steps', text: '12 V → 1 kΩ → nudo A; 6 V → 1 kΩ → A; y de A, 1 kΩ a masa. ¿Cuánto vale VA?', sch: 'm5_nodal', steps: ['Entra por R1: <b>(12 − VA) / 1k</b>. Entra por R2: <b>(6 − VA) / 1k</b>. Sale por R3: <b>VA / 1k</b>.', 'Lo que entra = lo que sale: (12 − VA) + (6 − VA) = VA (los 1k se van, son iguales).', '18 − 2·VA = VA → 18 = 3·VA', '<b>VA = 6 V</b>. Por R1 pasan (12 − 6) / 1k = 6 mA; por R2, (6 − 6) / 1k = 0 mA.'], result: 'VA = 6 V: la pila de 6 V ni da ni recibe corriente.' },
      Nm('En ese ejemplo, ¿qué corriente sale de la pila de 6 V, en mA?', 0, 'mA', 'VA = 6 V: en R2 no hay diferencia de tensión, así que no pasa corriente.', { tol: 0.05, c: 'ba_nodecur', h: 'Calcula (6 − VA) / 1 kΩ con el VA que acabas de obtener.' }),
      Nm('¿Y cuántos mA pasan por R3?', 6, 'mA', 'VA / R3 = 6 V / 1 kΩ = 6 mA: todo lo que da la pila de 12 V.', { c: 'ba_nodecur', h: 'R3 une el nudo A con masa (0 V).' }),
      G('m5_nodeCur'),
      G('m5_nodeV'),
      Q('Un circuito tiene 4 nudos y uno de ellos es masa. Las pilas no fijan ninguno de los otros. ¿Cuántas ecuaciones de nudo necesitas?', ['3', '4', '1', '6'], 'Una por cada nudo cuya tensión no conoces: 4 − 1 = 3.', { c: 'ba_nodal', h: 'La masa ya la conoces: vale 0 V.' }),
      Q('Montas el ejemplo y mides VA = 6,2 V cuando el cálculo dice 6 V. ¿Qué es lo más probable?', ['La tolerancia de las resistencias y de la pila', 'Que la ley de nudos no se cumple', 'Que el multímetro inventa', 'Que has montado mal el circuito'], 'Un 3 % de diferencia encaja con resistencias del ±5 % y una pila que no da exactamente su valor.', { c: 'ba_measdiff', h: 'Calcula qué porcentaje se aleja la medida y compáralo con la tolerancia.' }),
      Q('¿Qué hace por dentro un simulador de circuitos como SPICE?', ['Escribe y resuelve ecuaciones de nudos como estas', 'Prueba valores al azar', 'Mide un circuito real', 'Solo suma resistencias en serie'], 'El análisis nodal escala a miles de nudos con álgebra de matrices.', { c: 'ba_nodal', h: 'Piensa en el método que acabas de aprender.' }),
      I('<b>Resumen</b>\n· Elige masa y nombra los nudos desconocidos.\n· Corriente entre nudos: <b>(VA − VB) / R</b>; el signo dice el sentido.\n· En cada nudo, lo que entra = lo que sale, y despejas.')
    ]),
    L('d7', 'Thévenin', 'div', ['ba_thev', 'ba_thevload', 'ba_intres'], [
      Q('Un divisor de 9 V con dos resistencias de 1 kΩ da 4,5 V sin nada conectado. Le conectas una carga de 500 Ω. ¿Qué tensión crees que tendrá?', ['Menos de 4,5 V', 'Justo 4,5 V', 'Más de 4,5 V'], 'Baja bastante: a 2,25 V. Thévenin te dice cuánto, sin rehacer el divisor.', { predict: true, c: 'ba_thevload', h: 'Al conectar algo, parte de la corriente pasa por la carga: piensa en el divisor.' }),
      I('Idea de Thévenin: cualquier red de pilas y resistencias, vista desde dos bornes, se porta como <b>una sola pila Vth con una resistencia Rth en serie</b>. Desde fuera no se distinguen.', { svg: boxSVG, more: 'Léon Thévenin lo publicó en 1883. Es una de las ideas más útiles del curso: te deja olvidar lo que hay dentro de un circuito y quedarte con dos números.\nFunciona con cualquier red lineal: pilas, fuentes de corriente y resistencias.' }),
      { t: 'explore', text: 'La caja de la izquierda es una pila de 9 V con Rth en serie. Mueve Rth y la carga RL y mira cuánto cae la tensión en la carga.', viz: 'thevenin', params: thevP(),
        tasks: [
          { q: 'drop', min: 0, max: 10, text: 'Consigue que la salida caiga menos de un 10 %', done: 'Con RL mucho mayor que Rth, casi toda la tensión queda en la carga.', hint: 'Sube RL o baja Rth.' },
          { q: 'drop', min: 49, max: 51, text: 'Ahora haz que caiga justo a la mitad', done: 'Con RL = Rth, la tensión se reparte a medias.', hint: 'Pon la misma resistencia en los dos deslizadores.' },
          { q: 'ILmA', min: 30, max: 1000, text: 'Haz que la carga reciba más de 30 mA', done: 'Para dar mucha corriente, la caja necesita una Rth pequeña.', hint: 'Baja las dos resistencias.' }
        ] },
      I('<b>Vth</b> es la tensión entre los bornes <b>sin carga</b> (en vacío). En un divisor: Vth = V · R2 / (R1 + R2).', { sch: 'm5_div' }),
      I('<b>Rth</b>: cambia cada pila por un <b>cable</b> y calcula la resistencia que se ve desde los bornes. En el divisor, R1 y R2 quedan en paralelo.', { svg: rthSVG, more: '¿Por qué un cable? Una pila ideal mantiene su tensión pase lo que pase: lo único que hace es sumar tensión. Si la «apagas» (0 V) queda una unión sin resistencia: un cable.' }),
      { t: 'steps', text: 'Divisor de 9 V con dos de 1 kΩ. ¿Qué tensión queda con una carga de 500 Ω?', sch: 'm5_div', steps: ['Vth (sin carga): 9 × 1k / (1k + 1k) = <b>4,5 V</b>', 'Rth (pila → cable): 1 kΩ ∥ 1 kΩ = <b>500 Ω</b>', 'Con carga: Vth, Rth y RL en serie forman un divisor.', 'VL = 4,5 × 500 / (500 + 500) = <b>2,25 V</b>'], result: 'La salida cae de 4,5 V a 2,25 V: la mitad.' },
      Q('Divisor de 12 V con dos de 2 kΩ. ¿Vth en la salida?', ['6 V', '12 V', '3 V', '0 V'], 'Sin carga, la mitad.', { c: 'ba_thev', h: 'Vth es la salida del divisor sin nada conectado.' }),
      Q('¿Y su Rth?', ['1 kΩ', '4 kΩ', '2 kΩ', '0 Ω'], 'Pila → cable: 2 kΩ ∥ 2 kΩ = 1 kΩ.', { c: 'ba_thev', h: 'Cambia la pila por un cable: ¿cómo quedan las dos resistencias vistas desde la salida?' }),
      Nm('Con una carga de 3 kΩ en esa salida (6 V, 1 kΩ), ¿qué tensión queda, en V?', 4.5, 'V', 'Divisor entre Rth y la carga: 6 × 3 / (1 + 3) = 4,5 V.', { c: 'ba_thevload', h: 'Vth, Rth y la carga en serie: aplica el divisor de tensión.' }),
      G('m5_thev'),
      G('m5_thevLoad'),
      I('Tu pila también es un Thévenin: una pila ideal con una pequeña <b>resistencia interna</b> r. Sin carga mides la tensión completa; al pedirle corriente, parte se queda dentro: <b>r = (Vvacío − Vcarga) / I</b>.', { svg: CONCEPTS.ba_intres.alts[0].svg }),
      Nm('Una pila de 9 V marca 9,3 V en vacío y 7,5 V cuando da 0,3 A. ¿Resistencia interna, en Ω?', 6, 'Ω', 'Se pierden 9,3 − 7,5 = 1,8 V dentro: r = 1,8 / 0,3 = 6 Ω.', { c: 'ba_intres', h: 'La tensión que falta con carga se ha quedado en r: divídela entre la corriente.' }),
      { t: 'match', q: 'Une cada idea con lo que significa.', pairs: [['Vth', 'Tensión entre los bornes sin carga'], ['Rth', 'Resistencia vista con las pilas cambiadas por cables'], ['Rth pequeña', 'Salida fuerte: casi no cae con carga'], ['Rth grande', 'Salida débil: cae mucho con carga']], c: 'ba_thev', h: 'Piensa en qué medirías sin carga y qué pasa al conectar algo.' },
      Q('¿Para qué te sirve Thévenin en la práctica?', ['Para saber cuánto caerá una salida al conectarle una carga', 'Para leer el código de colores', 'Para medir corriente sin multímetro', 'Para nada: es solo teoría'], 'Rth dice lo «débil» que es una salida.', { c: 'ba_thev', h: 'Recuerda el reto: qué pasaba con la salida al cambiar la carga.' }),
      I('<b>Resumen</b>\n· Desde dos bornes, todo es <b>Vth en serie con Rth</b>.\n· Vth: tensión en vacío. Rth: pilas → cables.\n· Con carga: divisor entre Rth y RL. Una pila real tiene su r interna.')
    ]),
    L('d10', 'Norton y el paso de Thévenin a Norton', 'div', ['ba_isource', 'ba_norton', 'ba_rthmeas'], [
      Q('Imagina una fuente que da siempre 2 mA, conectes lo que conectes. Le pones 1 kΩ y luego 2 kΩ. ¿Qué crees que hace su tensión?', ['Se duplica, para mantener los 2 mA', 'Se queda igual', 'Se reduce a la mitad'], 'V = I · R: con la corriente fija, al doble de resistencia, el doble de tensión. Es una fuente de corriente.', { predict: true, c: 'ba_isource', h: 'Si la corriente no puede cambiar, ¿qué tiene que cambiar según la ley de Ohm?' }),
      I('Una pila fija la <b>tensión</b>. Una <b>fuente de corriente</b> ideal fija la <b>corriente</b> y ajusta su tensión a lo que haga falta. Se dibuja como un círculo con una flecha.', { svg: CONCEPTS.ba_isource.alts[0].svg, more: 'Ya has usado una: tu fuente de laboratorio en modo CC (corriente constante) se porta así hasta el tope de tensión que le pongas.\nUna fuente de corriente ideal tendría resistencia interna infinita: por eso, al «apagarla», queda un hueco abierto.' }),
      { t: 'explore', text: 'La caja es una fuente de corriente IN con RN en paralelo. La corriente se reparte entre RN y la carga.', viz: 'norton', params: { IN: { label: 'IN', val: 2, min: 0.5, max: 10, step: 0.5, unit: 'mA', dec: 1 }, RN: { label: 'RN', val: 10000, fmt: 'R', min: 100, max: 1000000 }, RL: { label: 'Carga RL', val: 1000, fmt: 'R', min: 100, max: 100000 } },
        tasks: [
          { q: 'share', min: 95, max: 100, text: 'Haz que más del 95 % de la corriente llegue a la carga', done: 'Con RN mucho mayor que la carga, casi toda la corriente va a la carga: la caja parece una fuente de corriente ideal.', hint: 'Sube RN.' },
          { q: 'VL', min: 5.9, max: 6.1, text: 'Consigue 6 V en la carga', done: 'V = I · R: con 6 mA por 1 kΩ, 6 V.', hint: 'Con RN muy grande, toda IN pasa por la carga: elige IN y RL que den 6 V.' },
          { q: 'share', min: 49, max: 51, text: 'Ahora reparte la corriente a medias', done: 'Con RN = RL, cada una se lleva la mitad.', hint: 'Pon RN igual que RL.' }
        ] },
      I('<b>Norton</b> resume la red como una fuente de corriente <b>IN</b> con <b>RN</b> en paralelo. Es otra foto de la misma caja que Thévenin.', { svg: twoBoxes }),
      I('Conversión:\n· <b>RN = Rth</b>.\n· <b>IN = Vth / Rth</b>: la corriente que daría la caja con los bornes en cortocircuito.\n· Al revés: <b>Vth = IN · RN</b>, la tensión en vacío.', { svg: twoBoxes }),
      { t: 'steps', text: 'Pasa a Norton un Thévenin de 9 V con 3 kΩ.', svg: twoBoxes, steps: ['RN = Rth = <b>3 kΩ</b>', 'IN = Vth / Rth = 9 V / 3 kΩ = <b>3 mA</b>', 'Comprueba en vacío: los 3 mA pasan todos por RN → 3 mA × 3 kΩ = 9 V ✓', 'Comprueba en cortocircuito: en Thévenin, 9 V / 3 kΩ = 3 mA; en Norton, toda IN va por el cable: 3 mA ✓'], result: 'Norton: 3 mA con 3 kΩ en paralelo.' },
      Q('Conviertes Vth = 9 V con Rth = 3 kΩ. ¿Norton?', ['3 mA con 3 kΩ en paralelo', '3 mA con 3 kΩ en serie', '27 mA con 3 kΩ en paralelo', '9 mA con 1 kΩ en paralelo'], 'IN = 9 / 3000 = 3 mA; RN = Rth.', { c: 'ba_norton', h: 'IN es la corriente de cortocircuito y RN va en paralelo.' }),
      Q('¿Qué es una fuente de corriente ideal?', ['Da siempre la misma corriente y ajusta su tensión a la carga', 'Da siempre la misma tensión', 'Una pila muy grande', 'Un interruptor'], 'Su resistencia interna sería infinita.', { c: 'ba_isource', h: 'Piensa en lo que fija y lo que deja libre.' }),
      G('m5_norton'),
      I('Truco de banco: para medir Rth de una salida, mide la tensión <b>en vacío</b> y luego <b>con una carga conocida</b>. La tensión que falta se ha quedado en Rth. Si cortocircuitar no daña nada, también vale <b>Rth = Vvacío / Icorto</b>.', { svg: CONCEPTS.ba_rthmeas.alts[0].svg }),
      Nm('Una salida da 5 V en vacío y 4 V con una carga de 400 Ω. ¿Rth, en Ω?', 100, 'Ω', 'Con carga pasan 4 / 400 = 10 mA y se pierde 1 V dentro: Rth = 1 V / 10 mA = 100 Ω.', { c: 'ba_rthmeas', h: 'Primero la corriente por la carga; luego divide la tensión perdida entre esa corriente.' }),
      Nm('Otra salida da 6 V en vacío y 30 mA en cortocircuito. ¿Rth, en Ω?', 200, 'Ω', 'Rth = Vvacío / Icorto = 6 / 0,03 = 200 Ω.', { c: 'ba_rthmeas', h: 'Pasa los 30 mA a amperios y divide.' }),
      Q('¿Cuándo resulta cómodo pensar en Norton?', ['Con algo que da una corriente casi fija, como la fuente de laboratorio en modo CC', 'Nunca: Thévenin siempre es mejor', 'Solo con pilas', 'Solo con interruptores'], 'Lo verás también con sensores de luz y transistores, que se portan como fuentes de corriente.', { c: 'ba_isource', h: 'Norton usa una fuente de corriente: ¿qué aparato de tu mesa se porta así?' }),
      Q('Una fuente de corriente ideal se queda sin carga (bornes al aire). ¿Qué pasaría?', ['Su tensión intentaría subir sin límite: las reales tienen un tope', 'Daría 0 V', 'Daría la mitad de corriente', 'Nada especial'], 'Para empujar corriente por un hueco haría falta tensión infinita; las fuentes reales se quedan en su tensión máxima.', { c: 'ba_isource', h: 'V = I · R con R enorme…' }),
      I('<b>Resumen</b>\n· Fuente de corriente: fija I, la tensión se adapta.\n· Norton: <b>IN ∥ RN</b>, con RN = Rth e IN = Vth / Rth.\n· Rth se mide con vacío y carga (o vacío y cortocircuito).')
    ]),
    L('d9', 'Superposición', 'div', ['ba_superpos', 'ba_linear'], [
      Q('Con solo la pila 1, un nudo está a 4 V. Con solo la pila 2, a 2 V. ¿Qué crees que pasa con las dos puestas?', ['Está a 6 V', 'Está a 4 V', 'Está a 2 V', 'No se puede saber'], 'En circuitos de resistencias, los efectos de cada fuente se suman. Es el principio de superposición.', { predict: true, c: 'ba_superpos', h: 'Imagina que cada pila pone su parte por separado.' }),
      I('<b>Superposición</b>: con varias fuentes, calcula lo que produce <b>cada una sola</b>, con las demás apagadas, y <b>suma</b> los resultados.', { svg: '<svg viewBox="0 0 300 100" class="viz"><rect x="10" y="20" width="80" height="50" rx="8" fill="none" stroke="currentColor" stroke-width="2"/><text x="50" y="50" text-anchor="middle" class="vizsm">las dos</text><text x="100" y="52" class="vizbig">=</text><rect x="115" y="20" width="75" height="50" rx="8" fill="none" stroke="var(--led)" stroke-width="2"/><text x="152" y="50" text-anchor="middle" class="vizsm">solo la 1</text><text x="197" y="52" class="vizbig">+</text><rect x="212" y="20" width="78" height="50" rx="8" fill="none" stroke="var(--ice)" stroke-width="2"/><text x="251" y="50" text-anchor="middle" class="vizsm">solo la 2</text><text x="150" y="92" text-anchor="middle" class="vizsm">6 V = 4 V + 2 V</text></svg>' }),
      { t: 'explore', text: 'El circuito del análisis nodal: 12 V y 6 V, y tres de 1 kΩ. Ahora puedes cambiar cada pila por un cable (0 = cable, 1 = pila).', viz: 'nodal', params: nodalP({ V1: { val: 12, fixed: true }, V2: { val: 6, fixed: true }, on1: { label: 'Pila 1 (1 = puesta, 0 = cable)', val: 0, list: oneOf, dec: 0 }, on2: { label: 'Pila 2 (1 = puesta, 0 = cable)', val: 0, list: oneOf, dec: 0 } }),
        tasks: [
          { q: 'cfg', min: 1, max: 1, text: 'Pon solo la pila 1 y mira A', done: 'Solo con 12 V: A = 4 V.', hint: 'Pila 1 a 1 y pila 2 a 0.' },
          { q: 'cfg', min: 2, max: 2, text: 'Ahora solo la pila 2', done: 'Solo con 6 V: A = 2 V.', hint: 'Pila 1 a 0 y pila 2 a 1.' },
          { q: 'cfg', min: 3, max: 3, text: 'Pon las dos', done: 'A = 6 V = 4 V + 2 V. ¡Se suman!', hint: 'Las dos a 1.' }
        ] },
      I('<b>Apagar</b> una fuente es dejarla en 0 sin quitar su sitio:\n· Pila (0 V) → un <b>cable</b>.\n· Fuente de corriente (0 A) → un <b>hueco abierto</b>.', { svg: offSVG }),
      { t: 'steps', text: 'Resuelve por superposición: 12 V y 6 V llegan al nudo A, cada una por 1 kΩ, y de A sale 1 kΩ a masa.', sch: 'm5_nodal', steps: ['Solo 12 V (la de 6 V → cable): R2 y R3 quedan en paralelo → <b>500 Ω</b>.', 'Divisor: VA = 12 × 500 / (1000 + 500) = <b>4 V</b>.', 'Solo 6 V (la de 12 V → cable): R1 ∥ R3 = 500 Ω → VA = 6 × 500 / 1500 = <b>2 V</b>.', 'Suma: 4 + 2 = <b>6 V</b>, lo mismo que con el análisis nodal.'], result: 'VA = 6 V por los dos caminos.' },
      Q('Al apagar una fuente de corriente para aplicar superposición, la sustituyes por…', ['Un circuito abierto', 'Un cable', 'Una resistencia de 1 kΩ', 'Otra fuente igual'], 'Una fuente de 0 A no deja pasar nada: un hueco.', { c: 'ba_superpos', h: 'Apagar = dejarla en 0 A. ¿Qué componente no deja pasar corriente?' }),
      Q('¿Por qué conviene resolver un circuito con dos métodos distintos?', ['Si los dos dan lo mismo, es casi seguro que está bien', 'Porque uno siempre falla', 'Porque la superposición da el doble', 'No conviene'], 'Nodal y superposición dieron 6 V: comprobación cruzada.', { c: 'ba_superpos', h: 'Piensa en lo que pasó con el nudo A en el ejemplo.' }),
      Nm('Dos pilas, de 9 V y 3 V, llegan a un nudo, cada una por 2 kΩ, y del nudo a masa hay 1 kΩ. ¿Tensión del nudo, en V?', 3, 'V', 'Con una sola pila, la otra rama (2 kΩ) queda en paralelo con 1 kΩ: 0,667 kΩ. Solo 9 V: 9 × 0,667 / 2,667 = 2,25 V. Solo 3 V: 0,75 V. Suma: 3 V.', { tol: 0.03, c: 'ba_superpos', h: 'Con una pila sola, la rama de la otra se vuelve un cable a masa: queda en paralelo con 1 kΩ.' }),
      G('m5_superpos'),
      I('Solo vale en circuitos <b>lineales</b>: los que tienen componentes de gráfica recta, como las resistencias. El LED (con su codo) no lo es. Y aunque el circuito sea lineal, las <b>potencias no se suman</b>: van con el cuadrado.', { svg: CONCEPTS.ba_linear.alts[0].svg }),
      Q('¿Puedes calcular la potencia total sumando la que produce cada fuente por separado?', ['No: la potencia va con el cuadrado y no se suma así', 'Sí, siempre', 'Solo en serie', 'Solo con dos fuentes'], 'Suma tensiones o corrientes y calcula la potencia al final.', { c: 'ba_linear', h: 'Recuerda P = I² · R: ¿qué pasa al elevar al cuadrado una suma?' }),
      Nm('Una fuente sola hace pasar 3 mA por una resistencia de 1 kΩ y la otra, en el mismo sentido, 1 mA. ¿Potencia en la resistencia con las dos, en mW?', 16, 'mW', 'Corriente total: 4 mA. P = 0,004² × 1000 = 16 mW (no 9 + 1 = 10 mW).', { c: 'ba_linear', h: 'Suma primero las corrientes y calcula I² · R al final.' }),
      Q('Un circuito tiene dos pilas y un LED. ¿Admite superposición?', ['No: el LED no es lineal', 'Sí, siempre', 'Solo si el LED es rojo', 'Solo si las pilas son iguales'], 'Su curva tiene un codo: los efectos no se suman.', { c: 'ba_linear', h: 'Recuerda la gráfica tensión–corriente de un LED.' }),
      I('<b>Resumen</b>\n· Cada fuente sola, las demás apagadas (pila → cable, fuente de corriente → hueco), y se suma.\n· Solo con componentes lineales.\n· Suma tensiones y corrientes, no potencias.', { more: 'Uso real: muchas señales son una pequeña variación montada sobre una tensión fija. Se analiza la parte fija por un lado y la variación por otro, y se suman. Lo harás cuando polarices transistores.' })
    ]),
    L('d11', 'Máxima transferencia de potencia', 'heat', ['ba_maxpow', 'ba_adapt'], [
      Q('Una pila tiene 10 Ω de resistencia interna. ¿Con qué carga crees que entrega más potencia?', ['Con una de 10 Ω', 'Con una de 1 Ω', 'Con una de 1000 Ω'], 'Con 1 Ω pasa mucha corriente pero casi toda la tensión se queda dentro; con 1000 Ω hay tensión pero casi no hay corriente. El máximo está en medio: con la misma resistencia que la interna.', { predict: true, c: 'ba_maxpow', h: 'Con mucha corriente cae poca tensión fuera; con mucha tensión pasa poca corriente.' }),
      { t: 'explore', text: 'Fuente de 10 V con 10 Ω internos. Mueve la carga: el punto recorre la curva de potencia y la barra de abajo dice qué parte de la energía llega a la carga.', viz: 'maxPower', params: { V: { val: 10, fixed: true }, Rth: { val: 10, fixed: true }, RL: { label: 'Carga RL', val: 1, list: [1, 2.2, 4.7, 6.8, 10, 15, 22, 47, 100], unit: 'Ω', dec: 1 } },
        tasks: [
          { q: 'rel', min: 99, max: 101, text: 'Saca la máxima potencia posible a la carga', done: 'Máximo con RL = Rth = 10 Ω: 2,5 W.', hint: 'Busca el pico de la curva.' },
          { q: 'eta', min: 80, max: 100, text: 'Ahora consigue un rendimiento de más del 80 %', done: 'Con RL grande se desperdicia poco, aunque la carga reciba menos potencia que el máximo.', hint: 'Sube la carga bastante por encima de 10 Ω.' }
        ] },
      I('El máximo está justo en <b>RL = Rth</b>. Con menos resistencia, la carga apenas tiene tensión; con más, apenas pasa corriente.', { svg: peakSVG, more: 'Puedes comprobarlo con P = I² · RL e I = V / (Rth + RL). Con 10 V y 10 Ω: RL = 2,5 Ω → 1,6 W; 10 Ω → 2,5 W; 40 Ω → 1,6 W. Fíjate: RL = Rth ÷ 4 y RL = Rth × 4 dan la misma potencia.' }),
      { t: 'steps', text: 'Fuente de 10 V con Rth = 10 Ω y una carga de 10 Ω. ¿Potencia en la carga y rendimiento?', steps: ['Corriente: I = 10 V / (10 + 10) Ω = <b>0,5 A</b>', 'En la carga: P = I² · RL = 0,25 × 10 = <b>2,5 W</b>', 'Dentro de la fuente: 0,25 × 10 = 2,5 W de calor', 'Rendimiento: 2,5 / 5 = <b>50 %</b>'], result: '2,5 W en la carga, pero la mitad de la energía se pierde dentro.' },
      Nm('La misma fuente (10 V, 10 Ω) con RL = 40 Ω. ¿Potencia en la carga, en W?', 1.6, 'W', 'I = 10 / 50 = 0,2 A; P = 0,04 × 40 = 1,6 W.', { c: 'ba_maxpow', h: 'Corriente con las dos resistencias en serie y luego I² · RL.' }),
      Nm('¿Y con RL = 2,5 Ω?', 1.6, 'W', 'I = 10 / 12,5 = 0,8 A; P = 0,64 × 2,5 = 1,6 W. Igual que con 40 Ω: el máximo está en medio.', { c: 'ba_maxpow', h: 'Mismo método: I = V / (Rth + RL) y después I² · RL.' }),
      G('m5_maxpow'),
      I('El precio: con RL = Rth la fuente calienta por dentro tanto como entrega: <b>rendimiento del 50 %</b>. Rendimiento = RL / (Rth + RL).', { svg: CONCEPTS.ba_adapt.alts[0].svg }),
      Nm('Rth = 10 Ω y una carga de 90 Ω. ¿Rendimiento, en %?', 90, '%', 'η = RL / (Rth + RL) = 90 / 100.', { c: 'ba_adapt', h: 'La corriente es la misma en las dos: la potencia se reparte en proporción a las resistencias.' }),
      Q('¿Por qué no se alimenta un motor buscando RL = Rth con la batería?', ['Porque se perdería la mitad de la energía en calor dentro de la batería', 'Porque es ilegal', 'Porque daría poca tensión', 'Sí se hace siempre'], 'Para alimentar interesa el rendimiento: Rth mucho menor que la carga.', { c: 'ba_adapt', h: 'Piensa en el rendimiento con RL = Rth.' }),
      Q('¿En cuál de estos casos sí interesa adaptar (RL = Rth)?', ['Una antena que recoge una señal muy débil', 'Una batería que alimenta un motor', 'Un cargador de móvil', 'Una linterna'], 'Con señales débiles importa aprovecharlo todo; con energía para alimentar, el rendimiento.', { c: 'ba_adapt', h: '¿Dónde importa más sacar el máximo que no desperdiciar?' }),
      Q('Un amplificador pensado para altavoces de 8 Ω se conecta a uno de 4 Ω. ¿Qué puede pasar?', ['Que dé más corriente de la prevista y se caliente o se proteja', 'Nada', 'Que suene la mitad', 'Que el altavoz no funcione'], 'Los amplificadores de audio no buscan adaptación: tienen Rth muy baja y una carga mínima.', { c: 'ba_adapt', h: 'Menos resistencia de carga, ¿más o menos corriente?' }),
      I('<b>Resumen</b>\n· Máxima potencia en la carga con <b>RL = Rth</b>: P = V² / (4 · Rth).\n· Ahí el rendimiento es solo del 50 %.\n· Se adapta con señales débiles; para alimentar, RL ≫ Rth.')
    ]),
    L('d8', 'Puente de Wheatstone', 'div', ['ba_bridge', 'ba_bridgecalc'], [
      Q('Pones dos divisores iguales (1 kΩ y 1 kΩ) en paralelo con una pila de 9 V, y un voltímetro entre sus dos puntos medios. ¿Qué crees que marca?', ['0 V', '4,5 V', '9 V'], 'Los dos puntos medios están a 4,5 V: entre ellos no hay diferencia. Eso es un puente equilibrado.', { predict: true, c: 'ba_bridge', h: 'Calcula la tensión de cada punto medio.' }),
      I('Un <b>puente de Wheatstone</b> son dos divisores enfrentados. Si dan la misma tensión, entre sus puntos medios hay <b>0 V</b>: está <b>equilibrado</b>.', { svg: bridgeSVG, more: 'Charles Wheatstone lo popularizó en 1843 para medir resistencias. Hoy está dentro de básculas, sensores de presión y medidores de temperatura.' }),
      { t: 'explore', text: 'Tres resistencias de 1 kΩ y un sensor Rx (abajo a la derecha). El medidor del centro da la diferencia en milivoltios.', viz: 'bridge', params: { V: { val: 10, fixed: true }, Rx: { label: 'Sensor Rx', val: 1050, min: 900, max: 1100, step: 1, unit: 'Ω', dec: 0 } },
        tasks: [
          { q: 'absVd', min: 0, max: 0.99, text: 'Equilibra el puente', done: 'Rx = 1000 Ω: los dos lados dan 5 V.', hint: 'Iguala el sensor a las otras resistencias.' },
          { q: 'Vd', min: 9, max: 11, text: 'Consigue unos +10 mV', done: 'Con solo 4 Ω de cambio (un 0,4 %) ya ves 10 mV desde cero.', hint: 'Sube el sensor muy poco por encima de 1000 Ω.' },
          { q: 'Vd', min: -1000, max: -5, text: 'Ahora haz que la salida sea negativa', done: 'Si el sensor baja, la salida cambia de signo: el puente también dice hacia dónde ha cambiado.', hint: 'Baja el sensor por debajo de 1000 Ω.' }
        ] },
      I('Está equilibrado cuando los dos lados tienen la misma proporción: <b>R1 / R2 = R3 / Rx</b>. No hace falta que sean iguales: 1k/1k frente a 2k/2k también da 0 V.', { svg: bridgeSVG }),
      { t: 'steps', text: '9 V: a la izquierda 1 kΩ arriba y 1 kΩ abajo; a la derecha 2 kΩ y 2 kΩ. ¿Qué marca el medidor?', svg: bridgeSVG, steps: ['Izquierda: 9 × 1k / (1k + 1k) = <b>4,5 V</b>', 'Derecha: 9 × 2k / (2k + 2k) = <b>4,5 V</b>', 'Diferencia: 4,5 − 4,5 = <b>0 V</b>'], result: 'Equilibrado: misma proporción a los dos lados.' },
      Q('9 V: a la izquierda 1 kΩ arriba y 2 kΩ abajo; a la derecha 2 kΩ arriba y 4 kΩ abajo. ¿Tensión entre puntos medios?', ['0 V', '3 V', '6 V', '9 V'], 'Los dos lados dan 6 V: misma proporción 1:2.', { c: 'ba_bridgecalc', h: 'Calcula cada divisor por separado y resta.' }),
      I('¿Para qué? Un sensor que cambia un 0,1 % mueve un divisor de 5 V a 5,0025 V: difícil de ver. En un puente, la salida pasa de <b>0</b> a 2,5 mV, y eso se amplifica fácil. Así funcionan las básculas con <b>galgas extensiométricas</b>.', { svg: gaugeSVG }),
      Q('¿Por qué se usa un puente con sensores que cambian muy poco?', ['Porque la salida parte de 0 V y el pequeño cambio destaca', 'Porque consume menos', 'Porque no necesita alimentación', 'Porque amplifica solo'], 'Medir cerca de cero es mucho más fácil que ver una pequeña variación sobre varios voltios.', { c: 'ba_bridge', h: 'Compara medir 5,0025 V con medir 2,5 mV.' }),
      Nm('10 V, tres de 1 kΩ y un sensor de 1010 Ω abajo a la derecha. ¿Diferencia (derecha − izquierda), en mV?', 24.9, 'mV', 'Izquierda: 5 V. Derecha: 10 × 1010 / 2010 = 5,0249 V. Diferencia ≈ 24,9 mV.', { tol: 0.5, c: 'ba_bridgecalc', h: 'Calcula el lado derecho con cuatro decimales antes de restar.' }),
      Nm('R1 = 1 kΩ y R2 = 2 kΩ a la izquierda; R3 = 4,7 kΩ arriba a la derecha. ¿Qué Rx equilibra el puente, en kΩ?', 9.4, 'kΩ', 'Misma proporción: Rx = R3 · R2 / R1 = 4,7 × 2 / 1 = 9,4 kΩ.', { tol: 0.05, c: 'ba_bridgecalc', h: 'La proporción de arriba y abajo tiene que ser la misma en los dos lados.' }),
      G('m5_bridge'),
      Q('Conectas entre los puntos medios un medidor de resistencia interna baja. ¿Qué problema hay?', ['Carga a los dos divisores y cambia lo que mides', 'Ninguno', 'Que el puente se equilibra solo', 'Que la pila se descarga antes'], 'Cada punto medio tiene su Rth (la de su divisor): el medidor debe tener resistencia de entrada alta.', { c: 'ba_bridge', h: 'Recuerda Thévenin: ¿qué pasa al poner una carga pequeña en la salida de un divisor?' }),
      I('<b>Resumen</b>\n· Dos divisores enfrentados; equilibrio si <b>R1 / R2 = R3 / Rx</b>.\n· La salida parte de 0 V y sigue al sensor, con signo.\n· Mide con algo que no cargue el puente.')
    ])
  ] });
})();
