/* Voltio · curso base, módulo 13: Amplificadores operacionales
   Orden: k6 (reglas de oro, no inversor, inversor, seguidor) → k10 (límites reales) → k11 (sumador y restador)
   → k7 (comparador) → s5 → k14 (Schmitt) → k12 (integrador) → k13 (filtros activos).
   Usa lo visto antes: divisor (d6), Wheatstone (d8), RC (g4), filtros RC y dB (h1, h5, h10), pull-up y colector abierto (k20).
   Aún NO se puede hablar de microcontroladores, ADC ni muestreo (llegan en m11b–m11c). */
(() => {
  const { num, fR, fV, st, ledBulb, hbar, resBody } = Widgets.H;
  const RES = (...k) => I('<b>Resumen</b>\n· ' + k.join('\n· '));
  const LS = (label, val, list, unit = '', dec = 0) => ({ label, val, list, unit, dec });
  const SL = (label, val, min, max, step, unit = '', dec = 1) => ({ label, val, min, max, step, unit, dec });
  // Símbolo del operacional: + arriba, − abajo (entradas en x−30·s, salida en x+30·s)
  const OP = (x, y, s = 1, top = '+', bot = '−') => `<g transform="translate(${x} ${y}) scale(${s})" style="color:var(--ink)"><path d="M-18 -22v44l36 -22z M-30 -10h12M-30 10h12M18 0h12" ${st}/><text x="-15" y="-5" font-size="11" fill="currentColor">${top}</text><text x="-14" y="15" font-size="12" fill="currentColor">${bot}</text></g>`;
  const GND = (x, y) => `<path d="M${x} ${y}v6M${x - 9} ${y + 6}h18M${x - 6} ${y + 10}h12M${x - 3} ${y + 14}h6" ${st} stroke-width="1.8"/>`;
  const RV = (x, y) => `<g transform="translate(${x} ${y}) rotate(90)">${resBody()}</g>`;
  const RH = (x, y) => `<g transform="translate(${x} ${y})">${resBody()}</g>`;
  const clamp = (v, a, b) => Math.max(a, Math.min(b, v));

  /* ===================== VISUALIZACIONES ===================== */
  Object.assign(Widgets.VIZ, {
    // No inversor (o seguidor): la salida se ajusta hasta que V− = V+, salvo que se sature
    opNI: {
      calc: p => { const fol = p.fol ? 1 : 0, G = fol ? 1 : 1 + p.Rf / p.Rg, Vid = p.Vin * G, Vout = Math.min(7.5, Vid), Vm = fol ? Vout : Vout * p.Rg / (p.Rf + p.Rg); return { G, Vout, Vm, diff: p.Vin - Vm, clip: Vid > 7.5 ? 1 : 0, fol }; },
      svg: (p, o) => {
        const eq = !o.clip, fb = o.fol ? `<path d="M240 70V112H96V83H111" ${st} stroke="var(--led)"/>` : `<path d="M111 83H96V122M96 122H152M192 122H240V70" ${st}/>${RH(172, 122)}<text x="172" y="143" text-anchor="middle" class="vizsm">Rf ${fR(p.Rf)}</text>${RV(96, 146)}<text x="80" y="150" text-anchor="end" class="vizsm">Rg ${fR(p.Rg)}</text><path d="M96 122V126M96 166V170" ${st}/>${GND(96, 170)}`;
        return `<svg viewBox="0 0 300 200" class="viz"><path d="M30 57H111M189 70H275" ${st}/><circle cx="30" cy="57" r="4" fill="var(--ice)"/>${OP(150, 70, 1.3)}${fb}
          <circle cx="240" cy="70" r="3.5" fill="currentColor"/><circle cx="96" cy="${o.fol ? 112 : 122}" r="3.5" fill="currentColor"/>
          <text x="30" y="47" class="vizlab">Vent ${fV(p.Vin)}</text><text x="275" y="60" text-anchor="end" class="vizlab" style="fill:${o.clip ? 'var(--err)' : 'currentColor'}">Vsal ${fV(o.Vout)}</text>
          <text x="118" y="30" class="vizsm">V+ = ${fV(p.Vin)}</text><text x="122" y="108" class="vizsm" style="fill:${eq ? 'var(--ok)' : 'var(--err)'}">V− = ${fV(o.Vm)}</text>
          <text x="10" y="194" class="vizlab">${o.fol ? 'Seguidor: ganancia 1' : 'Ganancia ' + num(o.G, 2)} · ${eq ? 'V− = V+' : 'saturada: V− ya no llega a V+'}</text></svg>`;
      }
    },
    // Inversor: la − se queda a 0 V (masa virtual); la corriente de Rin sigue por Rf
    opInv: {
      calc: p => { const G = -p.Rf / p.Rin, Vid = G * p.Vin, Vout = clamp(Vid, -7.5, 7.5), I = p.Vin / p.Rin; return { G, Vout, I, clip: Math.abs(Vid) > 7.5 ? 1 : 0, Vm: Math.abs(Vid) > 7.5 ? p.Vin - (p.Vin - Vout) * p.Rin / (p.Rin + p.Rf) : 0 }; },
      svg: (p, o) => {
        const sp = Math.abs(o.I) < 1e-7 ? 'animation:none;opacity:0' : `animation-duration:${clamp(0.0002 / Math.abs(o.I), 0.3, 4).toFixed(2)}s`;
        return `<svg viewBox="0 0 300 190" class="viz"><path d="M20 83H60M100 83H111M111 57H104" ${st}/>${GND(104, 57)}${RH(80, 83)}
          <path d="M100 83V125H152M192 125H240V70M189 70H280" ${st}/>${RH(172, 125)}
          <path d="M20 83H100V125H240V70" class="flow" style="${sp}${o.I < 0 ? ';animation-direction:reverse' : ''}"/>
          ${OP(150, 70, 1.3)}
          <circle cx="100" cy="83" r="3.5" fill="currentColor"/><circle cx="240" cy="70" r="3.5" fill="currentColor"/>
          <text x="20" y="73" class="vizlab">Vent ${fV(p.Vin)}</text><text x="80" y="104" text-anchor="middle" class="vizsm">Rin ${fR(p.Rin)}</text><text x="172" y="146" text-anchor="middle" class="vizsm">Rf ${fR(p.Rf)}</text>
          <text x="104" y="40" class="vizsm" style="fill:${o.clip ? 'var(--err)' : 'var(--ok)'}">− a ${fV(o.Vm)}${o.clip ? '' : ' (masa virtual)'}</text>
          <text x="280" y="60" text-anchor="end" class="vizlab" style="fill:${o.clip ? 'var(--err)' : 'currentColor'}">Vsal ${fV(o.Vout)}</text>
          <text x="10" y="172" class="vizlab">Ganancia ${num(o.G, 2)} · corriente ${num(o.I * 1000, 3)} mA</text>
          <text x="10" y="186" class="vizsm">${o.clip ? 'Saturada: la salida no pasa de ±7,5 V' : 'Alimentación ±9 V · la salida sale invertida'}</text></svg>`;
      }
    },
    // Ganancia frente a frecuencia: el GBW manda
    gbw: {
      calc: p => { const GBW = p.gbw * 1e6, f = p.f * 1000, BW = GBW / p.G, Gr = p.G / Math.sqrt(1 + (f / BW) ** 2); return { BW: BW / 1000, Gr, drop: Gr < 0.75 * p.G ? 1 : 0, t2: p.G === 10 && p.f === 100 && Gr >= 9 ? 1 : 0 }; },
      svg: (p, o) => {
        const X = f => 30 + (Math.log10(f) - 1) * 42.5, Y = db => 140 - db * 1.25, GBW = p.gbw * 1e6, G = p.G;
        let ol = '', cl = '';
        for (let i = 0; i <= 60; i++) { const f = 10 ** (1 + i / 10), dbo = Math.min(100, 20 * Math.log10(GBW / f)), g = G / Math.sqrt(1 + (f * G / GBW) ** 2), dbc = 20 * Math.log10(g); ol += (i ? 'L' : 'M') + X(f).toFixed(1) + ' ' + Y(Math.max(-8, dbo)).toFixed(1); cl += (i ? 'L' : 'M') + X(f).toFixed(1) + ' ' + Y(Math.max(-8, dbc)).toFixed(1); }
        const fx = X(p.f * 1000), fy = Y(20 * Math.log10(Math.max(o.Gr, 0.4)));
        const lab = ['10 Hz', '1 kHz', '100 kHz', '10 MHz'];
        return `<svg viewBox="0 0 300 180" class="viz"><path d="M30 12V145H288" ${st} stroke-width="1.4"/>
          ${[1, 3, 5, 7].map((e, i) => `<path d="M${X(10 ** e)} 145v4" stroke="currentColor"/><text x="${X(10 ** e)}" y="159" text-anchor="middle" class="vizsm">${lab[i]}</text>`).join('')}
          ${[0, 20, 40, 60].map(d => `<text x="27" y="${Y(d) + 4}" text-anchor="end" class="vizsm">${d}</text>`).join('')}
          <path d="${ol}" fill="none" stroke="var(--muted)" stroke-dasharray="4 4"/><path d="${cl}" fill="none" stroke="var(--led)" stroke-width="3"/>
          <path d="M${fx.toFixed(1)} 14V145" stroke="var(--ice)" stroke-dasharray="3 3"/><circle cx="${fx.toFixed(1)}" cy="${fy.toFixed(1)}" r="5" fill="var(--ice)"/>
          <text x="36" y="20" class="vizsm">dB · discontinua: ganancia máxima del chip</text>
          <text x="10" y="174" class="vizlab">Ancho de banda ${o.BW >= 1000 ? num(o.BW / 1000, 2) + ' MHz' : num(o.BW, 1) + ' kHz'} · a ${num(p.f, 1)} kHz amplifica ×${num(o.Gr, 1)}</text></svg>`;
      }
    },
    // Sumador inversor: corrientes que se juntan en la masa virtual
    summer: {
      calc: p => { const I1 = p.V1 / p.R1, I2 = p.V2 / p.R2, Vid = -p.Rf * (I1 + I2), Vout = clamp(Vid, -7.5, 7.5); return { Vout, I1, I2, ratio: p.R1 / p.R2, zero: Math.abs(Vout) < 0.05 && Math.abs(p.V1) > 0.2 ? 1 : 0, clip: Vid !== Vout ? 1 : 0 }; },
      svg: (p, o) => {
        const fl = (d, I) => Math.abs(I) < 1e-7 ? '' : `<path d="${d}" class="flow" style="animation-duration:${clamp(0.0002 / Math.abs(I), 0.3, 4).toFixed(2)}s${I < 0 ? ';animation-direction:reverse' : ''}"/>`;
        return `<svg viewBox="0 0 300 190" class="viz"><path d="M15 50H50M90 50H110V95M15 120H50M90 120H110V95M110 95H131M131 69H122" ${st}/>${GND(122, 69)}${RH(70, 50)}${RH(70, 120)}
          ${fl('M15 50H110V95', o.I1)}${fl('M15 120H110V95', o.I2)}
          <path d="M110 95V150H172M212 150H245V82M209 82H285" ${st}/>${RH(192, 150)}${fl('M110 95V150H245V82', o.I1 + o.I2)}
          ${OP(170, 82, 1.3)}<circle cx="110" cy="95" r="4" fill="currentColor"/><circle cx="245" cy="82" r="3.5" fill="currentColor"/>
          <text x="12" y="40" class="vizlab">V1 ${fV(p.V1)}</text><text x="12" y="110" class="vizlab">V2 ${fV(p.V2)}</text>
          <text x="70" y="70" text-anchor="middle" class="vizsm">R1 ${fR(p.R1)}</text><text x="70" y="140" text-anchor="middle" class="vizsm">R2 ${fR(p.R2)}</text><text x="192" y="171" text-anchor="middle" class="vizsm">Rf ${fR(p.Rf)}</text>
          <text x="114" y="112" class="vizsm" style="fill:var(--ok)">0 V</text>
          <text x="285" y="72" text-anchor="end" class="vizlab" style="fill:${o.clip ? 'var(--err)' : 'currentColor'}">${fV(o.Vout)}</text>
          <text x="10" y="186" class="vizsm">I1 ${num(o.I1 * 1000, 2)} mA + I2 ${num(o.I2 * 1000, 2)} mA = ${num((o.I1 + o.I2) * 1000, 2)} mA por Rf</text></svg>`;
      }
    },
    // Restador: amplifica la diferencia; con resistencias desparejas se cuela la tensión común
    diffAmp: {
      calc: p => { const vd = p.Vd / 1000, ideal = p.G * vd, d = p.tol / 100, err = 4 * d * p.G / (1 + p.G) * p.Vcm, Vout = clamp(ideal + err, -7.5, 7.5); return { ideal, Vout, err, cmOk: p.tol === 0 && p.Vcm >= 4 ? 1 : 0, bigErr: err >= 0.1 ? 1 : 0 }; },
      svg: (p, o) => {
        const V1 = p.Vcm - p.Vd / 2000, V2 = p.Vcm + p.Vd / 2000, X = v => 150 + v * 16;
        return `<svg viewBox="0 0 300 180" class="viz">${hbar(30, 34, 240, V1 / 5, '#3E8FCB', 'V1 = ' + num(V1, 3) + ' V')}${hbar(30, 70, 240, V2 / 5, '#3E8FCB', 'V2 = ' + num(V2, 3) + ' V')}
          <text x="30" y="98" class="vizsm">Salida (escala de −8 a 8 V)</text><path d="M22 120H278" stroke="var(--line)" stroke-width="10" stroke-linecap="round"/><path d="M150 112v16" stroke="currentColor"/>
          <path d="M${X(o.ideal).toFixed(1)} 108v24" stroke="var(--ok)" stroke-width="3"/><circle cx="${X(o.Vout).toFixed(1)}" cy="120" r="6" fill="var(--led)"/>
          <text x="10" y="152" class="vizlab">Vsal ${fV(o.Vout)} · ideal ${fV(o.ideal)} (raya verde)</text>
          <text x="10" y="170" class="vizsm">${p.tol ? 'Error por la tensión común: ' + num(o.err * 1000, 0) + ' mV (peor caso)' : 'Resistencias perfectas: la tensión común no cuenta'}</text></svg>`;
      }
    },
    // Comparador con una LDR: señal contra umbral, con ruido opcional
    comparator: {
      anim: true,
      calc: p => { const vin = l => { const r = 1000 * 100 ** (1 - l / 100); return 5 * r / (10000 + r); }; const Vin = vin(p.luz); return { Vin, on: Vin > p.Vref ? 1 : 0, darkOnly: vin(10) > p.Vref && vin(30) < p.Vref ? 1 : 0, chatter: p.ruido > 0 && Math.abs(Vin - p.Vref) < p.ruido ? 1 : 0 }; },
      svg: (p, o, t) => {
        const Y = v => 100 - v * 17, N = 80; let s = '', q = '', on = 0;
        for (let i = 0; i <= N; i++) { const x = i / N, v = o.Vin + p.ruido * (0.6 * Math.sin(2 * Math.PI * 7 * x + t * 6) + 0.4 * Math.sin(2 * Math.PI * 17 * x - t * 4)), b = v > p.Vref ? 1 : 0; on += b; s += (i ? 'L' : 'M') + (20 + i * 2.4).toFixed(1) + ' ' + Y(clamp(v, 0, 5)).toFixed(1); q += (i ? 'L' : 'M') + (20 + i * 2.4).toFixed(1) + ' ' + (b ? 120 : 140); }
        return `<svg viewBox="0 0 300 180" class="viz"><path d="M20 12V102M20 142H215" ${st} stroke-width="1.2"/>
          <path d="${s}" fill="none" stroke="var(--ice)" stroke-width="2"/><path d="M20 ${Y(p.Vref).toFixed(1)}H215" stroke="var(--err)" stroke-dasharray="5 4"/><path d="${q}" fill="none" stroke="var(--led)" stroke-width="2.5"/>
          <text x="24" y="116" class="vizsm">salida</text>
          <g transform="translate(258 70)">${ledBulb(on / (N + 1))}</g><text x="258" y="112" text-anchor="middle" class="vizsm">LED</text>
          <text x="10" y="160" class="vizlab">IN+ ${fV(o.Vin)} · IN− ${fV(p.Vref)} · salida ${o.chatter ? 'temblando' : o.on ? 'alta' : 'baja'}</text>
          <text x="10" y="176" class="vizsm">azul: IN+ (LDR) · rojo: umbral · a oscuras sube IN+</text></svg>`;
      }
    },
    // Integrador: rampa con entrada constante; triangular con entrada cuadrada
    integrator: {
      anim: true,
      calc: p => { const slope = p.Vin / (p.R * p.C * 1e-6), pp = slope * 0.05; return { slope, tsat: 7.5 / slope, pp, tri: p.mode === 1 && pp > 0.3 && pp < 15 ? 1 : 0 }; },
      svg: (p, o, t) => {
        const X = s => 30 + s * 250, Y = v => 80 - v * 8;
        let inp = '', out = '', T, cur;
        if (p.mode === 1) { T = 0.3; for (let i = 0; i <= 120; i++) { const s = i / 120 * T, ph = (s % 0.1) < 0.05, v = ph ? p.Vin : -p.Vin; inp += (i ? 'L' : 'M') + X(s / T).toFixed(1) + ' ' + Y(v).toFixed(1); const u = s % 0.1, tri = ph ? -o.slope * u + o.pp / 2 : -o.slope * 0.05 + o.slope * (u - 0.05) + o.pp / 2; out += (i ? 'L' : 'M') + X(s / T).toFixed(1) + ' ' + Y(clamp(tri, -7.5, 7.5)).toFixed(1); } }
        else { T = Math.max(0.2, Math.min(4, o.tsat * 1.4)); inp = `M${X(0)} ${Y(p.Vin)}H${X(1)}`; for (let i = 0; i <= 80; i++) { const s = i / 80 * T; out += (i ? 'L' : 'M') + X(s / T).toFixed(1) + ' ' + Y(Math.max(-7.5, -o.slope * s)).toFixed(1); } }
        cur = X((t % 3) / 3);
        const tl = T >= 1 ? num(T, 1) + ' s' : num(T * 1000, 0) + ' ms';
        return `<svg viewBox="0 0 300 175" class="viz"><path d="M30 14V146M30 80H285" ${st} stroke-width="1.2"/><path d="M30 ${Y(-7.5)}H285" stroke="var(--err)" stroke-dasharray="3 4"/>
          <path d="${inp}" fill="none" stroke="var(--ice)" stroke-width="2"/><path d="${out}" fill="none" stroke="var(--led)" stroke-width="3"/><path d="M${cur.toFixed(1)} 14V146" stroke="var(--muted)" stroke-width="1"/>
          <text x="34" y="24" class="vizsm">entrada (azul) · salida (naranja) · límite −7,5 V</text><text x="285" y="160" text-anchor="end" class="vizsm">${tl}</text>
          <text x="10" y="160" class="vizlab">Pendiente ${num(o.slope, 1)} V/s</text>
          <text x="10" y="173" class="vizsm">${p.mode === 1 ? 'Triangular de ' + num(o.pp, 2) + ' V pico a pico' + (o.pp > 15 ? ': se satura' : '') : 'Llega al límite en ' + (o.tsat >= 1 ? num(o.tsat, 2) + ' s' : num(o.tsat * 1000, 1) + ' ms')}</text></svg>`;
      }
    },
    // Sallen-Key paso bajo con R iguales
    sallenKey: {
      calc: p => { const C1 = p.C1 * 1e-9, C2 = p.C2 * 1e-9, f0 = 1 / (2 * Math.PI * p.R * Math.sqrt(C1 * C2)), Q = 0.5 * Math.sqrt(C1 / C2); return { f0, Q, peak: Q > 0.707 ? 20 * Math.log10(Q * Q / Math.sqrt(Q * Q - 0.25)) : 0 }; },
      svg: (p, o) => {
        const X = f => 30 + (Math.log10(f) - 1) * 63.75, Y = db => 40 - db * 2.2;
        let d = ''; for (let i = 0; i <= 100; i++) { const f = 10 ** (1 + i / 25), x = f / o.f0, h = 1 / Math.sqrt((1 - x * x) ** 2 + (x / o.Q) ** 2), db = Math.max(-45, 20 * Math.log10(h)); d += (i ? 'L' : 'M') + X(f).toFixed(1) + ' ' + Y(db).toFixed(1); }
        const fl = f => f >= 1000 ? num(f / 1000, 2) + ' kHz' : num(f, 0) + ' Hz';
        return `<svg viewBox="0 0 300 180" class="viz"><path d="M30 12V145H288" ${st} stroke-width="1.4"/><path d="M30 40H288" stroke="var(--line)"/><path d="M30 ${Y(-3).toFixed(1)}H288" stroke="var(--line)" stroke-dasharray="2 4"/>
          ${[10, 100, 1000, 10000, 100000].map((f, i) => `<text x="${X(f).toFixed(1)}" y="158" text-anchor="middle" class="vizsm">${['10', '100', '1k', '10k', '100k'][i]}</text>`).join('')}
          <text x="26" y="44" text-anchor="end" class="vizsm">0</text><text x="26" y="${Y(-40) + 4}" text-anchor="end" class="vizsm">−40</text>
          <path d="${d}" fill="none" stroke="var(--led)" stroke-width="3"/><path d="M${X(o.f0).toFixed(1)} 14V145" stroke="var(--ice)" stroke-dasharray="3 3"/>
          <text x="36" y="24" class="vizsm">dB · Hz</text>
          <text x="10" y="174" class="vizlab">f₀ ${fl(o.f0)} · Q ${num(o.Q, 2)}${o.Q > 1 ? ' · pico de ' + num(o.peak, 1) + ' dB' : o.Q > 0.68 && o.Q < 0.76 ? ' · casi plana' : ''}</text></svg>`;
      }
    }
  });

  /* ===================== GENERADORES (con pista) ===================== */
  const { pick, fmt, MC, N } = Gen.helpers;
  const fRg = r => r >= 1000 ? fmt(r / 1000) + ' kΩ' : fmt(r) + ' Ω';
  Gen.add('opNonInv', () => { const Rf = pick([9000, 10000, 22000, 47000, 100000]), Rg = pick([1000, 2200, 4700, 10000]), G = 1 + Rf / Rg; if (Math.random() < 0.5) return { ...N(`No inversor: Rf = ${fRg(Rf)} y Rg = ${fRg(Rg)}. ¿Ganancia?`, G, '', `G = 1 + Rf / Rg = 1 + ${fmt(Rf / Rg, 3)} = ${fmt(G, 2)}.`, 0.05), h: 'No inversor: 1 + Rf / Rg. Pon las dos resistencias en la misma unidad antes de dividir.' }; const Vin = pick([0.1, 0.2, 0.25, 0.5]); return { ...N(`No inversor con Rf = ${fRg(Rf)}, Rg = ${fRg(Rg)} y ${fmt(Vin)} V en la entrada +. ¿Tensión de salida en V (sin saturar)?`, Vin * G, 'V', `G = 1 + ${fmt(Rf / Rg, 3)} = ${fmt(G, 2)}; Vsal = ${fmt(Vin)} × ${fmt(G, 2)} = ${fmt(Vin * G, 2)} V.`, Math.max(0.02, Vin * G * 0.01)), h: 'Primero la ganancia (1 + Rf / Rg) y luego multiplica por la entrada.' }; }, 'bb_opgain');
  Gen.add('opInverting', () => { const Rf = pick([10000, 22000, 47000, 100000]), Ri = pick([1000, 4700, 10000]), G = -Rf / Ri; if (Math.random() < 0.5) return { ...N(`Inversor: Rf = ${fRg(Rf)} y Rin = ${fRg(Ri)}. ¿Ganancia, con su signo?`, G, '', `G = −Rf / Rin = −${fmt(Rf / Ri, 3)}.`, 0.05), h: 'Inversor: −Rf / Rin. No te olvides del signo menos.' }; const Vin = pick([0.1, 0.2, 0.3, -0.2]); const Vo = G * Vin; if (Math.abs(Vo) > 7.5) return Gen.make('opInverting'); return { ...N(`Inversor con Rf = ${fRg(Rf)}, Rin = ${fRg(Ri)} y ${fmt(Vin)} V a la entrada. ¿Tensión de salida en V, con signo?`, Vo, 'V', `Vsal = −Rf / Rin × Vent = −${fmt(Rf / Ri, 3)} × ${fmt(Vin)} = ${fmt(Vo, 2)} V.`, 0.03), h: 'Multiplica la entrada por −Rf / Rin: el signo de la salida es el contrario al de la entrada.' }; }, 'bb_opgain');
  Gen.add('opBandwidth', () => { const gbw = pick([0.7e6, 1e6, 3e6, 10e6]), G = pick([10, 20, 50, 100, 1000]), bw = gbw / G; return { ...N(`Operacional de ${fmt(gbw / 1e6)} MHz de producto ganancia–ancho de banda, montado con ganancia ${G}. ¿Ancho de banda en kHz?`, bw / 1000, 'kHz', `BW ≈ GBW / G = ${fmt(gbw / 1e6)} MHz / ${G} = ${fmt(bw / 1000, 2)} kHz.`, bw / 1000 * 0.02), h: 'Divide el GBW entre la ganancia y pasa el resultado a kHz.' }; }, 'bb_gbw');
  Gen.add('opSlew', () => { const sr = pick([0.3, 0.5, 13, 20]), vp = pick([1, 2, 5, 10]), f = sr * 1e6 / (2 * Math.PI * vp); return { ...N(`Slew rate de ${fmt(sr)} V/µs y una senoide de ${vp} V de pico. ¿Frecuencia máxima sin deformarla, en kHz?`, f / 1000, 'kHz', `fmax = SR / (2π · Vp) = ${fmt(sr)} × 10⁶ / (2π × ${vp}) ≈ ${fmt(f / 1000, 1)} kHz.`, f / 1000 * 0.03), h: 'fmax = SR / (2π · Vp). Pasa el slew rate a V/s (× 1 000 000) antes de dividir.' }; }, 'bb_gbw');
  Gen.add('summerOut', () => { const Rf = pick([10000, 20000]), R1 = pick([10000, 5000, 20000]), R2 = pick([10000, 5000, 20000]), V1 = pick([0.5, 1, -0.5, 0.2]), V2 = pick([1, 0.5, -1, 0.3]), Vo = -Rf * (V1 / R1 + V2 / R2); if (Math.abs(Vo) > 7.5) return Gen.make('summerOut'); return { ...N(`Sumador inversor: Rf = ${fRg(Rf)}, R1 = ${fRg(R1)}, R2 = ${fRg(R2)}, V1 = ${fmt(V1)} V y V2 = ${fmt(V2)} V. ¿Vsal en V, con signo?`, Vo, 'V', `Vsal = −Rf · (V1/R1 + V2/R2) = −(${fmt(V1 * Rf / R1, 3)} + ${fmt(V2 * Rf / R2, 3)}) = ${fmt(Vo, 3)} V.`, 0.03), h: 'Cada entrada pesa Rf / Ri. Suma las aportaciones y cambia el signo.' }; }, 'bb_summer');
  Gen.add('schmittThr', () => { const vcc = pick([5, 9, 12]), R1 = pick([1000, 2200, 4700, 10000]), R2 = pick([47000, 100000, 220000]), vr = vcc / 2, H = vcc * R1 / R2, up = vr * (R1 + R2) / R2, dn = up - H, c = pick(['H', 'up', 'dn']); return { ...N(`Schmitt no inversor a ${vcc} V con salida rail-to-rail: ${fmt(vr, 2)} V en IN−, entrada por R1 = ${fRg(R1)} y realimentación R2 = ${fRg(R2)}. ¿Cuánto vale ${{ H: 'la histéresis', up: 'el umbral de subida', dn: 'el umbral de bajada' }[c]}, en V?`, { H, up, dn }[c], 'V', `Subida = Vref · (R1 + R2) / R2 = ${fmt(up, 3)} V. Histéresis = Vcc · R1 / R2 = ${fmt(H, 3)} V. Bajada = subida − histéresis = ${fmt(dn, 3)} V.`, 0.02), h: { H: 'Histéresis = Vcc · R1 / R2.', up: 'Subida = Vref · (R1 + R2) / R2.', dn: 'Calcula la subida y réstale la histéresis (Vcc · R1 / R2).' }[c] }; }, 'bb_schmitt_calc');
  Gen.add('sallenF0', () => { const R = pick([4700, 10000, 22000, 47000]), [C1, C2] = pick([[22, 10], [47, 22], [10, 10], [100, 47], [22, 22]]), f0 = 1 / (2 * Math.PI * R * Math.sqrt(C1 * C2) * 1e-9); return { ...N(`Sallen-Key paso bajo con R = ${fRg(R)}, C1 = ${C1} nF y C2 = ${C2} nF. ¿f₀ en Hz?`, f0, 'Hz', `f₀ = 1 / (2π · R · √(C1 · C2)) = 1 / (2π × ${R} × √(${C1} × ${C2}) nF) ≈ ${fmt(f0, 0)} Hz.`, f0 * 0.03), h: 'Multiplica los dos condensadores, haz la raíz y úsala como si fuera una sola C en 1 / (2π · R · C).' }; }, 'bb_actfilt');

  /* ===================== CONCEPTOS NUEVOS ===================== */
  Object.assign(CONCEPTS, {
    bb_opgold: { name: 'Reglas de oro del operacional', alts: [
      { title: 'Un empujón que se corrige solo', text: 'El operacional amplifica muchísimo la diferencia entre sus entradas. Si la salida vuelve a la entrada − (realimentación negativa), cualquier diferencia empuja la salida justo en el sentido que la corrige. El equilibrio llega cuando <b>V− = V+</b>. Mueve la entrada y mira cómo V− la persigue.', tune: { viz: 'opNI', params: { Vin: SL('Entrada', 0.5, 0, 2, 0.05, 'V', 2), Rf: pR('Rf', 10000, 1000, 100000), Rg: pR('Rg', 10000, 1000, 100000), fol: { val: 0, fixed: true } } }, q: mcq('Un no inversor funciona bien con 0,8 V en la entrada +. ¿A qué tensión está la −?', ['0,8 V', '0 V', 'La de la salida', 'La mitad de la salida, siempre'], 'Con realimentación negativa y sin saturar, la − se iguala a la +.') },
      { title: 'Dos reglas y nada más', text: 'Con realimentación negativa y sin saturar: 1) <b>por las entradas no entra corriente</b> (son de muy alta impedancia); 2) <b>la salida hace lo que haga falta para que las dos entradas estén a la misma tensión</b>. Con eso se resuelven casi todos los montajes. Si la salida llega al límite de la alimentación, la regla 2 deja de cumplirse.', q: mcq('La salida de un no inversor está saturada en 7,5 V. ¿Se cumple que V− = V+?', ['No: saturada ya no puede igualarlas', 'Sí, siempre', 'Solo si la ganancia es 1', 'Solo con alimentación negativa'], 'Las reglas de oro solo valen mientras la salida tenga margen.') }
    ] },
    bb_cmpoc: { name: 'Comparadores de colector abierto', alts: [
      { title: 'Solo sabe tirar a masa', text: 'Un LM393 o un LM339 tiene a la salida un transistor que <b>une la salida a masa</b> (nivel bajo) o la deja suelta. Suelta, la salida flota: hace falta una <b>pull-up</b> a la tensión que quieras ver como nivel alto. Con 10 kΩ a 5 V, cuando el transistor conduce pasan 5 / 10 000 = 0,5 mA.', svg: '<svg viewBox="0 0 300 150" class="viz"><path d="M150 20V45M150 85V120M150 65H240" stroke="currentColor" stroke-width="2.2" fill="none"/><rect x="142" y="45" width="16" height="40" rx="6" fill="#E7D3A8" stroke="#C9B183"/><text x="166" y="70" class="vizsm">pull-up</text><text x="150" y="14" text-anchor="middle" class="vizlab">+5 V</text><path d="M150 120l-14 0M150 120h14M144 126h12" stroke="currentColor" stroke-width="2"/><path d="M60 65H110" stroke="currentColor" stroke-width="2"/><circle cx="125" cy="98" r="14" fill="none" stroke="currentColor" stroke-width="2"/><path d="M118 90v16M118 94l14 -10M118 102l14 10" stroke="currentColor" stroke-width="2"/><text x="20" y="62" class="vizsm">comparador</text><text x="240" y="58" text-anchor="end" class="vizlab">salida</text><text x="20" y="145" class="vizsm">el transistor solo puede tirar a masa</text></svg>', q: mcq('Conectas la salida de un LM339 a un LED con su resistencia hacia masa, sin pull-up. ¿Qué pasa?', ['El LED no se enciende nunca: la salida solo sabe tirar a masa', 'Funciona igual', 'Se quema el comparador', 'El LED parpadea'], 'Un colector abierto no da tensión: necesita una pull-up.') },
      { title: 'Ventaja: tú eliges el nivel alto', text: 'Como la tensión alta la pone la pull-up, puedes alimentar el comparador a 12 V y llevar la pull-up a 5 V: la salida tendrá 0 o 5 V. Además, varias salidas de colector abierto se pueden unir con una sola pull-up: basta que una tire a masa para que la línea baje.', q: mcq('Comparador LM393 a 12 V con pull-up a 5 V. ¿Qué tensiones da su salida?', ['0 V o 5 V', '0 V o 12 V', 'Solo 5 V', '0 V o 17 V'], 'La pull-up decide el nivel alto.') }
    ] }
  });

  /* ===================== LECCIONES ===================== */
  const pIn = (v = 0.5) => SL('Entrada', v, 0, 2, 0.05, 'V', 2);
  UNITS.push({ id: 'm10b', title: 'Amplificadores operacionales', desc: 'Reglas de oro, límites reales, sumadores, comparadores, Schmitt, integradores y filtros activos.', nodes: [
    L('k6', 'Amplificadores operacionales', 'amp', ['bb_opgold', 'bb_opgain', 'bb_oplimits'], [
      Q('Un chip amplifica 100 000 veces la diferencia entre sus dos entradas y está alimentado a 9 V. Si una entrada está solo 1 mV por encima de la otra, ¿qué crees que sale?', ['Lo máximo que permite la alimentación: se satura', '100 V', '1 mV', '0 V'], '1 mV × 100 000 = 100 V, pero la salida no puede pasar de la alimentación: se queda pegada arriba. Así, a pelo, no sirve para amplificar nada. El truco es devolver parte de la salida a la entrada. Vamos a verlo.', { predict: true, c: 'bb_oplimits', h: 'Multiplica y compara el resultado con la alimentación.' }),
      I('Un <b>amplificador operacional</b> es un chip con dos entradas, <b>+</b> (no inversora) y <b>−</b> (inversora), y una salida. Amplifica muchísimo la diferencia <b>V+ − V−</b>: cien mil veces o más.\nEl <b>LM358</b> trae dos en un DIP-8; el <b>TL072</b>, otros dos, más rápidos.', { svg: `<svg viewBox="0 0 300 160" class="viz">${OP(150, 75, 1.6)}<path d="M150 30V40M150 110V120" ${st}/><text x="150" y="24" text-anchor="middle" class="vizsm">+ alimentación</text><text x="150" y="134" text-anchor="middle" class="vizsm">− alimentación o masa</text><text x="40" y="62" class="vizlab">V+</text><text x="40" y="96" class="vizlab">V−</text><text x="255" y="70" class="vizlab">Vsal</text><path d="M210 75H245" stroke="var(--led)" stroke-width="3" class="a-flow"/><text x="150" y="155" text-anchor="middle" class="vizsm">Vsal ≈ 100 000 × (V+ − V−), hasta saturar</text></svg>`, more: 'La ganancia «en lazo abierto» es enorme pero poco precisa: cambia de un chip a otro y con la temperatura. Por eso nunca se usa tal cual para amplificar.\nLo que se hace es <b>realimentar</b>: llevar parte de la salida a la entrada −. Entonces la ganancia ya no depende del chip, sino de dos resistencias, que sí son precisas y estables.\nAlimentación: puede ser simétrica (±9 V) o única (de 0 a 5 V, de 0 a 12 V…). La salida nunca pasa de lo que le das.' }),
      { t: 'explore', text: 'Un <b>no inversor</b>: la señal entra por +, y la salida vuelve a la − a través de un divisor (Rf y Rg). Mira siempre V+ y V−.', viz: 'opNI', params: { Vin: pIn(0.3), Rf: pR('Rf', 10000, 1000, 100000), Rg: pR('Rg', 10000, 1000, 100000), fol: LS('Unir la salida a − (0 no, 1 sí)', 0, [0, 1]) },
        tasks: [
          { q: 'G', min: 10.9, max: 11.1, text: 'Consigue una ganancia de 11', done: '1 + Rf / Rg = 11 con Rf diez veces Rg. Y V− sigue valiendo lo mismo que V+.', hint: 'Haz Rf diez veces mayor que Rg.' },
          { q: 'clip', min: 1, max: 1, text: 'Sube la entrada hasta que la salida se quede pegada', done: 'Con 9 V de alimentación, la salida no pasa de unos 7,5 V. Ahí V− ya no alcanza a V+.', hint: 'Con ganancia 11, más de 0,7 V a la entrada.' },
          { q: 'fol', min: 1, max: 1, text: 'Une la salida directamente a la entrada −', done: 'Es un seguidor: ganancia 1. Copia la tensión de la entrada.', hint: 'Pon el último deslizador a 1.' }
        ] },
      I('Lo que acabas de ver tiene nombre: las <b>reglas de oro</b>. Con realimentación negativa (salida hacia la −) y sin saturar:\n1. Por las entradas <b>no entra corriente</b>.\n2. La salida hace lo necesario para que <b>V− = V+</b>.', { svg: `<svg viewBox="0 0 300 150" class="viz">${OP(150, 70, 1.4)}<path d="M108 56H60M108 84H90V120H240V70M192 70H262" ${st}/><path d="M240 70V120H90V84" stroke="var(--led)" stroke-width="3" fill="none" class="a-flow-slow"/><text x="40" y="52" class="vizlab">1 V</text><text x="62" y="98" class="vizlab" style="fill:var(--ok)">1 V</text><text x="262" y="62" text-anchor="end" class="vizlab">Vsal</text><text x="150" y="142" text-anchor="middle" class="vizsm">la salida se mueve hasta igualar las entradas</text></svg>`, more: '¿Por qué se igualan? Si V− fuera un poco menor que V+, la diferencia (amplificada cien mil veces) subiría la salida; al subir la salida, sube V−. Si se pasa, baja. En microsegundos queda quieta justo donde V− = V+.\nEsa es la gracia: el chip pone el empuje y las resistencias deciden dónde se para.' }),
      I('En el no inversor, Rf y Rg forman un divisor (como en d6) entre la salida y masa. Como V− tiene que valer Vent:\nVsal · Rg / (Rf + Rg) = Vent → <b>G = 1 + Rf / Rg</b>.\nNunca baja de 1 y no invierte la señal.', { tune: { viz: 'opNI', params: { Vin: pIn(0.4), Rf: pR('Rf', 47000, 1000, 100000), Rg: pR('Rg', 4700, 1000, 100000), fol: { val: 0, fixed: true } } } }),
      { t: 'steps', text: 'No inversor con Rf = 47 kΩ, Rg = 4,7 kΩ y 0,2 V a la entrada. ¿Qué sale?', steps: ['Ganancia: <b>G = 1 + Rf / Rg</b> = 1 + 47 / 4,7', 'G = 1 + 10 = <b>11</b>', 'Salida: 0,2 V × 11 = <b>2,2 V</b> (cabe: no se satura)', 'Comprueba la regla de oro: V− = 2,2 × 4,7 / (47 + 4,7) = 2,2 × 0,091 = <b>0,2 V</b> = V+'], result: 'Sale 2,2 V y la entrada − está a 0,2 V, igual que la +.' },
      I('<b>Inversor</b>: la + va a masa y la señal entra a la − por Rin. Como la − debe igualar a la + (0 V), toda la corriente Vent / Rin sigue por Rf y la salida queda al otro lado:\n<b>G = −Rf / Rin</b>. El signo menos: sale dada la vuelta.', { tune: { viz: 'opInv', params: { Vin: SL('Entrada', 0.5, -1, 1, 0.05, 'V', 2), Rin: pR('Rin', 10000, 1000, 100000), Rf: pR('Rf', 22000, 1000, 100000) } }, more: 'A ese punto que está a 0 V sin estar conectado a masa se le llama <b>masa virtual</b>. Lo aprovecharás en el sumador.\nPara que la salida pueda ser negativa hace falta alimentación simétrica (por ejemplo, ±9 V). Con alimentación única hay un truco que verás en k11.' }),
      I('<b>Seguidor</b>: salida unida a la −, señal a la +. Ganancia 1: copia la tensión.\n¿Para qué copiar? Porque el operacional <b>no pide corriente</b> a lo que mide y sí puede darla. Un divisor o un sensor débil ya no se «cae» al conectarle una carga.', { svg: `<svg viewBox="0 0 300 140" class="viz">${OP(150, 60, 1.3)}<path d="M111 47H40M111 73H96V105H240V60M189 60H270" ${st}/><text x="40" y="38" class="vizlab">2,5 V (divisor débil)</text><text x="270" y="50" text-anchor="end" class="vizlab">2,5 V fuertes</text><path d="M200 60H262" stroke="var(--led)" stroke-width="3" class="a-flow"/><text x="150" y="130" text-anchor="middle" class="vizsm">entra casi nada de corriente · sale la que haga falta</text></svg>` }),
      Q('Un seguidor de tensión tiene una ganancia de…', ['1', '0', 'Infinita', '−1'], 'Copia la tensión, pero con una salida fuerte que no carga a la fuente.', { c: 'bb_opgain', h: 'La salida está unida directamente a la −, y la − se iguala a la +.' }),
      G('opNonInv'), G('opInverting'),
      Nm('Inversor con Rf = 22 kΩ, Rin = 10 kΩ y 0,5 V a la entrada. ¿Tensión de salida en V, con signo?', -1.1, 'V', '−22 / 10 × 0,5 = −1,1 V.', { tol: 0.02, c: 'bb_opgain', h: 'Ganancia −Rf / Rin, por la entrada. El resultado es negativo.' }),
      Q('Un no inversor funciona bien y su entrada + está a 1,2 V. ¿A qué tensión está su entrada −?', ['1,2 V', '0 V', 'La de la salida', 'Depende de Rf'], 'Regla de oro: con realimentación negativa y sin saturar, V− = V+.', { c: 'bb_opgold', h: 'Recuerda la segunda regla de oro.' }),
      Q('Un LM358 alimentado a 9 V con ganancia 20 recibe 1 V. ¿Qué sale?', ['Unos 7,5 V: se satura', '20 V', '9 V exactos', '0,05 V'], '1 × 20 = 20 V no cabe: la salida se queda en el máximo que da el chip, algo por debajo de la alimentación.', { c: 'bb_oplimits', h: 'Calcula la salida ideal y compárala con la alimentación.' }),
      { t: 'match', q: 'Une cada montaje con su ganancia.', pairs: [['No inversor, Rf = 9 kΩ y Rg = 1 kΩ', '10'], ['Inversor, Rf = Rin = 10 kΩ', '−1'], ['Seguidor', '1'], ['Inversor, Rf = 47 kΩ y Rin = 4,7 kΩ', '−10']], c: 'bb_opgain', h: 'No inversor: 1 + Rf / Rg. Inversor: −Rf / Rin.' },
      RES('Amplifica muchísimo V+ − V−; solo, se satura.', 'Con realimentación negativa: <b>V− = V+</b> y las entradas no consumen.', 'No inversor <b>1 + Rf / Rg</b> · inversor <b>−Rf / Rin</b> · seguidor <b>1</b>.', 'La salida nunca pasa de la alimentación.')
    ]),
    L('k10', 'El operacional real', 'amp', ['bb_oplimits', 'bb_gbw'], [
      Q('Montas un LM358 con ganancia 100 para amplificar una señal de 50 kHz. ¿Qué crees que pasará?', ['Amplificará mucho menos de 100', 'Amplificará 100 sin problema', 'Amplificará más de 100', 'No dejará pasar nada'], 'Un LM358 tiene un producto ganancia–ancho de banda de 1 MHz: con ganancia 100 solo llega bien hasta unos 10 kHz. A 50 kHz se queda en torno a ×20. Hoy verás por qué.', { predict: true, c: 'bb_gbw', h: 'Piensa si un chip puede dar mucha ganancia a cualquier frecuencia.' }),
      I('Las reglas de oro describen un operacional <b>ideal</b>. Los reales tienen cuatro límites que la hoja de datos detalla:\n· <b>Offset</b>: un pequeño error en la entrada.\n· <b>GBW</b>: menos ganancia a más frecuencia.\n· <b>Slew rate</b>: la salida no puede cambiar infinitamente rápido.\n· <b>Márgenes</b>: hasta dónde llegan entradas y salida.', { svg: `<svg viewBox="0 0 300 120" class="viz">${['Offset', 'GBW', 'Slew rate', 'Márgenes'].map((t, i) => `<rect x="${8 + i * 73}" y="30" width="66" height="54" rx="8" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="${41 + i * 73}" y="62" text-anchor="middle" class="vizlab" style="font-size:11px">${t}</text>`).join('')}<text x="150" y="108" text-anchor="middle" class="vizsm">cuatro defectos · cuatro síntomas distintos</text></svg>` }),
      I('<b>Offset</b>: aunque las dos entradas estén a la misma tensión, el chip se comporta como si hubiera unos milivoltios de diferencia (un LM358, hasta unos 7 mV). La ganancia también lo amplifica: con G = 100, 5 mV son 0,5 V de error.', { svg: `<svg viewBox="0 0 300 120" class="viz">${OP(130, 55, 1.2)}<path d="M94 43H40M94 67H40" ${st}/><text x="30" y="40" class="vizsm">0 V</text><text x="30" y="80" class="vizsm">0 V</text><circle cx="94" cy="43" r="7" fill="none" stroke="var(--err)" stroke-width="2"/><text x="72" y="25" class="vizsm" style="fill:var(--err)">+5 mV escondidos</text><path d="M166 55H230" ${st}/><text x="235" y="59" class="vizlab" style="fill:var(--err)">0,5 V</text><text x="150" y="110" text-anchor="middle" class="vizsm">con ganancia 100, el error sale ×100</text></svg>` }),
      Nm('Un operacional tiene 2 mV de offset y está montado con ganancia 1000. ¿Error en la salida, en V?', 2, 'V', '0,002 × 1000 = 2 V: con ganancias grandes, el offset importa mucho.', { tol: 0.05, c: 'bb_oplimits', h: 'Pasa los mV a V y multiplica por la ganancia.' }),
      { t: 'explore', text: 'Ganancia real frente a frecuencia. La línea discontinua es lo máximo que puede dar el chip: cae 20 dB por década. Tu montaje (naranja) no puede pasar de ella.', viz: 'gbw', params: { gbw: LS('GBW del chip', 1, [1, 3, 10], 'MHz'), G: LS('Ganancia del montaje', 100, [1, 10, 100, 1000]), f: LS('Frecuencia de la señal', 1, [0.1, 1, 10, 100, 1000], 'kHz', 1) },
        tasks: [
          { q: 'drop', min: 1, max: 1, text: 'Con 1 MHz de GBW y ganancia 100, sube la frecuencia hasta que la ganancia real caiga claramente', done: 'A partir de GBW / G = 10 kHz, la ganancia empieza a caer.', hint: 'Sube la frecuencia a 10 o 100 kHz.' },
          { q: 't2', min: 1, max: 1, text: 'Ahora amplifica ×10 una señal de 100 kHz con al menos ×9 de verdad', done: 'Con ganancia 10 hace falta un GBW bastante mayor que 10 × 100 kHz = 1 MHz: el de 3 MHz ya da ×9,5.', hint: 'Ganancia 10, frecuencia 100 kHz, y elige un chip más rápido.' }
        ] },
      I('<b>Producto ganancia–ancho de banda</b> (GBW): ganancia × ancho de banda ≈ constante.\n<b>BW ≈ GBW / G</b>. Un LM358 tiene unos 1 MHz (según fabricante, de 0,7 a 1,1): con G = 100, unos 10 kHz; con G = 10, unos 100 kHz.', { svg: `<svg viewBox="0 0 300 130" class="viz"><path d="M30 10V105H285" ${st} stroke-width="1.4"/><path d="M40 20L260 105" stroke="var(--muted)" stroke-dasharray="4 4" fill="none"/><path d="M30 45H96L190 82" stroke="var(--led)" stroke-width="3" fill="none"/><path d="M30 70H160L218 92" stroke="var(--ice)" stroke-width="3" fill="none"/><text x="34" y="40" class="vizsm">G = 100</text><text x="34" y="66" class="vizsm">G = 10</text><path d="M96 45V105M160 70V105" stroke="var(--line)" stroke-dasharray="2 3"/><text x="96" y="118" text-anchor="middle" class="vizsm">10 kHz</text><text x="160" y="118" text-anchor="middle" class="vizsm">100 kHz</text></svg>` }),
      { t: 'steps', text: 'Quieres amplificar ×100 una señal de audio (hasta 20 kHz) con un LM358 (GBW = 1 MHz). ¿Llega?', steps: ['Ancho de banda con G = 100: <b>BW = GBW / G</b> = 1 MHz / 100 = 10 kHz', '10 kHz < 20 kHz: <b>no llega</b>, los agudos salen atenuados', 'Truco: reparte la ganancia en <b>dos etapas de ×10</b> (10 × 10 = 100)', 'Cada etapa: BW = 1 MHz / 10 = <b>100 kHz</b>, de sobra para 20 kHz'], result: 'Dos etapas de ×10 en lugar de una de ×100 (o un chip con más GBW).' },
      G('opBandwidth'),
      I('<b>Slew rate</b> (SR): la máxima velocidad a la que puede cambiar la salida, en V/µs. LM358: unos 0,3–0,6 V/µs; TL072: unos 13 V/µs. Si la señal pide subir más rápido, la salida sube en línea recta: la senoide se convierte en triángulo.\n<b>fmax = SR / (2π · Vp)</b>.', { svg: '<svg viewBox="0 0 300 120" class="viz"><path d="M20 60H285" stroke="var(--line)"/><path d="M20 60C45 10 70 10 95 60S145 110 170 60S220 10 245 60S285 95 285 95" fill="none" stroke="var(--muted)" stroke-dasharray="4 4"/><path d="M20 60L57 22L95 60L132 98L170 60L207 22L245 60L282 98" fill="none" stroke="var(--led)" stroke-width="3" class="a-draw" style="--len:420"/><text x="20" y="114" class="vizsm">gris: lo que debería salir · naranja: lo que sale</text></svg>' }),
      G('opSlew'),
      Q('Una senoide grande de 20 kHz sale triangular de un LM358. ¿Causa más probable?', ['Slew rate insuficiente', 'Offset', 'Falta de alimentación negativa', 'Exceso de GBW'], 'La pendiente de la senoide supera la que puede dar el chip.', { c: 'bb_gbw', h: 'Una forma triangular delata un límite de velocidad de la salida.' }),
      I('<b>Márgenes</b>: un LM358 a 5 V solo saca de unos 0 a 3,5 V, y sus entradas funcionan desde masa hasta unos 3,5 V. Un operacional <b>rail-to-rail</b> (MCP6002, TLV2372…) llega casi a 0 y a 5 V. Con alimentación única y baja, se nota muchísimo.', { svg: `<svg viewBox="0 0 300 110" class="viz">${hbar(30, 40, 240, 3.5 / 5, '#F2A900', 'LM358 a 5 V: salida de 0 a 3,5 V')}${hbar(30, 85, 240, 4.95 / 5, '#1F9D55', 'Rail-to-rail a 5 V: de casi 0 a casi 5 V')}</svg>` }),
      Q('Alimentas un LM358 a 5 V y su salida tiene que llegar a 4,8 V para la entrada de un chip que mide tensión. ¿Qué pasa?', ['No llega: se queda en unos 3,5 V; usa un rail-to-rail', 'Llega sin problema', 'Llega a 10 V', 'Se quema'], 'Mira la tensión máxima de salida (VOH) en la hoja de datos.', { c: 'bb_oplimits', h: 'Busca hasta dónde llega la salida del LM358 con 5 V.' }),
      { t: 'match', q: 'Une cada síntoma con el límite que lo causa.', pairs: [['Salida a 0,3 V con entrada a 0 V y G = 100', 'Offset'], ['Ganancia que cae a 50 kHz', 'GBW'], ['Senoide grande convertida en triángulo', 'Slew rate'], ['Salida que no pasa de 3,5 V a 5 V', 'No es rail-to-rail']], c: 'bb_oplimits', h: 'Error fijo, frecuencia, velocidad o tope: un límite para cada síntoma.' },
      RES('<b>Offset</b>: mV de error que la ganancia multiplica.', '<b>BW ≈ GBW / G</b>: mucha ganancia, poco ancho de banda.', '<b>Slew rate</b>: fmax = SR / (2π · Vp); si no, triángulos.', 'Para llegar a la alimentación: <b>rail-to-rail</b>.')
    ]),
    L('k11', 'Sumador y restador', 'amp', ['bb_summer', 'bb_diffamp', 'bb_opgain'], [
      Q('En un inversor con la entrada + a masa y funcionando bien, ¿a qué tensión está la entrada −?', ['A 0 V, aunque no esté conectada a masa', 'A la tensión de la entrada', 'A la de la salida', 'A la de la alimentación'], 'Regla de oro: V− = V+ = 0 V. A ese punto se le llama masa virtual, y con él se pueden sumar señales.', { predict: true, c: 'bb_summer', h: 'Aplica la regla de oro: ¿a cuánto está la +?' }),
      I('<b>Masa virtual</b>: en el inversor, la − se queda a 0 V. Si llegan varias entradas por su resistencia, cada una mete su corriente <b>Vi / Ri</b> sin molestar a las demás (el punto no se mueve), y todas salen por Rf.', { svg: `<svg viewBox="0 0 300 140" class="viz"><path d="M20 35H120V70M20 105H120V70M120 70H200" ${st}/><path d="M20 35H120V70M20 105H120V70M120 70H200" stroke="var(--led)" stroke-width="3" fill="none" class="a-flow"/><circle cx="120" cy="70" r="6" fill="var(--ok)"/><text x="128" y="62" class="vizlab" style="fill:var(--ok)">0 V</text><text x="20" y="27" class="vizsm">I1 = V1 / R1</text><text x="20" y="125" class="vizsm">I2 = V2 / R2</text><text x="200" y="62" class="vizsm">I1 + I2 por Rf</text></svg>` }),
      { t: 'explore', text: 'Un <b>sumador inversor</b>. Las dos corrientes se juntan en la masa virtual y pasan por Rf.', viz: 'summer', params: { V1: SL('V1', 1, -2, 2, 0.1, 'V', 1), V2: SL('V2', 1, -2, 2, 0.1, 'V', 1), R1: LS('R1', 10000, [5000, 10000, 20000]), R2: LS('R2', 10000, [5000, 10000, 20000]), Rf: LS('Rf', 10000, [5000, 10000, 20000]) },
        tasks: [
          { q: 'Vout', min: -3.05, max: -2.95, text: 'Consigue −3 V en la salida', done: 'Con todas las resistencias iguales, la salida es la suma cambiada de signo: −(V1 + V2).', hint: 'Con 10 kΩ en todas, V1 + V2 = 3 V.' },
          { q: 'ratio', min: 1.95, max: 2.05, text: 'Haz que V2 pese el doble que V1', done: 'Si R2 es la mitad que R1, por ella entra el doble de corriente con la misma tensión.', hint: 'R2 la mitad de R1.' },
          { q: 'zero', min: 1, max: 1, text: 'Consigue 0 V en la salida con V1 distinta de 0', done: 'Si una corriente entra y la otra sale en la misma cantidad, se anulan.', hint: 'Una entrada positiva y otra negativa.' }
        ] },
      I('<b>Vsal = −Rf · (V1 / R1 + V2 / R2 + …)</b>\nCon todas las resistencias iguales, Vsal = −(V1 + V2 + …). Cambiando cada Ri cambias el peso de esa entrada: así funciona una mesa de mezclas.'),
      { t: 'steps', text: 'Sumador con Rf = R1 = R2 = 10 kΩ, V1 = 1 V y V2 = 2 V. ¿Vsal?', steps: ['La − está a 0 V (masa virtual)', 'I1 = 1 V / 10 kΩ = <b>0,1 mA</b>; I2 = 2 V / 10 kΩ = <b>0,2 mA</b>', 'Por Rf pasan 0,1 + 0,2 = <b>0,3 mA</b>', 'En Rf caen 0,3 mA × 10 kΩ = 3 V, y la salida queda por debajo del 0 V: <b>−3 V</b>'], result: 'Vsal = −3 V: la suma, cambiada de signo.' },
      Nm('Sumador con Rf = 10 kΩ, R1 = 10 kΩ, R2 = 5 kΩ y V1 = V2 = 1 V. ¿Vsal en V, con signo?', -3, 'V', '−10k · (1/10k + 1/5k) = −(1 + 2) = −3 V: la entrada de 5 kΩ pesa el doble.', { tol: 0.03, c: 'bb_summer', h: 'Cada entrada pesa Rf / Ri: aquí 1 y 2.' }),
      G('summerOut'),
      I('<b>Restador</b> (amplificador diferencial): cuatro resistencias. Con R1 = R3 y R2 = R4:\n<b>Vsal = (R2 / R1) · (V2 − V1)</b>.\nSolo amplifica la <b>diferencia</b>: lo que tengan en común las dos entradas (la tensión común) no sale.', { svg: `<svg viewBox="0 0 300 165" class="viz">${OP(180, 75, 1.3, '−', '+')}<path d="M20 62H60M100 62H141M120 62V25H160M200 25H235V75M219 75H285M20 88H60M100 88H141M120 88V95M120 135V140" ${st}/>${RH(80, 62)}${RH(180, 25)}${RH(80, 88)}${RV(120, 115)}${GND(120, 140)}<circle cx="120" cy="62" r="3" fill="currentColor"/><circle cx="120" cy="88" r="3" fill="currentColor"/><circle cx="235" cy="75" r="3" fill="currentColor"/><text x="14" y="55" class="vizsm">V1</text><text x="14" y="104" class="vizsm">V2</text><text x="80" y="48" text-anchor="middle" class="vizsm">R1</text><text x="180" y="13" text-anchor="middle" class="vizsm">R2</text><text x="80" y="110" text-anchor="middle" class="vizsm">R3</text><text x="130" y="120" class="vizsm">R4</text><text x="285" y="66" text-anchor="end" class="vizlab">Vsal</text></svg>` }),
      { t: 'explore', text: 'Dos entradas que comparten una tensión común (Vcm) y se diferencian en unos milivoltios (Vd). Mira la salida.', viz: 'diffAmp', params: { Vcm: SL('Tensión común', 2.5, 0, 5, 0.1, 'V', 1), Vd: LS('Diferencia V2 − V1', 10, [-50, -20, -10, 0, 10, 20, 50], 'mV'), G: LS('Ganancia R2 / R1', 10, [1, 10, 100]), tol: LS('Desajuste de las resistencias', 0, [0, 0.1, 1, 5], '%', 1) },
        tasks: [
          { q: 'cmOk', min: 1, max: 1, text: 'Sube la tensión común por encima de 4 V con resistencias perfectas', done: 'La salida ni se mueve: solo cuenta la diferencia.', hint: 'Desajuste en 0 % y mueve la tensión común.' },
          { q: 'bigErr', min: 1, max: 1, text: 'Ahora usa resistencias desparejas y busca un error de 100 mV o más', done: 'Parte de la tensión común se cuela en la salida como si fuera señal. Por eso se usan resistencias del 0,1 %.', hint: 'Desajuste del 5 % y ganancia alta.' }
        ] },
      Nm('Restador con R2 / R1 = 10, V2 = 2,05 V y V1 = 2,00 V. ¿Vsal en V?', 0.5, 'V', '10 × (2,05 − 2,00) = 10 × 0,05 = 0,5 V. Los 2 V comunes no salen.', { tol: 0.01, c: 'bb_diffamp', h: 'Resta primero las entradas y multiplica la diferencia por R2 / R1.' }),
      Q('¿Para qué sirve un restador detrás de un puente de Wheatstone?', ['Para amplificar la pequeña diferencia entre sus salidas e ignorar la tensión común', 'Para sumar sus salidas', 'Para alimentar el puente', 'Para filtrarlo'], 'Los dos puntos medios están a unos 2,5 V; lo interesante son los milivoltios de diferencia.', { c: 'bb_diffamp', h: 'Piensa qué tienen en común y en qué se diferencian las dos salidas del puente.' }),
      Q('Las resistencias del restador tienen un 5 % de tolerancia. ¿Qué empeora?', ['El rechazo de la tensión común: parte de ella aparece en la salida', 'Nada', 'La alimentación', 'El offset desaparece'], 'Para medir bien se usan resistencias del 0,1 % o amplificadores de instrumentación integrados (INA).', { c: 'bb_diffamp', h: 'Recuerda lo que pasaba en la exploración con el desajuste.' }),
      I('Truco para <b>alimentación única</b>: si no tienes tensión negativa, lleva la + a una <b>referencia</b> de media alimentación (2,5 V con un divisor y un condensador). Ahora la masa virtual está a 2,5 V y la salida oscila alrededor de 2,5 V en lugar de 0 V.', { svg: '<svg viewBox="0 0 300 120" class="viz"><path d="M20 20H285M20 100H285" stroke="var(--line)"/><path d="M20 60H285" stroke="var(--ok)" stroke-dasharray="5 4"/><path d="M20 60C50 25 80 25 110 60S170 95 200 60S260 25 285 60" fill="none" stroke="var(--led)" stroke-width="3"/><text x="288" y="24" text-anchor="end" class="vizsm">5 V</text><text x="288" y="56" text-anchor="end" class="vizsm" style="fill:var(--ok)">2,5 V</text><text x="288" y="114" text-anchor="end" class="vizsm">0 V</text></svg>' }),
      Q('Alimentación única de 5 V, la + a 2,5 V y un inversor de ganancia −1. Con la entrada a 0 V, ¿qué sale?', ['5 V (2,5 + 2,5), si la salida llega', '0 V', '−2,5 V', '2,5 V'], 'La entrada está 2,5 V por debajo de la referencia; la salida se aleja lo mismo hacia arriba: 2,5 + 2,5 = 5 V.', { c: 'bb_opgain', h: 'Mide todo respecto a la referencia de 2,5 V, no respecto a masa.' }),
      RES('<b>Masa virtual</b>: la − a la tensión de la +, sin corriente.', 'Sumador: <b>Vsal = −Rf · (V1/R1 + V2/R2 …)</b>.', 'Restador: <b>(R2 / R1) · (V2 − V1)</b>; la tensión común no sale si las resistencias casan.', 'Alimentación única: referencia a media tensión.')
    ]),
    L('k7', 'Comparadores', 'amp', ['bb_comp', 'bb_cmpoc', 'bb_hystwhy'], [
      Q('Quitas las resistencias de realimentación: el operacional a pelo, con IN+ a 2,6 V e IN− a 2,5 V. ¿Qué crees que sale?', ['Lo máximo: la salida se va arriba', '0,1 V', 'A mitad de la alimentación', '2,6 V'], 'Sin realimentación, 0,1 V × 100 000 satura la salida. En vez de amplificar, decide: ¿cuál de las dos es mayor? Eso es un comparador.', { predict: true, c: 'bb_comp', h: 'Sin realimentación, la ganancia es enorme.' }),
      { t: 'explore', text: 'Una LDR en un divisor va a IN+ y un potenciómetro (el <b>umbral</b>) a IN−. Mueve la luz y el umbral.', viz: 'comparator', params: { luz: SL('Luz', 50, 0, 100, 5, '%', 0), Vref: SL('Umbral (IN−)', 4.8, 0, 5, 0.1, 'V', 1), ruido: LS('Ruido en la señal', 0, [0, 0.05, 0.2], 'V', 2) },
        tasks: [
          { q: 'on', min: 1, max: 1, text: 'Enciende el LED moviendo solo el umbral', done: 'Cuando IN+ supera a IN−, la salida sube.', hint: 'Baja el umbral por debajo de la señal.' },
          { q: 'darkOnly', min: 1, max: 1, text: 'Ajusta el umbral para que el LED se encienda con un 10 % de luz y no con un 30 %', done: 'El umbral queda entre las dos tensiones del divisor: así eliges con cuánta oscuridad salta.', hint: 'Busca un umbral entre unos 3,6 y 4,3 V.' },
          { q: 'chatter', min: 1, max: 1, text: 'Pon ruido y deja la señal justo en el umbral', done: 'La salida tiembla: cada pico de ruido cruza el umbral. Lo arreglarás en la próxima lección.', hint: 'Ruido de 0,2 V y mueve la luz hasta que la señal toque la línea roja.' }
        ] },
      I('Sin realimentación, el operacional es un <b>comparador</b>: si <b>IN+ > IN−</b>, salida alta; si no, baja. No hay término medio.\nUna entrada lleva la <b>señal</b> que vigilas; la otra, una <b>referencia</b> (el umbral).', { svg: `<svg viewBox="0 0 300 130" class="viz">${OP(150, 60, 1.3)}<path d="M111 47H40M111 73H40M189 60H230" ${st}/><text x="30" y="40" class="vizlab">señal</text><text x="30" y="92" class="vizlab">umbral</text><g transform="translate(255 60)">${ledBulb(1)}</g><text x="150" y="122" text-anchor="middle" class="vizsm">señal > umbral → LED encendido</text></svg>` }),
      { t: 'steps', text: 'Luz nocturna: 10 kΩ arriba y la LDR abajo van a IN+; un potenciómetro a 2,5 V va a IN−. Alimentación de 5 V. La LDR mide 1 kΩ con luz y 100 kΩ a oscuras.', steps: ['Con luz: IN+ = 5 × 1 / (10 + 1) = <b>0,45 V</b>', '0,45 V < 2,5 V → salida <b>baja</b>, LED apagado', 'A oscuras: IN+ = 5 × 100 / (10 + 100) = <b>4,5 V</b>', '4,5 V > 2,5 V → salida <b>alta</b>, LED encendido'], result: 'Girando el potenciómetro eliges a partir de qué oscuridad se enciende.' },
      Q('IN+ = 2,1 V e IN− = 2,5 V. ¿Cómo está la salida del comparador?', ['Baja', 'Alta', 'A mitad', 'Oscilando'], 'IN+ es menor que IN−.', { c: 'bb_comp', h: 'Compara las dos entradas: ¿gana la +?' }),
      Q('En la luz nocturna, ¿para qué sirve el potenciómetro de IN−?', ['Para ajustar el umbral', 'Para alimentar el circuito', 'Para fijar la ganancia', 'Para medir la luz'], 'Es la referencia con la que se compara la señal de la LDR.', { c: 'bb_comp', h: 'Una entrada vigila; la otra marca el límite.' }),
      Q('Ahora la señal de un termistor va a IN− y el potenciómetro a IN+. Cuando la señal supera la referencia, la salida…', ['Baja', 'Sube', 'No cambia', 'Oscila sin parar'], 'Ahora IN− > IN+: al cambiar de entrada se invierte el sentido.', { c: 'bb_comp', h: 'Mira en qué entrada está la señal.' }),
      I('Hay <b>comparadores dedicados</b> (LM393, LM339), más rápidos que un operacional usado así. Su salida es de <b>colector abierto</b>: un transistor que la une a masa o la deja suelta. Necesita una <b>pull-up</b> (como en k20) a la tensión que quieras como nivel alto.', { svg: `<svg viewBox="0 0 300 130" class="viz">${OP(90, 60, 1.2)}<path d="M126 60H200M200 20V60M200 60V110" ${st}/><rect x="192" y="22" width="16" height="30" rx="6" fill="#E7D3A8" stroke="#C9B183"/><text x="214" y="40" class="vizsm">pull-up</text><text x="200" y="14" text-anchor="middle" class="vizsm">+5 V</text><path d="M200 75v20" stroke="var(--err)" stroke-width="3" class="a-blink"/>${GND(200, 110)}<text x="214" y="90" class="vizsm" style="fill:var(--err)">tira a masa</text><text x="250" y="64" class="vizlab">salida</text></svg>` }),
      Q('Usas un LM339 y su salida no sube nunca a nivel alto. ¿Qué falta?', ['La resistencia pull-up', 'Más tensión en IN+', 'Un condensador en la salida', 'Un LED en serie'], 'Un colector abierto solo sabe tirar a masa; el nivel alto lo pone la pull-up.', { c: 'bb_cmpoc', h: 'Recuerda cómo es la salida de un LM339.' }),
      Nm('Salida de colector abierto con una pull-up de 10 kΩ a 5 V. Cuando la salida está baja, ¿cuánta corriente pasa por la pull-up, en mA?', 0.5, 'mA', '5 V / 10 kΩ = 0,5 mA (casi toda la tensión cae en la pull-up).', { tol: 0.01, c: 'bb_cmpoc', h: 'Con la salida a 0 V, la pull-up tiene los 5 V entre sus patas: ley de Ohm.' }),
      I('Cerca del umbral, el <b>ruido</b> cruza la línea una y otra vez y la salida tiembla: el LED parpadea, un relé zumba. La cura es la <b>histéresis</b>: un umbral para subir y otro, algo más bajo, para bajar.', { svg: '<svg viewBox="0 0 300 120" class="viz"><path d="M20 50H285" stroke="var(--err)" stroke-dasharray="5 4"/><path d="M20 62L60 56L70 46L80 54L90 44L100 52L110 45L120 55L130 47L160 38L285 30" fill="none" stroke="var(--ice)" stroke-width="2"/><path d="M20 105H66V85H72V105H86V85H96V105H104V85H285" fill="none" stroke="var(--led)" stroke-width="2.5"/><text x="20" y="20" class="vizsm">la señal ruidosa cruza el umbral varias veces…</text><text x="150" y="80" class="vizsm">…y la salida rebota</text></svg>' }),
      Q('Cerca del umbral la salida del comparador tiembla. ¿Qué lo soluciona?', ['Histéresis: algo de realimentación positiva', 'Más tensión de alimentación', 'Quitar el potenciómetro', 'Nada'], 'Con dos umbrales separados, el ruido pequeño ya no la hace cambiar.', { c: 'bb_hystwhy', h: 'Piensa en un termostato que enciende a una temperatura y apaga a otra.' }),
      RES('Sin realimentación: <b>IN+ > IN−</b> → alta; si no, baja.', 'Señal en una entrada, umbral (referencia) en la otra.', 'LM393/LM339: colector abierto → <b>pull-up</b>.', 'El ruido en el umbral hace temblar la salida: histéresis.')
    ]),
    SIM('s5', 'Reto: luz nocturna automática', 'El LED se enciende a oscuras (5 % de luz) y se apaga con luz (95 %).', { battery: 9, parts: ['ldr', 'res', 'pot', 'cmp', 'led'], hint: 'R arriba y LDR abajo → IN+. Cursor del potenciómetro → IN−. VCC al +. Salida → resistencia → LED → −.' }, 'nightLight'),
    L('k14', 'Schmitt trigger con números', 'amp', ['bb_schmitt_calc', 'bb_hystwhy'], [
      Q('Un termostato enciende la calefacción por debajo de 20,0 °C y la apaga por encima de 20,0 °C. ¿Qué crees que pasará cuando la casa esté a unos 20 °C?', ['Encenderá y apagará sin parar', 'Funcionará perfecto', 'No encenderá nunca', 'Se quedará siempre encendida'], 'Cualquier décima arriba o abajo lo hace cambiar. Los termostatos reales encienden a 19 °C y apagan a 21 °C: dos umbrales. Eso es histéresis.', { predict: true, c: 'bb_hystwhy', h: 'Piensa en lo que pasa con pequeñas variaciones alrededor de un único umbral.' }),
      I('El <b>Schmitt trigger</b> es un comparador con <b>realimentación positiva</b>: la salida vuelve a la entrada + y la empuja en su mismo sentido. Así el umbral depende de la salida: mientras está baja, la entrada tiene que llegar a un umbral <b>alto</b> para que suba; en cuanto sube, el umbral pasa a uno <b>más bajo</b>, y la entrada tiene que caer hasta él para que vuelva a bajar. Dos umbrales: uno para <b>subir</b> y otro, más bajo, para <b>bajar</b>.', { svg: `<svg viewBox="0 0 300 140" class="viz">${OP(150, 60, 1.3)}<path d="M30 47H111M111 73H60M189 60H250V20H90V47" ${st}/><path d="M250 60V20H90V47" stroke="var(--led)" stroke-width="3" fill="none" class="a-flow-slow"/><g transform="translate(55 47)">${resBody()}</g><g transform="translate(170 20)">${resBody()}</g><text x="55" y="34" text-anchor="middle" class="vizsm">R1</text><text x="170" y="12" text-anchor="middle" class="vizsm">R2</text><text x="22" y="40" class="vizsm">ent.</text><text x="40" y="90" class="vizsm">Vref</text><text x="150" y="128" text-anchor="middle" class="vizsm">la salida vuelve a la + (realimentación positiva)</text></svg>` }),
      { t: 'explore', text: 'Una señal triangular con ruido entra a un Schmitt a 5 V. Rojo: umbral de subida. Verde: de bajada. Ajusta R1 y R2.', viz: 'schmittHyst', params: { R1: { label: 'R1', val: 1000, list: [1000, 2200, 4700, 10000, 22000, 47000], fmt: 'R' }, R2: { label: 'R2', val: 220000, list: [10000, 22000, 47000, 100000, 220000], fmt: 'R' } },
        tasks: [
          { q: 'clean', min: 1, max: 1, text: 'Consigue una salida limpia: 4 cambios, sin rebotes', done: 'La histéresis supera al ruido (unos 0,4 V pico a pico): cada cruce cuenta una sola vez.', hint: 'Más R1 o menos R2 separan las líneas.' },
          { q: 'tr', min: 0, max: 0, text: 'Ahora pásate: que la salida no cambie nunca', done: 'Con demasiada histéresis, el umbral de subida queda por encima de la señal: pierdes sensibilidad.', hint: 'R1 grande y R2 pequeña.' }
        ] },
      I('Schmitt no inversor con alimentación única: Vref a IN−, la entrada llega a IN+ por R1 y la salida vuelve a IN+ por R2. Con salida rail-to-rail:\n· Histéresis: <b>H = Vcc · R1 / R2</b>\n· Subida: <b>Vref · (R1 + R2) / R2</b>\n· Bajada: subida − H.', { svg: '<svg viewBox="0 0 300 140" class="viz"><path d="M30 120H280M40 130V15" stroke="currentColor" stroke-width="1.4"/><path d="M40 112H190V28H280" fill="none" stroke="var(--led)" stroke-width="3"/><path d="M280 28H130V112H40" fill="none" stroke="var(--ice)" stroke-width="2" stroke-dasharray="5 4"/><path d="M190 62l-6 8h12zM130 70l-6 -8h12z" fill="currentColor"/><text x="190" y="134" text-anchor="middle" class="vizsm">sube</text><text x="130" y="134" text-anchor="middle" class="vizsm">baja</text><text x="160" y="14" text-anchor="middle" class="vizsm">H</text><path d="M130 19H190" stroke="currentColor" stroke-width="1.4"/><text x="275" y="116" text-anchor="end" class="vizsm">entrada →</text><text x="46" y="14" class="vizsm">salida</text></svg>', more: 'Por qué: con la salida baja (0 V), R1 y R2 forman un divisor entre la entrada y 0 V; para que IN+ llegue a Vref, la entrada tiene que pasar un poco más arriba. Con la salida alta (Vcc), el divisor va hacia Vcc y la entrada puede bajar algo más antes de que IN+ caiga por debajo de Vref.\nCon Vref = Vcc / 2, los dos umbrales quedan centrados a ±H/2.' }),
      { t: 'steps', text: 'Vcc = 5 V, Vref = 2,5 V, R1 = 4,7 kΩ y R2 = 47 kΩ. ¿Umbrales e histéresis?', steps: ['Histéresis: <b>H = Vcc · R1 / R2</b> = 5 × 4,7 / 47 = <b>0,5 V</b>', 'Subida: 2,5 × (4,7 + 47) / 47 = 2,5 × 1,1 = <b>2,75 V</b>', 'Bajada: 2,75 − 0,5 = <b>2,25 V</b>', 'Comprueba: centrados en 2,5 V, a ±0,25 V'], result: 'Sube a 2,75 V, baja a 2,25 V: 0,5 V de histéresis.' },
      G('schmittThr'), G('schmittThr'),
      Q('Aumentas R1 sin tocar R2. La histéresis…', ['Aumenta', 'Disminuye', 'No cambia', 'Desaparece'], 'H = Vcc · R1 / R2: crece con R1.', { c: 'bb_schmitt_calc', h: 'Mira dónde está R1 en la fórmula de H.' }),
      Q('¿Cuánta histéresis conviene?', ['Algo más que el ruido pico a pico, sin pasarse para no perder sensibilidad', 'Toda la posible', 'Ninguna', '10 V siempre'], 'Es un compromiso entre limpieza y precisión.', { c: 'bb_hystwhy', h: 'Recuerda los dos extremos de la exploración.' }),
      Nm('Schmitt a 12 V con Vref = 6 V, R1 = 10 kΩ y R2 = 100 kΩ. ¿Umbral de subida en V?', 6.6, 'V', '6 × (10 + 100) / 100 = 6,6 V. La histéresis es 12 × 10 / 100 = 1,2 V, así que baja a 5,4 V.', { tol: 0.02, c: 'bb_schmitt_calc', h: 'Subida = Vref · (R1 + R2) / R2.' }),
      Q('A 5 V, tu señal tiene 0,3 V de ruido pico a pico y quieres unos 0,5 V de histéresis. ¿Qué pareja eliges?', ['R1 = 10 kΩ y R2 = 100 kΩ', 'R1 = 100 kΩ y R2 = 10 kΩ', 'R1 = 1 kΩ y R2 = 1 MΩ', 'R1 = R2 = 10 kΩ'], '5 × 10 / 100 = 0,5 V. Las demás dan 50 V (imposible), 5 mV o 5 V.', { c: 'bb_schmitt_calc', h: 'Calcula 5 · R1 / R2 para cada pareja.' }),
      I('Hay chips lógicos con un Schmitt en cada entrada: limpian señales lentas o ruidosas con un solo componente. Los conocerás en el módulo de lógica digital.', { svg: '<svg viewBox="0 0 300 100" class="viz"><path d="M20 80C80 80 100 20 150 20" fill="none" stroke="var(--ice)" stroke-width="2.5"/><path d="M170 80H215V20H285" fill="none" stroke="var(--led)" stroke-width="3"/><text x="20" y="96" class="vizsm">entrada lenta</text><text x="285" y="96" text-anchor="end" class="vizsm">un único flanco limpio</text><path d="M155 50h12" stroke="currentColor" stroke-width="2"/><path d="M167 50l-5 -4v8z" fill="currentColor"/></svg>' }),
      RES('Realimentación positiva → <b>dos umbrales</b>.', '<b>H = Vcc · R1 / R2</b>; subida = Vref · (R1 + R2) / R2.', 'Histéresis algo mayor que el ruido, sin pasarse.')
    ]),
    L('k12', 'Integrador y derivador', 'amp', ['bb_integ'], [
      Q('Cargas un condensador con una corriente constante. ¿Cómo crees que sube su tensión?', ['En línea recta: lo mismo cada segundo', 'Cada vez más despacio, como en el RC', 'De golpe', 'No sube'], 'Con corriente fija entra la misma carga cada segundo, y como Q = C · V, la tensión sube lo mismo cada segundo: una rampa. En el RC se frenaba porque la corriente iba bajando.', { predict: true, c: 'bb_integ', h: 'Recuerda Q = C · V: ¿cuánta carga entra cada segundo?' }),
      { t: 'explore', text: 'Un <b>integrador</b>: un inversor con un condensador en lugar de Rf. Azul: la entrada. Naranja: la salida.', viz: 'integrator', params: { mode: LS('Entrada (0 continua, 1 cuadrada de 10 Hz)', 0, [0, 1]), Vin: LS('Amplitud de la entrada', 1, [0.5, 1, 2], 'V', 1), R: { label: 'R', val: 100000, list: [10000, 47000, 100000], fmt: 'R' }, C: LS('C', 1, [0.1, 1, 10], 'µF', 1) },
        tasks: [
          { q: 'slope', min: 99, max: 101, text: 'Consigue una rampa de 100 V/s', done: 'Pendiente = Vent / (R · C) = 1 V / (10 kΩ × 1 µF) = 100 V/s.', hint: 'Pendiente = Vent / (R · C). Prueba con 10 kΩ y 1 µF.' },
          { q: 'tsat', min: 1, max: 1000, text: 'Que tarde más de 1 s en llegar al límite', done: 'Menos pendiente: más R, más C o menos entrada.', hint: 'Más R · C o menos entrada.' },
          { q: 'tri', min: 1, max: 1, text: 'Pasa a entrada cuadrada y consigue una triangular que no se sature', done: 'Cada tramo constante de la cuadrada se convierte en una rampa: sube, baja, sube…', hint: 'Entrada a 1 y una pendiente moderada (R · C grande).' }
        ] },
      I('La entrada mete una corriente <b>Vent / R</b> (la − es masa virtual) que carga el condensador de la realimentación. Corriente constante → rampa.\n<b>Pendiente = Vent / (R · C)</b>, con el signo cambiado (es un inversor).', { svg: `<svg viewBox="0 0 300 140" class="viz">${OP(170, 70, 1.3)}<path d="M20 83H55M95 83H131M110 83V30H160M180 30H230V70M209 70H280M131 57H124" ${st}/>${RH(75, 83)}<path d="M160 18v24M168 18v24" ${st}/>${GND(124, 57)}<text x="164" y="12" text-anchor="middle" class="vizsm">C</text><text x="75" y="104" text-anchor="middle" class="vizsm">R</text><path d="M240 120L280 95" stroke="var(--led)" stroke-width="3"/><text x="20" y="130" class="vizsm">entrada fija → salida en rampa</text></svg>` }),
      { t: 'steps', text: 'Integrador con R = 10 kΩ, C = 1 µF y 1 V a la entrada. ¿Pendiente? ¿Cuánto tarda en moverse 5 V?', steps: ['Corriente de entrada: 1 V / 10 kΩ = <b>0,1 mA</b>', 'Pendiente: <b>Vent / (R · C)</b> = 1 / (10 000 × 0,000 001) = <b>100 V/s</b>', 'Tiempo para 5 V: 5 V / 100 V/s = <b>0,05 s = 50 ms</b>', 'La salida baja (inversor): de 0 a −5 V en 50 ms'], result: '100 V/s: 5 V en 50 ms.' },
      Nm('Integrador con R = 100 kΩ, C = 10 µF y 2 V a la entrada. ¿Pendiente en V/s (sin signo)?', 2, 'V/s', '2 / (100 000 × 0,000 01) = 2 / 1 = 2 V/s.', { tol: 0.02, c: 'bb_integ', h: 'Pendiente = Vent / (R · C); pasa los µF a F.' }),
      Q('Un integrador tiene una pendiente de 100 V/s. ¿Cuánto tarda la salida en moverse 5 V?', ['50 ms', '5 s', '0,5 ms', '500 ms'], '5 / 100 = 0,05 s.', { c: 'bb_integ', h: 'Tiempo = cambio de tensión / pendiente.' }),
      I('Un integrador ideal acaba saturado por culpa del offset: también lo acumula, sin parar. En la práctica se pone una <b>resistencia grande en paralelo</b> con el condensador (por ejemplo, 1 MΩ) que limita la ganancia en continua.', { svg: '<svg viewBox="0 0 300 100" class="viz"><path d="M20 20H285M20 80H285" stroke="var(--line)"/><path d="M20 50L120 80H285" fill="none" stroke="var(--err)" stroke-width="2.5"/><path d="M20 50C80 55 120 58 285 58" fill="none" stroke="var(--ok)" stroke-width="2.5"/><text x="285" y="95" text-anchor="end" class="vizsm" style="fill:var(--err)">sin resistencia: deriva</text><text x="285" y="48" text-anchor="end" class="vizsm" style="fill:var(--ok)">con resistencia: quieta</text></svg>' }),
      Q('¿Qué hace un integrador con una onda cuadrada?', ['La convierte en triangular', 'La convierte en una senoide perfecta', 'La deja igual', 'La anula'], 'Cada tramo constante se convierte en una rampa.', { c: 'bb_integ', h: 'Recuerda la tercera prueba de la exploración.' }),
      I('Al revés, condensador en la entrada y resistencia en la realimentación: <b>derivador</b>. Su salida es proporcional a lo rápido que cambia la entrada: −R · C · ΔVent / Δt. Una rampa de pendiente fija da una salida constante. Amplifica mucho el ruido rápido: se le pone una resistencia en serie con el condensador.', { svg: '<svg viewBox="0 0 300 110" class="viz"><path d="M20 50L70 15L120 50L170 15L220 50L270 15" fill="none" stroke="var(--ice)" stroke-width="2"/><path d="M20 100V70H70V100H120V70H170V100H220V70H270" fill="none" stroke="var(--led)" stroke-width="3"/><text x="285" y="35" text-anchor="end" class="vizsm">entrada</text><text x="285" y="90" text-anchor="end" class="vizsm">salida</text></svg>' }),
      Q('¿Qué hace un derivador con una onda triangular?', ['La convierte en cuadrada', 'La hace más grande', 'La anula', 'La convierte en continua'], 'Cada rampa tiene pendiente constante: da una salida constante, que cambia de signo con la rampa.', { c: 'bb_integ', h: 'El derivador mide la pendiente de cada tramo.' }),
      Q('En el fondo, un integrador es…', ['Un paso bajo con mucha ganancia', 'Un paso alto', 'Un comparador', 'Un oscilador'], 'Su ganancia baja 20 dB por década, como la de un RC por encima del corte.', { c: 'bb_integ', h: 'Piensa qué hace un condensador en la realimentación con las frecuencias altas.' }),
      I('Junta un integrador y un Schmitt en lazo y tienes un <b>generador de funciones</b>: el Schmitt da una cuadrada, el integrador la convierte en rampa y, cuando la rampa toca un umbral, el Schmitt cambia y la rampa se da la vuelta.', { svg: '<svg viewBox="0 0 300 130" class="viz"><rect x="20" y="40" width="90" height="44" rx="8" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="65" y="67" text-anchor="middle" class="vizlab">Schmitt</text><rect x="190" y="40" width="90" height="44" rx="8" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="235" y="67" text-anchor="middle" class="vizlab">Integrador</text><path d="M110 62H190" stroke="var(--led)" stroke-width="2.5" class="a-flow"/><path d="M235 84V112H65V84" fill="none" stroke="var(--led)" stroke-width="2.5" class="a-flow"/><text x="150" y="54" text-anchor="middle" class="vizsm">cuadrada</text><text x="150" y="126" text-anchor="middle" class="vizsm">triangular</text></svg>' }),
      { t: 'order', q: 'Ordena el lazo del generador de funciones.', items: ['El Schmitt da una cuadrada', 'El integrador la convierte en rampa', 'La rampa llega a un umbral del Schmitt', 'El Schmitt cambia de estado', 'La rampa cambia de sentido'], e: 'Dos umbrales y una rampa: una triangular de amplitud fija.', c: 'bb_integ', h: 'Empieza por la cuadrada y sigue la flecha del lazo.' },
      RES('Integrador: C en la realimentación; <b>pendiente = Vent / (R · C)</b>.', 'Cuadrada → triangular; una resistencia en paralelo evita la deriva.', 'Derivador: triangular → cuadrada.', 'Schmitt + integrador = generador de funciones.')
    ]),
    L('k13', 'Filtros activos', 'amp', ['bb_actfilt', 'bb_gbw'], [
      Q('Tienes un filtro RC paso bajo de 1 kHz y conectas a su salida una carga de la misma resistencia que la R del filtro. ¿Qué crees que pasa?', ['El filtro cambia: la carga queda en paralelo y mueve el corte', 'Nada, el filtro no se entera', 'Desaparece el condensador', 'Se duplica la tensión'], 'La carga forma un divisor con la R del filtro: la salida baja a la mitad y la frecuencia de corte sube. Un filtro pasivo se «cae» al cargarlo.', { predict: true, c: 'bb_actfilt', h: 'Piensa en el divisor que forma la carga con la R del filtro.' }),
      I('Un RC seguido de un <b>seguidor</b> ya es un <b>filtro activo</b>: el seguidor no le pide corriente al condensador y da una salida fuerte. La carga ya no mueve el corte, y puedes encadenar etapas sin que se afecten.', { svg: `<svg viewBox="0 0 300 130" class="viz"><path d="M15 47H50M90 47H144M110 47V70M110 82V100M216 59H285M144 71H135V95H216V59" ${st}/>${RH(70, 47)}<path d="M98 70h24M98 82h24" ${st}/>${GND(110, 100)}${OP(180, 59, 1.2)}<text x="70" y="34" text-anchor="middle" class="vizsm">R</text><text x="128" y="80" class="vizsm">C</text><text x="285" y="50" text-anchor="end" class="vizlab">salida fuerte</text></svg>` }),
      Q('¿Qué ventaja da el seguidor detrás de un RC?', ['Que la carga no cambia la frecuencia de corte', 'Más atenuación', 'Que no necesita alimentación', 'Que sube la frecuencia'], 'La salida del operacional tiene muy baja impedancia: la carga no se nota.', { c: 'bb_actfilt', h: 'Recuerda qué le pasaba al RC con la carga.' }),
      Q('Encadenas dos filtros RC paso bajo para que caigan más deprisa, pero el segundo carga al primero. ¿Qué pones entre los dos?', ['Un seguidor de tensión', 'Un condensador más', 'Una resistencia de 1 Ω', 'Un comparador'], 'El seguidor aísla las etapas: cada filtro trabaja como si estuviera solo.', { c: 'bb_actfilt', h: 'Necesitas algo que no pida corriente y la dé.' }),
      { t: 'explore', text: 'Un <b>Sallen-Key</b> paso bajo: dos R iguales, dos condensadores y un seguidor. C1 va a la salida y C2 a masa.', viz: 'sallenKey', params: { R: { label: 'R', val: 10000, list: [4700, 10000, 22000], fmt: 'R' }, C1: LS('C1', 10, [10, 22, 47, 100, 220], 'nF'), C2: LS('C2', 10, [10, 22, 47], 'nF') },
        tasks: [
          { q: 'f0', min: 950, max: 1100, text: 'Lleva el corte a 1 kHz (entre 950 y 1100 Hz)', done: 'f₀ = 1 / (2π · R · √(C1 · C2)).', hint: 'Con 10 kΩ, prueba C1 = 22 nF y C2 = 10 nF.' },
          { q: 'Q', min: 0.68, max: 0.76, text: 'Que la curva sea casi plana hasta el corte (Q ≈ 0,7)', done: 'Q ≈ 0,707 es la respuesta Butterworth: la más plana sin pico. Sale con C1 ≈ 2 · C2.', hint: 'C1 el doble que C2.' },
          { q: 'Q', min: 2, max: 10, text: 'Ahora provoca un pico (Q mayor que 2)', done: 'Con C1 mucho mayor que C2, Q sube y aparece una resonancia antes del corte.', hint: 'C1 muy grande y C2 pequeño.' }
        ] },
      I('<b>Sallen-Key</b> paso bajo con R iguales:\n· <b>f₀ = 1 / (2π · R · √(C1 · C2))</b>\n· <b>Q ≈ ½ · √(C1 / C2)</b>\nPor encima de f₀ cae 40 dB por década (segundo orden), el doble que un RC.'),
      { t: 'steps', text: 'Sallen-Key con R = 10 kΩ, C1 = 22 nF y C2 = 10 nF. ¿f₀ y Q?', steps: ['C1 · C2 = 22 nF × 10 nF; √ = <b>14,8 nF</b>', 'f₀ = 1 / (2π × 10 000 × 14,8 nF) = 1 / 0,000 932 ≈ <b>1073 Hz</b>', 'Q = ½ · √(22 / 10) = ½ × 1,48 = <b>0,74</b>', 'Q cerca de 0,707: respuesta casi plana (Butterworth)'], result: 'Corte en unos 1,07 kHz, casi sin pico.' },
      Nm('Sallen-Key paso bajo con R = 22 kΩ, C1 = 22 nF y C2 = 10 nF. ¿f₀ en Hz?', 488, 'Hz', '√(22 × 10) nF = 14,8 nF; 1 / (2π × 22 000 × 14,8 nF) ≈ 488 Hz.', { tol: 12, c: 'bb_actfilt', h: 'Raíz del producto de los condensadores y luego 1 / (2π · R · C).' }),
      G('sallenF0'),
      Q('Un filtro de segundo orden tiene Q ≈ 0,74. ¿Qué respuesta da?', ['Casi plana, cerca de Butterworth', 'Un pico enorme', 'Una caída muy suave', 'Ninguna atenuación'], 'Butterworth es Q = 0,707.', { c: 'bb_actfilt', h: 'Compara con 0,707.' }),
      Q('Montas un filtro activo de 200 kHz con un LM358. ¿Qué pasa?', ['No funcionará bien: el operacional no tiene ancho de banda suficiente', 'Perfecto', 'Mejor que a 1 kHz', 'Da igual el operacional'], 'El LM358 tiene 1 MHz de GBW: elige uno con un GBW muy por encima de f₀ × ganancia.', { c: 'bb_gbw', h: 'Recuerda el GBW del LM358.' }),
      { t: 'match', q: 'Une cada Q con la forma de la curva.', pairs: [['Q = 0,5', 'Caída suave, empieza antes del corte'], ['Q = 0,707', 'Plana hasta el corte'], ['Q = 3', 'Pico marcado cerca de f₀']], c: 'bb_actfilt', h: 'Recuerda lo que pasaba en la exploración al separar C1 y C2.' },
      RES('RC + seguidor: la carga ya no mueve el corte; se encadenan etapas.', 'Sallen-Key: <b>f₀ = 1 / (2π · R · √(C1 · C2))</b>, <b>Q ≈ ½ · √(C1 / C2)</b>.', 'Q ≈ 0,707: Butterworth.', 'El operacional necesita un GBW muy por encima de f₀.')
    ]),
    PRJ('p15', 'Proyecto: amplificador de audio con LM386', 'audioAmp'),
    PRJ('p12', 'Proyecto: termómetro con barra de LEDs', 'thermoBar')
  ],
  // Banco del examen de nivel: preguntas nuevas que cubren todas las lecciones del módulo
  exam: [
    // k6 · amplificadores operacionales
    Nm('Necesitas un no inversor de ganancia 5 con Rg = 10 kΩ. ¿Rf, en kΩ?', 40, 'kΩ', 'G = 1 + Rf / Rg = 5 → Rf / Rg = 4 → Rf = 40 kΩ (39 kΩ comercial).', { tol: 0.5, c: 'bb_opgain', h: 'Despeja Rf de G = 1 + Rf / Rg.', l: 'k6' }),
    Nm('Un inversor con Rin = 10 kΩ y Rf = 100 kΩ recibe 0,3 V. ¿Qué corriente pasa por Rf, en µA?', 30, 'µA', 'La − es masa virtual (0 V): por Rin entran 0,3 V / 10 kΩ = 30 µA. Como por la entrada no entra corriente, esos 30 µA siguen todos por Rf.', { tol: 0.5, c: 'bb_opgold', h: 'Usa las dos reglas de oro: ¿a qué tensión está la −? ¿Entra corriente en el chip?', l: 'k6' }),
    Q('Un sensor da una señal débil con 100 kΩ de resistencia interna. ¿Qué montaje la lee sin cargarlo?', ['Un seguidor (o un no inversor): su entrada + no pide corriente', 'Un inversor con Rin = 1 kΩ', 'Una resistencia de 1 kΩ a masa', 'Un comparador'], 'La señal entra por la +, que no consume. Un inversor con 1 kΩ de entrada formaría un divisor con los 100 kΩ del sensor y la señal casi desaparecería.', { c: 'bb_opgain', h: '¿Por qué entrada entra la señal en cada montaje y cuánta corriente pide?', l: 'k6' }),
    Q('Un no inversor de ganancia 11 con un LM358 alimentado a 12 V (alimentación única) recibe 1,5 V. ¿Qué sale?', ['Unos 10,5 V: se queda en el máximo que da el chip', '16,5 V', '12 V exactos', '1,5 V'], '1,5 × 11 = 16,5 V no cabe. La salida se satura un poco por debajo de la alimentación: con un LM358, alrededor de 1,5 V menos.', { c: 'bb_oplimits', h: 'Calcula la salida ideal y compárala con la alimentación.', l: 'k6' }),
    // k10 · el operacional real
    Nm('Un TL072 tiene unos 3 MHz de GBW. ¿Qué ganancia máxima puedes pedirle para que llegue hasta 20 kHz?', 150, '', 'BW ≈ GBW / G → G = GBW / BW = 3 000 000 / 20 000 = 150.', { tol: 2, c: 'bb_gbw', h: 'Despeja G de BW ≈ GBW / G.', l: 'k10' }),
    Nm('Quieres sacar una senoide de 10 V de pico a 50 kHz. ¿Qué slew rate mínimo necesita el operacional, en V/µs?', 3.14, 'V/µs', 'De fmax = SR / (2π · Vp): SR = 2π × 50 000 × 10 ≈ 3 140 000 V/s = 3,14 V/µs. Un LM358 (0,5 V/µs) no llega; un TL072 sí.', { tol: 0.05, c: 'bb_gbw', h: 'Despeja SR de fmax = SR / (2π · Vp) y pasa de V/s a V/µs.', l: 'k10' }),
    Nm('Un operacional con 3 mV de offset amplifica ×200 la señal de un sensor. Con el sensor dando 0 V, ¿cuánto marca la salida, en V?', 0.6, 'V', 'El offset se amplifica como si fuera señal: 0,003 × 200 = 0,6 V de error.', { tol: 0.02, c: 'bb_oplimits', h: 'El offset se comporta como una pequeña tensión en la entrada.', l: 'k10' }),
    Q('Alimentas un operacional a 3,3 V y su salida debe recorrer de 0 a 3,3 V. ¿Qué buscas en la hoja de datos?', ['Que sea rail-to-rail en la salida', 'Mucho offset', 'Poco GBW', 'Que sea un LM358'], 'Un operacional normal se queda a un voltio o más de los extremos; con 3,3 V eso es casi todo el margen. Uno rail-to-rail llega casi a 0 y a 3,3 V.', { c: 'bb_oplimits', h: '¿Hasta dónde llega la salida de un operacional normal respecto a la alimentación?', l: 'k10' }),
    // k11 · sumador y restador
    Nm('Mezclador inversor con Rf = 10 kΩ: V1 = 0,5 V por R1 = 10 kΩ y V2 = −0,2 V por R2 = 5 kΩ. ¿Vsal, en V (con signo)?', -0.1, 'V', 'Vsal = −Rf · (V1 / R1 + V2 / R2) = −10k · (0,5 / 10k − 0,2 / 5k) = −(0,5 − 0,4) = −0,1 V.', { tol: 0.01, c: 'bb_summer', h: 'Suma las corrientes con su signo (Vi / Ri) y multiplícalas por −Rf.', l: 'k11' }),
    Q('En una mesa de mezclas con un sumador inversor, ¿por qué subir un canal no cambia lo que llega de los demás?', ['La − es masa virtual: se queda en 0 V y cada corriente depende solo de su propia entrada', 'Porque todas las resistencias son iguales', 'Porque el operacional está saturado', 'Sí los cambia'], 'Como la − no se mueve de 0 V, la corriente de cada entrada es Vi / Ri, sin importar lo que hagan las demás. Por eso se mezclan sin molestarse.', { c: 'bb_summer', h: '¿A qué tensión está el punto donde se juntan las corrientes?', l: 'k11' }),
    Nm('Restador con R1 = R3 = 10 kΩ y R2 = R4 = 220 kΩ. V2 = 2,512 V y V1 = 2,500 V. ¿Vsal, en V?', 0.264, 'V', 'Ganancia R2 / R1 = 22. Vsal = 22 × (2,512 − 2,500) = 22 × 0,012 = 0,264 V. Los 2,5 V comunes no salen.', { tol: 0.005, c: 'bb_diffamp', h: 'Solo cuenta la diferencia V2 − V1, multiplicada por R2 / R1.', l: 'k11' }),
    Nm('Inversor de ganancia −2 con alimentación única de 5 V y la + a 2,5 V. Le entran 3 V. ¿Qué sale, en V?', 1.5, 'V', 'La entrada está 0,5 V por encima de la referencia. La salida se aleja el doble hacia el otro lado: 2,5 − 2 × 0,5 = 1,5 V.', { tol: 0.02, c: 'bb_opgain', h: 'Mide todo respecto a la referencia de 2,5 V, no respecto a masa.', l: 'k11' }),
    // k7 · comparadores
    Q('Alarma de calor: una NTC (abajo) y 10 kΩ (arriba, al +) forman un divisor que va a IN−; el umbral va a IN+. ¿Cuándo sube la salida?', ['Cuando hace calor: la NTC baja, IN− cae por debajo del umbral', 'Cuando hace frío', 'Nunca: IN− siempre es mayor', 'Siempre'], 'Al calentarse, la NTC baja su resistencia y la tensión del divisor (IN−) baja. Cuando cae por debajo del umbral, IN+ > IN− y la salida sube.', { c: 'bb_comp', h: 'Sigue la cadena: calor → resistencia de la NTC → tensión del divisor → comparación.', l: 'k7' }),
    Nm('Un LM393 con pull-up de 4,7 kΩ a 3,3 V tiene la salida baja (unos 0,2 V). ¿Corriente por la pull-up, en mA?', 0.66, 'mA', 'En la pull-up caen 3,3 − 0,2 = 3,1 V: I = 3,1 / 4700 ≈ 0,66 mA.', { tol: 0.02, c: 'bb_cmpoc', h: 'Con la salida baja, la pull-up tiene casi toda la alimentación encima.', l: 'k7' }),
    Q('Un LM339 alimentado a 12 V debe dar niveles de 0 y 3,3 V a otro chip. ¿Cómo lo haces?', ['Con la pull-up de su salida a 3,3 V, no a 12 V', 'Con la pull-up a 12 V', 'Sin pull-up', 'Con un diodo en serie con la salida'], 'Su salida de colector abierto solo tira a masa; el nivel alto lo pone la pull-up. Llevándola a 3,3 V, el alto es 3,3 V aunque el comparador vaya a 12 V.', { c: 'bb_cmpoc', h: 'En un colector abierto, ¿quién decide la tensión del nivel alto?', l: 'k7' }),
    // k14 · Schmitt
    Nm('Quieres 1 V de histéresis en un Schmitt a 5 V (salida rail-to-rail) con R2 = 100 kΩ. ¿R1, en kΩ?', 20, 'kΩ', 'H = Vcc · R1 / R2 → R1 = H · R2 / Vcc = 1 × 100 / 5 = 20 kΩ (22 kΩ comercial da 1,1 V).', { tol: 0.3, c: 'bb_schmitt_calc', h: 'Despeja R1 de H = Vcc · R1 / R2.', l: 'k14' }),
    Q('Un termostato con histéresis enciende a 19 °C y apaga a 21 °C. La casa está a 20 °C y la calefacción encendida. ¿Qué hará?', ['Seguir encendida hasta llegar a 21 °C', 'Apagarse ya', 'Encender y apagar sin parar', 'Apagarse al llegar a 19 °C'], 'Entre los dos umbrales, la salida mantiene su último estado. Estaba encendida, así que sigue así hasta cruzar el umbral de apagado.', { c: 'bb_hystwhy', h: 'Entre los dos umbrales, ¿cambia la salida o recuerda lo que hacía?', l: 'k14' }),
    Q('Tu Schmitt (5 V, Vref = 2,5 V) tiene 2 V de histéresis. Una señal que oscila entre 2 y 3 V nunca hace cambiar la salida. ¿Por qué?', ['Los umbrales quedan en unos 3,5 y 1,5 V: la señal no llega a ninguno', 'La salida está rota', 'Falta realimentación positiva', 'La histéresis es demasiado pequeña'], 'Con Vref = Vcc / 2, los umbrales quedan centrados a ±H / 2: 2,5 ± 1 V. La señal entre 2 y 3 V no cruza ninguno. Sobra histéresis: se pierde sensibilidad.', { c: 'bb_schmitt_calc', h: 'Con Vref en el centro, los umbrales quedan a ±H / 2.', l: 'k14' }),
    // k12 · integrador
    Nm('Integrador con R = 47 kΩ y C = 0,1 µF, con 0,5 V constantes a la entrada. ¿Cuánto tarda la salida en moverse 4 V, en ms?', 37.6, 'ms', 'Pendiente = Vent / (R · C) = 0,5 / (47 000 × 0,0000001) ≈ 106 V/s. Para 4 V: 4 / 106 ≈ 0,0376 s = 37,6 ms.', { tol: 0.5, c: 'bb_integ', h: 'Calcula la pendiente Vent / (R · C) y divide los 4 V entre ella.', l: 'k12' }),
    Q('Un integrador sin resistencia en paralelo con su condensador, con la entrada a 0 V, acaba con la salida pegada a un extremo. ¿Por qué?', ['Acumula sin parar el pequeño offset de la entrada', 'Porque la entrada está a 0 V', 'Porque el condensador se seca', 'Por el slew rate'], 'El offset actúa como una pequeña tensión constante en la entrada, y una constante se integra como una rampa sin fin. La resistencia en paralelo limita la ganancia en continua.', { c: 'bb_integ', h: '¿Qué hace un integrador con una tensión constante, por pequeña que sea?', l: 'k12' }),
    // k13 · filtros activos
    Nm('Sallen-Key paso bajo con R iguales y C2 = 10 nF. ¿Qué C1 da una respuesta Butterworth (Q ≈ 0,707), en nF?', 20, 'nF', 'Q ≈ ½ · √(C1 / C2) = 0,707 → √(C1 / C2) ≈ 1,414 → C1 / C2 = 2 → C1 = 20 nF (22 nF comercial da Q ≈ 0,74).', { tol: 0.5, c: 'bb_actfilt', h: 'Despeja C1 / C2 de Q ≈ ½ · √(C1 / C2).', l: 'k13' }),
    Q('Encadenas, con un seguidor entre ellos, dos Sallen-Key paso bajo iguales. ¿Cuánto caen juntos por encima del corte?', ['Unos 80 dB por década', 'Unos 40 dB por década', 'Unos 20 dB por década', 'Unos 160 dB por década'], 'Cada Sallen-Key es de segundo orden: 40 dB por década. Aislados por el seguidor, sus atenuaciones en dB se suman: 80 dB por década.', { c: 'bb_actfilt', h: '¿Cuánto cae cada etapa de segundo orden y cómo se combinan los dB en cadena?', l: 'k13' }),
    TU('Elige R, C1 y C2 para llevar el corte de este Sallen-Key a unos 500 Hz.', 'sallenKey', { R: { label: 'R', val: 10000, list: [4700, 10000, 22000], fmt: 'R' }, C1: { label: 'C1', val: 10, list: [10, 22, 47, 100, 220], unit: 'nF', dec: 0 }, C2: { label: 'C2', val: 10, list: [10, 22, 47], unit: 'nF', dec: 0 } }, { q: 'f0', min: 450, max: 550, text: 'Objetivo: corte entre 450 y 550 Hz', hint: 'f₀ = 1 / (2π · R · √(C1 · C2)).' }, 'Por ejemplo R = 22 kΩ con 22 nF y 10 nF (unos 488 Hz) o R = 10 kΩ con 47 nF y 22 nF (unos 495 Hz). Las dos tienen C1 ≈ 2 · C2: casi Butterworth.', { c: 'bb_actfilt', h: 'f₀ = 1 / (2π · R · √(C1 · C2)): con R grande hacen falta condensadores más pequeños.', l: 'k13' }),
  ] });
})();
