/* Voltio · curso base, módulo 14: Alimentación
   Orden: o1 (pilas) → sg5 → o5 (cargar litio) → k8 (reguladores: margen y LDO) → o2 (el calor del lineal)
   → o20 (LM317) → p8 → o3 (conmutados) → o4 (protección) → p14.
   Usa: b7, b9, c4, c6 (autonomía), d6, f10 (CV/CC), g9 (bobina), h20 (ciclo de trabajo), i2, i5, i9 (Schottky, TVS),
   j6–j11 (MOSFET, disipadores, fuente de corriente), k2 (hoja de datos) y k6 (operacional).
   Aún NO: microcontroladores (m11b) ni dimensionar un buck (o6, tras la puerta). */
(() => {
  const { num, fR, fV, st, ledBulb, hbar, resBody, heat } = Widgets.H;
  const RES = (...k) => I('<b>Resumen</b>\n· ' + k.join('\n· '));
  const LS = (label, val, list, unit = '', dec = 0) => ({ label, val, list, unit, dec });
  const SL = (label, val, min, max, step, unit = '', dec = 1) => ({ label, val, min, max, step, unit, dec });
  const GND = (x, y) => `<path d="M${x} ${y}v6M${x - 9} ${y + 6}h18M${x - 6} ${y + 10}h12M${x - 3} ${y + 14}h6" ${st} stroke-width="1.8"/>`;
  const RV = (x, y) => `<g transform="translate(${x} ${y}) rotate(90)">${resBody()}</g>`;
  const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
  const fW = p => p >= 1 ? num(p, 2) + ' W' : num(p * 1000, 0) + ' mW';

  /* ===================== VISUALIZACIONES ===================== */
  const CHEM = [
    { n: 'Alcalina', pts: [[100, 1.58], [90, 1.45], [70, 1.35], [50, 1.25], [30, 1.17], [15, 1.08], [5, 0.95], [0, 0.8]], lo: 0.7, hi: 1.7 },
    { n: 'NiMH', pts: [[100, 1.4], [90, 1.3], [70, 1.26], [50, 1.23], [30, 1.2], [15, 1.16], [5, 1.08], [0, 1.0]], lo: 0.9, hi: 1.5 },
    { n: 'Li-ion', pts: [[100, 4.2], [90, 4.05], [70, 3.9], [50, 3.78], [30, 3.7], [15, 3.62], [5, 3.45], [0, 3.0]], lo: 2.8, hi: 4.4 },
    { n: 'LiFePO4', pts: [[100, 3.55], [90, 3.36], [70, 3.31], [50, 3.29], [30, 3.26], [15, 3.21], [5, 3.0], [0, 2.5]], lo: 2.3, hi: 3.7 }
  ];
  const interp = (pts, x) => { for (let i = 0; i < pts.length - 1; i++) { const [a, va] = pts[i], [b, vb] = pts[i + 1]; if (x <= a && x >= b) return vb + (va - vb) * (x - b) / (a - b); } return pts[pts.length - 1][1]; };
  const REG = [{ n: '7805', vo: 5, dr: 2 }, { n: 'LDO 5 V', vo: 5, dr: 0.3 }, { n: 'LDO 3,3 V', vo: 3.3, dr: 0.3 }];
  Object.assign(Widgets.VIZ, {
    dischargeCurve: {
      calc: p => { const V = interp(CHEM[p.q].pts, p.carga); return { V, liLow: p.q === 2 && V < 3.5 ? 1 : 0, flat: p.q === 3 && p.carga >= 20 && p.carga <= 80 ? 1 : 0, alkHalf: p.q === 0 && p.carga <= 50 ? 1 : 0 }; },
      svg: (p, o) => {
        const c = CHEM[p.q], X = k => 40 + (100 - k) * 2.4, Y = v => 140 - (v - c.lo) / (c.hi - c.lo) * 120;
        const d = c.pts.map(([k, v], i) => (i ? 'L' : 'M') + X(k).toFixed(1) + ' ' + Y(v).toFixed(1)).join('');
        const ticks = [c.lo, (c.lo + c.hi) / 2, c.hi].map(v => `<text x="36" y="${(Y(v) + 4).toFixed(1)}" text-anchor="end" class="vizsm">${num(v, 1)}</text>`).join('');
        return `<svg viewBox="0 0 300 180" class="viz"><path d="M40 14V140H282" ${st} stroke-width="1.4"/>${ticks}
          <path d="${d}" fill="none" stroke="var(--led)" stroke-width="3"/><circle cx="${X(p.carga).toFixed(1)}" cy="${Y(o.V).toFixed(1)}" r="6" fill="var(--ice)"/>
          <text x="40" y="154" class="vizsm">llena (100 %)</text><text x="282" y="154" text-anchor="end" class="vizsm">vacía (0 %)</text>
          <text x="46" y="24" class="vizsm">tensión de una celda (V)</text>
          <text x="10" y="174" class="vizlab">${c.n} · carga ${p.carga} % · ${num(o.V, 2)} V</text></svg>`;
      }
    },
    cccv: {
      calc: p => { const Iset = p.cap * p.rate, tcc = 0.7 / p.rate, tau = 0.5, tend = tcc + tau * Math.log(10), t = p.t; let I, V, phase; if (t < tcc) { I = Iset; V = 3.5 + 0.7 * Math.pow(t / tcc, 0.6); phase = 0; } else if (t < tend) { I = Iset * Math.exp(-(t - tcc) / tau); V = 4.2; phase = 1; } else { I = 0; V = 4.2; phase = 2; } return { Iset, I, V, phase, tend }; },
      svg: (p, o) => {
        const X = t => 30 + t / 6 * 250, YV = v => 140 - (v - 3.3) / 1.0 * 110, YI = i => 140 - i / Math.max(o.Iset, 1) * 100;
        const tcc = 0.7 / p.rate; let dv = '', di = '';
        for (let k = 0; k <= 120; k++) { const t = k / 20; let I, V; if (t < tcc) { I = o.Iset; V = 3.5 + 0.7 * Math.pow(t / tcc, 0.6); } else if (t < o.tend) { I = o.Iset * Math.exp(-(t - tcc) / 0.5); V = 4.2; } else { I = 0; V = 4.2; } dv += (k ? 'L' : 'M') + X(t).toFixed(1) + ' ' + YV(V).toFixed(1); di += (k ? 'L' : 'M') + X(t).toFixed(1) + ' ' + YI(I).toFixed(1); }
        const ph = ['Fase CC: corriente constante', 'Fase CV: 4,2 V fijos, la corriente baja', 'Carga terminada'][o.phase];
        return `<svg viewBox="0 0 300 185" class="viz"><path d="M30 14V140H282" ${st} stroke-width="1.4"/>
          <path d="${di}" fill="none" stroke="var(--ice)" stroke-width="2.5"/><path d="${dv}" fill="none" stroke="var(--led)" stroke-width="3"/>
          <path d="M${X(p.t).toFixed(1)} 14V140" stroke="var(--muted)" stroke-dasharray="3 3"/>
          ${[0, 2, 4, 6].map(h => `<text x="${X(h)}" y="153" text-anchor="middle" class="vizsm">${h} h</text>`).join('')}
          <text x="36" y="24" class="vizsm" style="fill:var(--led)">tensión</text><text x="90" y="24" class="vizsm" style="fill:var(--ice)">corriente</text>
          <text x="10" y="168" class="vizlab">${ph}</text>
          <text x="10" y="182" class="vizsm">${num(o.I, 0)} mA · ${num(o.V, 2)} V · programada a ${num(o.Iset, 0)} mA</text></svg>`;
      }
    },
    linreg: {
      calc: p => { const r = REG[p.tipo], I = p.I / 1000, reg = p.Vin - r.dr >= r.vo - 1e-9 ? 1 : 0, Vout = reg ? r.vo : Math.max(0, p.Vin - r.dr), P = (p.Vin - Vout) * I, eff = Vout / p.Vin * 100; return { reg, Vout, P, eff, effReg: reg ? eff : 0, minVin: reg && p.tipo === 1 && p.Vin <= 5.5 ? 1 : 0, li33: reg && p.tipo === 2 && p.Vin <= 3.7 ? 1 : 0 }; },
      svg: (p, o) => {
        const r = REG[p.tipo], hot = clamp(o.P / 3, 0, 1);
        return `<svg viewBox="0 0 300 185" class="viz"><path d="M20 55H110M190 55H280" ${st}/><path d="M150 85V100" ${st}/>${GND(150, 100)}
          <rect x="110" y="30" width="80" height="55" rx="6" fill="${heat(hot)}" stroke="currentColor" stroke-width="2"/><text x="150" y="62" text-anchor="middle" class="vizlab" style="fill:#14213D">${r.n}</text>
          ${o.P > 1 ? `<path d="M135 22q-5 -6 0 -12M150 22q-5 -6 0 -12M165 22q-5 -6 0 -12" stroke="var(--err)" stroke-width="2" fill="none" class="a-bob"/>` : ''}
          <text x="20" y="45" class="vizlab">Vent ${fV(p.Vin)}</text><text x="280" y="45" text-anchor="end" class="vizlab" style="fill:${o.reg ? 'var(--ok)' : 'var(--err)'}">Vsal ${fV(o.Vout)}</text>
          <rect x="20" y="128" width="${(260 * o.eff / 100).toFixed(1)}" height="14" rx="3" fill="var(--ok)"/><rect x="${(20 + 260 * o.eff / 100).toFixed(1)}" y="128" width="${(260 * (1 - o.eff / 100)).toFixed(1)}" height="14" rx="3" fill="var(--err)" opacity=".8"/>
          <text x="20" y="123" class="vizsm">potencia útil (verde) y calor (rojo)</text>
          <text x="10" y="162" class="vizlab">${o.reg ? 'Regula' : 'Sin margen: no regula'} · calor ${fW(o.P)}</text>
          <text x="10" y="178" class="vizsm">Rendimiento ${num(o.eff, 0)} % · margen mínimo de este regulador: ${num(r.dr, 1)} V</text></svg>`;
      }
    },
    lm317: {
      calc: p => {
        if (p.mode === 1) { const I = 1.25 / p.R1, ok = p.Vin >= 3.3 + 1.25 + 2 ? 1 : 0; return { Vout: 0, I, Iled: I * 1000, P: Math.max(0, p.Vin - 3.3 - 1.25) * I, PR: 1.25 * I, reg: ok }; }
        const Vset = 1.25 * (1 + p.R2 / p.R1), reg = p.Vin - 2 >= Vset ? 1 : 0, Vout = reg ? Vset : Math.max(1.25, p.Vin - 2); return { Vout, I: p.IL, Iled: 0, P: Math.max(0, p.Vin - Vout) * p.IL, PR: 1.25 * 1.25 / p.R1, reg };
      },
      svg: (p, o) => {
        const m1 = p.mode === 1;
        return `<svg viewBox="0 0 300 215" class="viz"><path d="M20 55H90M150 55H200V65M200 105V120M120 80V120H200" ${st}/>${m1 ? '' : `<path d="M200 55H280" ${st}/>`}
          <rect x="90" y="30" width="60" height="50" rx="5" fill="var(--ice-soft)" stroke="currentColor" stroke-width="2"/><text x="120" y="59" text-anchor="middle" class="vizlab">LM317</text>
          <text x="94" y="74" class="vizsm">IN</text><text x="146" y="74" text-anchor="end" class="vizsm">OUT</text><text x="124" y="96" class="vizsm">ADJ</text>
          ${RV(200, 85)}<text x="212" y="82" class="vizsm">${m1 ? 'R' : 'R1'} ${fR(p.R1)}</text><text x="212" y="96" class="vizsm" style="fill:var(--ok)">1,25 V</text>
          ${m1 ? `<path d="M200 120H235V128M235 160V170" ${st}/><g transform="translate(235 144) scale(.7)">${ledBulb(clamp(o.I / 0.35, 0.15, 1))}</g>${GND(235, 170)}<text x="248" y="148" class="vizsm">LED</text>`
            : `<path d="M200 120V125M200 165V168" ${st}/>${RV(200, 145)}<text x="212" y="149" class="vizsm">R2 ${fR(p.R2)}</text>${GND(200, 168)}`}
          <circle cx="200" cy="120" r="3.5" fill="currentColor"/>
          <text x="20" y="45" class="vizlab">Vent ${fV(p.Vin)}</text>${m1 ? '' : `<text x="280" y="45" text-anchor="end" class="vizlab" style="fill:${o.reg ? 'var(--ok)' : 'var(--err)'}">Vsal ${fV(o.Vout)}</text>`}
          <text x="10" y="198" class="vizlab">${m1 ? `Corriente 1,25 / R = ${num(o.Iled, 0)} mA` : `Vsal = 1,25 · (1 + R2 / R1) = ${fV(1.25 * (1 + p.R2 / p.R1))}`}${o.reg ? '' : ' · ¡falta margen!'}</text>
          <text x="10" y="212" class="vizsm">El LM317 disipa ${fW(o.P)}${m1 ? ' · la R, ' + fW(o.PR) : ' con ' + num(p.IL, 1) + ' A de carga'}</text></svg>`;
      }
    },
    buckSw: {
      anim: true,
      calc: p => { const Vout = p.Vin * p.D / 100; return { Vout, v5: Vout >= 4.9 && Vout <= 5.1 ? 1 : 0, v33: Math.abs(p.Vin - 5) < 0.01 && Vout >= 3.25 && Vout <= 3.35 ? 1 : 0 }; },
      svg: (p, o, t) => {
        const T = 1.6, on = ((t % T) / T) < p.D / 100, coil = 'M120 40q8 -14 16 0q8 -14 16 0q8 -14 16 0q8 -14 16 0';
        let w = 'M20 165'; for (let k = 0; k < 4; k++) { const x = 20 + k * 65, x2 = x + 65 * p.D / 100; w += `V${165 - 40 * p.Vin / 24}H${x2.toFixed(1)}V165H${x + 65}`; }
        const ya = 165 - 40 * o.Vout / 24, cur = 20 + ((t % T) / T) * 65;
        return `<svg viewBox="0 0 300 195" class="viz"><path d="M20 40H50M90 40H120M184 40H260V60M260 80V95M215 40V62M215 70V95M110 95H260" ${st}/><path d="${coil}" ${st}/>
          <path d="M50 40L88 ${on ? 40 : 24}" ${st} stroke="${on ? 'var(--ok)' : 'currentColor'}"/><circle cx="50" cy="40" r="3" fill="currentColor"/><circle cx="90" cy="40" r="3" fill="currentColor"/>
          <path d="M110 40V95M102 72h16M102 72l8 -12l8 12z" ${st}/><path d="M206 62h18M206 70h18" ${st}/><rect x="252" y="60" width="16" height="20" rx="5" fill="#E7D3A8" stroke="#C9B183"/>
          <path d="${on ? 'M20 40H120M184 40H260' : 'M110 95V40H120M184 40H260'}" class="flow" style="animation-duration:.6s"/>
          <text x="20" y="30" class="vizsm">${fV(p.Vin)}</text><text x="20" y="114" class="vizsm">${on ? 'interruptor cerrado: la entrada empuja' : 'interruptor abierto: el diodo conduce'}</text><text x="152" y="62" text-anchor="middle" class="vizsm">bobina</text><text x="272" y="30" text-anchor="end" class="vizlab">${fV(o.Vout)}</text>
          <path d="${w}" fill="none" stroke="var(--led)" stroke-width="2"/><path d="M20 ${ya.toFixed(1)}H280" stroke="var(--ok)" stroke-dasharray="5 4"/><path d="M${cur.toFixed(1)} 118V168" stroke="var(--muted)"/>
          <text x="10" y="190" class="vizlab">Vsal = D × Vent = ${num(p.D / 100, 2)} × ${num(p.Vin, 1)} = ${fV(o.Vout)} (línea verde)</text></svg>`;
      }
    },
    buckBoost: {
      calc: p => { const lo = Math.min(p.Va, p.Vb), hi = Math.max(p.Va, p.Vb), type = lo > p.Vo ? 0 : hi < p.Vo ? 1 : 2; return { type, lo, hi }; },
      svg: (p, o) => {
        const X = v => 20 + v / 15 * 260, names = ['Buck: siempre hay que bajar', 'Boost: siempre hay que subir', 'Buck-boost: a veces sube y a veces baja'];
        return `<svg viewBox="0 0 300 150" class="viz"><path d="M20 80H280" stroke="var(--line)" stroke-width="12" stroke-linecap="round"/>
          <rect x="${X(o.lo).toFixed(1)}" y="72" width="${Math.max(3, X(o.hi) - X(o.lo)).toFixed(1)}" height="16" rx="4" fill="var(--ice)"/>
          <path d="M${X(p.Vo).toFixed(1)} 58V102" stroke="var(--led)" stroke-width="4"/>
          ${[0, 5, 10, 15].map(v => `<text x="${X(v)}" y="118" text-anchor="middle" class="vizsm">${v} V</text>`).join('')}
          <text x="20" y="40" class="vizsm" style="fill:var(--ice)">azul: lo que da la fuente</text><text x="280" y="40" text-anchor="end" class="vizsm" style="fill:var(--led)">naranja: lo que necesitas</text>
          <text x="10" y="142" class="vizlab">${names[o.type]}</text></svg>`;
      }
    },
    polProt: {
      calc: p => { const drop = [0.7 + 0.1 * p.I, 0.3 + 0.1 * p.I, 0.02 * p.I][p.tipo], P = drop * p.I; return { drop, P, lowDrop: p.I === 2 && drop < 0.05 ? 1 : 0 }; },
      svg: (p, o) => {
        const n = ['Diodo normal', 'Diodo Schottky', 'MOSFET P'][p.tipo];
        return `<svg viewBox="0 0 300 160" class="viz"><rect x="20" y="40" width="260" height="18" rx="4" fill="var(--ok)"/><rect x="${(280 - 260 * o.drop / 12).toFixed(1)}" y="40" width="${(260 * o.drop / 12).toFixed(1)}" height="18" rx="2" fill="var(--err)"/>
          <text x="20" y="32" class="vizsm">12 V de la fuente: lo que se come la protección, en rojo</text>
          <rect x="105" y="78" width="90" height="34" rx="6" fill="${heat(clamp(o.P / 2, 0, 1))}" stroke="currentColor" stroke-width="1.6"/><text x="150" y="99" text-anchor="middle" class="vizlab" style="fill:#14213D;font-size:11px">${n}</text>
          <text x="10" y="135" class="vizlab">Caída ${o.drop >= 0.1 ? num(o.drop, 2) + ' V' : num(o.drop * 1000, 0) + ' mV'} · disipa ${fW(o.P)}</text>
          <text x="10" y="152" class="vizsm">a ${num(p.I, 1)} A · al circuito le llegan ${fV(12 - o.drop)}</text></svg>`;
      }
    }
  });

  /* ===================== GENERADORES (con pista) ===================== */
  const { pick, fmt, N } = Gen.helpers;
  Gen.add('battSeriesPar', () => {
    const [n, v, cap] = pick([['pilas AA alcalinas', 1.5, 2500], ['pilas AA de NiMH', 1.2, 2000], ['celdas de Li-ion', 3.7, 3000], ['celdas LiFePO4', 3.2, 1500]]), s = pick([2, 3, 4]), pp = pick([1, 2, 3]);
    const desc = pp === 1 ? `${s} ${n} en serie` : `${s * pp} ${n} en ${pp} ramas de ${s} en serie`;
    if (Math.random() < 0.5) return { ...N(`${desc} (${fmt(v)} V y ${cap} mAh cada una). ¿Tensión nominal del conjunto, en V?`, s * v, 'V', `En serie se suman las tensiones: ${s} × ${fmt(v)} = ${fmt(s * v, 2)} V. Las ramas en paralelo no suben la tensión.`, 0.01), h: 'Para la tensión solo cuentan las celdas en serie de una rama.' };
    return { ...N(`${desc} (${fmt(v)} V y ${cap} mAh cada una). ¿Capacidad del conjunto, en mAh?`, cap * pp, 'mAh', `En serie la capacidad no cambia; cada rama en paralelo suma la suya: ${pp} × ${cap} = ${cap * pp} mAh.`, 1), h: 'La capacidad solo se suma con las ramas en paralelo.' };
  }, 'bb_cells');
  Gen.add('liChargeI', () => ({ ...Gen.make('cRate'), h: '1C es la capacidad en mA durante una hora. Multiplica por la tasa C; para el tiempo, divide capacidad entre corriente.' }), 'bb_crate');
  Gen.add('tp4056R', () => { if (Math.random() < 0.5) { const I = pick([200, 300, 400, 500, 600, 800, 1000]); return { ...N(`¿Qué resistencia RPROG pones en un TP4056 para cargar a ${I} mA? (en Ω)`, 1200 / (I / 1000), 'Ω', `RPROG = 1200 / I = 1200 / ${fmt(I / 1000)} = ${fmt(1200 / (I / 1000), 0)} Ω.`, 12000 / I * 0.5), h: 'RPROG = 1200 / I, con I en amperios.' }; } const R = pick([1200, 2000, 2400, 3000, 4000, 6000]); return { ...N(`Un TP4056 lleva RPROG = ${fmt(R / 1000, 1)} kΩ. ¿Corriente de carga en mA?`, 1200 / R * 1000, 'mA', `I = 1200 / RPROG = 1200 / ${R} = ${fmt(1200 / R, 3)} A = ${fmt(1200 / R * 1000, 0)} mA.`, 2), h: 'I = 1200 / RPROG (en Ω) da amperios; pásalo a mA.' }; }, 'bb_crate');
  Gen.add('linRegHeat', () => ({ ...Gen.make('regLoss'), h: 'Lo que sobra (Vent − Vsal) por la corriente, en amperios.' }), 'bb_linreg');
  Gen.add('linRegEff', () => ({ ...Gen.make('efficiency'), h: 'Entra y sale la misma corriente: el rendimiento es Vsal / Vent.' }), 'bb_linreg');
  Gen.add('lm317', () => { const R1 = pick([120, 240, 330]); if (Math.random() < 0.5) { const R2 = pick([220, 470, 680, 1000, 1500, 2200, 3300]), V = 1.25 * (1 + R2 / R1); return { ...N(`LM317 con R1 = ${R1} Ω (entre OUT y ADJ) y R2 = ${fR(R2)} (de ADJ a masa). ¿Tensión de salida en V?`, V, 'V', `Vsal = 1,25 · (1 + R2 / R1) = 1,25 × (1 + ${fmt(R2 / R1, 3)}) = ${fmt(V, 2)} V.`, 0.05), h: 'Vsal = 1,25 · (1 + R2 / R1).' }; } const V = pick([3.3, 5, 9, 12, 15]), R2 = R1 * (V / 1.25 - 1); return { ...N(`LM317 con R1 = ${R1} Ω. ¿Qué R2 necesitas para ${fmt(V)} V? (en Ω)`, R2, 'Ω', `R2 = R1 · (Vsal / 1,25 − 1) = ${R1} × (${fmt(V / 1.25, 3)} − 1) = ${fmt(R2, 0)} Ω; luego eliges el valor comercial más cercano o un potenciómetro.`, Math.max(2, R2 * 0.02)), h: 'Despeja: R2 = R1 · (Vsal / 1,25 − 1).' }; }, 'bb_lm317');
  Gen.add('lm317I', () => { const I = pick([0.02, 0.05, 0.1, 0.35, 0.7, 1]); if (Math.random() < 0.6) return { ...N(`LM317 como fuente de corriente: ¿qué resistencia entre OUT y ADJ da ${I >= 1 ? fmt(I) + ' A' : fmt(I * 1000, 0) + ' mA'}? (en Ω)`, 1.25 / I, 'Ω', `R = 1,25 V / I = 1,25 / ${fmt(I, 3)} = ${fmt(1.25 / I, 2)} Ω.`, Math.max(0.05, 1.25 / I * 0.01)), h: 'R = 1,25 V / I, con la corriente en amperios.' }; return { ...N(`LM317 como fuente de ${I >= 1 ? fmt(I) + ' A' : fmt(I * 1000, 0) + ' mA'}. ¿Cuánta potencia disipa la resistencia que fija la corriente, en W?`, 1.25 * I, 'W', `Siempre tiene 1,25 V: P = 1,25 × ${fmt(I, 3)} = ${fmt(1.25 * I, 3)} W.`, Math.max(0.005, 1.25 * I * 0.02)), h: 'La resistencia siempre tiene 1,25 V: P = V · I.' }; }, 'bb_lm317i');
  Gen.add('smpsPin', () => { const eta = pick([0.8, 0.85, 0.9, 0.95]), Vo = pick([3.3, 5, 12]), Io = pick([0.5, 1, 2]), Pin = Vo * Io / eta; if (Math.random() < 0.5) return { ...N(`Convertidor con un rendimiento del ${fmt(eta * 100, 0)} % que entrega ${fmt(Vo)} V y ${fmt(Io)} A. ¿Potencia de entrada en W?`, Pin, 'W', `Psal = ${fmt(Vo * Io, 2)} W; Pent = Psal / η = ${fmt(Vo * Io, 2)} / ${fmt(eta, 2)} = ${fmt(Pin, 2)} W.`, Math.max(0.05, Pin * 0.02)), h: 'Calcula la potencia de salida (V · I) y divídela entre el rendimiento.' }; const Vin = pick([9, 12, 24].filter(v => v > Vo)), Iin = Pin / Vin; return { ...N(`Buck del ${fmt(eta * 100, 0)} % de ${Vin} V a ${fmt(Vo)} V con ${fmt(Io)} A de salida. ¿Corriente de entrada en A?`, Iin, 'A', `Pent = ${fmt(Vo * Io, 2)} / ${fmt(eta, 2)} = ${fmt(Pin, 2)} W; Ient = Pent / Vent = ${fmt(Iin, 3)} A: menos que la de salida.`, Math.max(0.01, Iin * 0.03)), h: 'Primero la potencia de entrada (Psal / η) y luego divídela entre la tensión de entrada.' }; }, 'bb_smps_how');

  /* ===================== CONCEPTOS NUEVOS ===================== */
  const pLin = (tipo = 0, Vin = 9, I = 100) => ({ tipo: LS('Regulador (0 7805, 1 LDO 5 V, 2 LDO 3,3 V)', tipo, [0, 1, 2]), Vin: SL('Entrada', Vin, 3, 15, 0.1, 'V', 1), I: LS('Corriente', I, [50, 100, 200, 500, 1000], 'mA') });
  const pLM = (mode = 0, R1 = 240, R2 = 220, Vin = 15) => ({ mode: LS('Uso (0 tensión, 1 corriente para un LED)', mode, [0, 1]), R1: { label: 'R1 (OUT–ADJ)', val: R1, list: [3.6, 10, 62, 120, 240, 330], fmt: 'R' }, R2: { label: 'R2 (ADJ–masa)', val: R2, list: [220, 470, 720, 1000, 1500, 2200, 3300, 4700], fmt: 'R' }, Vin: SL('Entrada', Vin, 5, 25, 0.5, 'V', 1), IL: LS('Corriente de carga', 0.1, [0.1, 0.5, 1], 'A', 1) });
  Object.assign(CONCEPTS, {
    bb_discharge: { name: 'Curva de descarga y capacidad real', alts: [
      { title: 'La tensión baja al gastarse', text: 'Ninguna pila da su tensión nominal todo el rato. Una alcalina empieza en 1,5–1,6 V y va bajando sin parar; una Li-ion va de 4,2 V llena a unos 3,6 V casi toda la descarga y cae deprisa al final; una LiFePO4 se queda casi plana en 3,2–3,3 V. Mueve la carga y mira cada química.', tune: { viz: 'dischargeCurve', params: { q: LS('Química (0 alcalina, 1 NiMH, 2 Li-ion, 3 LiFePO4)', 0, [0, 1, 2, 3]), carga: SL('Carga que queda', 50, 0, 100, 5, '%', 0) } }, q: mcq('Una AA alcalina a media carga, ¿qué tensión tiene más o menos?', ['Unos 1,25 V', '1,5 V exactos', '0,75 V', '3 V'], 'Va bajando poco a poco desde 1,5–1,6 V.') },
      { title: 'Más corriente, menos capacidad', text: 'Los mAh del envoltorio se miden con consumos pequeños. Si le pides mucha corriente, la pila se calienta y su tensión cae antes: entrega menos mAh. En las alcalinas se nota muchísimo (con consumos de amperios, puede quedarse en menos de la mitad); en las de litio, mucho menos.', q: mcq('Una alcalina de 2500 mAh alimenta un motor que pide 1 A. ¿Cuánto durará?', ['Bastante menos de 2,5 h', 'Exactamente 2,5 h', 'Más de 2,5 h', '25 h'], 'Con consumos grandes la capacidad real baja.') }
    ] },
    bb_regmargin: { name: 'Regulador lineal: margen y LDO', alts: [
      { title: 'Necesita sitio para trabajar', text: 'Un regulador lineal solo puede quitar tensión, y necesita un <b>margen mínimo</b> (dropout) entre entrada y salida: un 7805 pide unos 2 V (entrada de 7 V o más); un <b>LDO</b>, solo 0,1–0,5 V. Por debajo de ese margen deja de regular y la salida cae con la entrada. Pruébalo bajando la entrada.', tune: { viz: 'linreg', params: pLin(0, 8, 100) }, q: mcq('Necesitas 5 V desde 6 V con un regulador lineal. ¿Cuál?', ['Un LDO', 'Un 7805', 'Un zener de 6 V', 'Ninguno puede'], 'El 7805 pediría 7 V.') },
      { title: 'El caso de la Li-ion', text: 'Una celda de litio da de 4,2 V (llena) a unos 3,0 V. Para sacar 3,3 V hace falta un LDO de 3,3 V con poco dropout: regula hasta que la celda baja a unos 3,5 V y, por debajo, deja pasar lo que hay. Un 7805 no sirve: ni siquiera puede subir a 5 V.', q: mcq('LDO de 3,3 V con 0,2 V de dropout. ¿Hasta qué tensión de la celda regula?', ['Hasta unos 3,5 V', 'Hasta 3,3 V', 'Hasta 5,3 V', 'Siempre'], '3,3 + 0,2 = 3,5 V.') }
    ] },
    bb_regpins: { name: 'Montar un regulador: patas y condensadores', alts: [
      { title: 'Entrada, masa, salida', text: 'El 7805 en TO-220, mirado de frente (con las letras hacia ti y las patas abajo): <b>1 entrada, 2 masa, 3 salida</b>; la aleta metálica va a masa. Lleva un condensador en la entrada (unos 0,33 µF) y otro en la salida (unos 0,1 µF), pegados a las patas. Otros reguladores tienen otro orden: el LM317 es ADJ, OUT, IN. Mira siempre la hoja de datos.', svg: '<svg viewBox="0 0 300 160" class="viz"><rect x="105" y="10" width="90" height="30" rx="4" fill="#B9C4D3" stroke="currentColor"/><circle cx="150" cy="25" r="7" fill="var(--bg)" stroke="currentColor"/><rect x="100" y="40" width="100" height="60" rx="4" fill="#1c1c1c"/><text x="150" y="75" text-anchor="middle" fill="#ddd" font-size="14">7805</text><path d="M125 100v40M150 100v40M175 100v40" stroke="#9AA3B2" stroke-width="5" stroke-linecap="round"/><text x="125" y="153" text-anchor="middle" class="vizlab">1</text><text x="150" y="153" text-anchor="middle" class="vizlab">2</text><text x="175" y="153" text-anchor="middle" class="vizlab">3</text><text x="210" y="70" class="vizsm">1 entrada</text><text x="210" y="84" class="vizsm">2 masa</text><text x="210" y="98" class="vizsm">3 salida</text></svg>', q: mcq('Un 7805 de frente, ¿qué pata es la salida?', ['La 3, la de la derecha', 'La 1, la de la izquierda', 'La 2, la del centro', 'La aleta'], 'Entrada, masa, salida.') },
      { title: 'Los condensadores no son opcionales', text: 'Un regulador es un pequeño amplificador realimentado: sin sus condensadores puede <b>oscilar</b>. Muchos LDO exigen además un condensador de salida de cierto valor y con una ESR dentro de un rango (la hoja de datos lo dice). Ponlos lo más cerca posible de las patas.', q: mcq('Montas un LDO sin el condensador de salida que pide su hoja de datos. ¿Qué puede pasar?', ['Que oscile y la salida no sea estable', 'Nada', 'Que dé el doble de tensión', 'Que regule mejor'], 'La estabilidad depende de ese condensador.') }
    ] },
    bb_regheat: { name: '¿Necesita disipador el regulador?', alts: [
      { title: 'Calor y temperatura', text: 'Calcula lo que disipa, P = (Vent − Vsal) · I, y luego su temperatura como en j10: <b>Tj = Ta + P · Rθ</b>. Un TO-220 sin disipador tiene unos 65 °C/W: con 1 W sube unos 65 °C sobre el ambiente. Por encima de 1 W aproximadamente, disipador. Sube la entrada y la corriente y mira cómo se calienta.', tune: { viz: 'linreg', params: pLin(0, 12, 500) }, q: mcq('Un TO-220 sin disipador (65 °C/W) disipa 2 W a 25 °C. ¿Temperatura de la unión?', ['155 °C: demasiado', '65 °C', '27 °C', '130 °C'], '25 + 2 × 65 = 155 °C.') },
      { title: 'Mejor no generar calor', text: 'Antes de poner un disipador enorme, pregúntate si puedes bajar la tensión de entrada (una fuente de 7–8 V en vez de 12 V) o usar un regulador conmutado. El calor de un lineal es la tensión que sobra por la corriente: si sobra poca tensión, hay poco calor.', q: mcq('Tu 7805 se calienta mucho alimentado a 12 V. ¿Qué es lo más eficaz?', ['Alimentarlo con menos tensión o usar un conmutado', 'Poner un condensador mayor', 'Cambiarlo por otro 7805', 'Pedirle más corriente'], 'Menos tensión sobrante, menos calor.') }
    ] },
    bb_lm317: { name: 'LM317: ajustar la tensión', alts: [
      { title: '1,25 V que mandan', text: 'El LM317 mantiene siempre <b>1,25 V entre OUT y ADJ</b>. Esos 1,25 V sobre R1 fijan una corriente (con 240 Ω, 5,2 mA) que también pasa por R2. Así, Vsal = 1,25 V + 5,2 mA · R2, que es lo mismo que <b>Vsal = 1,25 · (1 + R2 / R1)</b>. Cambia R2 y mira la salida.', tune: { viz: 'lm317', params: pLM(0, 240, 720, 15) }, q: mcq('LM317 con R1 = 240 Ω y R2 = 720 Ω. ¿Salida?', ['5 V', '3 V', '1,25 V', '3,75 V'], '1,25 × (1 + 3) = 5 V.') },
      { title: 'Despejar R2', text: 'Si te dan la tensión que quieres, despeja: <b>R2 = R1 · (Vsal / 1,25 − 1)</b>. Para 12 V con R1 = 240 Ω: 240 × (9,6 − 1) = 2064 Ω; pondrás 2 kΩ más algo, o un potenciómetro. Y recuerda el margen: la entrada debe estar unos 2 V por encima de la salida.', q: mcq('LM317 con R1 = 120 Ω. ¿R2 para 5 V?', ['360 Ω', '480 Ω', '120 Ω', '600 Ω'], '120 × (4 − 1) = 360 Ω.') }
    ] },
    bb_lm317i: { name: 'LM317 como fuente de corriente', alts: [
      { title: 'Una sola resistencia', text: 'Pon la resistencia entre OUT y ADJ y la carga detrás de ADJ. El LM317 mantiene 1,25 V en esa resistencia, así que la corriente es <b>I = 1,25 V / R</b>, sea cual sea la carga (mientras haya margen). Ideal para LEDs de potencia.', tune: { viz: 'lm317', params: pLM(1, 3.6, 220, 12) }, q: mcq('¿Qué resistencia da 350 mA con un LM317 como fuente de corriente?', ['Unos 3,6 Ω', '350 Ω', 'Unos 0,36 Ω', '1,25 Ω'], '1,25 / 0,35 ≈ 3,57 Ω.') },
      { title: 'No te olvides de su potencia', text: 'Esa resistencia siempre tiene 1,25 V, así que disipa <b>P = 1,25 · I</b>: a 350 mA, 0,44 W (pon una de 1 W). Y el LM317 disipa lo que sobra: (Vent − Vcarga − 1,25) · I.', q: mcq('LM317 como fuente de 0,7 A. ¿Potencia en la resistencia?', ['Unos 0,88 W', '0,7 W', '1,25 W', '8,75 W'], '1,25 × 0,7 ≈ 0,88 W.') }
    ] },
    bb_smps_how: { name: 'Cómo funciona un conmutado', alts: [
      { title: 'Trocear y promediar', text: 'Un buck conecta y desconecta la entrada muy deprisa (decenas o cientos de miles de veces por segundo). La bobina y el condensador se quedan con la <b>media</b>: Vsal = D × Vent, con D el ciclo de trabajo. Como el interruptor está o cerrado (sin tensión) o abierto (sin corriente), casi no se calienta.', tune: { viz: 'buckSw', params: { Vin: SL('Entrada', 12, 5, 24, 0.5, 'V', 1), D: SL('Ciclo de trabajo D', 50, 5, 95, 1, '%', 0) } }, q: mcq('Un buck ideal con 12 V de entrada y D = 25 %. ¿Salida?', ['3 V', '9 V', '12 V', '0,25 V'], '0,25 × 12 = 3 V.') },
      { title: 'La potencia se conserva (casi)', text: 'En un conmutado, Pent ≈ Psal / η. Si baja la tensión, la corriente de entrada es <b>menor</b> que la de salida: un buck de 12 a 5 V que da 2 A (10 W) al 90 % toma 11,1 W, es decir, 0,93 A de la entrada. Un lineal tomaría los mismos 2 A de la entrada.', q: mcq('Buck al 100 % de 10 V a 5 V con 1 A de salida. ¿Corriente de entrada?', ['0,5 A', '1 A', '2 A', '5 A'], '5 W / 10 V = 0,5 A.') }
    ] },
    bb_inprot: { name: 'Proteger la entrada de alimentación', alts: [
      { title: 'Cada pieza, un peligro', text: '<b>Fusible o PTC</b>: corta si pasa demasiada corriente (un cortocircuito). <b>Diodo o MOSFET P en serie</b>: impide que la polaridad invertida llegue al circuito. <b>TVS</b>: se come los picos de tensión. <b>Condensador grande</b>: aguanta caídas cortas. Se ponen en ese orden, desde el conector.', svg: '<svg viewBox="0 0 300 120" class="viz"><path d="M10 50H290" stroke="var(--led)" stroke-width="3" class="a-flow"/>' + ['Fusible', 'MOSFET P', 'TVS', 'Cond.'].map((t, i) => `<rect x="${18 + i * 70}" y="35" width="58" height="30" rx="6" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="${47 + i * 70}" y="54" text-anchor="middle" class="vizsm" style="fill:currentColor">${t}</text>`).join('') + '<text x="10" y="95" class="vizsm">conector →</text><text x="290" y="95" text-anchor="end" class="vizsm">→ regulador</text></svg>', q: mcq('¿Qué pieza protege contra un cortocircuito en tu circuito?', ['El fusible o PTC', 'El TVS', 'El condensador de entrada', 'El MOSFET P'], 'Corta la corriente excesiva.') },
      { title: 'Fusible o PTC', text: 'El <b>fusible</b> se funde y hay que cambiarlo; el <b>PTC</b> (fusible rearmable) sube mucho su resistencia al calentarse y se recupera al enfriarse. El PTC es cómodo (USB, juguetes), pero es más lento y deja pasar algo de corriente cuando ha saltado.', q: mcq('Ventaja del PTC frente al fusible:', ['Se rearma solo al enfriarse', 'Es más rápido', 'No se calienta nunca', 'Sube la tensión'], 'Es un fusible que se recupera.') }
    ] },
    bb_revpol: { name: 'Protección de polaridad: cuánto cuesta', alts: [
      { title: 'La caída se paga en calor', text: 'Un diodo en serie protege, pero se come su caída: unos 0,7–0,9 V (un Schottky, 0,3–0,5 V). Esa caída por la corriente es calor: a 2 A, un diodo normal disipa más de 1,5 W. Un <b>MOSFET P</b> bien colocado solo cae I · Rds(on): milivoltios. Prueba las tres opciones.', tune: { viz: 'polProt', params: { tipo: LS('Protección (0 diodo, 1 Schottky, 2 MOSFET P)', 0, [0, 1, 2]), I: LS('Corriente', 2, [0.1, 0.5, 1, 2], 'A', 1) } }, q: mcq('Un Schottky de protección cae 0,4 V con 1 A. ¿Potencia?', ['0,4 W', '4 W', '0,04 W', '1 W'], '0,4 V × 1 A.') },
      { title: 'El MOSFET P al revés de lo que parece', text: 'En la protección con MOSFET P, la fuente (S) va hacia el circuito y el drenador (D) hacia el conector; la puerta, a masa (con una resistencia y un zener si la tensión es alta). Al conectar bien, primero conduce su diodo de cuerpo, la fuente sube, Vgs se hace negativa y el canal se abre. Al revés, el diodo no conduce y la puerta no lo enciende.', q: mcq('Con 12 V y 2 A, un MOSFET P de 20 mΩ como protección. ¿Cuánto disipa?', ['0,08 W', '24 W', '0,04 W', '1,4 W'], 'P = I² · R = 4 × 0,02.') }
    ] }
  });

  /* ===================== LECCIONES ===================== */
  /* ===================== EXAMEN DE NIVEL (banco propio) ===================== */
  const exam = [
    // o1 · pilas y baterías
    Nm('Un portapilas lleva 3 pilas NiMH AA en serie, de 2000 mAh cada una. ¿Cuánta energía guarda el conjunto, en Wh?', 7.2, 'Wh', 'En serie se suman las tensiones (3 × 1,2 = 3,6 V) y la capacidad es la de una (2 Ah). Energía = 3,6 V × 2 Ah = 7,2 Wh.', { tol: 0.1, c: 'bb_cells', l: 'o1', h: 'Primero la tensión del conjunto y la capacidad; luego energía = V × Ah.' }),
    Q('Quieres hacer un indicador de carga que solo mida la tensión de la batería. ¿Con qué química te costará más saber cuánto le queda?', ['LiFePO4: su tensión casi no cambia entre el 80 % y el 20 %', 'Alcalina: su tensión no cambia nunca', 'Li-ion: siempre marca 3,7 V', 'NiMH: su tensión sube al gastarse'], 'La LiFePO4 se queda en 3,2–3,3 V durante casi toda la descarga: muy estable para el circuito, pero la tensión apenas dice cuánto queda. La alcalina, en cambio, baja sin parar.', { c: 'bb_discharge', l: 'o1', h: 'Piensa en qué curva de descarga es más plana.' }),
    Q('Una linterna pide 2 A a cuatro AA alcalinas de 2500 mAh. Con la cuenta de c6 salen 1,25 h. ¿Qué esperas en la realidad?', ['Bastante menos: con tanta corriente la alcalina se calienta y entrega mucho menos', 'Justo 1,25 h', 'Más de 1,25 h, porque son cuatro pilas', 'El doble, porque la tensión baja despacio'], 'Los mAh del envoltorio se miden con consumos pequeños. Con 2 A, una alcalina pierde gran parte de su capacidad útil.', { c: 'bb_discharge', l: 'o1', h: '¿Con qué consumo se miden los mAh del envoltorio?' }),
    Q('Unes en paralelo una celda de litio llena (4,2 V) con otra casi vacía (3,3 V). ¿Qué pasa?', ['Pasa una corriente grande de la llena a la vacía, limitada solo por sus resistencias internas: se calientan y se dañan', 'Nada: en paralelo cada una trabaja por su cuenta', 'Las dos se quedan en 7,5 V', 'La vacía se desconecta sola'], 'Dos fuentes de tensión distinta unidas directamente: la diferencia (0,9 V) cae sobre resistencias internas muy pequeñas, y la corriente es enorme. Por eso solo se juntan celdas iguales y con la misma carga.', { c: 'bb_cells', l: 'o1', h: 'Hay 0,9 V de diferencia entre dos fuentes unidas: ¿qué resistencia limita la corriente?' }),
    // o5 · cargar litio
    Nm('Quieres cargar a 0,5C una celda de 1200 mAh con un TP4056. ¿Qué RPROG pones, en Ω?', 2000, 'Ω', '0,5C de 1200 mAh son 600 mA = 0,6 A. RPROG = 1200 / 0,6 = 2000 Ω (2 kΩ).', { tol: 20, c: 'bb_crate', l: 'o5', h: 'Calcula la corriente en amperios y usa RPROG = 1200 / I.' }),
    Q('Un TP4056 con RPROG = 2,4 kΩ carga una celda de 1000 mAh. ¿A qué tasa la está cargando?', ['A 0,5C', 'A 2C', 'A 0,05C', 'A 5C'], 'I = 1200 / 2400 = 0,5 A = 500 mA. Sobre 1000 mAh, eso es 0,5C.', { c: 'bb_crate', l: 'o5', h: 'Saca la corriente con I = 1200 / RPROG y compárala con la capacidad.' }),
    Q('Durante una carga ves 4,20 V fijos en la celda y la corriente bajando de 800 a 300 mA. Lo programado era 800 mA. ¿Qué está pasando?', ['Está en la fase CV; terminará cuando la corriente baje a unos 80 mA', 'Está en la fase CC y acaba de empezar', 'El cargador se ha estropeado: la corriente debería ser fija', 'La celda está llena y ya se puede desconectar'], 'Al llegar a 4,2 V el cargador fija la tensión y la corriente baja sola. Corta al llegar a un 10 % de la programada: 80 mA.', { c: 'bb_libms', l: 'o5', h: '¿Qué se mantiene fijo en cada una de las dos fases?' }),
    Q('Tu aparato con una Li-ion protegida (DW01A) se apaga de golpe y mides unos 2,5 V en la celda. ¿Qué ha pasado?', ['La protección ha cortado por descarga profunda: hay que recargarla', 'El cargador está sobrecargando la celda', 'Hay un cortocircuito en la celda', 'El DW01A está roto: hay que puentearlo'], 'La protección desconecta la celda si baja de unos 2,5 V, para que no se dañe. Al recargarla vuelve a conectarla.', { c: 'bb_libms', l: 'o5', h: 'Repasa a qué tres cosas reacciona la protección de una celda.' }),
    Q('Montas un pack 3S de litio (tres celdas en serie). ¿Cómo lo cargas?', ['Con un cargador de 3S (12,6 V al final) y un BMS que equilibre las celdas', 'Con un TP4056 en los extremos del pack', 'Con una fuente de 12 V sin nada más', 'Con tres cargadores de una celda conectados a la vez al pack sin separarlo'], 'El pack lleno tiene 3 × 4,2 = 12,6 V, y si una celda se llena antes, el resto la sobrecargaría: hace falta equilibrado.', { c: 'bb_libms', l: 'o5', h: '¿Qué tensión tiene el pack lleno y qué pasa si una celda se llena antes?' }),
    { t: 'order', q: 'Ordena lo que pasa durante una carga completa de una celda de Li-ion.', items: ['Fase CC: la corriente se mantiene fija y la tensión sube', 'La tensión de la celda llega a 4,2 V', 'Fase CV: la tensión se queda fija y la corriente baja sola', 'La corriente cae a un 10 % de la programada y el cargador corta'], e: 'Primero corriente constante; al llegar a 4,2 V, tensión constante hasta que la corriente es pequeña.', c: 'bb_libms', l: 'o5', h: 'Piensa qué se mantiene fijo en cada fase y cuándo termina.' },
    // k8 · reguladores
    Nm('Un LDO de 3,3 V tiene, con tu consumo, un dropout de 0,25 V. ¿Por debajo de qué tensión de la celda deja de regular, en V?', 3.55, 'V', 'Necesita que la entrada supere a la salida en el dropout: 3,3 + 0,25 = 3,55 V.', { tol: 0.01, c: 'bb_regmargin', l: 'k8', h: 'Tensión de salida más el margen mínimo.' }),
    Q('Un 7805 se alimenta de una pila de 9 V que, al gastarse, baja hasta 6,5 V. ¿Qué pasa al final?', ['La salida cae por debajo de 5 V: ya no tiene sus 2 V de margen', 'Sigue dando 5 V hasta que la pila llega a 5 V', 'La salida sube a 6,5 V', 'El regulador se calienta más'], 'Un 7805 necesita unos 7 V a la entrada. Con 6,5 V la salida sigue a la entrada, un par de voltios por debajo.', { c: 'bb_regmargin', l: 'k8', h: 'Suma a la salida el margen que necesita un 7805.' }),
    Q('Montas un 7805 en la protoboard con sus condensadores a 10 cm, al otro lado de la placa, y la salida no es estable. ¿Qué cambias primero?', ['Poner los condensadores pegados a sus patas', 'Quitar los condensadores', 'Subir la tensión de entrada', 'Cambiarlo por un 7812'], 'Un regulador es un amplificador realimentado: necesita sus condensadores junto a las patas para ser estable.', { c: 'bb_regpins', l: 'k8', h: '¿Dónde dice el montaje que van los condensadores?' }),
    Q('Atornillas un 7805 en TO-220 a un disipador que toca el chasis metálico, y el chasis está unido a masa. ¿Hay problema?', ['No: la aleta del 7805 ya está unida a masa', 'Sí: cortocircuita la salida', 'Sí: cortocircuita la entrada', 'Sí: el disipador deja de servir'], 'En el 7805 la aleta va a masa (la pata 2). Con otros reguladores no tiene por qué ser así: compruébalo siempre en la hoja de datos.', { c: 'bb_regpins', l: 'k8', h: 'Repasa a qué pata está unida la aleta del 7805.' }),
    // o2 · el calor del lineal
    Nm('Un 7805 sin disipador (65 °C/W) baja de 9 V a 5 V con 300 mA, a 30 °C de ambiente. ¿Temperatura de la unión, en °C?', 108, '°C', 'P = (9 − 5) × 0,3 = 1,2 W. Tj = 30 + 1,2 × 65 = 108 °C: por debajo de 125 °C, pero quema al tocarlo y con poco margen.', { tol: 2, c: 'bb_regheat', l: 'o2', h: 'Primero la potencia, (Vent − Vsal) · I; luego Tj = Ta + P · Rθ.' }),
    Q('Un LDO de 3,3 V se alimenta de una Li-ion a 3,7 V. ¿Qué rendimiento tiene?', ['Un 89 %', 'Un 50 %', 'Un 11 %', 'Un 100 %'], 'En un lineal, rendimiento = Vsal / Vent = 3,3 / 3,7 ≈ 0,89. Con la entrada tan cerca de la salida, un lineal rinde bien.', { c: 'bb_linreg', l: 'o2', h: 'En un lineal entra la misma corriente que sale.' }),
    Q('Para sacar 5 V y 0,5 A fijos desde 12 V, alguien propone una resistencia en serie que tire 7 V en vez de un 7805. ¿Qué es cierto?', ['Los dos disipan 3,5 W, pero solo el 7805 mantiene los 5 V si cambia el consumo', 'La resistencia se calienta mucho menos', 'El 7805 se calienta el doble', 'La resistencia rinde más del 90 %'], 'Por los dos pasan 0,5 A con 7 V de caída: 3,5 W en calor. Pero la caída de la resistencia depende de la corriente (Ohm): si el consumo cambia, la salida cambia. El regulador se ajusta solo.', { c: 'bb_linreg', l: 'o2', h: 'Calcula la potencia en cada caso y piensa qué pasa si cambia la corriente.' }),
    { t: 'match', q: 'Une cada regulador lineal con lo que disipa en calor.', pairs: [['De 12 V a 5 V con 0,5 A', '3,5 W'], ['De 9 V a 5 V con 0,1 A', '0,4 W'], ['De 5,5 V a 5 V con 1 A', '0,5 W'], ['De 24 V a 12 V con 0,25 A', '3 W']], e: 'Por un lineal pasa toda la corriente y cae toda la tensión que sobra: (Vent − Vsal) · I. Fíjate en que 5,5 V con 1 A calienta poco: lo que manda es la diferencia.', c: 'bb_linreg', l: 'o2', h: 'En cada caso, (Vent − Vsal) · I.' },
    // o20 · LM317
    Nm('Un LM317 lleva R1 = 120 Ω (entre OUT y ADJ) y R2 = 1 kΩ (de ADJ a masa). ¿Tensión de salida, en V?', 11.67, 'V', 'Vsal = 1,25 × (1 + 1000 / 120) = 1,25 × 9,33 ≈ 11,67 V.', { tol: 0.1, c: 'bb_lm317', l: 'o20', h: 'Vsal = 1,25 · (1 + R2 / R1).' }),
    TU('Elige R1 y R2 para que el LM317 dé entre 11,5 y 12 V.', 'lm317', { mode: { val: 0, fixed: true }, R1: { label: 'R1 (OUT–ADJ)', val: 240, list: [62, 120, 240, 330], fmt: 'R' }, R2: { label: 'R2 (ADJ–masa)', val: 220, list: [220, 470, 720, 1000, 1500, 2200], fmt: 'R' }, Vin: { val: 15, fixed: true }, IL: { val: 0.1, fixed: true } }, { q: 'Vout', min: 11.5, max: 12, text: 'Objetivo: entre 11,5 y 12 V', hint: 'Necesitas R2 / R1 entre 8,2 y 8,6.' }, 'Hace falta R2 / R1 = 12 / 1,25 − 1 ≈ 8,6: con 120 Ω y 1 kΩ salen 11,67 V. Y con 15 V a la entrada sobra margen.', { c: 'bb_lm317', l: 'o20', h: 'Despeja: R2 / R1 = Vsal / 1,25 − 1.' }),
    Nm('Un LM317 hace de fuente de corriente de 700 mA para un LED de potencia. ¿Cuánta potencia disipa la resistencia que fija la corriente, en W?', 0.875, 'W', 'Siempre tiene 1,25 V: P = 1,25 × 0,7 = 0,875 W. Una de 1 W va justa; mejor de 2 W.', { tol: 0.02, c: 'bb_lm317i', l: 'o20', h: '¿Qué tensión tiene siempre esa resistencia?' }),
    Nm('Un LM317 alimenta con 350 mA un LED de potencia que cae 3,3 V, desde 12 V. ¿Cuánto disipa el propio LM317, en W?', 2.61, 'W', 'Al LM317 le queda lo que sobra: 12 − 3,3 (LED) − 1,25 (resistencia) = 7,45 V. P = 7,45 × 0,35 ≈ 2,61 W: necesita disipador.', { tol: 0.05, c: 'bb_linreg', l: 'o20', h: 'Resta a la entrada la caída del LED y los 1,25 V de la resistencia: el resto cae en el LM317.' }),
    // o3 · conmutados
    Nm('Un buck con un 90 % de rendimiento baja de 24 V a 12 V y entrega 1,5 A. ¿Qué corriente toma de la entrada, en A?', 0.833, 'A', 'Salida: 12 × 1,5 = 18 W. Entrada: 18 / 0,9 = 20 W. Corriente: 20 / 24 ≈ 0,83 A.', { tol: 0.02, c: 'bb_smps_how', l: 'o3', h: 'Calcula la potencia de salida, divide por el rendimiento y luego por la tensión de entrada.' }),
    Q('Un buck baja de 9 V a 3,3 V. ¿Qué ciclo de trabajo usa, más o menos?', ['Un 37 %', 'Un 63 %', 'Un 27 %', 'Un 100 %'], 'D ≈ Vsal / Vent = 3,3 / 9 ≈ 0,37.', { c: 'bb_smps_how', l: 'o3', h: 'En un buck la salida es la media: Vsal ≈ D × Vent.' }),
    Q('Una placa a 12 V consume 1 A a 3,3 V y además lleva un sensor analógico muy sensible al ruido, de pocos mA. ¿Qué alimentación eliges?', ['Un buck para todo y un LDO detrás solo para el sensor', 'Un 7805 para todo', 'Un boost', 'Un divisor de tensión'], 'Con 1 A, un lineal desde 12 V disiparía casi 9 W. El buck rinde mucho más, y el LDO detrás limpia su ruido para el sensor.', { c: 'bb_smps_pick', l: 'o3', h: 'Piensa en el calor de un lineal con 1 A y en la pega de los conmutados.' }),
    TU('Tu circuito necesita 5 V. Elige una fuente (tensión llena y vacía) con la que haga falta un boost.', 'buckBoost', { Va: { label: 'Fuente: tensión llena', val: 12, min: 0.5, max: 15, step: 0.1, unit: 'V', dec: 1 }, Vb: { label: 'Fuente: tensión vacía', val: 10, min: 0.5, max: 15, step: 0.1, unit: 'V', dec: 1 }, Vo: { val: 5, fixed: true } }, { q: 'type', min: 1, max: 1, text: 'Objetivo: que haga falta un boost', hint: 'La fuente tiene que estar siempre por debajo de 5 V.' }, 'Si la fuente está siempre por debajo de lo que necesitas, hay que subir: boost. Por ejemplo, una celda de litio (4,2 a 3,0 V) para sacar 5 V, como en una batería externa.', { c: 'bb_smps_pick', l: 'o3', h: 'Boost sube; la fuente llena y la vacía deben quedar por debajo de 5 V.' }),
    // o4 · protección
    Nm('Un MOSFET P de 30 mΩ protege la polaridad de una placa que consume 1,5 A. ¿Cuánto disipa, en mW?', 67.5, 'mW', 'P = I² · Rds(on) = 1,5² × 0,03 = 0,0675 W = 67,5 mW. Un diodo de 0,8 V disiparía 1,2 W.', { tol: 1, c: 'bb_revpol', l: 'o4', h: 'El MOSFET encendido es una resistencia pequeña: P = I² · R.' }),
    Q('Pones un fusible rápido de 1 A en una placa que al enchufarse tiene un pico de 3 A durante unos milisegundos y luego consume 0,8 A. ¿Qué pasa?', ['Puede fundirse cada vez que enchufas: conviene uno lento y con más margen', 'Nada: el pico es muy corto', 'Protege mejor que uno lento', 'El fusible limita el pico a 1 A sin fundirse'], 'El pico de arranque (los condensadores de entrada cargándose) puede fundir un fusible rápido y justo. Uno lento aguanta el pico y sigue cortando un cortocircuito.', { c: 'bb_inprot', l: 'o4', h: 'Compara el pico de arranque con lo que aguanta el fusible.' }),
    Q('Proteges una entrada de 12 V con una TVS. ¿Cuál eliges?', ['Una que no actúe a 12 V y recorte poco por encima, de unos 15 V de trabajo', 'Una de 5 V, para que proteja más', 'Una de 100 V, por si acaso', 'Cualquiera: todas recortan igual'], 'Con 5 V conduciría siempre y se quemaría; con 100 V dejaría pasar picos que rompen el circuito. Debe quedar justo por encima de la tensión normal.', { c: 'bb_inprot', l: 'o4', h: 'La TVS no debe hacer nada con la tensión normal, solo con los picos.' })
  ];
  /* ===================== FIN DEL EXAMEN ===================== */
  UNITS.push({ id: 'm10c', title: 'Alimentación', desc: 'Baterías y litio, reguladores lineales, LDO y LM317, convertidores conmutados y protección.', exam, nodes: [
    L('o1', 'Pilas y baterías', 'bat', ['bb_cells', 'bb_discharge', 'bb_lisafe'], [
      Q('Una pila AA alcalina pone «1,5 V». ¿Qué tensión crees que tiene cuando está medio gastada?', ['Bastante menos: unos 1,2–1,3 V', 'Sigue en 1,5 V hasta que se acaba de golpe', 'Más de 1,5 V', '0,75 V justos'], 'La tensión va bajando a medida que se gasta. Cuánto y cómo depende de la química: hoy verás las curvas.', { predict: true, c: 'bb_discharge', h: 'Piensa si una pila puede mantener su tensión mientras se vacía.' }),
      I('Cada química tiene su tensión por celda:\n· <b>Alcalina</b>: 1,5 V (no recargable).\n· <b>NiMH</b>: 1,2 V (recargable).\n· <b>Li-ion y LiPo</b>: 3,6–3,7 V nominales, 4,2 V llena.\n· <b>LiFePO4</b>: 3,2 V, muy segura y duradera.\n· <b>Botón CR2032</b>: 3 V.', { svg: `<svg viewBox="0 0 300 150" class="viz">${[['Alcalina', 1.5], ['NiMH', 1.2], ['Li-ion', 3.7], ['LiFePO4', 3.2], ['CR2032', 3]].map(([n, v], i) => `<rect x="${22 + i * 56}" y="${120 - v * 26}" width="40" height="${v * 26}" rx="5" fill="${i === 2 ? 'var(--led)' : 'var(--ice)'}" opacity=".85"/><text x="${42 + i * 56}" y="${113 - v * 26}" text-anchor="middle" class="vizlab" style="font-size:11px">${num(v, 1)} V</text><text x="${42 + i * 56}" y="138" text-anchor="middle" class="vizsm">${n}</text>`).join('')}</svg>`, more: 'La tensión «nominal» es un valor medio de la descarga, no la que mides con la pila llena.\nLiPo es una Li-ion en bolsa flexible en vez de cilindro metálico: misma química básica y mismos cuidados (o más, porque se perfora con facilidad).\nLa 18650 es el formato cilíndrico de Li-ion más común: 18 mm de diámetro y 65 mm de largo.' }),
      { t: 'explore', text: 'Curvas de descarga: la tensión de una celda según la carga que le queda.', viz: 'dischargeCurve', params: { q: LS('Química (0 alcalina, 1 NiMH, 2 Li-ion, 3 LiFePO4)', 2, [0, 1, 2, 3]), carga: SL('Carga que queda', 100, 0, 100, 5, '%', 0) },
        tasks: [
          { q: 'liLow', min: 1, max: 1, text: 'Con la Li-ion, baja la carga hasta que la tensión caiga de 3,5 V', done: 'Casi toda la descarga ocurre entre 4,2 y 3,6 V; al final cae deprisa.', hint: 'Lleva la carga casi a 0.' },
          { q: 'flat', min: 1, max: 1, text: 'Cambia a LiFePO4 y mírala entre el 80 % y el 20 %', done: 'Casi plana, en 3,2–3,3 V: tensión muy estable, pero difícil saber cuánto queda midiéndola.', hint: 'Química 3 y carga a mitad.' },
          { q: 'alkHalf', min: 1, max: 1, text: 'Ahora una alcalina a media carga o menos', done: 'Baja sin parar: con media carga ya ronda 1,25 V. Por eso algunos aparatos dicen «pila baja» muy pronto.', hint: 'Química 0 y carga al 50 %.' }
        ] },
      I('<b>Capacidad real</b>: los mAh del envoltorio se miden con consumos pequeños. Si le pides mucha corriente, la pila se calienta, su tensión cae antes y entrega menos. Las alcalinas lo notan muchísimo; las de litio, poco.', { svg: `<svg viewBox="0 0 300 120" class="viz">${hbar(30, 40, 240, 1, '#1F9D55', 'Alcalina AA con 25 mA: casi toda su capacidad')}${hbar(30, 90, 240, 0.4, '#D64545', 'Con 1 A: a veces menos de la mitad')}</svg>` }),
      I('Recuerda la autonomía de c6: <b>horas ≈ mAh / mA</b>. Aquí lo afinas: con consumos grandes, cuenta con bastante menos de lo que da la cuenta.', { tune: { viz: 'battery', params: { mAh: SL('Capacidad', 2000, 200, 3000, 100, 'mAh', 0), mA: SL('Consumo', 50, 5, 500, 5, 'mA', 0) } } }),
      I('<b>Serie</b>: se suman las tensiones; la capacidad es la de una. <b>Paralelo</b>: misma tensión; se suman las capacidades. Solo se juntan celdas <b>iguales y con la misma carga</b>.', { svg: '<svg viewBox="0 0 300 140" class="viz">' + [0, 1, 2, 3].map(i => `<rect x="${20 + i * 30}" y="40" width="24" height="50" rx="4" fill="var(--ice)"/>`).join('') + '<text x="74" y="110" text-anchor="middle" class="vizlab">4 en serie</text><text x="74" y="128" text-anchor="middle" class="vizsm">6 V · 2500 mAh</text>' + [0, 1].map(i => `<rect x="190" y="${30 + i * 36}" width="70" height="26" rx="4" fill="var(--led)"/>`).join('') + '<text x="225" y="110" text-anchor="middle" class="vizlab">2 en paralelo</text><text x="225" y="128" text-anchor="middle" class="vizsm">1,5 V · 5000 mAh</text></svg>' }),
      { t: 'steps', text: 'Un portapilas tiene 8 AA alcalinas (1,5 V y 2500 mAh cada una): dos ramas de 4 en serie, puestas en paralelo. ¿Tensión, capacidad y energía?', steps: ['Una rama: 4 en serie → 4 × 1,5 = <b>6 V</b>, 2500 mAh', 'Dos ramas en paralelo: la tensión no cambia, <b>6 V</b>', 'Capacidad: 2 × 2500 = <b>5000 mAh</b> = 5 Ah', 'Energía (b9): 6 V × 5 Ah = <b>30 Wh</b>'], result: '6 V, 5000 mAh y unos 30 Wh (menos si el consumo es grande).' },
      G('battSeriesPar'),
      Q('Pones dos pilas iguales en paralelo. ¿Qué consigues?', ['La misma tensión y el doble de capacidad', 'El doble de tensión', 'La mitad de tensión', 'Nada: no se puede'], 'En paralelo se suman los mAh; en serie, los voltios.', { c: 'bb_cells', h: 'Paralelo: todas tienen sus extremos unidos.' }),
      MT('¿Está cargada esta pila de 9 V? Mide su tensión.', 'bat', { measure: 'V', between: ['P', 'N'], best: true, sign: true }, 'Por encima de 9 V está bien; por debajo de unos 7 V, gastada.', { c: 'bb_cells', h: 'Voltios de continua, punta roja en el + y negra en el −.' }),
      Q('Acabas de cargar una celda de Li-ion de «3,7 V». ¿Qué marca el multímetro?', ['Unos 4,2 V', '3,7 V justos', '3,0 V', '5 V'], '3,7 V es la nominal (la media); llena tiene 4,2 V.', { c: 'bb_cells', h: 'Mira la curva de la Li-ion al 100 %.' }),
      I('<b>Seguridad con el litio</b>: guarda mucha energía y puede arder de forma violenta y difícil de apagar.\n· Nunca la cortocircuites ni la perfores.\n· Si se hincha, deja de usarla y llévala a reciclar.\n· Cárgala solo con un cargador de litio (lo verás en la siguiente lección).', { svg: '<svg viewBox="0 0 300 110" class="viz"><path d="M150 12L250 95H50Z" fill="var(--err-soft)" stroke="var(--err)" stroke-width="3" stroke-linejoin="round"/><text x="150" y="80" text-anchor="middle" font-size="44" font-weight="800" fill="var(--err)" class="a-pulse">!</text></svg>' }),
      Q('Una batería de Li-ion se ha hinchado. ¿Qué haces?', ['Dejar de usarla y llevarla a reciclar', 'Pincharla para desinflarla', 'Cargarla más para compensar', 'Seguir usándola con cuidado'], 'Una celda hinchada puede arder.', { c: 'bb_lisafe', h: 'Piensa en el riesgo, no en aprovecharla.' }),
      { t: 'match', q: 'Une cada química con su tensión por celda.', pairs: [['Alcalina', '1,5 V'], ['NiMH', '1,2 V'], ['Li-ion (nominal)', '3,7 V'], ['LiFePO4', '3,2 V']], c: 'bb_cells', h: 'Las de litio rondan 3–4 V; las de níquel y las alcalinas, 1–1,5 V.' },
      RES('Cada química, su tensión: 1,5 · 1,2 · 3,7 (4,2 llena) · 3,2 V.', 'La tensión baja al descargarse; con mucha corriente, menos capacidad.', '<b>Serie</b> suma voltios; <b>paralelo</b> suma mAh.', 'Litio: ni cortos, ni golpes, ni cargadores que no sean de litio.')
    ]),
    SIM('sg5', 'Reto: aviso de batería baja', 'Vigila la tensión del cursor del potenciómetro (tu “batería”) con un comparador y la referencia de un zener de 5,1 V: el LED se enciende cuando el cursor baja de la referencia.', { battery: 9, parts: ['pot', 'zener', 'res', 'cmp', 'led'], hint: '+ → 1 kΩ → cátodo del zener; ánodo al −. Cátodo del zener → IN+ del comparador. Potenciómetro entre + y −, cursor → IN−. VCC del comparador al +. Salida → 470 Ω → LED → −.' }, 'battMonitor'),
    L('o5', 'Cargar baterías de litio', 'bat', ['bb_crate', 'bb_libms', 'bb_lisafe', 'bb_cells'], [
      Q('Para cargar una celda de Li-ion, ¿crees que basta con conectarla a una fuente de 5 V?', ['No: hay que limitar la corriente y parar exactamente en 4,2 V', 'Sí: cuanta más tensión, más rápido', 'Sí, si la fuente es USB', 'No: necesita corriente alterna'], 'A 5 V la celda se sobrecargaría y podría arder. El litio se carga con un método preciso de dos fases: CC y CV.', { predict: true, c: 'bb_lisafe', h: 'Recuerda la tensión máxima de una Li-ion llena.' }),
      I('Se carga en dos fases, como la fuente de laboratorio de f10:\n· <b>CC</b> (corriente constante): por ejemplo 1 A mientras la tensión sube.\n· <b>CV</b> (tensión constante): al llegar a <b>4,2 V</b> se queda fija y la corriente va bajando sola.\nTermina cuando la corriente cae a un 10 % aproximadamente.'),
      { t: 'explore', text: 'Una carga completa. Naranja: tensión de la celda. Azul: corriente.', viz: 'cccv', params: { cap: LS('Capacidad de la celda', 2000, [1000, 2000, 3000], 'mAh'), rate: LS('Tasa de carga', 0.2, [0.2, 0.5, 1], 'C', 1), t: SL('Tiempo', 0, 0, 6, 0.1, 'h', 1) },
        tasks: [
          { q: 'Iset', min: 990, max: 1010, text: 'Programa una carga de 1 A', done: 'Por ejemplo, 2000 mAh a 0,5C = 1000 mA.', hint: 'Capacidad × tasa = 1000 mA.' },
          { q: 'phase', min: 1, max: 1, text: 'Avanza el tiempo hasta que empiece la fase CV', done: 'Al llegar a 4,2 V la tensión se queda fija y la corriente empieza a bajar.', hint: 'Mueve el tiempo hasta que la naranja se aplane.' },
          { q: 'phase', min: 2, max: 2, text: 'Llega al final de la carga', done: 'Cuando la corriente cae a un 10 % de la programada, el cargador corta.', hint: 'Sigue avanzando el tiempo.' }
        ] },
      I('<b>Tasa C</b>: 1C es la corriente que llenaría (o vaciaría) la celda en una hora: para 2000 mAh, 2000 mA. Lo habitual es cargar a 0,5C, sin pasar nunca de la máxima que da la hoja de datos.\nTiempo mínimo de CC ≈ capacidad / corriente; la fase CV añade bastante.'),
      G('liChargeI'),
      Q('¿Qué pasa si cargas hasta 4,4 V una celda de 4,2 V?', ['Se degrada deprisa y aumenta el riesgo de incendio', 'Guarda más energía sin problema', 'Nada', 'Se descarga sola'], 'Los cargadores de litio tienen una tensión final muy precisa (±1 %).', { c: 'bb_lisafe', h: 'La tensión final es un límite, no una sugerencia.' }),
      I('El <b>TP4056</b> es un cargador CC/CV de una celda muy usado. La corriente se fija con la resistencia de su pata PROG: <b>I ≈ 1200 / RPROG</b> (1,2 kΩ → 1 A). Tiene dos salidas para LEDs: cargando y terminado.', { svg: '<svg viewBox="0 0 300 130" class="viz"><rect x="40" y="20" width="220" height="90" rx="8" fill="#1F4E9C"/><rect x="20" y="48" width="34" height="34" rx="4" fill="#B9C4D3"/><text x="37" y="125" text-anchor="middle" class="vizsm">USB</text><rect x="120" y="45" width="50" height="40" rx="3" fill="#1c1c1c"/><text x="145" y="69" text-anchor="middle" fill="#ddd" font-size="9">TP4056</text><rect x="185" y="38" width="14" height="8" fill="#1c1c1c"/><text x="192" y="34" text-anchor="middle" fill="#fff" font-size="8">RPROG</text><circle cx="95" cy="40" r="5" fill="#E5484D" class="a-blink"/><circle cx="95" cy="90" r="5" fill="#2EA44F"/><text x="250" y="40" text-anchor="end" fill="#fff" font-size="10">B+ B−</text><text x="250" y="95" text-anchor="end" fill="#fff" font-size="10">OUT±</text></svg>' }),
      { t: 'steps', text: 'Celda de 2000 mAh que admite hasta 1C. Quieres cargarla a 0,5C con un TP4056. ¿Corriente, RPROG y tiempo aproximado?', steps: ['Corriente: 0,5 × 2000 mA = <b>1000 mA</b> = 1 A', 'RPROG = 1200 / I = 1200 / 1 = <b>1200 Ω</b> (1,2 kΩ)', 'Fase CC: unos 2000 mAh / 1000 mA ≈ 2 h como mucho (en realidad acaba antes)', 'Más la fase CV: en total, <b>unas 2,5 h</b>'], result: '1 A con 1,2 kΩ: unas dos horas y media.' },
      Nm('¿Qué RPROG pones en un TP4056 para cargar a 400 mA? (en Ω)', 3000, 'Ω', '1200 / 0,4 = 3000 Ω = 3 kΩ.', { tol: 30, c: 'bb_crate', h: 'RPROG = 1200 / I, con I en amperios.' }),
      G('tp4056R'),
      I('Cargar no es proteger. La <b>protección</b> (un DW01A con dos MOSFET, o un BMS) corta la celda si:\n· baja de unos 2,5 V (descarga profunda),\n· sube de unos 4,3 V (sobrecarga),\n· la corriente se dispara (cortocircuito).', { svg: '<svg viewBox="0 0 300 120" class="viz"><rect x="20" y="40" width="60" height="40" rx="6" fill="var(--led)"/><text x="50" y="65" text-anchor="middle" class="vizlab" style="fill:#14213D">celda</text><rect x="110" y="35" width="80" height="50" rx="6" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="150" y="58" text-anchor="middle" class="vizsm" style="fill:currentColor">DW01A +</text><text x="150" y="72" text-anchor="middle" class="vizsm" style="fill:currentColor">2 MOSFET</text><path d="M80 60H110M190 60H280" stroke="currentColor" stroke-width="2.2"/><text x="280" y="52" text-anchor="end" class="vizlab">OUT±</text><text x="150" y="110" text-anchor="middle" class="vizsm">la protección abre el camino si algo va mal</text></svg>' }),
      Q('Tu módulo TP4056 tiene contactos B+/B− y OUT+/OUT−. ¿Dónde conectas tu circuito?', ['En OUT+/OUT−, que pasan por la protección', 'En B+/B− directamente', 'En la entrada USB', 'Da igual'], 'B± van a la celda; OUT± están protegidas.', { c: 'bb_libms', h: 'Busca las salidas que pasan por los MOSFET de protección.' }),
      I('<b>Varias celdas en serie</b> (2S, 3S…) necesitan un cargador de esa tensión y un BMS con <b>equilibrado</b>: si una celda se llena antes, el resto la sobrecargaría. Nunca cargues celdas en serie con un cargador de una sola celda.'),
      Q('Un pack 2S (dos celdas de litio en serie) lleno, ¿qué tensión tiene?', ['8,4 V', '4,2 V', '7,4 V', '3,7 V'], '2 × 4,2 V; 7,4 V es la nominal.', { c: 'bb_cells', h: 'Serie: se suman las tensiones de celdas llenas.' }),
      Q('La mayoría de celdas de litio…', ['No deben cargarse por debajo de 0 °C', 'Se cargan mejor bajo cero', 'Solo se cargan a más de 60 °C', 'Se cargan igual a cualquier temperatura'], 'Cargar en frío deposita litio metálico dentro y daña la celda. Mira su hoja de datos.', { c: 'bb_lisafe', h: 'El frío es un problema al cargar, no al guardar.' }),
      { t: 'order', q: 'Ordena las comprobaciones antes de cargar una celda que has recuperado de un aparato viejo.', items: ['Inspecciona: sin golpes, hinchazón ni fugas', 'Mide la tensión: por encima de unos 2,5 V', 'Busca su corriente máxima de carga en la hoja de datos', 'Carga vigilada sobre una superficie no inflamable', 'Tócala de vez en cuando: como mucho, templada'], e: 'Si algo falla, recíclala.', c: 'bb_lisafe', h: 'Primero mirar, luego medir, luego informarte y por último cargar vigilando.' },
      RES('Carga <b>CC</b> y luego <b>CV a 4,2 V</b>; termina al 10 % de corriente.', '<b>1C</b> = capacidad en mA; normalmente 0,5C.', 'TP4056: <b>RPROG = 1200 / I</b>.', 'Protección (DW01A, BMS) aparte; packs en serie con equilibrado.')
    ]),
    L('k8', 'Reguladores integrados', 'ic', ['bb_regmargin', 'bb_regpins'], [
      Q('Una pila de 9 V baja a 7 V al gastarse y tu circuito necesita 5 V fijos. Si usas un divisor de tensión, ¿qué crees que pasará?', ['La salida bajará con la pila y cambiará con el consumo', 'Dará 5 V siempre', 'Dará 9 V', 'Funcionará igual que un regulador'], 'El divisor reparte lo que le llega: si baja la pila, baja la salida, y si el circuito consume más, también. Hace falta algo que se corrija solo: un regulador.', { predict: true, c: 'bb_regmargin', h: 'Recuerda el divisor de d6 y lo que pasaba al cargarlo.' }),
      I('Un <b>regulador lineal</b> por dentro: un transistor en serie (el «de paso») y un amplificador que compara una parte de la salida con una <b>referencia</b> fija (como un zener). Si la salida baja, el amplificador abre más el transistor; si sube, lo cierra.', { svg: '<svg viewBox="0 0 300 160" class="viz"><path d="M15 40H110M150 40H285M130 55V82M230 40V60M230 100V112M230 80H200V128H142M100 128H118M230 112v6M221 118h18M224 122h12M227 126h6" stroke="currentColor" stroke-width="2" fill="none"/><rect x="110" y="25" width="40" height="30" rx="4" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="130" y="44" text-anchor="middle" class="vizsm" style="fill:currentColor">paso</text><path d="M112 140L148 140L130 84Z" fill="var(--surface)" stroke="currentColor" stroke-width="2"/><path d="M130 82V55" stroke="var(--led)" stroke-width="2.5" class="a-flow-slow"/><rect x="223" y="60" width="14" height="40" rx="6" fill="#E7D3A8" stroke="#C9B183"/><text x="20" y="132" class="vizsm">referencia</text><text x="205" y="148" class="vizsm">parte de Vsal</text><text x="15" y="32" class="vizsm">Vent</text><text x="285" y="32" text-anchor="end" class="vizsm">Vsal</text><text x="150" y="158" text-anchor="middle" class="vizsm">un amplificador realimentado, como en k6</text></svg>', more: 'Es el mismo truco que en el no inversor: la realimentación hace que la parte de la salida que vuelve iguale a la referencia. Por eso la salida no depende de la pila ni del consumo, mientras haya margen.\nLa familia <b>78xx</b> da tensiones fijas: 7805 (5 V), 7812 (12 V)…; la 79xx, negativas.' }),
      { t: 'explore', text: 'Elige regulador, tensión de entrada y corriente. Mira si regula.', viz: 'linreg', params: { tipo: LS('Regulador (0 7805, 1 LDO 5 V, 2 LDO 3,3 V)', 0, [0, 1, 2]), Vin: SL('Entrada', 6, 3, 15, 0.1, 'V', 1), I: LS('Corriente', 100, [50, 100, 200, 500, 1000], 'mA') },
        tasks: [
          { q: 'reg', min: 1, max: 1, text: 'Con el 7805, sube la entrada hasta que regule', done: 'Necesita unos 2 V de margen: 7 V o más a la entrada.', hint: 'Sube la entrada por encima de 7 V.' },
          { q: 'minVin', min: 1, max: 1, text: 'Consigue 5 V regulados con 5,5 V o menos a la entrada', done: 'Un LDO (regulador de baja caída) se conforma con unos 0,3 V de margen.', hint: 'Cambia al LDO de 5 V.' },
          { q: 'li33', min: 1, max: 1, text: 'Saca 3,3 V regulados de una Li-ion casi vacía (3,7 V o menos)', done: 'El LDO de 3,3 V regula mientras la celda dé más de 3,6 V.', hint: 'LDO de 3,3 V y entrada entre 3,6 y 3,7 V.' }
        ] },
      I('<b>Margen mínimo</b> (dropout): lo mínimo que la entrada debe superar a la salida para que regule. Un 7805 clásico, unos 2 V. Un <b>LDO</b> (Low DropOut), de 0,1 a 0,5 V según modelo y corriente. Por debajo, la salida cae con la entrada.', { svg: `<svg viewBox="0 0 300 110" class="viz">${hbar(30, 35, 240, 7 / 9, '#F2A900', '7805: entrada mínima ≈ 7 V para dar 5 V')}${hbar(30, 85, 240, 5.3 / 9, '#1F9D55', 'LDO de 5 V: entrada mínima ≈ 5,3 V')}</svg>` }),
      { t: 'steps', text: 'Quieres 3,3 V desde una celda Li-ion (4,2 V llena, unos 3,0 V vacía). ¿Qué regulador?', steps: ['¿Un 7805? Da 5 V, más que la celda: <b>no sirve</b>', '¿Un regulador de 3,3 V con 2 V de margen? Pediría 5,3 V: <b>no llega nunca</b>', 'LDO de 3,3 V con 0,2 V de dropout: regula mientras la celda dé más de <b>3,5 V</b>', 'Por debajo deja pasar lo que hay (3,4 V, 3,3 V…): casi toda la carga útil está por encima'], result: 'Un LDO de 3,3 V con poco dropout.' },
      Q('Necesitas 3,3 V desde una celda de litio (3,7–4,2 V). ¿Qué usas?', ['Un LDO de 3,3 V: el margen es pequeño', 'Un 7805', 'Ninguno', 'Un zener de 10 V'], 'Un regulador normal pediría 5,3 V a la entrada.', { c: 'bb_regmargin', h: 'Compara el margen disponible con el que pide cada regulador.' }),
      Nm('Un 7812 necesita unos 2 V de margen. ¿Tensión mínima de entrada, en V?', 14, 'V', '12 + 2 = 14 V.', { tol: 0.1, c: 'bb_regmargin', h: 'Suma el margen a la tensión de salida.' }),
      Q('Un 7805 recibe 12 V y entrega 100 mA. ¿Qué tensión hay a su salida?', ['5 V', '12 V', '7 V', '10 V'], 'Mientras haya margen, la salida es 5 V; lo demás lo absorbe el regulador (en la siguiente lección verás a qué precio).', { c: 'bb_regmargin', h: 'Hay margen de sobra: ¿qué hace un regulador entonces?' }),
      I('Montaje: el 7805 en TO-220, de frente: <b>1 entrada, 2 masa, 3 salida</b>; la aleta va a masa. Un condensador en la entrada (unos 0,33 µF) y otro en la salida (unos 0,1 µF), pegados a las patas. Los LDO suelen pedir un condensador de salida concreto: mira su hoja de datos.', { svg: '<svg viewBox="0 0 300 165" class="viz"><rect x="105" y="10" width="90" height="30" rx="4" fill="#B9C4D3" stroke="currentColor"/><circle cx="150" cy="25" r="7" fill="var(--bg)" stroke="currentColor"/><rect x="100" y="40" width="100" height="60" rx="4" fill="#1c1c1c"/><text x="150" y="75" text-anchor="middle" fill="#ddd" font-size="14">7805</text><path d="M125 100v40M150 100v40M175 100v40" stroke="#9AA3B2" stroke-width="5" stroke-linecap="round"/><text x="125" y="153" text-anchor="middle" class="vizlab">1</text><text x="150" y="153" text-anchor="middle" class="vizlab">2</text><text x="175" y="153" text-anchor="middle" class="vizlab">3</text><text x="210" y="70" class="vizsm">1 entrada</text><text x="210" y="84" class="vizsm">2 masa</text><text x="210" y="98" class="vizsm">3 salida</text></svg>' }),
      { t: 'match', q: 'Patas del 7805 (de frente, de izquierda a derecha).', pairs: [['Pata 1', 'Entrada'], ['Pata 2', 'Masa'], ['Pata 3', 'Salida']], c: 'bb_regpins', h: 'La tensión entra por un lado y sale por el otro; la masa, en medio.' },
      Q('Montas un LDO sin el condensador de salida que pide su hoja de datos. ¿Qué puede pasar?', ['Que oscile y la salida no sea estable', 'Nada', 'Que dé el doble de tensión', 'Que regule mejor'], 'Un regulador es un amplificador realimentado: su estabilidad depende de ese condensador.', { c: 'bb_regpins', h: 'Recuerda qué hay dentro del regulador.' }),
      RES('Regulador lineal: transistor de paso + amplificador + referencia.', 'Necesita <b>margen</b>: 7805 ≈ 2 V; <b>LDO</b> 0,1–0,5 V.', '7805 de frente: entrada, masa, salida; condensadores pegados.', 'Para 3,3 V desde litio: LDO.')
    ]),
    L('o2', 'Reguladores lineales: el calor', 'ic', ['bb_linreg', 'bb_regheat'], [
      Q('Un 7805 baja de 12 V a 5 V y entrega 0,5 A. ¿Qué crees que pasa con los 7 V que sobran?', ['Se convierten en calor en el regulador: 3,5 W', 'Vuelven a la fuente', 'Desaparecen sin calentar', 'Se guardan en el regulador'], 'El lineal es como una resistencia que se ajusta sola: por él pasa toda la corriente y cae toda la tensión que sobra. Eso es potencia (c4) convertida en calor.', { predict: true, c: 'bb_linreg', h: 'Por el regulador pasa la corriente y cae una tensión: P = V · I.' }),
      I('Un lineal es una <b>resistencia variable automática</b>: deja caer justo lo que sobra. Entra la misma corriente que sale, así que pierde\n<b>P = (Vent − Vsal) · I</b>.', { svg: '<svg viewBox="0 0 300 120" class="viz"><path d="M15 50H105M195 50H285" stroke="currentColor" stroke-width="2.2"/><path d="M15 50H105M195 50H285" stroke="var(--led)" stroke-width="3" class="a-flow"/><rect x="105" y="30" width="90" height="40" rx="6" fill="rgb(250,130,60)" stroke="currentColor"/><text x="150" y="55" text-anchor="middle" class="vizlab" style="fill:#14213D">7 V × 0,5 A</text><path d="M130 22q-5 -6 0 -12M150 22q-5 -6 0 -12M170 22q-5 -6 0 -12" stroke="var(--err)" stroke-width="2" fill="none" class="a-bob"/><text x="15" y="40" class="vizlab">12 V</text><text x="285" y="40" text-anchor="end" class="vizlab">5 V</text><text x="150" y="100" text-anchor="middle" class="vizsm">0,5 A entran y 0,5 A salen: 3,5 W de calor</text></svg>' }),
      { t: 'explore', text: 'El mismo regulador, ahora mirando el calor y el rendimiento.', viz: 'linreg', params: { tipo: LS('Regulador (0 7805, 1 LDO 5 V, 2 LDO 3,3 V)', 0, [0, 1, 2]), Vin: SL('Entrada', 9, 3, 15, 0.1, 'V', 1), I: LS('Corriente', 100, [50, 100, 200, 500, 1000], 'mA') },
        tasks: [
          { q: 'P', min: 3, max: 100, text: 'Haz que disipe más de 3 W', done: 'Mucha tensión sobrante y mucha corriente: (Vent − Vsal) × I.', hint: 'Entrada alta y corriente grande.' },
          { q: 'effReg', min: 85, max: 100, text: 'Consigue un rendimiento de más del 85 % regulando', done: 'Rendimiento ≈ Vsal / Vent: solo es bueno si la entrada está muy cerca de la salida (y eso pide un LDO).', hint: 'LDO de 5 V con la entrada justo por encima de 5,3 V.' }
        ] },
      I('<b>Rendimiento</b> = potencia útil / potencia que entra. Como la corriente es la misma, en un lineal es <b>Vsal / Vent</b>. De 12 a 5 V: 5 / 12 = 42 %. Más de la mitad se va en calor.', { svg: `<svg viewBox="0 0 300 80" class="viz"><rect x="20" y="25" width="109" height="22" rx="3" fill="var(--ok)"/><rect x="129" y="25" width="151" height="22" rx="3" fill="var(--err)" opacity=".85"/><text x="74" y="40" text-anchor="middle" class="vizsm" style="fill:#fff">5 V útiles</text><text x="204" y="40" text-anchor="middle" class="vizsm" style="fill:#fff">7 V en calor</text><text x="150" y="70" text-anchor="middle" class="vizsm">de 12 V a 5 V: rendimiento del 42 %</text></svg>` }),
      { t: 'steps', text: 'Un 7805 en TO-220 sin disipador baja de 12 V a 5 V con 500 mA. ¿Aguanta? (sin disipador, unos 65 °C/W; 25 °C de ambiente)', steps: ['Potencia: (12 − 5) × 0,5 = <b>3,5 W</b>', 'Rendimiento: 5 / 12 = <b>42 %</b>', 'Temperatura (j10): Tj = 25 + 3,5 × 65 ≈ <b>252 °C</b>', 'Muy por encima de su máximo (unos 125 °C): se protegería apagándose. Necesita <b>disipador</b> o menos tensión de entrada'], result: '3,5 W: con un TO-220 al aire, imposible.' },
      G('linRegHeat'), G('linRegEff'),
      Nm('Un regulador de 3,3 V alimentado a 9 V entrega 200 mA. ¿Potencia en calor, en W?', 1.14, 'W', '(9 − 3,3) × 0,2 = 5,7 × 0,2 = 1,14 W.', { tol: 0.02, c: 'bb_linreg', h: 'Tensión que sobra por la corriente en amperios.' }),
      Nm('Un regulador en TO-220 sin disipador (65 °C/W) disipa 1 W con 25 °C de ambiente. ¿Temperatura de la unión, en °C?', 90, '°C', '25 + 1 × 65 = 90 °C: aguanta, pero quema al tocarlo.', { tol: 1, c: 'bb_regheat', h: 'Tj = Ta + P · Rθ, como en j10.' }),
      Q('¿Cuándo necesita disipador un 7805 en TO-220?', ['Cuando (Vent − Vsal) × I pasa de 1 W aproximadamente', 'Siempre', 'Nunca', 'Solo en verano'], 'Sin disipador, poco más de 1 W lo pone muy caliente.', { c: 'bb_regheat', h: 'Calcula la potencia y piensa en los 65 °C/W.' }),
      Q('Tu 7805 alimentado a 12 V se calienta mucho. ¿Qué es lo más eficaz?', ['Alimentarlo con menos tensión (7–8 V) o usar un conmutado', 'Ponerle un condensador más grande', 'Cambiarlo por otro 7805', 'Pedirle más corriente'], 'El calor sale de la tensión que sobra: si sobra menos, se calienta menos.', { c: 'bb_regheat', h: '¿De dónde sale el calor del lineal?' }),
      Q('¿Qué ventaja tiene un lineal frente a otras soluciones?', ['Es sencillo y su salida es muy limpia, sin ruido de conmutación', 'Rinde más del 90 %', 'Puede subir la tensión', 'No necesita margen'], 'Por eso se usa con poca corriente, poca diferencia de tensión o circuitos sensibles al ruido.', { c: 'bb_linreg', h: 'Piensa en lo que hace por dentro: no conmuta nada.' }),
      RES('Pierde <b>P = (Vent − Vsal) · I</b> en calor.', 'Rendimiento = <b>Vsal / Vent</b>.', 'Más de ~1 W en un TO-220: disipador (Tj = Ta + P · Rθ).', 'Bueno con poca corriente o poca diferencia; salida limpia.')
    ]),
    L('o20', 'El regulador ajustable LM317', 'ic', ['bb_lm317', 'bb_lm317i', 'bb_linreg'], [
      Q('El LM317 mantiene siempre 1,25 V entre sus patas OUT y ADJ. Si pones una resistencia de 240 Ω entre ellas, ¿qué corriente crees que pasa por esa resistencia?', ['Unos 5,2 mA', '1,25 A', '240 mA', '0,3 mA'], 'Ley de Ohm: 1,25 / 240 ≈ 5,2 mA. Esa corriente fija es la clave de todo el LM317.', { predict: true, c: 'bb_lm317', h: 'Ley de Ohm con 1,25 V y 240 Ω.' }),
      I('El <b>LM317</b> es un regulador lineal ajustable con tres patas (de frente: <b>ADJ, OUT, IN</b>). Su truco: mantiene <b>1,25 V entre OUT y ADJ</b>. Con dos resistencias eliges la salida, de 1,25 V a unos 37 V.', { svg: '<svg viewBox="0 0 300 140" class="viz"><rect x="100" y="10" width="100" height="70" rx="4" fill="#1c1c1c"/><text x="150" y="50" text-anchor="middle" fill="#ddd" font-size="14">LM317</text><path d="M125 80v40M150 80v40M175 80v40" stroke="#9AA3B2" stroke-width="5" stroke-linecap="round"/><text x="125" y="135" text-anchor="middle" class="vizsm">ADJ</text><text x="150" y="135" text-anchor="middle" class="vizsm">OUT</text><text x="175" y="135" text-anchor="middle" class="vizsm">IN</text><path d="M125 100H150" stroke="var(--ok)" stroke-width="3"/><text x="118" y="112" text-anchor="end" class="vizsm" style="fill:var(--ok)">1,25 V</text></svg>' }),
      { t: 'explore', text: 'R1 va entre OUT y ADJ; R2, de ADJ a masa. Busca las tensiones y luego prueba el modo corriente.', viz: 'lm317', params: { mode: LS('Uso (0 tensión, 1 corriente para un LED)', 0, [0, 1]), R1: { label: 'R1 (OUT–ADJ)', val: 240, list: [3.6, 10, 62, 120, 240, 330], fmt: 'R' }, R2: { label: 'R2 (ADJ–masa)', val: 220, list: [220, 470, 720, 1000, 1500, 2200, 3300, 4700], fmt: 'R' }, Vin: SL('Entrada', 15, 5, 25, 0.5, 'V', 1), IL: LS('Corriente de carga', 0.1, [0.1, 0.5, 1], 'A', 1) },
        tasks: [
          { q: 'Vout', min: 4.95, max: 5.05, text: 'Saca 5 V', done: 'Con R1 = 240 Ω y R2 = 720 Ω: 1,25 × (1 + 3) = 5 V.', hint: 'R2 tres veces R1.' },
          { q: 'Vout', min: 8.9, max: 9.2, text: 'Ahora 9 V', done: 'R2 / R1 ≈ 6,2: por ejemplo 240 Ω y 1,5 kΩ dan 9,06 V.', hint: 'Prueba R1 = 240 Ω y R2 = 1,5 kΩ.' },
          { q: 'Iled', min: 340, max: 360, text: 'Pasa al modo corriente y da 350 mA a un LED de potencia', done: 'I = 1,25 / R: con 3,6 Ω, unos 347 mA.', hint: 'Modo 1 y la R más pequeña.' }
        ] },
      I('¿Por qué <b>Vsal = 1,25 · (1 + R2 / R1)</b>? Los 1,25 V sobre R1 fijan una corriente (con 240 Ω, 5,2 mA). Por la pata ADJ apenas sale corriente (unos 50 µA), así que esa misma corriente pasa por R2 y suma su caída: Vsal = 1,25 V + 5,2 mA × R2.'),
      { t: 'steps', text: 'LM317 con R1 = 240 Ω y R2 = 720 Ω, alimentado a 12 V. ¿Salida? ¿Hay margen?', steps: ['Corriente por R1: 1,25 / 240 = <b>5,2 mA</b>', 'Caída en R2: 5,2 mA × 720 Ω = <b>3,75 V</b>', 'Vsal = 1,25 + 3,75 = <b>5 V</b> (o 1,25 × (1 + 3))', 'Margen: necesita unos 2 V; 12 − 5 = 7 V, de sobra (pero ojo al calor, como en o2)'], result: '5 V, con margen.' },
      G('lm317'),
      Nm('LM317 con R1 = 240 Ω. ¿Qué R2 necesitas para 12 V? (en Ω)', 2064, 'Ω', 'R2 = 240 × (12 / 1,25 − 1) = 240 × 8,6 = 2064 Ω: 2 kΩ con algo en serie, o un potenciómetro.', { tol: 25, c: 'bb_lm317', h: 'Despeja: R2 = R1 · (Vsal / 1,25 − 1).' }),
      I('Detalles de la hoja de datos:\n· Necesita una <b>corriente mínima de carga</b> (unos mA): por eso R1 suele ser de 120 o 240 Ω, que ya la consume.\n· Margen de unos 2 V.\n· Disipa como cualquier lineal: (Vent − Vsal) · I. Con mucha diferencia, disipador.'),
      Nm('Un LM317 baja de 24 V a 12 V con 0,5 A. ¿Cuánto disipa, en W?', 6, 'W', '(24 − 12) × 0,5 = 6 W: necesita un buen disipador.', { tol: 0.05, c: 'bb_linreg', h: 'Igual que en o2: tensión que sobra por la corriente.' }),
      I('<b>Fuente de corriente</b> con una sola resistencia: R entre OUT y ADJ, y la carga detrás de ADJ. El LM317 mantiene 1,25 V en R, así que <b>I = 1,25 V / R</b>, sea cual sea la carga. Perfecta para LEDs de potencia, cuya tensión cambia con la temperatura.', { svg: '<svg viewBox="0 0 300 120" class="viz"><rect x="30" y="30" width="60" height="40" rx="5" fill="var(--ice-soft)" stroke="currentColor" stroke-width="2"/><text x="60" y="55" text-anchor="middle" class="vizsm" style="fill:currentColor">LM317</text><path d="M90 50H130M170 50H200M60 70V90H200V50M200 90" stroke="currentColor" stroke-width="2.2" fill="none"/><rect x="130" y="42" width="40" height="16" rx="8" fill="#E7D3A8" stroke="#C9B183"/><text x="150" y="35" text-anchor="middle" class="vizsm">R</text><path d="M200 90H250" stroke="currentColor" stroke-width="2.2"/><circle cx="262" cy="90" r="11" fill="#FF3B30" class="a-pulse"/><text x="150" y="112" text-anchor="middle" class="vizsm">I = 1,25 / R, con cualquier LED</text></svg>' }),
      Nm('¿Qué resistencia da 350 mA con un LM317 como fuente de corriente? (en Ω)', 3.57, 'Ω', '1,25 / 0,35 ≈ 3,57 Ω (3,6 Ω comercial).', { tol: 0.06, c: 'bb_lm317i', h: 'R = 1,25 / I, con I en amperios.' }),
      Nm('Esa resistencia, con 350 mA, ¿cuánta potencia disipa, en W?', 0.44, 'W', 'Siempre tiene 1,25 V: 1,25 × 0,35 ≈ 0,44 W. Pon una de 1 W.', { tol: 0.01, c: 'bb_lm317i', h: 'P = V · I, con los 1,25 V que siempre tiene.' }),
      G('lm317I'),
      Q('¿Por qué los LEDs de potencia se alimentan con corriente constante?', ['Su tensión cambia con la temperatura: con tensión fija, la corriente se dispararía al calentarse', 'Porque así brillan más', 'Porque no admiten tensión', 'Porque es más barato'], 'Al calentarse, la tensión del LED baja; con una fuente de tensión, la corriente subiría y lo calentaría aún más.', { c: 'bb_lm317i', h: 'Recuerda la curva del LED y lo sensible que es al calor.' }),
      RES('1,25 V entre OUT y ADJ.', 'Tensión: <b>Vsal = 1,25 · (1 + R2 / R1)</b>.', 'Corriente: <b>I = 1,25 / R</b>; la R disipa 1,25 · I.', 'Margen de ~2 V y el calor de cualquier lineal.')
    ]),
    PRJ('p8', 'Proyecto: fuente de 5 V', 'psu'),
    L('o3', 'Reguladores conmutados', 'ic', ['bb_smps_how', 'bb_smps_pick'], [
      Q('Un regulador de 12 V a 5 V que, en vez de quemar lo que sobra, conecta y desconecta la entrada muy deprisa… ¿qué rendimiento crees que puede tener?', ['Más del 85 %', 'Como un lineal, un 42 %', 'Exactamente el 50 %', 'Más del 100 %'], 'Un interruptor cerrado no tiene tensión y uno abierto no tiene corriente: en ninguno de los dos casos se calienta. Los conmutados rinden del 85 al 95 %.', { predict: true, c: 'bb_smps_how', h: 'P = V · I en un interruptor cerrado o abierto: ¿cuánto vale?' }),
      { t: 'explore', text: 'Un <b>buck</b> (reductor) a cámara lenta: el interruptor se abre y se cierra, y la bobina y el condensador se quedan con la media.', viz: 'buckSw', params: { Vin: SL('Entrada', 12, 5, 24, 0.5, 'V', 1), D: SL('Ciclo de trabajo D', 25, 5, 95, 1, '%', 0) },
        tasks: [
          { q: 'v5', min: 1, max: 1, text: 'Saca 5 V de la entrada que quieras', done: 'Vsal = D × Vent: de 12 V hace falta D ≈ 42 %.', hint: 'Con 12 V, D entre 41 y 42 %.' },
          { q: 'v33', min: 1, max: 1, text: 'Ahora, con 5 V de entrada, consigue 3,3 V', done: 'D = 3,3 / 5 = 66 %. El ciclo de trabajo de h20, convertido en tensión.', hint: 'Entrada a 5 V y D en torno al 66 %.' }
        ] },
      I('Piezas de un buck:\n· Un <b>interruptor</b> (un MOSFET) que se abre y se cierra decenas o cientos de miles de veces por segundo.\n· Una <b>bobina</b>: no deja que su corriente cambie de golpe (g9).\n· Un <b>diodo</b> Schottky (o un segundo MOSFET) que da camino a esa corriente con el interruptor abierto.\n· Un <b>condensador</b> que alisa la salida.'),
      I('La salida es la <b>media</b> de la onda cuadrada que deja pasar el interruptor (h20): <b>Vsal ≈ D × Vent</b>. Un circuito de control ajusta D sin parar para que la salida se quede fija aunque cambien la entrada o la carga.', { svg: '<svg viewBox="0 0 300 110" class="viz"><path d="M20 90V30H70V90H120V30H170V90H220V30H270V90" fill="none" stroke="var(--led)" stroke-width="2.5"/><path d="M20 65H280" stroke="var(--ok)" stroke-dasharray="6 4" stroke-width="2"/><text x="284" y="69" text-anchor="end" class="vizsm" style="fill:var(--ok)">media</text><text x="20" y="22" class="vizsm">Vent</text><text x="20" y="106" class="vizsm">D = tiempo cerrado / periodo</text></svg>' }),
      { t: 'steps', text: 'Un buck con un rendimiento del 90 % convierte 12 V en 5 V para una carga de 2 A. ¿Qué pide a la entrada? ¿Y un lineal?', steps: ['Potencia de salida: 5 V × 2 A = <b>10 W</b>', 'Entrada del buck: 10 / 0,9 = <b>11,1 W</b> → 11,1 / 12 = <b>0,93 A</b>', 'Pierde en calor solo 11,1 − 10 = <b>1,1 W</b>', 'Un lineal: 2 A también a la entrada → 24 W, y <b>14 W</b> de calor'], result: 'El buck toma menos corriente de la que da y pierde unas trece veces menos.' },
      Nm('Buck al 90 % que entrega 5 V y 2 A. ¿Potencia de entrada, en W?', 11.1, 'W', '10 / 0,9 ≈ 11,1 W.', { tol: 0.15, c: 'bb_smps_how', h: 'Potencia de salida dividida entre el rendimiento.' }),
      G('smpsPin'),
      I('Tres familias:\n· <b>Buck</b>: baja (12 V → 5 V).\n· <b>Boost</b>: sube (una celda de 3,7 V → 5 V, como en una batería externa).\n· <b>Buck-boost</b>: sube o baja, para entradas que cruzan la salida (una Li-ion de 3,0 a 4,2 V → 3,3 V).', { svg: '<svg viewBox="0 0 300 100" class="viz">' + [['Buck', '12 → 5 V'], ['Boost', '3,7 → 5 V'], ['Buck-boost', '3–4,2 → 3,3 V']].map(([a, b], i) => `<rect x="${10 + i * 97}" y="25" width="88" height="50" rx="8" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="${54 + i * 97}" y="47" text-anchor="middle" class="vizlab" style="font-size:11px">${a}</text><text x="${54 + i * 97}" y="63" text-anchor="middle" class="vizsm" style="fill:currentColor">${b}</text>`).join('') + '</svg>' }),
      TU('Elige una fuente cuya tensión cruce la que necesitas, para que haga falta un buck-boost.', 'buckBoost', { Va: SL('Fuente: tensión llena', 12, 0.5, 15, 0.1, 'V', 1), Vb: SL('Fuente: tensión vacía', 10, 0.5, 15, 0.1, 'V', 1), Vo: LS('Necesitas', 5, [3.3, 5, 12], 'V', 1) }, { q: 'type', min: 2, max: 2, text: 'Objetivo: que haga falta un buck-boost', hint: 'La tensión llena por encima de lo que necesitas y la vacía por debajo.' }, 'Por ejemplo, una Li-ion (4,2 a 3,0 V) para 3,3 V.', { c: 'bb_smps_pick', h: 'La franja azul tiene que atravesar la raya naranja.' }),
      { t: 'match', q: 'Une cada caso con el regulador más adecuado.', pairs: [['12 V → 5 V con 2 A', 'Buck'], ['Una celda de 3,7 V → 5 V', 'Boost'], ['9 V → 5 V con 20 mA, sin ruido', 'Lineal'], ['Celda de 3–4,2 V → 3,3 V', 'Buck-boost o LDO']], c: 'bb_smps_pick', h: '¿Hay que subir, bajar o las dos cosas? ¿Mucha o poca corriente?' },
      Q('¿Cuál es la pega principal de los conmutados?', ['El ruido eléctrico de la conmutación', 'Que rinden poco', 'Que solo funcionan con alterna', 'Que no existen pequeños'], 'Por eso a veces se pone un LDO detrás para los circuitos sensibles.', { c: 'bb_smps_pick', h: 'Piensa en lo que hace el interruptor cientos de miles de veces por segundo.' }),
      Q('Un buck de 12 V a 5 V entrega 2 A. ¿Qué corriente toma de la entrada?', ['Menos de 1 A', '2 A', 'Más de 2 A', 'Ninguna'], 'La potencia se conserva casi entera: unos 11 W / 12 V ≈ 0,93 A.', { c: 'bb_smps_how', h: 'Iguala potencias (con un poco de pérdida), no corrientes.' }),
      RES('Conmutar y promediar: <b>Vsal ≈ D × Vent</b> en un buck.', 'Rendimiento del 85–95 %: <b>Pent = Psal / η</b>.', '<b>Buck</b> baja, <b>boost</b> sube, <b>buck-boost</b> las dos.', 'Pega: ruido; detrás, un LDO si hace falta.')
    ]),
    L('o4', 'Protección', 'bat', ['bb_inprot', 'bb_revpol'], [
      Q('Conectas al revés el jack de alimentación de tu circuito. Sin protección, ¿qué crees que puede pasar?', ['Se pueden romper chips y condensadores electrolíticos', 'Nada: a la electricidad le da igual el sentido', 'Funciona igual, al revés', 'Solo se apaga'], 'Muchos chips y los electrolíticos se rompen con tensión invertida. Una buena entrada de alimentación lleva varias protecciones.', { predict: true, c: 'bb_inprot', h: 'Recuerda qué le pasa a un electrolítico al revés (g3).' }),
      I('Una entrada de alimentación protegida, desde el conector:\n<b>fusible → protección de polaridad → TVS → condensador</b> → regulador.', { svg: '<svg viewBox="0 0 300 120" class="viz"><path d="M10 50H290" stroke="var(--led)" stroke-width="3" class="a-flow"/>' + ['Fusible', 'MOSFET P', 'TVS', 'Cond.'].map((t, i) => `<rect x="${18 + i * 70}" y="35" width="58" height="30" rx="6" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="${47 + i * 70}" y="54" text-anchor="middle" class="vizsm" style="fill:currentColor">${t}</text>`).join('') + '<text x="10" y="92" class="vizsm">conector</text><text x="290" y="92" text-anchor="end" class="vizsm">regulador</text><text x="150" y="112" text-anchor="middle" class="vizsm">corriente · polaridad · picos · caídas</text></svg>' }),
      I('<b>Fusible</b>: se funde si pasa demasiada corriente (un cortocircuito) y hay que cambiarlo. <b>PTC</b> (fusible rearmable): al calentarse sube mucho su resistencia y se recupera al enfriarse; cómodo, pero más lento.'),
      Q('¿Qué ventaja tiene un PTC frente a un fusible?', ['Se rearma solo al enfriarse', 'Es más rápido', 'No se calienta', 'Sube la tensión'], 'Útil en USB y en aparatos que no quieres abrir.', { c: 'bb_inprot', h: 'Piensa en qué pasa después de que salte.' }),
      { t: 'explore', text: 'Tres formas de proteger contra la polaridad invertida, con 12 V. Mira cuánto se comen.', viz: 'polProt', params: { tipo: LS('Protección (0 diodo, 1 Schottky, 2 MOSFET P)', 0, [0, 1, 2]), I: LS('Corriente', 0.5, [0.1, 0.5, 1, 2], 'A', 1) },
        tasks: [
          { q: 'P', min: 1, max: 100, text: 'Con el diodo normal, sube la corriente hasta que disipe más de 1 W', done: 'La caída del diodo por la corriente es calor: a 2 A, más de 1,5 W.', hint: 'Diodo normal y 2 A.' },
          { q: 'lowDrop', min: 1, max: 1, text: 'A 2 A, consigue que la protección se coma menos de 50 mV', done: 'El MOSFET P solo cae I · Rds(on): 2 A × 20 mΩ = 40 mV.', hint: 'Prueba la tercera opción.' }
        ] },
      I('<b>Diodo en serie</b>: sencillo, pero cae 0,7–0,9 V. <b>Schottky</b>: 0,3–0,5 V. <b>MOSFET P</b> (j9) en la línea positiva: su diodo de cuerpo conduce al principio, la puerta (a masa) queda negativa respecto a la fuente y el canal se abre: solo cae I · Rds(on). Si se conecta al revés, no conduce.'),
      Q('Proteger la polaridad con un diodo normal en serie cuesta…', ['Unos 0,7 V de caída (y su calor)', 'Nada', 'La mitad de la tensión', 'Toda la corriente'], 'Con un MOSFET P, mucho menos.', { c: 'bb_revpol', h: 'Recuerda la caída de un diodo de silicio.' }),
      Nm('Un Schottky de protección cae 0,4 V con 2 A. ¿Cuánto disipa, en W?', 0.8, 'W', '0,4 × 2 = 0,8 W.', { tol: 0.01, c: 'bb_revpol', h: 'P = caída × corriente.' }),
      I('<b>TVS</b> (i9): un diodo que no hace nada hasta que llega un pico por encima de su tensión, y entonces lo recorta. Va detrás de la protección de polaridad. Un <b>condensador grande</b> de entrada aguanta las caídas cortas cuando se enchufa algo.'),
      { t: 'steps', text: 'Diseña la entrada de una placa de 12 V y 2 A como máximo.', steps: ['<b>Fusible</b> lento de 3 A: aguanta el consumo normal y el pico al enchufar', '<b>MOSFET P</b> de 20 mΩ para la polaridad: pierde 2² × 0,02 = <b>0,08 W</b> (un diodo perdería más de 1,5 W)', '<b>TVS</b> de 15 V de trabajo: no actúa a 12 V y recorta los picos', '<b>Condensador</b> de 100 µF y 25 V o más (con margen sobre 12 V)'], result: 'Fusible de 3 A → MOSFET P → TVS de 15 V → 100 µF/25 V.' },
      { t: 'order', q: 'Ordena las protecciones desde el conector hacia el circuito.', items: ['Conector de alimentación', 'Fusible o PTC', 'Protección de polaridad', 'TVS', 'Condensador de entrada', 'Regulador'], e: 'Primero limitar la corriente, luego bloquear la polaridad, luego recortar picos y alisar.', c: 'bb_inprot', h: 'Lo que corta la corriente va lo primero.' },
      { t: 'match', q: 'Une cada pieza con lo que evita.', pairs: [['Fusible', 'Sobrecorriente por un cortocircuito'], ['MOSFET P en serie', 'Polaridad invertida'], ['TVS', 'Picos de tensión'], ['Condensador de entrada', 'Caídas cortas de tensión']], c: 'bb_inprot', h: 'Corriente, polaridad, picos y caídas: una pieza para cada peligro.' },
      RES('Fusible/PTC → polaridad → TVS → condensador.', 'Diodo: 0,7 V de caída · Schottky: 0,3–0,5 V · MOSFET P: I · Rds(on).', 'La caída por la corriente es calor.')
    ]),
    PRJ('p14', 'Proyecto: cargador USB de Li-ion con protección', 'liCharger')
  ] });
})();
