/* Voltio · curso base, módulo 15: Lógica digital
   Orden: l1 (binario) → l2 (hexadecimal) → l3 (puertas) → s6a, s6b → l4 (Boole) → l5 (combinacional)
   → k9 (chips lógicos) → l6 (biestables) → slatch → l7 (contadores y rebotes) → p6.
   Usa: a1 (potencias), d1/d2 (serie y paralelo de interruptores), b20, j4 (Darlington), k1–k4, k14 (Schmitt), k20 (pull-up).
   Aún NO: microcontroladores (llegan en m11b). */
(() => {
  const { num, st, ledBulb } = Widgets.H;
  const RES = (...k) => I('<b>Resumen</b>\n· ' + k.join('\n· '));
  const LS = (label, val, list, unit = '', dec = 0) => ({ label, val, list, unit, dec });
  const SL = (label, val, min, max, step, unit = '', dec = 0) => ({ label, val, min, max, step, unit, dec });
  const B01 = (label, val = 0) => LS(label, val, [0, 1]);
  const GB = { AND: 'M-20 -20h18a20 20 0 0 1 0 40h-18z', OR: 'M-22 -20q10 20 0 40q30 0 42 -20q-12 -20 -42 -20z', XOR: 'M-18 -20q10 20 0 40q30 0 42 -20q-12 -20 -42 -20zM-26 -20q10 20 0 40' };
  // Puerta dibujada en (x, y): AND, OR, XOR, con burbuja de salida (inv) y burbujas de entrada (inIn)
  const GATE = (x, y, g, inv = false, s = 1, inIn = false) => `<g transform="translate(${x} ${y}) scale(${s})" style="color:var(--ink)"><path d="${GB[g]}" ${st}/><path d="M-40 -10h${g === 'XOR' ? 16 : 20}M-40 10h${g === 'XOR' ? 16 : 20}M${inv ? 28 : 20} 0h16" ${st}/>${inv ? '<circle cx="24" cy="0" r="4" fill="none" stroke="currentColor" stroke-width="2.2"/>' : ''}${inIn ? '<circle cx="-24" cy="-10" r="3.5" fill="var(--surface)" stroke="currentColor" stroke-width="2"/><circle cx="-24" cy="10" r="3.5" fill="var(--surface)" stroke="currentColor" stroke-width="2"/>' : ''}</g>`;
  const NOTG = (x, y, s = 1) => `<g transform="translate(${x} ${y}) scale(${s})" style="color:var(--ink)"><path d="M-14 -14v28l24 -14z M-30 0h16M18 0h14" ${st}/><circle cx="14" cy="0" r="4" fill="none" stroke="currentColor" stroke-width="2.2"/></g>`;
  const SW = (x, y, on) => `<circle cx="${x}" cy="${y}" r="3" fill="currentColor"/><circle cx="${x + 40}" cy="${y}" r="3" fill="currentColor"/><path d="M${x} ${y}L${x + 38} ${on ? y : y - 15}" ${st} stroke="${on ? 'var(--ok)' : 'currentColor'}"/>`;
  const SWV = (x, y, on) => `<circle cx="${x}" cy="${y}" r="3" fill="currentColor"/><circle cx="${x}" cy="${y + 40}" r="3" fill="currentColor"/><path d="M${x} ${y}L${on ? x : x + 15} ${y + 38}" ${st} stroke="${on ? 'var(--ok)' : 'currentColor'}"/>`;
  const LED = (x, y, on, s = 0.75) => `<g transform="translate(${x} ${y}) scale(${s})">${ledBulb(on ? 1 : 0)}</g>`;
  const BIT = (x, y, b, w = 26) => `<rect x="${x}" y="${y}" width="${w}" height="30" rx="5" fill="${b ? 'var(--led)' : 'var(--line)'}"/><text x="${x + w / 2}" y="${y + 20}" text-anchor="middle" class="vizlab" style="fill:${b ? '#14213D' : 'currentColor'}">${b}</text>`;

  /* ===================== VISUALIZACIONES ===================== */
  const GN = ['AND', 'OR', 'NOT', 'NAND', 'NOR', 'XOR'], GF = [(a, b) => a & b, (a, b) => a | b, a => 1 - a, (a, b) => 1 - (a & b), (a, b) => 1 - (a | b), (a, b) => a ^ b];
  let latchQ = 0; const latchHist = [];
  Object.assign(Widgets.VIZ, {
    hexNibble: {
      calc: p => ({ val: p.hi * 16 + p.lo }),
      svg: (p, o) => {
        const b = o.val.toString(2).padStart(8, '0').split('').map(Number), H = '0123456789ABCDEF';
        return `<svg viewBox="0 0 300 175" class="viz">${b.map((x, i) => BIT(14 + i * 32 + (i > 3 ? 12 : 0), 50, x)).join('')}
          ${b.map((x, i) => `<text x="${27 + i * 32 + (i > 3 ? 12 : 0)}" y="96" text-anchor="middle" class="vizsm">${2 ** (7 - i)}</text>`).join('')}
          <path d="M14 40h122M162 40h122" stroke="var(--ice)" stroke-width="3"/><text x="75" y="30" text-anchor="middle" class="vizbig" style="font-size:20px;fill:var(--ice)">${H[p.hi]}</text><text x="223" y="30" text-anchor="middle" class="vizbig" style="font-size:20px;fill:var(--ice)">${H[p.lo]}</text>
          <text x="150" y="130" text-anchor="middle" class="vizbig" style="font-size:22px">0x${H[p.hi]}${H[p.lo]} = ${o.val}</text>
          <text x="150" y="160" text-anchor="middle" class="vizsm">${p.hi} × 16 + ${p.lo} = ${o.val} · cada cifra son 4 bits</text></svg>`;
      }
    },
    gateSw: {
      calc: p => { const out = GF[p.g](p.A, p.B); return { out, andOn: p.g === 0 && out ? 1 : 0, orOne: p.g === 1 && out && p.A + p.B === 1 ? 1 : 0, xorOff: p.g === 5 && p.A && p.B ? 1 : 0, notOff: p.g === 2 && p.A ? 1 : 0 }; },
      svg: (p, o) => {
        const fl = o.out ? 'class="flow" style="animation-duration:.9s"' : 'style="display:none"';
        let c = '';
        if (p.g === 0) c = `<path d="M30 40H60M100 40H130M170 40H200M240 40H260V68M260 102V130H30V40" ${st}/>${SW(60, 40, p.A)}${SW(130, 40, p.B)}<rect x="200" y="32" width="40" height="16" rx="8" fill="#E7D3A8" stroke="#C9B183"/>${LED(260, 85, o.out)}<path d="M30 40H260V130H30Z" ${fl} fill="none"/><rect x="22" y="70" width="16" height="30" rx="3" fill="var(--board)"/><rect x="22" y="70" width="16" height="7" rx="2" fill="#E5484D"/><text x="80" y="66" text-anchor="middle" class="vizsm">A</text><text x="150" y="66" text-anchor="middle" class="vizsm">B</text><text x="150" y="152" text-anchor="middle" class="vizsm">interruptores en serie</text>`;
        else if (p.g === 1) c = `<path d="M30 40H90M130 40H160M70 40V85H90M130 85H160V40M160 40H200M240 40H260V68M260 102V130H30V40" ${st}/>${SW(90, 40, p.A)}${SW(90, 85, p.B)}<rect x="200" y="32" width="40" height="16" rx="8" fill="#E7D3A8" stroke="#C9B183"/>${LED(260, 85, o.out)}<path d="M30 40H260V130H30Z" ${fl} fill="none"/><rect x="22" y="70" width="16" height="30" rx="3" fill="var(--board)"/><rect x="22" y="70" width="16" height="7" rx="2" fill="#E5484D"/><text x="110" y="60" text-anchor="middle" class="vizsm">A</text><text x="110" y="105" text-anchor="middle" class="vizsm">B</text><text x="150" y="152" text-anchor="middle" class="vizsm">interruptores en paralelo</text>`;
        else if (p.g === 2) c = `<path d="M30 40H90M130 40H260V68M260 102V130H30V40M180 40V60M180 100V130" ${st}/><rect x="90" y="32" width="40" height="16" rx="8" fill="#E7D3A8" stroke="#C9B183"/>${SWV(180, 60, p.A)}${LED(260, 85, o.out)}<path d="M30 40H260V130H30Z" ${fl} fill="none"/><rect x="22" y="70" width="16" height="30" rx="3" fill="var(--board)"/><rect x="22" y="70" width="16" height="7" rx="2" fill="#E5484D"/><text x="196" y="84" class="vizsm">A</text><text x="150" y="152" text-anchor="middle" class="vizsm">A cerrado puentea el LED: lo apaga</text>`;
        else c = `${GATE(150, 75, ['', '', '', 'AND', 'OR', 'XOR'][p.g], p.g === 3 || p.g === 4, 1.5)}<path d="M40 60H90M40 90H90M204 75H230" ${st}/><text x="30" y="64" text-anchor="end" class="vizlab">${p.A}</text><text x="30" y="94" text-anchor="end" class="vizlab">${p.B}</text>${LED(255, 75, o.out)}<text x="150" y="152" text-anchor="middle" class="vizsm">por dentro, transistores que hacen de interruptores</text>`;
        return `<svg viewBox="0 0 300 175" class="viz">${c}<text x="10" y="170" class="vizlab">${GN[p.g]} · A = ${p.A}${p.g === 2 ? '' : ', B = ' + p.B} → salida ${o.out}</text></svg>`;
      }
    },
    deMorgan: {
      calc: p => { const o1 = p.ley ? 1 - (p.A | p.B) : 1 - (p.A & p.B), o2 = p.ley ? (1 - p.A) & (1 - p.B) : (1 - p.A) | (1 - p.B); return { o1, o2, same: o1 === o2 ? 1 : 0, both1: p.A && p.B && !p.ley ? 1 : 0, mix: p.A !== p.B && !p.ley ? 1 : 0, nor00: p.ley && !p.A && !p.B ? 1 : 0 }; },
      svg: (p, o) => `<svg viewBox="0 0 300 175" class="viz">${GATE(80, 70, p.ley ? 'OR' : 'AND', true, 1.2)}${GATE(220, 70, p.ley ? 'AND' : 'OR', false, 1.2, true)}
        ${LED(80, 125, o.o1, 0.6)}${LED(220, 125, o.o2, 0.6)}<path d="M128 70V100H80V108M268 70V100H220V108" ${st} stroke-width="1.6"/>
        <text x="80" y="25" text-anchor="middle" class="vizsm">${p.ley ? 'NOR' : 'NAND'}</text><text x="220" y="25" text-anchor="middle" class="vizsm">${p.ley ? 'AND con entradas negadas' : 'OR con entradas negadas'}</text>
        <text x="150" y="50" text-anchor="middle" class="vizlab">A = ${p.A}</text><text x="150" y="70" text-anchor="middle" class="vizlab">B = ${p.B}</text>
        <text x="150" y="168" text-anchor="middle" class="vizlab">${p.ley ? '(A + B)‾ = Ā · B̄' : '(A · B)‾ = Ā + B̄'} · salidas ${o.o1} y ${o.o2}</text></svg>`
    },
    mux4: {
      calc: p => { const S = p.S1 * 2 + p.S0, Y = (p.D >> S) & 1; return { S, Y, y1d3: S === 3 && Y ? 1 : 0 }; },
      svg: (p, o) => {
        const d = [0, 1, 2, 3].map(k => (p.D >> k) & 1);
        return `<svg viewBox="0 0 300 180" class="viz"><path d="M110 20L190 45V125L110 150Z" fill="var(--ice-soft)" stroke="currentColor" stroke-width="2"/>
          ${d.map((b, k) => `<path d="M75 ${40 + k * 30}H110" stroke="${k === o.S ? 'var(--led)' : 'currentColor'}" stroke-width="${k === o.S ? 3.5 : 2}"/><text x="20" y="${44 + k * 30}" class="vizlab">D${k} = ${b}</text>`).join('')}
          <path d="M120 ${40 + o.S * 30}L180 85" stroke="var(--led)" stroke-width="3" stroke-dasharray="4 3"/><path d="M190 85H240" stroke="var(--led)" stroke-width="3"/>${LED(258, 85, o.Y, 0.6)}
          <path d="M140 140V165M165 133V165" ${st}/><text x="140" y="178" text-anchor="middle" class="vizsm">S1 = ${p.S1}</text><text x="185" y="178" text-anchor="middle" class="vizsm">S0 = ${p.S0}</text>
          <text x="150" y="90" text-anchor="middle" class="vizsm">MUX</text><text x="240" y="70" class="vizlab">Y = ${o.Y}</text></svg>`;
      }
    },
    latchSR: {
      calc: p => { if (!p.Sn && p.Rn) latchQ = 1; else if (p.Sn && !p.Rn) latchQ = 0; const bad = !p.Sn && !p.Rn, Q = bad ? 1 : latchQ, Qn = bad ? 1 : 1 - latchQ; const key = `${p.Sn}${p.Rn}${Q}`; if (latchHist[latchHist.length - 1] !== key) { latchHist.push(key); if (latchHist.length > 8) latchHist.shift(); } return { Q, Qn, bad: bad ? 1 : 0, memo1: p.Sn && p.Rn && Q ? 1 : 0, Sn: p.Sn, Rn: p.Rn }; },
      svg: (p, o) => `<svg viewBox="0 0 300 185" class="viz">${GATE(120, 45, 'AND', true, 1)}${GATE(120, 115, 'AND', true, 1)}
        <path d="M30 35H80M30 125H80M156 45H230M156 115H230M190 45V70L80 90V105M190 115V90L80 70V55" ${st} stroke-width="1.8"/>
        <text x="28" y="30" text-anchor="end" class="vizlab">S̄</text><text x="28" y="139" text-anchor="end" class="vizlab">R̄</text><text x="34" y="30" class="vizsm">${p.Sn}</text><text x="34" y="140" class="vizsm">${p.Rn}</text>
        ${LED(250, 45, o.Q, 0.6)}<text x="250" y="78" text-anchor="middle" class="vizlab">Q = ${o.Q}</text><text x="250" y="140" text-anchor="middle" class="vizsm">Q̄ = ${o.Qn}</text>
        <text x="10" y="165" class="vizsm">últimos estados (S̄ R̄ → Q): ${latchHist.map(h => h[0] + h[1] + '→' + h[2]).join(' · ')}</text>
        <text x="10" y="181" class="vizlab">${o.bad ? '¡Las dos a 0! Q y Q̄ a 1: estado prohibido' : p.Sn && p.Rn ? 'Nada pulsado: Q recuerda ' + o.Q : !p.Sn ? 'S̄ pulsado: pone Q a 1' : 'R̄ pulsado: pone Q a 0'}</text></svg>`
    },
    counter: {
      calc: p => { const raw = p.n * (1 + p.reb), count = (p.filtro ? p.n : raw) % 16; return { count, bad: p.reb > 0 && !p.filtro && count !== p.n % 16 ? 1 : 0, fixed: p.reb > 0 && p.filtro && p.n > 0 ? 1 : 0 }; },
      svg: (p, o) => {
        const b = o.count.toString(2).padStart(4, '0').split('').map(Number);
        let w = 'M15 70'; const n = Math.min(p.n, 6); for (let k = 0; k < n; k++) { const x = 25 + k * 44; w += `H${x}`; if (!p.filtro) for (let r = 0; r < p.reb; r++) w += `V40H${x + 3 + r * 4}V70H${x + 5 + r * 4}`; w += `V40H${x + 26}V70`; } w += 'H285';
        return `<svg viewBox="0 0 300 180" class="viz"><text x="15" y="28" class="vizsm">${p.filtro ? 'pulsos tras el RC y el Schmitt: limpios' : 'pulsos tal como salen del pulsador'}</text><path d="${w}" fill="none" stroke="var(--ice)" stroke-width="2"/>
          ${b.map((x, i) => `${LED(60 + i * 55, 112, x, 0.55)}<text x="${60 + i * 55}" y="142" text-anchor="middle" class="vizsm">Q${3 - i} (${2 ** (3 - i)})</text>`).join('')}
          <text x="10" y="172" class="vizlab">Pulsaciones ${p.n} · el contador marca ${b.join('')} = ${o.count}${o.count !== p.n % 16 ? ' ✗' : ''}</text></svg>`;
      }
    }
  });

  /* ===================== GENERADORES (con pista) ===================== */
  const { pick, ri, MC, N } = Gen.helpers;
  Gen.add('binToDec', () => ({ ...Gen.make('bin2dec'), c: 'bb_binread', h: 'Escribe los pesos 128, 64, 32, 16, 8, 4, 2, 1 encima y suma los de los unos.' }), 'bb_binread');
  Gen.add('decToBin', () => ({ ...Gen.make('dec2bin'), c: 'bb_binread', h: 'Ve restando el peso más grande que quepa: 16, 8, 4, 2, 1.' }), 'bb_binread');
  Gen.add('hexRead', () => ({ ...Gen.make('hex'), c: 'bb_hex', h: 'La cifra de la izquierda vale 16 veces su valor; A = 10 … F = 15.' }), 'bb_hex');
  Gen.add('nBitsVals', () => { if (Math.random() < 0.5) { const n = pick([3, 4, 5, 6, 7, 10, 12, 16]); return { ...N(`¿Cuántos valores distintos caben en ${n} bits?`, 2 ** n, '', `2 elevado a ${n} = ${2 ** n} (del 0 al ${2 ** n - 1}).`), h: 'Cada bit más duplica los valores: 2 elevado al número de bits.' }; } const v = ri(5, 1000), n = Math.ceil(Math.log2(v + 1)); return { ...N(`¿Cuántos bits necesitas como mínimo para contar del 0 al ${v}?`, n, 'bits', `Hacen falta ${v + 1} valores; 2 elevado a ${n} = ${2 ** n} es la primera potencia de 2 que llega.`), h: 'Busca la primera potencia de 2 que llegue al número de valores (no olvides contar el 0).' }; }, 'bb_nbits');

  /* ===================== CONCEPTOS NUEVOS ===================== */
  const pHex = (hi, lo) => ({ hi: SL('Cifra alta (4 bits de la izquierda)', hi, 0, 15, 1), lo: SL('Cifra baja (4 bits de la derecha)', lo, 0, 15, 1) });
  Object.assign(CONCEPTS, {
    bb_binread: { name: 'Leer y escribir en binario', alts: [
      { title: 'Pesos', text: 'Escribe encima de cada bit su peso, de derecha a izquierda: 1, 2, 4, 8, 16, 32, 64, 128. Para leer un binario, suma los pesos de los unos: 1010 0101 = 128 + 32 + 4 + 1 = 165. Para escribir un número, ve restando el peso más grande que quepa: 100 = 64 + 32 + 4 → 0110 0100. Mueve las cifras y mira los pesos.', tune: { viz: 'hexNibble', params: pHex(6, 4) }, q: mcq('¿Cuánto vale 0100 1001?', ['73', '37', '145', '9'], '64 + 8 + 1 = 73.') },
      { title: 'Mitades', text: 'Para pasar de decimal a binario sin tabla: divide entre 2 y apunta el resto, una y otra vez; los restos, leídos de abajo arriba, son los bits. 13 → 6 resto 1 → 3 resto 0 → 1 resto 1 → 0 resto 1: <b>1101</b>. Comprueba sumando pesos: 8 + 4 + 1 = 13.', q: mcq('¿Cómo se escribe 22 en binario?', ['10110', '01101', '10011', '11010'], '16 + 4 + 2 = 22.') }
    ] },
    bb_logicfam: { name: 'Familias lógicas y su alimentación', alts: [
      { title: 'Cada familia, su rango', text: 'La familia <b>74HC</b> trabaja de 2 a 6 V; la <b>CD4000</b>, de 3 a 15 V (18 V como máximo absoluto). Un 74HC00 a 9 V se puede dañar; un CD4011 (también cuatro NAND) a 9 V va bien. Mira siempre las condiciones de trabajo en la hoja de datos.', svg: '<svg viewBox="0 0 300 110" class="viz"><path d="M20 80H280" stroke="var(--line)" stroke-width="2"/><rect x="55" y="24" width="69" height="14" rx="4" fill="var(--ice)"/><rect x="72" y="58" width="208" height="14" rx="4" fill="var(--led)"/><text x="55" y="18" class="vizsm">74HC: 2–6 V</text><text x="72" y="52" class="vizsm">CD4000: 3–15 V</text><text x="20" y="96" class="vizsm">0 V</text><text x="276" y="96" text-anchor="end" class="vizsm">15 V</text></svg>', q: mcq('Tu circuito va a 12 V y necesitas cuatro NAND. ¿Qué chip?', ['Un CD4011 (CD4000)', 'Un 74HC00', 'Cualquiera', 'Ninguno existe'], 'La CD4000 admite hasta 15 V.') },
      { title: 'Lo que puede dar una salida', text: 'Una salida lógica da unos pocos miliamperios: basta para un LED con su resistencia, no para un relé o un motor. Para cargas mayores, un transistor o un <b>ULN2003</b> (siete Darlington en un chip).', q: mcq('Una salida de un 74HC tiene que activar un relé de 70 mA. ¿Qué pones?', ['Un transistor o un ULN2003', 'Nada, lo conectas directo', 'Una resistencia de 10 kΩ', 'Un condensador'], 'La salida solo da la orden.') }
    ] },
    bb_counter: { name: 'Contadores y divisores de frecuencia', alts: [
      { title: 'Cada biestable divide por dos', text: 'Encadenando biestables, cada uno cambia la mitad de veces que el anterior: es un contador binario y, a la vez, un divisor de frecuencia. Con n biestables cuentas de 0 a 2ⁿ − 1, y la última salida va a f / 2ⁿ. Mueve las pulsaciones y mira los cuatro LEDs.', tune: { viz: 'counter', params: { n: SL('Pulsaciones', 6, 0, 15, 1), reb: { val: 0, fixed: true }, filtro: { val: 0, fixed: true } } }, q: mcq('Un reloj de 800 Hz entra en tres biestables encadenados. ¿Frecuencia de la última salida?', ['100 Hz', '266 Hz', '2400 Hz', '400 Hz'], '800 / 2³ = 100 Hz.') },
      { title: 'Leer lo que cuenta', text: 'Las salidas Q3 Q2 Q1 Q0 son un número binario: Q0 vale 1, Q1 vale 2, Q2 vale 4 y Q3 vale 8. Si se encienden Q3 y Q0, ha contado 9. Al pasar de 15 vuelve a 0, como un byte que da la vuelta.', q: mcq('Un contador de 4 bits marca 1011. ¿Cuántos pulsos ha contado (si no ha dado la vuelta)?', ['11', '1011', '4', '13'], '8 + 2 + 1 = 11.') }
    ] }
  });

  /* ===================== LECCIONES ===================== */
  UNITS.push({ id: 'm11', title: 'Lógica digital', desc: 'Binario, hexadecimal, puertas, Boole, chips lógicos, biestables y contadores.', nodes: [
    L('l1', 'Sistema binario', 'bin', ['bb_binread', 'bb_nbits'], [
      Q('Tienes dos interruptores, cada uno encendido o apagado. ¿Cuántas combinaciones distintas crees que puedes hacer?', ['4', '2', '3', '8'], 'Apagado-apagado, apagado-encendido, encendido-apagado y encendido-encendido: 4. Con tres serían 8. Así cuentan los circuitos digitales.', { predict: true, c: 'bb_nbits', h: 'Escribe todas las parejas posibles.' }),
      I('En electrónica <b>digital</b> solo importan dos estados: <b>0</b> (tensión baja, cerca de 0 V) y <b>1</b> (tensión alta, cerca de la alimentación, por ejemplo 5 V). Cada uno de esos dígitos es un <b>bit</b>. Ocho bits forman un <b>byte</b>.', { svg: `<svg viewBox="0 0 300 120" class="viz">${LED(70, 50, 0)}${LED(220, 50, 1)}<text x="70" y="95" text-anchor="middle" class="vizbig" style="font-size:20px">0</text><text x="220" y="95" text-anchor="middle" class="vizbig" style="font-size:20px">1</text><text x="70" y="114" text-anchor="middle" class="vizsm">0 V</text><text x="220" y="114" text-anchor="middle" class="vizsm">5 V</text></svg>`, more: '¿Por qué solo dos estados? Porque distinguir «casi nada» de «casi todo» es muy fácil y muy robusto: un poco de ruido no cambia un 0 por un 1. Con diez niveles distintos, el ruido confundiría unos con otros.' }),
      { t: 'bits', q: 'Juega: enciende bits y mira el número que forman.', n: 8, live: true, target: -1, free: true, c: 'bb_binread', h: 'Empieza por el de la derecha y ve subiendo: cada uno vale el doble que el anterior.' },
      I('Cada posición vale el <b>doble</b> que la de su derecha: 1, 2, 4, 8, 16, 32, 64, 128 (son potencias de 2, como en a1 lo eran de 10). El número es la <b>suma de los pesos</b> de los bits que valen 1.', { svg: `<svg viewBox="0 0 300 110" class="viz">${[0, 0, 0, 0, 1, 1, 0, 1].map((b, i) => BIT(14 + i * 35, 30, b, 28) + `<text x="${28 + i * 35}" y="80" text-anchor="middle" class="vizsm">${2 ** (7 - i)}</text>`).join('')}<text x="150" y="104" text-anchor="middle" class="vizlab">0000 1101 = 8 + 4 + 1 = 13</text></svg>` }),
      { t: 'steps', text: '¿Cuánto vale 1101 en decimal? ¿Y cómo se escribe el 100?', steps: ['Pesos de 1101, de derecha a izquierda: 1, 2, 4, 8', 'Suma los pesos de los unos: 8 + 4 + 0 + 1 = <b>13</b>', 'Para 100: el peso más grande que cabe es 64 → quedan 36; cabe 32 → quedan 4; cabe 4 → quedan 0', '100 = 64 + 32 + 4 → <b>0110 0100</b>'], result: '1101 = 13 y 100 = 0110 0100.' },
      { t: 'bits', q: 'Forma el 13.', n: 8, target: 13, e: '8 + 4 + 1.', c: 'bb_binread', h: 'Busca pesos que sumen 13: empieza por el 8.' },
      { t: 'bits', q: 'Ahora el 100.', n: 8, target: 100, e: '64 + 32 + 4.', c: 'bb_binread', h: 'Resta el peso más grande que quepa: 64, y sigue con lo que queda.' },
      G('binToDec'), G('decToBin'),
      I('Con <b>n bits</b> caben <b>2ⁿ</b> valores, del 0 al 2ⁿ − 1:\n1 bit → 2 · 2 bits → 4 · 4 bits → 16 · 8 bits (un byte) → 256 (de 0 a 255) · 10 bits → 1024.'),
      Nm('¿Cuántos valores distintos caben en 8 bits?', 256, '', '2⁸ = 256: del 0 al 255.', { c: 'bb_nbits', h: 'Duplica ocho veces empezando en 1.' }),
      Q('¿Cuál es el número más alto que cabe en un byte?', ['255', '256', '128', '8'], 'Hay 256 valores, pero el primero es el 0.', { c: 'bb_nbits', h: 'Cuenta que el 0 también es un valor.' }),
      G('nBitsVals'),
      RES('Digital: 0 (tensión baja) y 1 (alta). 8 bits = 1 byte.', 'Pesos 1, 2, 4, 8… : el número es la suma de los pesos de los unos.', 'Con n bits, <b>2ⁿ</b> valores (de 0 a 2ⁿ − 1).')
    ]),
    L('l2', 'Hexadecimal', 'bin', ['bb_hex'], [
      Q('Escribir 1111 1111 es largo. Si usaras un sistema con 16 cifras distintas, ¿cuántas cifras crees que necesitarías para escribir 255?', ['2', '1', '3', '4'], 'Con 16 cifras, dos posiciones dan 16 × 16 = 256 valores: el 255 cabe en dos cifras. Eso es el hexadecimal: FF.', { predict: true, c: 'bb_hex', h: '¿Cuántos valores dan dos posiciones de 16 cifras?' }),
      I('El <b>hexadecimal</b> usa 16 cifras: 0–9 y luego <b>A = 10, B = 11, C = 12, D = 13, E = 14, F = 15</b>. Como 16 = 2⁴, cada cifra son exactamente <b>4 bits</b>, y un byte se escribe con dos cifras. Se marca con <b>0x</b> delante: 0xFF = 255.', { svg: `<svg viewBox="0 0 300 100" class="viz">${'0123456789ABCDEF'.split('').map((c, i) => `<text x="${14 + i * 18}" y="40" text-anchor="middle" class="vizlab" style="fill:${i > 9 ? 'var(--led)' : 'currentColor'}">${c}</text><text x="${14 + i * 18}" y="62" text-anchor="middle" class="vizsm">${i}</text>`).join('')}<text x="150" y="90" text-anchor="middle" class="vizsm">las seis letras valen de 10 a 15</text></svg>` }),
      { t: 'explore', text: 'Un byte partido en dos mitades de 4 bits. Cada mitad es una cifra hexadecimal.', viz: 'hexNibble', params: pHex(0, 0),
        tasks: [
          { q: 'val', min: 60, max: 60, text: 'Forma 0x3C', done: '3 = 0011 y C = 1100: cada cifra, cuatro bits. Vale 3 × 16 + 12 = 60.', hint: 'Cifra alta 3 y cifra baja 12 (C).' },
          { q: 'val', min: 255, max: 255, text: 'El byte más grande: 0xFF', done: 'Todos los bits a 1: 15 × 16 + 15 = 255.', hint: 'Las dos cifras al máximo.' },
          { q: 'val', min: 200, max: 200, text: 'Forma el 200 decimal', done: '200 = 12 × 16 + 8 = 0xC8.', hint: 'Divide 200 entre 16: cociente y resto.' }
        ] },
      { t: 'steps', text: '¿Cuánto vale 0x38 en decimal? ¿Y en binario?', steps: ['La cifra de la izquierda vale 16 veces: <b>3 × 16 = 48</b>', 'Súmale la de la derecha: 48 + 8 = <b>56</b>', 'En binario, cada cifra por separado: 3 = 0011 y 8 = 1000', 'Juntas: <b>0011 1000</b> (32 + 16 + 8 = 56)'], result: '0x38 = 56 = 0011 1000.' },
      Q('¿Cuánto vale la cifra hexadecimal C?', ['12', '13', '11', '14'], 'A10 B11 C12 D13 E14 F15.', { c: 'bb_hex', h: 'Cuenta desde A = 10.' }),
      G('hexRead'), G('hexRead'),
      Q('¿Cuántos bits representa cada cifra hexadecimal?', ['4', '8', '16', '2'], '2⁴ = 16 cifras distintas.', { c: 'bb_hex', h: '¿Cuántos bits hacen falta para 16 valores?' }),
      Q('¿Cómo se escribe 1010 0101 en hexadecimal?', ['0xA5', '0x5A', '0x165', '0xAA'], 'Cada mitad: 1010 = 10 = A y 0101 = 5.', { c: 'bb_hex', h: 'Traduce cada grupo de 4 bits por separado.' }),
      Q('¿Cómo se escribe 200 en hexadecimal?', ['0xC8', '0x200', '0x8C', '0xC0'], '200 / 16 = 12 (C) y sobran 8.', { c: 'bb_hex', h: 'Divide entre 16: el cociente es la primera cifra y el resto, la segunda.' }),
      RES('Cifras 0–9 y A–F (10 a 15); prefijo <b>0x</b>.', 'Cada cifra = <b>4 bits</b>; un byte = 2 cifras.', 'Valor = cifra alta × 16 + cifra baja.')
    ]),
    L('l3', 'Puertas lógicas', 'gate', ['bb_gates'], [
      Q('Una lámpara con dos interruptores en serie. ¿Cuándo se enciende?', ['Solo con los dos cerrados', 'Con cualquiera de los dos', 'Nunca', 'Con uno solo, el primero'], 'En serie, la corriente necesita pasar por los dos (d1). Es una puerta AND: «A y B».', { predict: true, c: 'bb_gates', h: 'Recuerda que en serie la corriente atraviesa los dos.' }),
      { t: 'explore', text: 'Puertas hechas con interruptores. A y B son las entradas (0 abierto, 1 cerrado) y el LED es la salida.', viz: 'gateSw', params: { A: B01('A'), B: B01('B'), g: LS('Puerta (0 AND, 1 OR, 2 NOT, 3 NAND, 4 NOR, 5 XOR)', 0, [0, 1, 2, 3, 4, 5]) },
        tasks: [
          { q: 'andOn', min: 1, max: 1, text: 'Con la AND, enciende el LED', done: 'Hacen falta las dos entradas a 1: A y B.', hint: 'A = 1 y B = 1.' },
          { q: 'orOne', min: 1, max: 1, text: 'Con la OR, enciéndelo cerrando solo uno', done: 'En paralelo, basta un camino: A o B.', hint: 'Puerta 1 y una sola entrada a 1.' },
          { q: 'notOff', min: 1, max: 1, text: 'Con la NOT, apaga el LED', done: 'La NOT invierte: entrada a 1, salida a 0.', hint: 'Puerta 2 y A = 1.' },
          { q: 'xorOff', min: 1, max: 1, text: 'Con la XOR, pon las dos entradas a 1', done: 'La XOR da 1 solo si las entradas son distintas: con las dos a 1, apagado.', hint: 'Puerta 5, A = 1 y B = 1.' }
        ] },
      I('Una <b>puerta lógica</b> hace lo mismo con tensiones: entradas a 0 o 1 y una salida. Por dentro son transistores haciendo de interruptores. Se dibujan con estos símbolos:', { svg: `<svg viewBox="0 0 300 100" class="viz">${GATE(60, 45, 'AND', false, 0.9)}${GATE(150, 45, 'OR', false, 0.9)}${NOTG(240, 45, 0.9)}<text x="60" y="90" text-anchor="middle" class="vizsm">AND</text><text x="150" y="90" text-anchor="middle" class="vizsm">OR</text><text x="240" y="90" text-anchor="middle" class="vizsm">NOT</text></svg>` }),
      { t: 'truth', q: 'AND: dos pulsadores en serie. Pulsa A y B, observa el LED y completa la tabla.', gate: 'AND', sch: 'andSw', live: true, c: 'bb_gates', h: 'Solo una fila tiene las dos entradas a 1.' },
      { t: 'truth', q: 'OR: dos pulsadores en paralelo. Explora y completa.', gate: 'OR', sch: 'orSw', live: true, c: 'bb_gates', h: 'Basta con que una entrada valga 1.' },
      I('La <b>NOT</b> invierte. Una bolita en la salida significa «invertida»: <b>NAND</b> es una AND invertida y <b>NOR</b>, una OR invertida.', { svg: `<svg viewBox="0 0 300 100" class="viz">${GATE(80, 45, 'AND', true, 0.9)}${GATE(210, 45, 'OR', true, 0.9)}<text x="80" y="90" text-anchor="middle" class="vizsm">NAND = NOT(AND)</text><text x="210" y="90" text-anchor="middle" class="vizsm">NOR = NOT(OR)</text></svg>` }),
      { t: 'truth', q: 'NAND: una AND con la salida invertida.', gate: 'NAND', c: 'bb_gates', h: 'Calcula la AND de cada fila y dale la vuelta.' },
      { t: 'truth', q: 'NOR: una OR con la salida invertida.', gate: 'NOR', c: 'bb_gates', h: 'Calcula la OR de cada fila y dale la vuelta.' },
      I('<b>XOR</b> (o exclusiva): 1 solo si las entradas son <b>distintas</b>. Sirve para comparar dos bits y, como verás pronto, para sumar.', { gate: 'XOR' }),
      { t: 'truth', q: 'XOR: 1 solo si las entradas son distintas.', gate: 'XOR', c: 'bb_gates', h: '00 y 11 son iguales; 01 y 10, distintas.' },
      { t: 'match', q: 'Une cada puerta con cuándo da 1.', pairs: [['AND', 'Si todas las entradas son 1'], ['OR', 'Si alguna entrada es 1'], ['NAND', 'Salvo si todas son 1'], ['XOR', 'Si las entradas son distintas']], c: 'bb_gates', h: 'Piensa en serie, paralelo e inversión.' },
      Q('Una NOR con A = 0 y B = 0 da…', ['1', '0', 'Depende del reloj', 'A'], 'La OR daría 0; invertida, 1.', { c: 'bb_gates', h: 'Haz primero la OR y luego invierte.' }),
      RES('<b>AND</b>: serie, todas a 1. <b>OR</b>: paralelo, alguna a 1.', '<b>NOT</b> invierte; la bolita indica inversión: <b>NAND</b>, <b>NOR</b>.', '<b>XOR</b>: 1 si son distintas.')
    ]),
    SIM('s6a', 'Reto: puerta AND', 'Monta una AND con dos pulsadores.', { battery: 9, parts: ['push', 'res', 'led'], sch: 'andSw', hint: 'Dos pulsadores en serie con resistencia y LED.' }, 'andGate'),
    SIM('s6b', 'Reto: puerta OR', 'Monta una OR con dos pulsadores.', { battery: 9, parts: ['push', 'res', 'led'], sch: 'orSw', hint: 'Pulsadores en paralelo y, en serie, resistencia y LED.' }, 'orGate'),
    L('l4', 'Álgebra de Boole', 'gate', ['bb_boole'], [
      Q('Una AND en la que una entrada está siempre a 0. ¿Qué crees que sale?', ['Siempre 0', 'Lo mismo que la otra entrada', 'Siempre 1', 'Lo contrario de la otra'], 'Un interruptor abierto en serie lo corta todo: A · 0 = 0. Estas reglas son el álgebra de Boole.', { predict: true, c: 'bb_boole', h: 'Piensa en un interruptor siempre abierto en serie.' }),
      I('El <b>álgebra de Boole</b> escribe la lógica como cuentas:\n· AND como producto: <b>A · B</b>\n· OR como suma: <b>A + B</b>\n· NOT con una raya encima: <b>Ā</b>\nCon números que solo valen 0 o 1, y con una diferencia: 1 + 1 = 1.'),
      I('Reglas que se ven con interruptores:\n· <b>A · 0 = 0</b> (uno abierto en serie corta) · A · 1 = A\n· <b>A + 1 = 1</b> (uno cerrado en paralelo deja pasar) · A + 0 = A\n· A · Ā = 0 · A + Ā = 1', { svg: `<svg viewBox="0 0 300 135" class="viz"><path d="M15 35H40M80 35H110M150 35H175" ${st}/>${SW(40, 35, 0)}${SW(110, 35, 1)}<text x="60" y="58" text-anchor="middle" class="vizsm">0</text><text x="130" y="58" text-anchor="middle" class="vizsm">A</text><text x="95" y="75" text-anchor="middle" class="vizlab">A · 0 = 0</text><path d="M195 35H210M250 35H275M195 35V85H210M250 85H275V35" ${st}/>${SW(210, 35, 0)}${SW(210, 85, 1)}<text x="230" y="58" text-anchor="middle" class="vizsm">A</text><text x="230" y="105" text-anchor="middle" class="vizsm">1</text><text x="235" y="128" text-anchor="middle" class="vizlab">A + 1 = 1</text></svg>` }),
      Q('A · 0 =', ['0', 'A', '1', 'Ā'], 'Una AND con un 0 da 0.', { c: 'bb_boole', h: 'Interruptor abierto en serie.' }),
      Q('A + 1 =', ['1', 'A', '0', 'Ā'], 'Una OR con un 1 da 1.', { c: 'bb_boole', h: 'Interruptor cerrado en paralelo.' }),
      { t: 'explore', text: 'Dos circuitos distintos. Prueba todas las entradas y compara sus salidas.', viz: 'deMorgan', params: { A: B01('A'), B: B01('B'), ley: LS('Comparar (0 NAND, 1 NOR)', 0, [0, 1]) },
        tasks: [
          { q: 'both1', min: 1, max: 1, text: 'Pon A = 1 y B = 1', done: 'Los dos LEDs apagados: la NAND da 0 y la OR de Ā y B̄ (0 y 0) también.', hint: 'Las dos entradas a 1.' },
          { q: 'mix', min: 1, max: 1, text: 'Ahora entradas distintas', done: 'Los dos encendidos. Coinciden siempre: son la misma función.', hint: 'Una a 1 y otra a 0.' },
          { q: 'nor00', min: 1, max: 1, text: 'Pasa a la NOR con las dos entradas a 0', done: 'La NOR da 1 y la AND de Ā y B̄ (1 y 1) también: la otra ley de De Morgan.', hint: 'Comparar 1, A = 0 y B = 0.' }
        ] },
      I('Leyes de <b>De Morgan</b>: al invertir, la AND se vuelve OR (y al revés) y cada entrada se invierte.\n<b>(A · B)‾ = Ā + B̄</b>\n<b>(A + B)‾ = Ā · B̄</b>'),
      { t: 'steps', text: 'Comprueba fila a fila que (A · B)‾ = Ā + B̄.', steps: ['A = 0, B = 0: NAND = 1; Ā + B̄ = 1 + 1 = <b>1</b>', 'A = 0, B = 1: NAND = 1; Ā + B̄ = 1 + 0 = <b>1</b>', 'A = 1, B = 0: NAND = 1; Ā + B̄ = 0 + 1 = <b>1</b>', 'A = 1, B = 1: NAND = 0; Ā + B̄ = 0 + 0 = <b>0</b>'], result: 'Las cuatro filas coinciden: son la misma puerta.' },
      Q('Por De Morgan, una NAND equivale a…', ['Una OR con las entradas invertidas', 'Una AND', 'Una NOR', 'Una XOR'], '(A·B)‾ = Ā + B̄.', { c: 'bb_boole', h: 'Al invertir, la AND se cambia por OR y se invierte cada entrada.' }),
      Q('Por De Morgan, (A + B)‾ es…', ['Ā · B̄', 'Ā + B̄', 'A · B', 'A + B'], 'La OR invertida es una AND de las entradas invertidas.', { c: 'bb_boole', h: 'Cambia + por · e invierte cada entrada.' }),
      I('La <b>NAND es universal</b>: con solo NAND puedes hacer cualquier puerta. Una NOT es una NAND con sus dos entradas unidas; una AND, una NAND seguida de otra NAND usada como NOT. Por eso un chip de cuatro NAND da para mucho.', { svg: `<svg viewBox="0 0 300 100" class="viz">${GATE(90, 45, 'AND', true, 1)}<path d="M30 45H45V35H50M45 45V55H50" ${st}/><text x="30" y="38" class="vizsm">A</text><text x="200" y="50" class="vizlab">= NOT A</text><text x="150" y="92" text-anchor="middle" class="vizsm">NAND con las entradas unidas: (A · A)‾ = Ā</text></svg>` }),
      Q('¿Cómo haces un inversor (NOT) con una NAND?', ['Uniendo sus dos entradas', 'Dejando una entrada al aire', 'Poniendo su salida a masa', 'No se puede'], '(A · A)‾ = Ā. Y nunca dejes entradas al aire.', { c: 'bb_boole', h: 'Si las dos entradas valen lo mismo, ¿qué hace la NAND?' }),
      Q('¿Por qué se dice que la NAND es universal?', ['Porque con solo NAND se hace cualquier puerta', 'Porque es la más rápida', 'Porque no consume', 'Porque tiene tres entradas'], 'NOT, AND, OR… todas salen combinando NAND.', { c: 'bb_boole', h: 'Recuerda cómo se hacía la NOT.' }),
      RES('AND = <b>·</b>, OR = <b>+</b>, NOT = raya encima.', 'A · 0 = 0 · A + 1 = 1 · A · 1 = A · A + 0 = A.', 'De Morgan: <b>(A · B)‾ = Ā + B̄</b> y <b>(A + B)‾ = Ā · B̄</b>.', 'Con solo NAND se hace todo.')
    ]),
    L('l5', 'Lógica combinacional', 'gate', ['bb_combi'], [
      Q('Tienes 4 señales y quieres elegir cuál pasa a una única salida. ¿Cuántas líneas de 0/1 crees que necesitas para decir cuál?', ['2', '4', '1', '3'], 'Con 2 bits hay 4 combinaciones (00, 01, 10, 11): una para cada señal. Eso hace un multiplexor.', { predict: true, c: 'bb_combi', h: 'Recuerda cuántos valores caben en n bits (l1).' }),
      I('Un circuito <b>combinacional</b> es el que solo depende de sus entradas <b>de ahora</b>: misma entrada, misma salida, siempre. Combinando puertas se construyen bloques muy útiles: multiplexores, decodificadores y sumadores.'),
      { t: 'explore', text: 'Un <b>multiplexor</b> de 4 entradas: S1 y S0 eligen qué entrada D llega a la salida Y.', viz: 'mux4', params: { D: SL('Datos D3 D2 D1 D0 (como número)', 5, 0, 15, 1), S1: B01('S1'), S0: B01('S0') },
        tasks: [
          { q: 'S', min: 2, max: 2, text: 'Selecciona la entrada D2', done: 'S1 S0 = 10, que es 2 en binario.', hint: 'S1 = 1 y S0 = 0.' },
          { q: 'y1d3', min: 1, max: 1, text: 'Haz que salga un 1 por la entrada D3', done: 'Hay que elegir D3 (S = 11) y que D3 valga 1: datos de 8 o más.', hint: 'Selecciona D3 y sube los datos hasta que D3 = 1.' }
        ] },
      I('<b>Multiplexor</b>: con n líneas de selección elige una de 2ⁿ entradas. <b>Decodificador</b>: al revés, n entradas activan una sola de 2ⁿ salidas (por ejemplo, para encender uno de 8 LEDs o elegir uno de varios chips).', { svg: '<svg viewBox="0 0 300 120" class="viz"><rect x="110" y="20" width="80" height="80" rx="6" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="150" y="64" text-anchor="middle" class="vizlab">2 → 4</text><path d="M60 45H110M60 75H110" stroke="currentColor" stroke-width="2"/><text x="40" y="49" class="vizsm">1</text><text x="40" y="79" class="vizsm">0</text>' + [0, 1, 2, 3].map(k => `<path d="M190 ${32 + k * 19}H240" stroke="${k === 2 ? 'var(--led)' : 'currentColor'}" stroke-width="${k === 2 ? 3 : 2}"/><text x="248" y="${36 + k * 19}" class="vizsm">salida ${k}${k === 2 ? ' ← activa' : ''}</text>`).join('') + '</svg>' }),
      Q('¿Cuántas líneas de selección necesita un multiplexor de 4 entradas?', ['2', '4', '1', '3'], '2² = 4.', { c: 'bb_combi', h: 'Busca n tal que 2ⁿ sea el número de entradas.' }),
      Q('Un decodificador de 3 entradas tiene…', ['8 salidas', '3 salidas', '6 salidas', '16 salidas'], '2³ = 8.', { c: 'bb_combi', h: '2 elevado al número de entradas.' }),
      I('Sumar dos bits: 0 + 0 = 0 · 0 + 1 = 1 · 1 + 1 = <b>10</b> (suma 0 y «me llevo 1»). La suma es una <b>XOR</b> (1 si son distintos) y el acarreo, una <b>AND</b> (1 si los dos son 1). Eso es un <b>semisumador</b>; encadenando sumadores se suman números de muchos bits.', { svg: `<svg viewBox="0 0 300 120" class="viz">${GATE(150, 35, 'XOR', false, 0.9)}${GATE(150, 90, 'AND', false, 0.9)}<path d="M60 26H114M60 44H114M60 81H114M60 99H114M80 26V81M95 44V99" ${st} stroke-width="1.6"/><text x="40" y="30" class="vizsm">A</text><text x="40" y="48" class="vizsm">B</text><text x="200" y="39" class="vizlab">suma</text><text x="200" y="94" class="vizlab">acarreo</text></svg>` }),
      { t: 'steps', text: 'Semisumador con A = 1 y B = 1.', steps: ['Suma = A XOR B = 1 XOR 1 = <b>0</b> (son iguales)', 'Acarreo = A AND B = 1 AND 1 = <b>1</b>', 'Resultado: acarreo y suma juntos, <b>10</b> en binario', '10 en binario es 2: 1 + 1 = 2 ✓'], result: 'Suma 0 y acarreo 1.' },
      Q('Semisumador: 1 + 1 da…', ['Suma 0, acarreo 1', 'Suma 1, acarreo 0', 'Suma 2', 'Suma 1, acarreo 1'], '10 en binario.', { c: 'bb_combi', h: 'XOR para la suma, AND para el acarreo.' }),
      Q('Semisumador con A = 1 y B = 0. ¿Resultado?', ['Suma 1, acarreo 0', 'Suma 0, acarreo 1', 'Suma 1, acarreo 1', 'Suma 0, acarreo 0'], 'XOR = 1; AND = 0.', { c: 'bb_combi', h: 'Son distintos: ¿qué da la XOR? ¿Y la AND?' }),
      { t: 'match', q: 'Une cada bloque con lo que hace.', pairs: [['Multiplexor', 'Elige una de varias entradas'], ['Decodificador', 'Activa una de varias salidas'], ['Semisumador', 'Suma dos bits'], ['XOR', 'Detecta si dos bits son distintos']], c: 'bb_combi', h: 'Entrar, salir, sumar o comparar.' },
      RES('Combinacional: depende solo de las entradas de ahora.', 'Multiplexor: n selecciones → 2ⁿ entradas. Decodificador: n entradas → 2ⁿ salidas.', 'Semisumador: <b>XOR</b> = suma, <b>AND</b> = acarreo.')
    ]),
    L('k9', 'Chips lógicos y de apoyo', 'ic', ['bb_chips', 'bb_logicfam'], [
      Q('Un 74HC00 lleva cuatro puertas NAND en un chip de 14 patas. ¿Cuántas patas crees que usan las cuatro puertas, entre entradas y salidas?', ['12', '14', '8', '4'], 'Cada NAND tiene dos entradas y una salida: 4 × 3 = 12. Las otras dos son la alimentación (VCC y masa).', { predict: true, c: 'bb_chips', h: 'Cuenta entradas y salidas de una puerta y multiplica.' }),
      I('Las puertas vienen en chips. Dos familias clásicas:\n· <b>74HC</b>: de 2 a 6 V, rápida.\n· <b>CD4000</b>: de 3 a 15 V, más lenta.\nCon el mismo número suelen hacer lo mismo: 74HC00 y CD4011 son cuatro NAND.', { svg: '<svg viewBox="0 0 300 100" class="viz"><path d="M20 80H280" stroke="var(--line)" stroke-width="2"/><rect x="55" y="24" width="69" height="14" rx="4" fill="var(--ice)"/><rect x="72" y="58" width="208" height="14" rx="4" fill="var(--led)"/><text x="55" y="18" class="vizsm">74HC: 2–6 V</text><text x="72" y="52" class="vizsm">CD4000: 3–15 V</text><text x="20" y="96" class="vizsm">0 V</text><text x="276" y="96" text-anchor="end" class="vizsm">15 V</text></svg>' }),
      Q('Conectas un 74HC00 a 9 V. ¿Qué pasa?', ['Se puede dañar: su máximo son unos 6 V', 'Funciona mejor', 'Va más rápido', 'Da 9 V sin problema'], 'Para 9 o 12 V, la familia CD4000.', { c: 'bb_logicfam', h: 'Recuerda el rango de la familia 74HC.' }),
      I('Patillaje del <b>74HC00</b> (DIP-14, se cuenta desde la muesca como en k1): pata <b>14 = VCC</b>, pata <b>7 = masa</b>. Puerta 1: entradas 1 y 2, salida 3; puerta 2: 4, 5 → 6; puerta 3: 9, 10 → 8; puerta 4: 12, 13 → 11.', { svg: '<svg viewBox="0 0 300 150" class="viz"><rect x="100" y="15" width="100" height="120" rx="4" fill="#1c1c1c"/><path d="M140 15a10 10 0 0 0 20 0" fill="var(--bg)"/>' + [1, 2, 3, 4, 5, 6, 7].map((n, i) => `<rect x="86" y="${22 + i * 16}" width="14" height="8" fill="#9AA3B2"/><text x="80" y="${30 + i * 16}" text-anchor="end" class="vizsm">${n}${n === 7 ? ' GND' : n === 3 || n === 6 ? ' sal.' : ''}</text>`).join('') + [14, 13, 12, 11, 10, 9, 8].map((n, i) => `<rect x="200" y="${22 + i * 16}" width="14" height="8" fill="#9AA3B2"/><text x="220" y="${30 + i * 16}" class="vizsm">${n}${n === 14 ? ' VCC' : n === 11 || n === 8 ? ' sal.' : ''}</text>`).join('') + '<text x="150" y="80" text-anchor="middle" fill="#ddd" font-size="11">74HC00</text></svg>' }),
      { t: 'steps', text: 'Quieres usar una NAND de un 74HC00 alimentado a 5 V.', steps: ['Pata <b>14 a +5 V</b> y pata <b>7 a masa</b>', 'Un condensador de <b>100 nF</b> entre 14 y 7, pegado al chip (k3)', 'Entradas en las patas <b>1 y 2</b>; la salida sale por la <b>3</b>', 'Las entradas de las puertas que no uses (4, 5, 9, 10, 12, 13), <b>a masa o a VCC</b>'], result: 'Alimentación, desacoplo, tu puerta y ninguna entrada al aire.' },
      Q('¿Qué pata del 74HC00 va al positivo de la alimentación?', ['La 14', 'La 7', 'La 1', 'La 8'], 'La 14 es VCC y la 7, masa: esquinas opuestas.', { c: 'bb_chips', h: 'La alimentación va en las esquinas: arriba a la derecha y abajo a la izquierda.' }),
      I('Otros chips de apoyo muy usados:\n· <b>74HC14</b>: seis inversores con Schmitt trigger (k14).\n· <b>CD4017</b>: contador con 10 salidas que se encienden por turnos.\n· <b>ULN2003</b>: siete Darlington (j4) para relés y motores.\n· <b>74HC595</b>: muchas salidas con pocos cables (lo verás más adelante).'),
      { t: 'match', q: 'Une cada chip con lo que hace.', pairs: [['74HC00', 'Cuatro NAND'], ['74HC14', 'Seis inversores Schmitt'], ['CD4017', 'Contador de 10 salidas'], ['ULN2003', 'Drivers para cargas']], c: 'bb_chips', h: 'Puertas, Schmitt, contar o mover cargas.' },
      I('Las entradas CMOS sin usar <b>no se dejan al aire</b>: flotan (k20), leen ruido, pueden quedarse a medio camino y hacer que el chip consuma de más. Se unen a masa o a VCC. Las <b>salidas</b> sin usar sí se dejan libres.'),
      Q('Usas tres de las cuatro NAND de un 74HC00. ¿Qué haces con las entradas de la cuarta?', ['Unirlas a masa o a VCC', 'Dejarlas al aire', 'Unirlas a su salida', 'Cortarlas'], 'Una entrada CMOS al aire flota.', { c: 'bb_chips', h: 'Recuerda lo que pasaba con una entrada flotante en k20.' }),
      Q('Una salida de un 74HC tiene que activar un relé de 70 mA. ¿Qué pones?', ['Un transistor o un ULN2003', 'Nada: directo a la salida', 'Una resistencia de 10 kΩ', 'Un condensador'], 'Una salida lógica da unos pocos mA: basta para un LED, no para un relé.', { c: 'bb_logicfam', h: '¿Cuánta corriente puede dar una salida lógica?' }),
      RES('74HC: 2–6 V · CD4000: 3–15 V.', '74HC00: 14 VCC, 7 masa, desacoplo de 100 nF.', 'Entradas sin usar a masa o VCC; cargas grandes con ULN2003 o transistor.')
    ]),
    L('l6', 'Memoria: biestables', 'gate', ['bb_latch'], [
      Q('Pulsas un timbre y lo sueltas. ¿Crees que un circuito hecho solo con puertas puede recordar que lo pulsaste?', ['Sí, si la salida de las puertas vuelve a entrar en ellas', 'No: las puertas no recuerdan nada', 'Solo con un condensador', 'Solo con una pila aparte'], 'Si la salida se realimenta, el circuito puede «sostenerse» en un estado. Así nace la memoria.', { predict: true, c: 'bb_latch', h: 'Recuerda la realimentación del Schmitt: la salida se mantenía a sí misma.' }),
      I('Hasta ahora, todo era <b>combinacional</b>: la salida solo depende de las entradas de ahora. Un circuito <b>secuencial</b> también depende de lo que pasó antes: tiene <b>memoria</b>. La pieza básica es el <b>biestable</b>, que guarda un bit.'),
      { t: 'explore', text: 'Dos NAND cruzadas: la salida de cada una entra en la otra. S̄ y R̄ son pulsadores que, al pulsarlos, ponen su entrada a 0.', viz: 'latchSR', params: { Sn: LS('S̄ (1 suelto, 0 pulsado)', 1, [0, 1]), Rn: LS('R̄ (1 suelto, 0 pulsado)', 1, [0, 1]) },
        tasks: [
          { q: 'Sn', min: 0, max: 0, text: 'Pulsa S̄ (ponlo a 0)', done: 'Q pasa a 1: el biestable se ha «puesto».', hint: 'S̄ a 0.' },
          { q: 'memo1', min: 1, max: 1, text: 'Suéltalo (S̄ a 1). ¿Se olvida?', done: 'No: Q sigue a 1 aunque ya no pulses nada. Eso es memoria.', hint: 'Vuelve S̄ a 1 con R̄ a 1.' },
          { q: 'Rn', min: 0, max: 0, text: 'Ahora pulsa R̄', done: 'Q vuelve a 0 y se quedará así al soltar.', hint: 'R̄ a 0.' }
        ] },
      I('<b>Biestable SR con NAND</b>: entradas S̄ (set, poner) y R̄ (reset, borrar), activas a nivel <b>bajo</b> (se activan con 0).\n· S̄ = 0 → Q = 1 · R̄ = 0 → Q = 0\n· Las dos a 1 → Q mantiene lo que tenía\n· Las dos a 0 → prohibido (Q y Q̄ a 1 a la vez)', { svg: `<svg viewBox="0 0 300 140" class="viz">${GATE(120, 40, 'AND', true, 1)}${GATE(120, 100, 'AND', true, 1)}<path d="M30 30H80M30 110H80M156 40H230M156 100H230M190 40V62L80 82V90M190 100V78L80 58V50" ${st} stroke-width="1.8"/><text x="25" y="34" text-anchor="end" class="vizlab">S̄</text><text x="25" y="114" text-anchor="end" class="vizlab">R̄</text><text x="236" y="44" class="vizlab">Q</text><text x="236" y="104" class="vizlab">Q̄</text></svg>` }),
      { t: 'steps', text: 'Un SR con NAND empieza con Q = 0. Pasa esta secuencia: S̄ = 0; luego las dos a 1; luego R̄ = 0; luego las dos a 1.', steps: ['S̄ = 0, R̄ = 1 → <b>Q = 1</b> (set)', 'S̄ = 1, R̄ = 1 → Q se queda en <b>1</b> (recuerda)', 'S̄ = 1, R̄ = 0 → <b>Q = 0</b> (reset)', 'S̄ = 1, R̄ = 1 → Q se queda en <b>0</b>'], result: 'Q acaba en 0, y en cada momento recuerda la última orden.' },
      Q('¿En qué se diferencia un circuito secuencial de uno combinacional?', ['El secuencial tiene memoria', 'En nada', 'El combinacional es más lento', 'El secuencial no usa puertas'], 'Los biestables añaden el tiempo: la salida depende también de lo que pasó.', { c: 'bb_latch', h: '¿De qué depende la salida en cada caso?' }),
      Q('En un biestable SR con NAND, las entradas S̄ y R̄ se activan con…', ['Un 0 (nivel bajo)', 'Un 1 (nivel alto)', 'Media tensión', 'Cualquier valor'], 'Por eso llevan la raya encima.', { c: 'bb_latch', h: 'Recuerda qué hacía falta para poner Q a 1 en la exploración.' }),
      Q('¿Qué pasa si pones S̄ = 0 y R̄ = 0 a la vez?', ['Q y Q̄ valen 1 a la vez: estado prohibido', 'Q pasa a 0', 'Q recuerda lo anterior', 'El chip se quema'], 'Las dos NAND reciben un 0 y dan 1: Q y Q̄ dejan de ser opuestas.', { c: 'bb_latch', h: 'Una NAND con alguna entrada a 0 siempre da…' }),
      I('El <b>biestable D</b> añade un <b>reloj</b>: en cada <b>flanco</b> (el instante en que el reloj sube de 0 a 1) copia lo que haya en D a la salida Q y lo mantiene hasta el flanco siguiente, aunque D cambie entretanto. Es como una foto.', { svg: '<svg viewBox="0 0 300 130" class="viz"><text x="10" y="30" class="vizsm">reloj</text><path d="M45 40H70V18H100V40H140V18H170V40H210V18H240V40H285" fill="none" stroke="var(--ice)" stroke-width="2"/><text x="10" y="72" class="vizsm">D</text><path d="M45 80H90V60H190V80H285" fill="none" stroke="var(--muted)" stroke-width="2"/><text x="10" y="112" class="vizsm">Q</text><path d="M45 120H140V100H210V120H285" fill="none" stroke="var(--led)" stroke-width="3"/><path d="M70 14V125M140 14V125M210 14V125" stroke="var(--line)" stroke-dasharray="2 3"/></svg>' }),
      Q('D cambia de 0 a 1 entre dos flancos de reloj. ¿Cuándo cambia Q?', ['En el siguiente flanco de reloj', 'En cuanto cambia D', 'Nunca', 'Al quitar la alimentación'], 'Solo captura en el flanco.', { c: 'bb_latch', h: 'Mira en la gráfica cuándo cambia la naranja.' }),
      RES('Secuencial = con memoria. Biestable = 1 bit.', 'SR con NAND: <b>S̄ = 0</b> pone, <b>R̄ = 0</b> borra, las dos a 1 recuerda; las dos a 0, prohibido.', 'Biestable D: copia D en el <b>flanco</b> del reloj.')
    ]),
    SIM('slatch', 'Reto: memoria con un 74HC00', 'Con dos NAND cruzadas, haz un biestable: un pulsador enciende el LED y se queda encendido; el otro lo apaga.', { battery: 5, parts: ['ic7400', 'push', 'res', 'led'], hint: 'Pata 14 al +, 7 al −. Patas 1 y 5 con 10 kΩ al + y un pulsador cada una a −. Cruza: salida 3 → entrada 4; salida 6 → entrada 2. LED con 470 Ω en la salida 3.' }, 'latch'),
    L('l7', 'Contadores, relojes y rebotes', 'bin', ['bb_counter', 'bb_nbits', 'bb_hystwhy'], [
      Q('Pulsas una sola vez un pulsador conectado a un contador y marca 3. ¿Por qué crees que pasa?', ['El contacto rebota y da varios pulsos', 'El contador está roto', 'Lo pulsaste tres veces sin darte cuenta', 'Le falta tensión'], 'Los contactos metálicos rebotan: al cerrar se abren y cierran varias veces en pocos milisegundos, y el contador los cuenta todos.', { predict: true, c: 'bb_hystwhy', h: 'Piensa en lo que hace un contacto metálico al chocar.' }),
      I('Encadenando biestables se hace un <b>contador</b>: cada uno cambia de estado cuando el anterior pasa de 1 a 0, así que cambia la mitad de veces. Las salidas Q3 Q2 Q1 Q0 forman el número en binario.', { svg: '<svg viewBox="0 0 300 130" class="viz"><text x="5" y="22" class="vizsm">Q0</text><path d="M30 30H50V12H70V30H90V12H110V30H130V12H150V30H170V12H190V30H210V12H230V30H250V12H270V30" fill="none" stroke="var(--led)" stroke-width="2"/><text x="5" y="62" class="vizsm">Q1</text><path d="M30 70H70V52H110V70H150V52H190V70H230V52H270V70" fill="none" stroke="var(--ice)" stroke-width="2"/><text x="5" y="102" class="vizsm">Q2</text><path d="M30 110H110V92H190V110H270V92" fill="none" stroke="var(--ok)" stroke-width="2"/><text x="150" y="127" text-anchor="middle" class="vizsm">cada salida va a la mitad de frecuencia que la anterior</text></svg>' }),
      { t: 'explore', text: 'Un contador de 4 bits con un pulsador. Elige cuántas veces pulsas, cuántos rebotes da cada pulsación y si hay filtro.', viz: 'counter', params: { n: SL('Pulsaciones', 0, 0, 15, 1), reb: SL('Rebotes por pulsación', 0, 0, 3, 1), filtro: LS('Filtro RC + Schmitt (0 no, 1 sí)', 0, [0, 1]) },
        tasks: [
          { q: 'count', min: 5, max: 5, text: 'Haz que el contador marque 5 (0101)', done: 'Cinco pulsaciones limpias: Q2 y Q0 encendidos, 4 + 1.', hint: 'Cinco pulsaciones sin rebotes.' },
          { q: 'bad', min: 1, max: 1, text: 'Añade rebotes sin filtro', done: 'Cada rebote cuenta como una pulsación más: el contador se vuelve loco.', hint: 'Sube los rebotes.' },
          { q: 'fixed', min: 1, max: 1, text: 'Activa el filtro', done: 'El RC suaviza los rebotes y el Schmitt da un único flanco limpio por pulsación.', hint: 'Filtro a 1.' }
        ] },
      { t: 'steps', text: '¿Cuántos biestables hacen falta para contar de 0 a 15? Si les metes un reloj de 1 Hz, ¿cada cuánto cambia el último?', steps: ['Del 0 al 15 hay <b>16</b> valores', '2⁴ = 16 → <b>4 biestables</b> (4 bits)', 'Cada biestable divide la frecuencia entre 2: 1 Hz → 0,5 → 0,25 → <b>0,125 Hz</b>', 'El último completa un ciclo cada 8 s: cambia de estado cada <b>4 s</b>'], result: '4 biestables; el último va 16 veces más lento que el reloj.' },
      Q('¿Cuántos biestables necesitas para contar de 0 a 15?', ['4', '15', '8', '16'], '16 valores = 2⁴.', { c: 'bb_nbits', h: 'Un biestable por bit.' }),
      I('El <b>reloj</b> puede ser un 555 en astable (k4). Y un contador es, a la vez, un <b>divisor de frecuencia</b>: cada biestable la divide entre 2. Así se sacan frecuencias lentas de una rápida (los relojes de cuarzo dividen 32 768 Hz quince veces para tener 1 Hz).'),
      Nm('Un 555 da 1 kHz y lo llevas a tres biestables encadenados. ¿Frecuencia de la última salida, en Hz?', 125, 'Hz', '1000 / 2³ = 125 Hz.', { c: 'bb_counter', h: 'Divide entre 2 una vez por cada biestable.' }),
      Nm('Un contador de 4 bits muestra Q3 Q2 Q1 Q0 = 1011. ¿Cuántos pulsos ha contado (sin dar la vuelta)?', 11, '', '8 + 2 + 1 = 11.', { c: 'bb_counter', h: 'Q3 vale 8, Q2 vale 4, Q1 vale 2 y Q0 vale 1.' }),
      I('Un pulsador <b>rebota</b>: varios cierres en unos pocos milisegundos. Solución por hardware: un <b>RC</b> que suaviza los rebotes en una subida lenta, y un <b>inversor Schmitt</b> (74HC14) que la convierte en un único flanco limpio, como en k14.', { svg: '<svg viewBox="0 0 300 130" class="viz"><path d="M15 50H50V20H54V50H58V20H64V50H68V20H140" fill="none" stroke="var(--ice)" stroke-width="2"/><text x="15" y="66" class="vizsm">pulsador</text><path d="M150 35h14" stroke="currentColor" stroke-width="2"/><path d="M164 35l-5 -4v8z" fill="currentColor"/><path d="M175 50C200 50 205 20 240 20H285" fill="none" stroke="var(--muted)" stroke-width="2"/><text x="175" y="66" class="vizsm">tras el RC</text><path d="M15 115H120V85H285" fill="none" stroke="var(--led)" stroke-width="3"/><text x="140" y="108" class="vizsm">tras el Schmitt: un solo flanco</text></svg>', more: 'Valores típicos: 10 kΩ y 1 µF dan una constante de tiempo de 10 ms, suficiente para tapar rebotes de unos pocos milisegundos.\nMás adelante verás que también se pueden filtrar por programa, ignorando los cambios durante unos milisegundos.' }),
      Q('Un pulsador con un RC de 10 kΩ y 1 µF da una subida lenta. ¿Qué pones antes de la entrada del contador?', ['Un inversor Schmitt (74HC14)', 'Una NAND normal del 74HC00', 'Un LED', 'Nada'], 'Una puerta normal, con una subida lenta y algo de ruido, puede dar varios cambios; la Schmitt da uno.', { c: 'bb_hystwhy', h: 'Necesitas dos umbrales para que la rampa dé un solo cambio.' }),
      Q('¿Cómo se eliminan por hardware los rebotes de un pulsador?', ['Con un RC seguido de un inversor Schmitt', 'Pulsando más fuerte', 'Con más tensión', 'Quitando la pull-up'], 'El RC suaviza y el Schmitt limpia.', { c: 'bb_hystwhy', h: 'Recuerda el filtro de la exploración.' }),
      RES('Biestables encadenados = <b>contador</b> y divisor de frecuencia (÷ 2 cada uno).', 'n biestables cuentan de 0 a 2ⁿ − 1.', 'Los pulsadores rebotan: <b>RC + Schmitt</b> (74HC14).')
    ]),
    PRJ('p6', 'Proyecto: lógica con pulsadores', 'logic')
  ] });
})();
