/* Voltio · curso base, módulo 16: Microcontroladores I: programar
   Orden: n1 (qué es) → n2 (primer programa) → n3 (salidas) → s7a → n15 (monitor serie) → n10 (variables)
   → n11 (cuentas) → n12 (decisiones y bucles) → n13 (funciones) → n14 (arrays) → s7b → p7.
   Convenciones (lotes 5 y 6): Uno por defecto, const int en mayúsculas para pines, Serial.begin(9600), comentarios en español.
   Aún NO: digitalRead/pull-up (n4), Serial.read (n16), analogRead/ADC (l11, n5), analogWrite (n6), millis() (n7), String (n16). */
(() => {
  const { num, st, ledBulb } = Widgets.H;
  const RES = (...k) => I('<b>Resumen</b>\n· ' + k.join('\n· '));
  const LS = (label, val, list, unit = '', dec = 0) => ({ label, val, list, unit, dec });
  const SL = (label, val, min, max, step, unit = '', dec = 0) => ({ label, val, min, max, step, unit, dec });
  const esc = s => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const LED = (x, y, on, s = 0.75, col) => `<g transform="translate(${x} ${y}) scale(${s})"${col ? ` style="filter:hue-rotate(${col}deg)"` : ''}>${ledBulb(on ? 1 : 0)}</g>`;
  // Bloque de código con una línea resaltada
  const CODE = (x, y, lines, hl, w = 170) => `<rect x="${x}" y="${y}" width="${w}" height="${lines.length * 15 + 8}" rx="6" fill="var(--board)"/>` + lines.map((l, i) => `${i === hl ? `<rect x="${x + 2}" y="${y + 4 + i * 15}" width="${w - 4}" height="15" rx="3" fill="var(--led)" opacity=".35"/>` : ''}<text x="${x + 6}" y="${y + 15 + i * 15}" style="font:11px ui-monospace,Consolas,monospace;white-space:pre;fill:${i === hl ? '#fff' : '#B9C4D3'}">${esc(l)}</text>`).join('');

  /* ===================== VISUALIZACIONES ===================== */
  Object.assign(Widgets.VIZ, {
    // El programa Blink ejecutándose línea a línea, con su LED y su cronograma
    blinkRun: {
      anim: true,
      calc: p => ({ f: 1000 / (p.on + p.off), pat: p.on === 200 && p.off === 800 ? 1 : 0, duty: p.on / (p.on + p.off) * 100 }),
      svg: (p, o, t) => {
        const T = (p.on + p.off) / 1000, ph = (t % T) / T, onNow = ph < p.on / (p.on + p.off), d = p.on / (p.on + p.off);
        const hl = onNow ? (ph < 0.04 ? 1 : 2) : (ph - d < 0.04 ? 3 : 4);
        let w = ''; for (let k = 0; k < 3; k++) { const x = 20 + k * 90; w += `${k ? 'L' : 'M'}${x} 140V118H${(x + 90 * d).toFixed(1)}V140H${x + 90}`; }
        return `<svg viewBox="0 0 300 175" class="viz">${CODE(10, 8, ['void loop() {', '  digitalWrite(13, HIGH);', `  delay(${p.on});`, '  digitalWrite(13, LOW);', `  delay(${p.off});`, '}'], hl, 185)}
          ${LED(250, 50, onNow, 0.9)}<text x="250" y="92" text-anchor="middle" class="vizsm">LED del 13</text>
          <path d="${w}" fill="none" stroke="var(--led)" stroke-width="2.5"/><path d="M${(20 + (ph * 90) % 90 + 90 * Math.floor((t / T) % 3)).toFixed(1)} 112V146" stroke="var(--ice)" stroke-width="2"/>
          <text x="10" y="166" class="vizlab">Periodo ${p.on + p.off} ms · ${num(o.f, 2)} destellos por segundo</text></svg>`;
      }
    },
    // Un pin de salida con un LED: lógica normal o invertida, resistencia y corriente
    pinOut: {
      calc: p => { const dv = p.wiring ? (p.lvl ? 0 : p.V) : (p.lvl ? p.V : 0), I = dv > 2 ? (dv - 2) / p.R * 1000 : 0; return { I, on: I > 0.5 ? 1 : 0, onInv: p.wiring && I > 0.5 ? 1 : 0, ok33: p.V === 3.3 && I >= 8 && I <= 12 ? 1 : 0, over: I > 20 ? 1 : 0 }; },
      svg: (p, o) => {
        const pinTxt = `pin ${p.lvl ? 'HIGH' : 'LOW'} = ${num(p.lvl ? p.V : 0, 1)} V`, top = p.wiring ? `${num(p.V, 1)} V fijos` : pinTxt, bot = p.wiring ? pinTxt : 'GND (0 V)';
        return `<svg viewBox="0 0 300 175" class="viz"><rect x="20" y="20" width="70" height="120" rx="6" fill="var(--board)"/><text x="55" y="84" text-anchor="middle" style="font-size:11px;fill:#E8EDF5">placa</text>
          <path d="M90 40H140M180 40H230V62M230 98V122H90" ${st}/><rect x="140" y="32" width="40" height="16" rx="8" fill="#E7D3A8" stroke="#C9B183"/>${LED(230, 80, o.on, 0.65)}
          ${o.on ? `<path d="M90 40H230V122H90" class="flow" style="animation-duration:${Math.max(0.3, 6 / o.I).toFixed(2)}s${p.wiring ? ';animation-direction:reverse' : ''}"/>` : ''}
          <text x="96" y="22" class="vizsm">${top}</text><text x="96" y="138" class="vizsm">${bot}</text>
          <text x="10" y="160" class="vizlab" style="fill:${o.over ? 'var(--err)' : 'currentColor'}">${o.on ? 'LED encendido · ' + num(o.I, 1) + ' mA por el pin' : 'LED apagado: no hay diferencia de tensión'}</text>
          <text x="10" y="173" class="vizsm">${o.over ? '¡Más de 20 mA! El pin sufre: pon más resistencia' : 'LED rojo de unos 2 V'}</text></svg>`;
      }
    },
    // Baudios: cuánto tarda un mensaje y cómo viaja un carácter
    baud: {
      anim: true,
      calc: p => ({ ms: p.n * 10 / p.bd * 1000 }),
      svg: (p, o, t) => {
        const bits = [0, 1, 0, 0, 0, 0, 0, 1, 0, 1], sh = (t * 40) % 300; // 'A' = 0x41: inicio, 8 bits (LSB primero), parada
        let w = 'M10 60'; bits.forEach((b, i) => { w += `V${b ? 40 : 60}H${10 + (i + 1) * 24}`; }); w += 'V40H290';
        return `<svg viewBox="0 0 300 150" class="viz"><text x="10" y="22" class="vizsm">la letra A por el cable: inicio, 8 bits y parada</text>
          <g transform="translate(${(sh - 60).toFixed(1)} 0)"><path d="${w}" fill="none" stroke="var(--led)" stroke-width="2.5"/></g><path d="M10 75H290" stroke="var(--line)"/>
          <text x="10" y="100" class="vizlab">${p.n} caracteres × 10 bits = ${p.n * 10} bits</text>
          <text x="10" y="120" class="vizlab">a ${p.bd} baudios tardan ${o.ms >= 10 ? num(o.ms, 1) : num(o.ms, 2)} ms</text>
          <text x="10" y="140" class="vizsm">${num(p.bd / 10, 0)} caracteres por segundo</text></svg>`;
      }
    },
    // División entera y resto con puntos agrupados
    intDiv: {
      calc: p => ({ q: Math.floor(p.a / p.b), r: p.a % p.b, minsec: p.a === 125 && p.b === 60 ? 1 : 0, impar: p.b === 2 && p.a % 2 === 1 ? 1 : 0 }),
      svg: (p, o) => {
        const s = Math.min(10, 250 / p.b), rows = Math.min(o.q, 7); let d = '';
        for (let r = 0; r < rows; r++) for (let c = 0; c < p.b; c++) d += `<circle cx="${(25 + c * s).toFixed(1)}" cy="${20 + r * 13}" r="${Math.min(4, s / 2.5).toFixed(1)}" fill="var(--ice)"/>`;
        for (let c = 0; c < o.r; c++) d += `<circle cx="${(25 + c * s).toFixed(1)}" cy="${20 + rows * 13 + 4}" r="${Math.min(4, s / 2.5).toFixed(1)}" fill="var(--led)"/>`;
        return `<svg viewBox="0 0 300 175" class="viz">${d}${o.q > 7 ? `<text x="280" y="110" text-anchor="end" class="vizsm">… y ${o.q - 7} grupos más</text>` : ''}
          <text x="10" y="140" class="vizlab">${p.a} / ${p.b} = ${o.q} grupos completos (azul)</text>
          <text x="10" y="156" class="vizlab" style="fill:var(--led)">${p.a} % ${p.b} = ${o.r} sobran (naranja)</text>
          <text x="10" y="171" class="vizsm">con float: ${num(p.a / p.b, 3)}</text></svg>`;
      }
    },
    // if / else if / else: qué rama se ejecuta
    flowTrace: {
      calc: p => ({ branch: p.t > 30 ? 0 : p.t > 20 ? 1 : 2, t30: p.t === 30 ? 1 : 0 }),
      svg: (p, o) => `<svg viewBox="0 0 300 175" class="viz">${CODE(8, 8, [`t = ${p.t};`, 'if (t > 30) {', '  encender(ROJO);', '} else if (t > 20) {', '  encender(AMARILLO);', '} else {', '  encender(VERDE);', '}'], [2, 4, 6][o.branch], 180)}
        ${LED(240, 35, o.branch === 0, 0.55)}${LED(240, 80, o.branch === 1, 0.55, 40)}${LED(240, 125, o.branch === 2, 0.55, 100)}
        <text x="266" y="39" class="vizsm">R</text><text x="266" y="84" class="vizsm">A</text><text x="266" y="129" class="vizsm">V</text>
        <text x="10" y="168" class="vizlab">${p.t > 30 ? `${p.t} > 30: primera rama` : p.t > 20 ? `${p.t} no es > 30, pero sí > 20` : `${p.t} no cumple ninguna: else`}</text></svg>`
    },
    // Traza de un for: cuántas vueltas y con qué valores
    forTrace: {
      calc: p => { const v = []; for (let i = p.i0; p.op ? i <= p.N : i < p.N; i += p.step) { v.push(i); if (v.length > 20) break; } return { count: v.length, v, le6: p.op === 1 && p.i0 === 0 && p.N === 5 && p.step === 1 ? 1 : 0 }; },
      svg: (p, o) => `<svg viewBox="0 0 300 160" class="viz">${CODE(8, 8, [`for (int i = ${p.i0}; i ${p.op ? '<=' : '<'} ${p.N}; i${p.step === 1 ? '++' : ' += 2'}) {`, '  parpadear();', '}'], -1, 284)}
        ${o.v.map((i, k) => `<rect x="${10 + k * 31}" y="82" width="27" height="27" rx="5" fill="var(--ice)"/><text x="${23.5 + k * 31}" y="101" text-anchor="middle" class="vizlab" style="fill:#fff">${i}</text>`).join('')}
        <text x="10" y="76" class="vizsm">valores de i en cada vuelta</text>
        <text x="10" y="130" class="vizlab">${o.count} vuelta${o.count === 1 ? '' : 's'}</text>
        <text x="10" y="150" class="vizsm">se para cuando i ${p.op ? '<=' : '<'} ${p.N} deja de cumplirse</text></svg>`
    },
    // Array de pines: índice → LED; fuera de rango, memoria ajena
    arrayIdx: {
      calc: p => ({ i: p.i, out: p.i > 4 ? 1 : 0 }),
      svg: (p, o) => {
        const pins = [8, 9, 10, 11, 12];
        return `<svg viewBox="0 0 300 165" class="viz"><text x="10" y="20" style="font:11px ui-monospace,Consolas,monospace;fill:currentColor">int leds[5] = {8, 9, 10, 11, 12};</text>
          ${[0, 1, 2, 3, 4, 5].map(k => `<rect x="${12 + k * 46}" y="34" width="40" height="34" rx="6" fill="${k > 4 ? 'var(--err-soft)' : k === p.i ? 'var(--led)' : 'var(--ice-soft)'}" stroke="${k > 4 ? 'var(--err)' : 'var(--ice)'}" ${k > 4 ? 'stroke-dasharray="4 3"' : ''}/><text x="${32 + k * 46}" y="56" text-anchor="middle" class="vizlab">${k > 4 ? '?' : pins[k]}</text><text x="${32 + k * 46}" y="82" text-anchor="middle" class="vizsm">[${k}]</text>`).join('')}
          ${pins.map((pn, k) => LED(32 + k * 46, 108, k === p.i, 0.45)).join('')}
          <text x="10" y="150" class="vizlab" style="fill:${o.out ? 'var(--err)' : 'currentColor'}">${o.out ? `leds[${p.i}] no existe: lees memoria ajena` : `leds[${p.i}] vale ${pins[p.i]}: se enciende el LED del pin ${pins[p.i]}`}</text></svg>`;
      }
    }
  });

  /* ===================== GENERADORES (con pista) ===================== */
  const { pick } = Gen.helpers;
  Gen.add('pinLedR', () => ({ ...Gen.make('mcLedR'), h: 'R = (V − Vled) / I, con la corriente en amperios.' }), 'mc_ledres');
  Gen.add('serialMs', () => ({ ...Gen.make('mcBaud'), h: 'Cada carácter son 10 bits: caracteres × 10 / baudios da segundos.' }), 'mc_baud');
  Gen.add('byteWrap', () => ({ ...Gen.make('mcOverflow'), h: 'Si no cabe, quita (o suma) vueltas completas: 256 en un byte, 65 536 en un unsigned int de la Uno.' }), 'mc_overflow');
  Gen.add('intDivMod', () => (pick([0, 1]) ? { ...Gen.make('mcIntDiv'), h: 'Entre enteros, / descarta los decimales; y / se calcula antes que +.' } : { ...Gen.make('mcModulo'), h: '% da lo que sobra al repartir: a = b × cociente + resto.' }), 'mc_intmath');
  Gen.add('bitMask', () => ({ ...Gen.make('mcBits'), h: '1 << k vale 2 elevado a k. Con | el bit queda a 1; con & ~ queda a 0. Al final, suma los pesos.' }), 'mc_bitops');
  Gen.add('arrayRam', () => ({ ...Gen.make('mcArrayBytes'), c: 'mc_varbytes', h: 'Elementos × bytes de cada uno. En la Uno, int ocupa 2 bytes; en el ESP32, 4.' }), 'mc_varbytes');

  /* ===================== CONCEPTOS ===================== */
  const pBlink = (on, off) => ({ on: LS('delay tras HIGH', on, [100, 200, 300, 500, 800, 1000], 'ms'), off: LS('delay tras LOW', off, [100, 200, 300, 500, 800, 1000], 'ms') });
  const pPin = (lvl, wiring, V, R) => ({ lvl: LS('digitalWrite (0 LOW, 1 HIGH)', lvl, [0, 1]), wiring: LS('Montaje (0 pin→LED→GND, 1 5V→LED→pin)', wiring, [0, 1]), V: LS('Tensión de la placa', V, [3.3, 5], 'V', 1), R: { label: 'Resistencia', val: R, list: [100, 150, 220, 330, 470, 1000], fmt: 'R' } });
  const pDiv = (a, b) => ({ a: SL('a', a, 1, 130, 1), b: LS('b', b, [2, 3, 4, 5, 6, 10, 60]) });
  Object.assign(CONCEPTS, {
    mc_mcuparts: { name: 'Qué hay dentro de un microcontrolador', alts: [
      { title: 'Un ordenador entero en un chip', text: 'Un microcontrolador junta en un solo chip la <b>CPU</b> (ejecuta instrucciones), la <b>Flash</b> (guarda el programa, también sin corriente), la <b>RAM</b> (las variables mientras funciona) y los <b>periféricos</b> (pines, temporizadores, comunicaciones). Por eso basta el chip con su alimentación para que funcione solo.', svg: '<svg viewBox="0 0 300 140" class="viz"><rect x="40" y="15" width="220" height="110" rx="10" fill="var(--board)"/>' + [['CPU', 55, 30], ['Flash', 155, 30], ['RAM', 55, 78], ['Periféricos', 155, 78]].map(([n, x, y]) => `<rect x="${x}" y="${y}" width="90" height="36" rx="6" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="${x + 45}" y="${y + 23}" text-anchor="middle" class="vizsm" style="fill:currentColor">${n}</text>`).join('') + '</svg>', q: mcq('¿Dónde se guarda el programa para que siga ahí al quitar la corriente?', ['En la Flash', 'En la RAM', 'En la CPU', 'En los pines'], 'La RAM se borra al apagar; la Flash no.') },
      { title: 'Qué sobrevive a un apagado', text: 'Al quitar la corriente, la RAM se borra: las variables empiezan de nuevo al volver. La Flash conserva el programa: por eso la placa arranca sola con una pila, sin el ordenador. El ordenador solo hace falta para escribir y subir el programa.', q: mcq('Alimentas con una pila una placa programada ayer. ¿Qué pasa?', ['Ejecuta el programa guardado en la Flash', 'No hace nada sin el ordenador', 'Hay que volver a subirlo', 'Ejecuta un programa vacío'], 'El programa vive en la Flash.') }
    ] },
    mc_boards: { name: 'Placas y sus pines de alimentación', alts: [
      { title: 'Uno, Nano y ESP32', text: '<b>Uno</b>: chip ATmega328P a 5 V, la clásica. <b>Nano</b>: el mismo chip en pequeño, cabe en la protoboard. <b>ESP32</b>: 3,3 V, mucho más rápida, con WiFi y Bluetooth; sus pines <b>no toleran 5 V</b>. En la Uno: <b>5V</b> y <b>3V3</b> dan esas tensiones, <b>GND</b> es masa y <b>VIN</b> recibe 7–12 V que pasan por el regulador de la placa (k8).', svg: '<svg viewBox="0 0 300 110" class="viz">' + [['VIN', '7–12 V entran'], ['5V', '5 V salen'], ['3V3', '3,3 V salen'], ['GND', 'masa']].map(([a, b], i) => `<rect x="${12 + i * 72}" y="25" width="62" height="30" rx="6" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="${43 + i * 72}" y="45" text-anchor="middle" class="vizlab">${a}</text><text x="${43 + i * 72}" y="75" text-anchor="middle" class="vizsm">${b}</text>`).join('') + '</svg>', q: mcq('Quieres alimentar una Uno con una pila de 9 V. ¿Dónde la conectas?', ['En VIN (y el − a GND)', 'En 5V', 'En el pin 13', 'En 3V3'], 'VIN pasa por el regulador de la placa.') },
      { title: 'Cuidado con los 3,3 V', text: 'Un ESP32 trabaja a 3,3 V: una salida de 5 V conectada a uno de sus pines puede dañarlo. Antes de conectar algo, mira a qué tensión trabaja cada lado. En la Uno, en cambio, un HIGH son 5 V.', q: mcq('¿Qué tensión da digitalWrite(pin, HIGH) en un ESP32?', ['3,3 V', '5 V', '9 V', '1,5 V'], 'Es una placa de 3,3 V.') }
    ] },
    mc_pinmax: { name: 'Cuánta corriente da un pin', alts: [
      { title: 'Un grifo pequeño', text: 'Un pin de la Uno da cómodamente unos <b>20 mA</b> (40 mA es el máximo absoluto) y el chip entero, unos 200 mA sumando todos sus pines. Basta para un LED, no para un relé ni un motor. Para cargas mayores, el pin manda la orden a un <b>transistor o MOSFET</b> (j3, j6) o a un ULN2003. Prueba resistencias pequeñas y mira el aviso.', tune: { viz: 'pinOut', params: pPin(1, 0, 5, 100) }, q: mcq('¿Cuánta corriente conviene sacar de un pin de la Uno?', ['Unos 20 mA como mucho', '2 A', '200 mA', 'Ilimitada'], 'Máximo absoluto, 40 mA.') },
      { title: 'Suma antes de conectar', text: 'Suma lo que piden las cargas: 12 LEDs a 20 mA son 240 mA, más que los unos 200 mA que aguanta el chip entero. Un motor de cientos de mA, ni hablar: transistor o MOSFET, con su diodo de rueda libre (j7).', q: mcq('Tienes 15 LEDs de 15 mA en pines de una Uno, todos encendidos. ¿Problema?', ['Sí: 225 mA superan lo que aguanta el chip entero', 'No, cada pin va sobrado', 'Solo si son azules', 'No, la Uno da 2 A'], 'Hay límite por pin y límite total.') }
    ] },
    mc_varbytes: { name: 'Cuánta memoria ocupan las variables', alts: [
      { title: 'Tamaño por cantidad', text: 'Memoria = número de elementos × bytes de cada uno. En la Uno: bool, byte y char, 1 byte; int, 2; long, unsigned long y float, 4. Un array de 20 int: 20 × 2 = 40 bytes. Y la Uno solo tiene <b>2048 bytes</b> de RAM.', svg: '<svg viewBox="0 0 300 110" class="viz">' + [['bool', 1], ['byte', 1], ['int', 2], ['long', 4], ['float', 4]].map(([n, b], i) => `<text x="12" y="${20 + i * 20}" class="vizsm">${n}</text>` + Array.from({ length: b }, (_, k) => `<rect x="${60 + k * 22}" y="${8 + i * 20}" width="18" height="15" rx="3" fill="var(--ice)"/>`).join('')).join('') + '<text x="160" y="60" class="vizsm">cada casilla, 1 byte</text></svg>', q: mcq('¿Cuántos bytes ocupan, en la Uno, un bool, dos int y un float?', ['9', '7', '6', '4'], '1 + 2 × 2 + 4 = 9.') },
      { title: 'int cambia de placa', text: 'int no mide lo mismo en todas las placas: 2 bytes en la Uno y 4 en el ESP32, la Pico o un STM32. Por lo demás, multiplica elementos por tamaño y suma.', q: mcq('Un array de 50 int en un ESP32, ¿cuánta RAM ocupa?', ['200 bytes', '100 bytes', '50 bytes', '400 bytes'], 'En el ESP32, int = 4 bytes.') }
    ] },
    mc_print: { name: 'Imprimir por el monitor serie', alts: [
      { title: 'print y println', text: 'Serial.print() envía texto sin saltar de línea; Serial.println() salta al final. Entre comillas se imprime el texto tal cual; sin comillas, el <b>valor</b> de la variable. Así, print("t="); println(t); con t = 23 da «t=23».', svg: '<svg viewBox="0 0 300 110" class="viz"><rect x="10" y="10" width="280" height="90" rx="8" fill="var(--board)"/><text x="22" y="34" style="font:12px ui-monospace,Consolas,monospace;fill:#B9C4D3">Serial.print("t=");</text><text x="22" y="52" style="font:12px ui-monospace,Consolas,monospace;fill:#B9C4D3">Serial.println(t);</text><text x="22" y="84" style="font:13px ui-monospace,Consolas,monospace;fill:#F2A900">t=23</text><text x="200" y="84" class="vizsm" style="fill:#B9C4D3">monitor</text></svg>', q: mcq('int n = 7; Serial.print("n"); Serial.println(n); ¿Qué sale?', ['n7', 'nn', '77', 'n n'], 'La primera, texto; la segunda, el valor.') },
      { title: 'Un chivato en el programa', text: 'Usa el monitor como chivato: pon un println dentro del if sospechoso. Si el mensaje no sale, esa parte no se ejecuta; entonces imprime los valores que compara la condición. Etiqueta cada dato para no confundirte.', q: mcq('Pones Serial.println("aquí") dentro de un if y no sale nunca. ¿Qué sabes?', ['Que la condición del if no se cumple', 'Que Serial está roto', 'Que el LED está fundido', 'Nada'], 'Ahora imprime lo que compara.') }
    ] },
    mc_typepick: { name: 'Elegir el tipo de una variable', alts: [
      { title: 'Cajas de distinto tamaño', text: 'Elige la caja por el dato más grande que vaya a guardar. En la Uno: <b>bool</b> (verdadero o falso), <b>byte</b> (0 a 255), <b>int</b> (−32 768 a 32 767), <b>long</b> (unos ±2100 millones), <b>unsigned long</b> (0 a unos 4300 millones), <b>float</b> (con decimales). Si te sales, el número da la vuelta. Mira qué pasa con un byte.', tune: { viz: 'mc_wrap', params: { v: { label: 'Valor que intentas guardar', val: 300, min: 0, max: 600, step: 1, unit: '', dec: 0 }, bits: { val: 8, fixed: true } } }, q: mcq('Vas a contar hasta 50 000 pulsaciones en una Uno. ¿Qué tipo?', ['unsigned int o long', 'int', 'byte', 'bool'], 'int llega a 32 767; unsigned int, a 65 535.') },
      { title: 'Bits y rangos', text: 'Con n bits hay 2ⁿ combinaciones (l1): 8 bits dan 256 valores, 16 bits 65 536 y 32 bits más de 4000 millones. Si el tipo tiene signo, la mitad son negativos: un int de 16 bits va de −32 768 a 32 767.', q: mcq('¿Hasta dónde llega un unsigned int de 16 bits?', ['65 535', '32 767', '255', '65 536'], '2¹⁶ − 1.') }
    ] }
  });
  // Explicaciones visuales añadidas a conceptos que solo usa este módulo
  const addAlt = (k, a) => { if (CONCEPTS[k] && !CONCEPTS[k].alts.some(x => x.title === a.title)) CONCEPTS[k].alts.push(a); };
  addAlt('mc_setup', { title: 'Míralo ejecutarse', text: 'Tras arrancar, setup() se hace una vez y loop() se repite sin fin. Aquí ves loop() funcionando: la línea resaltada es la que se está ejecutando; casi todo el tiempo está esperando en un delay. Cuando llega a la llave final, vuelve arriba.', tune: { viz: 'blinkRun', params: pBlink(500, 500) }, q: mcq('loop() termina su última línea. ¿Qué hace la placa?', ['Vuelve a empezar loop()', 'Ejecuta setup() otra vez', 'Se apaga', 'Se queda parada'], 'loop() se repite sin fin.') });
  addAlt('mc_delay', { title: 'Cronograma', text: 'Cada delay mantiene el pin como está durante esos milisegundos. Cambia los dos delay y mira la onda: el tiempo encendido es el delay tras HIGH, el apagado el delay tras LOW y el periodo, la suma.', tune: { viz: 'blinkRun', params: pBlink(200, 800) }, q: mcq('HIGH; delay(100); LOW; delay(400); ¿Periodo?', ['500 ms', '400 ms', '100 ms', '40 ms'], '100 + 400.') });
  addAlt('mc_syntax', { title: 'Las tres trampas', text: 'Casi todos los primeros errores son de tres tipos: una <b>mayúscula</b> mal (digitalwrite), un <b>punto y coma</b> que falta o una <b>llave</b> sin cerrar. Revisa en ese orden la línea que señala el compilador y la anterior.', svg: '<svg viewBox="0 0 300 100" class="viz"><rect x="10" y="10" width="280" height="80" rx="8" fill="var(--board)"/><text x="22" y="36" style="font:12px ui-monospace,Consolas,monospace;fill:#B9C4D3">digital<tspan fill="#E5484D">w</tspan>rite(13, HIGH)<tspan fill="#E5484D">▮</tspan></text><text x="22" y="62" style="font:11px ui-monospace,Consolas,monospace;fill:#E5484D">mayúscula   y   punto y coma</text></svg>', q: mcq('¿Qué línea compila?', ['digitalWrite(13, LOW);', 'digitalwrite(13, LOW);', 'digitalWrite(13, LOW)', 'DigitalWrite(13, LOW);'], 'Mayúsculas exactas y punto y coma.') });
  addAlt('mc_vars', { title: 'La caja cambia de contenido', text: 'Una variable guarda un valor que puede cambiar. En x = x + 3, primero se calcula la derecha con lo que hay ahora en la caja y luego el resultado sustituye al anterior. Con const delante, la caja queda sellada: solo sirve para dar nombre a un número.', svg: '<svg viewBox="0 0 300 110" class="viz"><rect x="20" y="30" width="70" height="50" rx="8" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="55" y="62" text-anchor="middle" class="vizbig" style="font-size:20px">5</text><text x="55" y="22" text-anchor="middle" class="vizsm">x</text><path d="M100 55H190" stroke="var(--led)" stroke-width="3" class="a-flow"/><text x="145" y="45" text-anchor="middle" class="vizsm">x = x + 3</text><rect x="200" y="30" width="70" height="50" rx="8" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="235" y="62" text-anchor="middle" class="vizbig" style="font-size:20px">8</text><text x="235" y="22" text-anchor="middle" class="vizsm">x</text><text x="150" y="102" text-anchor="middle" class="vizsm">el 5 se sustituye por el 8</text></svg>', q: mcq('int x = 2; x = x * 5; x = x + 1; ¿Cuánto vale x?', ['11', '7', '10', '2'], '2 × 5 = 10; 10 + 1 = 11.') });
  addAlt('mc_digout', { title: 'Pruébalo con el LED', text: 'HIGH une el pin a la alimentación y LOW a masa. Con el LED entre el pin y GND, luce con HIGH; con el LED entre 5 V y el pin, luce con LOW. Cambia el montaje y el valor y compruébalo.', tune: { viz: 'pinOut', params: pPin(0, 1, 5, 220) }, q: mcq('LED de 5V al pin 7 (con su resistencia). ¿Cuándo se enciende?', ['Con LOW', 'Con HIGH', 'Siempre', 'Nunca'], 'Con LOW hay 5 V de diferencia.') });
  addAlt('mc_ledres', { title: 'Mueve la resistencia', text: 'Con 5 V y un LED rojo de unos 2 V, a la resistencia le tocan 3 V: con 220 Ω pasan unos 13,6 mA; con 100 Ω, 30 mA (demasiado para un pin). Con 3,3 V solo sobran 1,3 V. Prueba valores.', tune: { viz: 'pinOut', params: pPin(1, 0, 3.3, 220) }, q: mcq('Pin de 5 V, LED rojo (2 V) y 330 Ω. ¿Corriente?', ['Unos 9 mA', 'Unos 15 mA', 'Unos 6 mA', 'Unos 3 mA'], '3 / 330 ≈ 9,1 mA.') });
  addAlt('mc_serial', { title: 'Los mismos baudios en los dos lados', text: 'Programa y monitor deben acordar la velocidad: si uno manda a 9600 y el otro escucha a 115 200, cada bit se lee mal y salen símbolos raros. Mira cómo viaja un carácter: si cambias la velocidad, cambia la duración de cada bit.', tune: { viz: 'baud', params: { bd: LS('Baudios', 9600, [9600, 19200, 57600, 115200]), n: SL('Caracteres', 20, 1, 200, 1) } }, q: mcq('Salen símbolos raros en el monitor. ¿Qué revisas primero?', ['Que los baudios del monitor coincidan con Serial.begin()', 'El cable USB', 'La resistencia del LED', 'El pin 13'], 'Es la causa más común.') });
  addAlt('mc_baud', { title: 'Míralo pasar', text: 'Cada carácter son 10 bits (inicio, 8 de datos y parada). Tiempo = caracteres × 10 / baudios. Cambia la velocidad y la longitud del mensaje.', tune: { viz: 'baud', params: { bd: LS('Baudios', 9600, [9600, 19200, 57600, 115200]), n: SL('Caracteres', 48, 1, 200, 1) } }, q: mcq('A 19 200 baudios, ¿cuánto tarda un mensaje de 96 caracteres?', ['50 ms', '5 ms', '100 ms', '0,5 ms'], '960 / 19 200 = 0,05 s.') });
  addAlt('mc_intmath', { title: 'Grupos y sobrantes', text: 'a / b son los grupos completos de b que caben en a, y a % b lo que sobra. Mueve a y b: los puntos azules son los grupos y los naranjas, el resto.', tune: { viz: 'intDiv', params: pDiv(17, 5) }, q: mcq('¿Cuánto vale 23 % 6?', ['5', '3', '3,8', '17'], '23 = 6 × 3 + 5.') });
  addAlt('mc_opertype', { title: 'Con puntos, otra vez', text: 'Entre enteros, la división da solo los grupos completos: 7 / 2 = 3. Si quieres 3,5, al menos uno de los números debe llevar decimales: 7.0 / 2. Compara aquí la cuenta entera con la de float.', tune: { viz: 'intDiv', params: pDiv(7, 2) }, q: mcq('float f = 9 / 2; ¿Qué guarda f?', ['4,0', '4,5', '5,0', '0,0'], 'La división se hace entre enteros antes de guardarse.') });
  addAlt('mc_bitops', { title: 'Los bits, uno a uno', text: 'Dibuja los 8 bits con sus pesos (128 … 1). 1 << k enciende solo el bit k; | une bits; & ~ apaga los que indiques. Al final, suma los pesos de los unos.', svg: '<svg viewBox="0 0 300 90" class="viz">' + [0, 1, 0, 0, 0, 0, 1, 0].map((b, i) => `<rect x="${14 + i * 34}" y="20" width="28" height="28" rx="5" fill="${b ? 'var(--led)' : 'var(--line)'}"/><text x="${28 + i * 34}" y="39" text-anchor="middle" class="vizlab">${b}</text><text x="${28 + i * 34}" y="64" text-anchor="middle" class="vizsm">${2 ** (7 - i)}</text>`).join('') + '<text x="150" y="85" text-anchor="middle" class="vizsm">(1 << 6) | (1 << 1) = 64 + 2 = 66</text></svg>', q: mcq('¿Cuánto vale (1 << 4) | (1 << 2)?', ['20', '6', '24', '16'], '16 + 4.') });
  addAlt('mc_if', { title: 'Sigue la rama', text: 'Las condiciones de una cadena if / else if / else se prueban de arriba abajo y solo se ejecuta la primera que se cumple. Mueve t y fíjate en el borde: con t = 30, «t > 30» es falso.', tune: { viz: 'flowTrace', params: { t: SL('t', 30, 0, 40, 1) } }, q: mcq('Con t = 20, ¿qué rama se ejecuta en el ejemplo (t > 30, t > 20, else)?', ['La del else (verde)', 'La amarilla', 'La roja', 'Ninguna'], '20 no es mayor que 20.') });
  addAlt('mc_flow', { title: 'Cuenta las vueltas', text: 'Un for da tantas vueltas como valores de i cumplen la condición. Cambia el inicio, el límite, el signo (< o <=) y el paso, y mira la lista de valores: es la forma más segura de no equivocarse por una vuelta.', tune: { viz: 'forTrace', params: { i0: LS('Inicio', 0, [0, 1]), N: SL('Límite', 5, 1, 10, 1), op: LS('Comparación (0 <, 1 <=)', 1, [0, 1]), step: LS('Paso', 1, [1, 2]) } }, q: mcq('for (int i = 1; i <= 5; i++) … ¿Cuántas vueltas?', ['5', '4', '6', '1'], 'i vale 1, 2, 3, 4 y 5.') });
  addAlt('mc_func', { title: 'La traza de una llamada', text: 'Cuando loop() llama a parpadear(8, 2), el programa salta a la función con pin = 8 y veces = 2, ejecuta su cuerpo y, al terminar (o al llegar a return), vuelve justo detrás de la llamada.', svg: '<svg viewBox="0 0 300 120" class="viz"><rect x="10" y="15" width="120" height="80" rx="8" fill="var(--board)"/><text x="20" y="38" style="font:11px ui-monospace,Consolas,monospace;fill:#B9C4D3">loop()</text><text x="20" y="60" style="font:11px ui-monospace,Consolas,monospace;fill:#F2A900">parpadear(8, 2);</text><text x="20" y="82" style="font:11px ui-monospace,Consolas,monospace;fill:#B9C4D3">delay(1000);</text><rect x="170" y="15" width="120" height="80" rx="8" fill="var(--board)"/><text x="180" y="38" style="font:11px ui-monospace,Consolas,monospace;fill:#B9C4D3">pin = 8</text><text x="180" y="60" style="font:11px ui-monospace,Consolas,monospace;fill:#B9C4D3">veces = 2</text><path d="M130 56H170" stroke="var(--led)" stroke-width="2.5" class="a-flow"/><path d="M230 95V108H70V95" fill="none" stroke="var(--ok)" stroke-width="2" class="a-flow-rev"/><text x="150" y="118" text-anchor="middle" class="vizsm">vuelve detrás de la llamada</text></svg>', q: mcq('void f(int a, int b) … ¿Qué valen a y b en f(3, 9)?', ['a = 3, b = 9', 'a = 9, b = 3', 'a = 3, b = 3', 'a = 12'], 'En el orden en que se escriben.') });
  addAlt('mc_scope', { title: 'Nace y muere', text: 'Una variable local nace al entrar en su función y desaparece al salir: en cada vuelta de loop() vuelve a nacer con su valor inicial. Una global vive todo el rato, fuera de las funciones.', svg: '<svg viewBox="0 0 300 110" class="viz"><rect x="10" y="10" width="135" height="90" rx="8" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="77" y="30" text-anchor="middle" class="vizlab">local</text><text x="77" y="55" text-anchor="middle" class="vizsm">vuelta 1: n = 1</text><text x="77" y="72" text-anchor="middle" class="vizsm">vuelta 2: n = 1</text><text x="77" y="89" text-anchor="middle" class="vizsm">vuelta 3: n = 1</text><rect x="155" y="10" width="135" height="90" rx="8" fill="var(--ok-soft)" stroke="var(--ok)"/><text x="222" y="30" text-anchor="middle" class="vizlab">global</text><text x="222" y="55" text-anchor="middle" class="vizsm">vuelta 1: n = 1</text><text x="222" y="72" text-anchor="middle" class="vizsm">vuelta 2: n = 2</text><text x="222" y="89" text-anchor="middle" class="vizsm">vuelta 3: n = 3</text></svg>', q: mcq('Un contador creado dentro de loop() con valor 0 y que suma 1, ¿qué vale al imprimirlo en la décima vuelta?', ['1', '10', '0', '9'], 'Vuelve a nacer en cada vuelta.') });
  addAlt('mc_array', { title: 'Taquillas numeradas', text: 'El índice elige la taquilla: leds[0] es la primera y leds[4] la última de un array de 5. Mueve el índice y mira qué LED se enciende; pasa al 5 y verás que ya no hay taquilla.', tune: { viz: 'arrayIdx', params: { i: SL('Índice i', 0, 0, 5, 1) } }, q: mcq('int v[4] = {3, 6, 9, 12}; ¿v[3]?', ['12', '9', '3', 'No existe'], 'Índices 0, 1, 2, 3.') });

  /* ===================== LECCIONES ===================== */
  UNITS.push({ id: 'm11b', title: 'Microcontroladores I: programar', desc: 'Qué es un microcontrolador, salidas, monitor serie, variables, cuentas, decisiones, funciones y arrays.', nodes: [
    L('n1', 'Qué es un microcontrolador', 'chip', ['mc_mcuparts', 'mc_boards', 'mc_setup'], [
      Q('Una lavadora, un mando a distancia y un termostato deciden qué hacer según lo que pasa. ¿Qué crees que llevan dentro?', ['Un pequeño ordenador en un chip: un microcontrolador', 'Un ordenador portátil escondido', 'Solo puertas lógicas sueltas', 'Un 555'], 'Hacer eso con puertas y biestables sueltos sería enorme. Un microcontrolador es un ordenador diminuto que sigue un programa.', { predict: true, c: 'mc_mcuparts', h: 'Piensa en algo que pueda seguir instrucciones y cambiar de comportamiento.' }),
      I('Un <b>microcontrolador</b> es un ordenador entero en un chip: ejecuta tu programa y lo repite sin fin. Con él, cambiar el comportamiento de un circuito es cambiar unas líneas de texto, no soldar.', { svg: '<svg viewBox="0 0 300 140" class="viz"><rect x="40" y="15" width="220" height="110" rx="10" fill="var(--board)"/>' + [['CPU', 55, 30], ['Flash', 155, 30], ['RAM', 55, 78], ['Periféricos', 155, 78]].map(([n, x, y], i) => `<rect x="${x}" y="${y}" width="90" height="36" rx="6" fill="var(--ice-soft)" stroke="var(--ice)" class="a-fade a-d${i + 1}"/><text x="${x + 45}" y="${y + 23}" text-anchor="middle" class="vizsm" style="fill:currentColor">${n}</text>`).join('') + [0, 1, 2, 3, 4, 5].map(i => `<path d="M${60 + i * 36} 125v12M${60 + i * 36} 15v-12" stroke="#9AA3B2" stroke-width="4"/>`).join('') + '</svg>', more: 'Los primeros microcontroladores aparecieron en los años 70. Hoy hay decenas en una casa: en el microondas, el mando de la tele, el ratón, el coche…\nNo hay que confundirlo con un ordenador como una Raspberry Pi, que lleva un sistema operativo (Linux) y necesita memoria y almacenamiento aparte.' }),
      I('Dentro del chip:\n· <b>CPU</b>: ejecuta las instrucciones.\n· <b>Flash</b>: guarda el programa, también sin corriente.\n· <b>RAM</b>: guarda las variables mientras funciona.\n· <b>Periféricos</b>: pines de entrada y salida, temporizadores, puertos de comunicación y entradas que miden tensiones (los irás conociendo).'),
      Q('¿En qué se diferencia de la CPU de un ordenador?', ['Lleva memoria y periféricos dentro del mismo chip y consume muy poco', 'Es mucho más rápido', 'Necesita un sistema operativo', 'No tiene memoria'], 'La CPU de un ordenador necesita memoria, discos y periféricos aparte. El microcontrolador lo integra todo para controlar cosas concretas.', { c: 'mc_mcuparts', h: 'Piensa en qué piezas van dentro del mismo chip.' }),
      Q('Desconectas el USB y alimentas la placa con una batería. ¿Qué pasa con el programa?', ['Arranca solo: está guardado en la Flash', 'Se ha borrado', 'Hay que volver a subirlo', 'Solo funciona con el ordenador'], 'La Flash no se borra al quitar la corriente.', { c: 'mc_mcuparts', h: '¿Qué memoria guarda el programa sin corriente?' }),
      { t: 'match', q: 'Une cada placa con su descripción.', pairs: [['Arduino Uno', 'ATmega328P, 5 V, la clásica'], ['Arduino Nano', 'El mismo chip, cabe en la protoboard'], ['ESP32', '3,3 V, WiFi y Bluetooth'], ['Raspberry Pi', 'Ordenador con Linux']], c: 'mc_boards', h: 'Una es un ordenador completo; las otras tres, microcontroladores.' },
      I('Cómo llega tu programa al chip: lo escribes en el <b>IDE</b> (en C++), el compilador lo traduce a instrucciones del chip y se <b>sube</b> por USB. Un pequeño programa de arranque ya grabado (el <b>bootloader</b>) lo copia en la Flash; la placa se reinicia y lo ejecuta.', { svg: '<svg viewBox="0 0 300 100" class="viz">' + [['Escribir', 10], ['Compilar', 82], ['Subir', 154], ['Ejecutar', 226]].map(([n, x], i) => `<rect x="${x}" y="30" width="64" height="34" rx="7" fill="var(--ice-soft)" stroke="var(--ice)"/><text x="${x + 32}" y="51" text-anchor="middle" class="vizsm" style="fill:currentColor">${n}</text>${i < 3 ? `<path d="M${x + 64} 47h8" stroke="var(--led)" stroke-width="3" class="a-flow"/>` : ''}`).join('') + '<text x="150" y="90" text-anchor="middle" class="vizsm">si la compilación falla, nada llega a la placa</text></svg>' }),
      { t: 'order', q: 'Ordena lo que pasa desde que escribes el programa.', items: ['Escribes el programa en el IDE', 'Compilas (verificar)', 'Lo subes por USB', 'La placa se reinicia y ejecuta setup()', 'loop() se repite sin fin'], e: 'Si la compilación falla, nada llega a la placa.', c: 'mc_setup', h: 'Primero texto, luego traducción, luego envío y por último ejecución.' },
      { t: 'steps', text: 'Tu placa hacía parpadear un LED. Cambias el programa, cometes un error de escritura y pulsas «Subir». ¿Qué hace la placa?', steps: ['El IDE intenta <b>compilar</b> y encuentra el error', 'Como no compila, <b>no se sube nada</b>', 'La Flash conserva el programa anterior', 'La placa sigue <b>parpadeando como antes</b>: corrige el error y vuelve a subir'], result: 'Un error de compilación no estropea la placa: simplemente no llega nada nuevo.' },
      I('Los pines de la Uno:\n· <b>D0–D13</b>: digitales (los marcados con ~ pueden dar PWM, h20).\n· <b>A0–A5</b>: entradas analógicas.\n· <b>5V</b> y <b>3V3</b>: dan esas tensiones. <b>GND</b>: masa.\n· <b>VIN</b>: entrada de 7–12 V, que pasa por el regulador de la placa (k8).', { svg: '<svg viewBox="0 0 300 110" class="viz">' + ['0', '1', '2', '~3', '4', '~5', '~6', '7', '8', '~9', '~10', '~11', '12', '13'].map((n, i) => `<rect x="${8 + i * 20.5}" y="20" width="17" height="22" rx="3" fill="var(--board)"/><text x="${16.5 + i * 20.5}" y="35" text-anchor="middle" style="font-size:8px;fill:#E8EDF5">${n}</text>`).join('') + ['VIN', 'GND', '5V', '3V3', 'A0', 'A1', 'A2'].map((n, i) => `<rect x="${8 + i * 41}" y="65" width="36" height="22" rx="3" fill="${i < 4 ? 'var(--err)' : 'var(--ice)'}" opacity=".85"/><text x="${26 + i * 41}" y="80" text-anchor="middle" style="font-size:9px;fill:#fff">${n}</text>`).join('') + '</svg>' }),
      { t: 'pin', q: '¿Qué pin de la Uno da 5 V fijos para alimentar un módulo pequeño?', a: '5V', e: 'El pin 5V da la tensión de la placa; VIN es una entrada.', c: 'mc_boards', h: 'Busca el pin que tiene el nombre de la tensión.' },
      Q('Diferencia clave al conectar cosas a un ESP32:', ['Trabaja a 3,3 V y sus pines no toleran 5 V', 'Ninguna', 'Trabaja a 12 V', 'No tiene pines'], 'Una salida de 5 V puede dañar un pin del ESP32.', { c: 'mc_boards', h: 'Compara la tensión de trabajo de la Uno y la del ESP32.' }),
      Q('Quieres alimentar la Uno con una pila de 9 V. ¿Dónde la conectas?', ['En VIN (y el − a GND)', 'En 5V', 'En el pin 13', 'En A0'], 'VIN pasa por el regulador de la placa, que saca 5 V.', { c: 'mc_boards', h: 'Solo un pin admite más de 5 V porque va a un regulador.' }),
      RES('Microcontrolador = <b>CPU + Flash + RAM + periféricos</b> en un chip.', 'Escribir → compilar → subir → ejecutar; el programa queda en la Flash.', 'Uno y Nano a 5 V; ESP32 a 3,3 V.', 'Pines: D0–D13, A0–A5, 5V, 3V3, GND, VIN.')
    ]),
    L('n2', 'Tu primer programa', 'chip', ['mc_setup', 'mc_delay', 'mc_syntax', 'mc_vars'], [
      Q('Le das a la placa estas órdenes: enciende el LED, espera medio segundo, apágalo, espera medio segundo. ¿Qué crees que hace al llegar al final?', ['Vuelve a empezar: parpadea sin parar', 'Se para con el LED apagado', 'Se reinicia la placa', 'Da un error'], 'Los programas de Arduino tienen una parte que se repite sin fin: loop(). Por eso parpadea para siempre.', { predict: true, c: 'mc_setup', h: 'Recuerda: el programa «se repite sin fin».' }),
      I('Todo programa tiene dos partes:\n· <b>setup()</b>: se ejecuta <b>una vez</b> al arrancar (preparar).\n· <b>loop()</b>: se repite <b>sin parar</b>.\nCada instrucción acaba en <b>;</b> y los bloques van entre <b>llaves</b>. <b>delay(ms)</b> espera ese número de milisegundos.', { code: 'void setup() {\n  pinMode(13, OUTPUT);     // el 13 será una salida\n}\n\nvoid loop() {\n  digitalWrite(13, HIGH);  // enciende\n  delay(500);              // espera medio segundo\n  digitalWrite(13, LOW);   // apaga\n  delay(500);\n}' }),
      { t: 'explore', text: 'El programa Blink funcionando. La línea resaltada es la que se ejecuta: fíjate en cuánto tiempo pasa en cada delay.', viz: 'blinkRun', params: pBlink(500, 500),
        tasks: [
          { q: 'pat', min: 1, max: 1, text: 'Haz un destello corto por segundo: 200 ms encendido y 800 apagado', done: 'El tiempo encendido es el delay que va tras HIGH; el apagado, el que va tras LOW.', hint: 'Primer delay 200 y segundo 800.' },
          { q: 'f', min: 4.99, max: 5.01, text: 'Ahora que parpadee 5 veces por segundo', done: 'Periodo de 200 ms: 100 encendido y 100 apagado (1000 / 200 = 5).', hint: 'Los dos delay tienen que sumar 200 ms.' }
        ] },
      { t: 'steps', text: 'Lee el Blink línea a línea.', code: 'void setup() {\n  pinMode(13, OUTPUT);\n}\nvoid loop() {\n  digitalWrite(13, HIGH);\n  delay(500);\n  digitalWrite(13, LOW);\n  delay(500);\n}', steps: ['<b>setup()</b>, una vez: el pin 13 pasa a ser una salida', '<b>loop()</b>: pone el 13 a HIGH → el LED se enciende', 'delay(500): espera medio segundo <b>con el LED encendido</b>', 'Pone el 13 a LOW y espera otro medio segundo apagado', 'Llega a la llave final de loop() y <b>vuelve a empezar</b>'], result: 'Un parpadeo por segundo, para siempre.' },
      Q('¿Cuántas veces se ejecuta setup()?', ['Una', 'Sin parar', 'Cada segundo', 'Nunca'], 'loop() es la que se repite.', { c: 'mc_setup', code: 'void setup() {\n  pinMode(13, OUTPUT);\n}\nvoid loop() {\n  ...\n}', h: 'Su nombre lo dice: preparar.' }),
      Q('delay(500) significa…', ['Espera 500 ms', 'Espera 500 s', 'Repite 500 veces', 'Usa el pin 500'], '1000 ms = 1 s: medio segundo.', { c: 'mc_delay', h: 'delay mide en milisegundos.' }),
      Q('Con este loop(), ¿cómo parpadea el LED?', ['200 ms encendido y 800 ms apagado: un destello por segundo', '200 ms encendido y 200 ms apagado', 'Siempre encendido', '800 ms encendido y 200 ms apagado'], 'Cada delay mantiene el estado anterior: 200 + 800 = 1000 ms por ciclo.', { c: 'mc_delay', code: 'void loop() {\n  digitalWrite(13, HIGH);\n  delay(200);\n  digitalWrite(13, LOW);\n  delay(800);\n}', h: 'Cada delay mantiene lo que se hizo justo antes.' }),
      { t: 'order', q: 'Ordena las líneas del programa de parpadeo.', items: ['void setup() {', 'pinMode(13, OUTPUT);', '}   // fin de setup()', 'void loop() {', 'digitalWrite(13, HIGH);', 'delay(500);   // encendido', 'digitalWrite(13, LOW);', 'delay(500);   // apagado', '}   // fin de loop()'], e: 'Primero se configura el pin en setup(); luego loop() enciende, espera, apaga y espera.', c: 'mc_setup', h: 'setup() va antes que loop(), y cada bloque se cierra con su llave.' },
      Q('El LED se queda siempre encendido, aunque el programa compila. ¿Dónde está el fallo?', ['Falta un delay tras apagar: está apagado solo unos microsegundos', 'Falta pinMode', 'HIGH y LOW están al revés', 'delay(500) es demasiado corto'], 'Después de LOW, loop() vuelve a empezar y enciende enseguida. El ojo no ve un apagón de microsegundos.', { c: 'mc_delay', code: 'void loop() {\n  digitalWrite(13, HIGH);\n  delay(500);\n  digitalWrite(13, LOW);\n}', h: '¿Cuánto tiempo pasa entre el LOW y el siguiente HIGH?' }),
      I('Detalles que dan guerra al principio:\n· Lo que va tras <b>//</b> es un comentario: el compilador lo ignora.\n· C++ distingue <b>mayúsculas y minúsculas</b>: digitalwrite no es digitalWrite.\n· Los errores suelen señalar la línea de <b>después</b> del fallo real.'),
      Q('¿Por qué no compila?', ['digitalwrite va en minúsculas: se escribe digitalWrite', 'Falta el punto y coma', 'HIGH debería ir entre comillas', 'El 13 no existe'], 'El compilador dice que digitalwrite no está declarado.', { c: 'mc_syntax', code: 'digitalwrite(13, HIGH);', h: 'Mira letra a letra el nombre de la función.' }),
      Q('¿Qué le falta a esta línea?', ['El punto y coma', 'Las llaves', 'Un número', 'Nada'], 'Cada instrucción acaba en ;.', { c: 'mc_syntax', code: 'digitalWrite(13, HIGH)', h: 'Mira el final de la línea.' }),
      I('Un truco para que el programa se lea mejor: dar <b>nombre</b> a los números. Con <b>const int LED = 13;</b> al principio, escribes LED en vez de 13; si mañana cambias de pin, lo cambias en un solo sitio. Por convención, estos nombres van en MAYÚSCULAS.', { code: 'const int LED = 13;\n\nvoid setup() {\n  pinMode(LED, OUTPUT);\n}' }),
      Q('¿Qué hace esta línea?', ['Da el nombre LED al número 13', 'Enciende el pin 13', 'Crea un LED nuevo', 'Nada'], 'Programas legibles: a partir de ahí, LED significa 13.', { c: 'mc_vars', code: 'const int LED = 13;', h: 'No hay ningún digitalWrite.' }),
      RES('<b>setup()</b> una vez; <b>loop()</b> sin fin.', '<b>delay(ms)</b> espera con los pines quietos: tras HIGH = encendido, tras LOW = apagado.', 'Mayúsculas exactas y <b>;</b> al final de cada instrucción.', '<b>const int LED = 13;</b> para dar nombre a los pines.')
    ]),
    L('n3', 'Salidas digitales', 'chip', ['mc_digout', 'mc_ledres', 'mc_pinmax'], [
      Q('digitalWrite(8, HIGH) en una Uno. ¿Qué crees que hace el pin 8 por dentro?', ['Lo une a 5 V, como un interruptor', 'Le manda corriente sin tensión', 'Lo desconecta', 'Lo une a 9 V'], 'Una salida es como un conmutador interno: HIGH la une a la alimentación (5 V) y LOW a masa (0 V).', { predict: true, c: 'mc_digout', h: 'Piensa en un interruptor que elige entre dos tensiones.' }),
      I('<b>pinMode(pin, OUTPUT)</b> convierte un pin en salida. Después, <b>digitalWrite(pin, HIGH)</b> lo conecta por dentro a 5 V y <b>LOW</b>, a 0 V. Un LED siempre con su resistencia en serie (d20).', { code: 'const int LED = 8;\n\nvoid setup() {\n  pinMode(LED, OUTPUT);\n  digitalWrite(LED, HIGH);   // el pin 8 da 5 V\n}' }),
      { t: 'explore', text: 'Un pin con un LED. Prueba los dos montajes, los dos valores de digitalWrite y distintas resistencias.', viz: 'pinOut', params: pPin(0, 0, 5, 220),
        tasks: [
          { q: 'onInv', min: 1, max: 1, text: 'Con el LED conectado entre 5 V y el pin, enciéndelo', done: 'Con LOW el pin hace de masa: hay 5 V de diferencia. Con HIGH, ninguna.', hint: 'Montaje 1 y digitalWrite a 0.' },
          { q: 'ok33', min: 1, max: 1, text: 'En una placa de 3,3 V, deja entre 8 y 12 mA', done: 'Con 3,3 V solo sobran 1,3 V para la resistencia: 150 Ω dan unos 8,7 mA.', hint: 'Tensión 3,3 V y una resistencia más pequeña.' },
          { q: 'over', min: 1, max: 1, text: 'Busca una resistencia con la que el pin pase de 20 mA', done: 'Con 5 V y 100 Ω pasan 30 mA: demasiado para un pin.', hint: '5 V y la resistencia más pequeña.' }
        ] },
      { t: 'pin', q: '¿A qué pin conectarías el LED de este programa?', code: 'void setup() {\n  pinMode(8, OUTPUT);\n}\nvoid loop() {\n  digitalWrite(8, HIGH);\n}', a: 'D8', e: 'El número que aparece en pinMode y digitalWrite.', c: 'mc_digout', h: 'Busca el número dentro de los paréntesis.' },
      Q('Completa para que el 13 pueda encender un LED.', ['OUTPUT', 'INPUT', 'HIGH', 'LOW'], 'Primero hay que hacerlo salida.', { c: 'mc_digout', code: 'pinMode(13, ____);', h: 'El pin va a dar tensión, no a leerla.' }),
      { t: 'pin', q: 'La Uno trae un LED soldado en la placa. ¿En qué pin está?', a: 'D13', e: 'Por eso el Blink usa el 13: funciona sin montar nada.', c: 'mc_digout', h: 'Es el pin del programa Blink.' },
      { t: 'pin', q: '¿A qué pin de la placa va el cátodo (−) de un LED que se enciende con HIGH?', a: 'GND', e: 'Masa: el punto de 0 V de la placa.', c: 'mc_digout', h: 'El cátodo va a 0 V.' },
      I('Un LED se puede conectar de dos formas:\n· pin → resistencia → LED → GND: se enciende con <b>HIGH</b>.\n· 5V → resistencia → LED → pin: se enciende con <b>LOW</b>, porque el pin hace de masa (lógica invertida).', { svg: '<svg viewBox="0 0 300 120" class="viz"><text x="70" y="18" text-anchor="middle" class="vizlab">con HIGH</text><text x="225" y="18" text-anchor="middle" class="vizlab">con LOW</text><text x="70" y="40" text-anchor="middle" class="vizsm">pin (5 V)</text><path d="M70 45V100" stroke="var(--led)" stroke-width="3" class="a-flow"/><text x="70" y="114" text-anchor="middle" class="vizsm">GND</text><text x="225" y="40" text-anchor="middle" class="vizsm">5V</text><path d="M225 45V100" stroke="var(--led)" stroke-width="3" class="a-flow"/><text x="225" y="114" text-anchor="middle" class="vizsm">pin (0 V)</text><circle cx="70" cy="72" r="9" fill="#FF3B30"/><circle cx="225" cy="72" r="9" fill="#FF3B30"/></svg>' }),
      Q('Un LED va de 5V, a través de una resistencia, hasta el pin 7. ¿Cuándo se enciende?', ['Con digitalWrite(7, LOW)', 'Con digitalWrite(7, HIGH)', 'Nunca', 'Siempre'], 'Con LOW hay 5 V de diferencia entre sus extremos; con HIGH, ninguna.', { c: 'mc_digout', h: 'Mira la tensión en cada extremo del LED.' }),
      { t: 'steps', text: 'Quieres un LED rojo (2 V) a 10 mA desde un pin de 3,3 V (ESP32).', steps: ['Lo que sobra para la resistencia: 3,3 − 2 = <b>1,3 V</b>', 'Corriente en amperios: 10 mA = <b>0,01 A</b>', 'R = 1,3 / 0,01 = <b>130 Ω</b>', 'Valor comercial cercano: 150 Ω (algo menos de corriente, unos 8,7 mA)'], result: '130 Ω calculados, 150 Ω en la práctica.' },
      Nm('LED rojo (2 V) con 220 Ω en un pin de 5 V. ¿Corriente en mA?', 13.6, 'mA', '(5 − 2) / 220 ≈ 0,0136 A = 13,6 mA: razonable para un pin.', { tol: 0.4, c: 'mc_ledres', h: 'I = (V − Vled) / R; pasa el resultado a mA.' }),
      G('pinLedR'),
      I('Límites: cada pin de la Uno da cómodamente unos <b>20 mA</b> (40 mA es el máximo absoluto) y el chip entero, unos <b>200 mA</b> sumando todos. Para cargas mayores, el pin solo da la orden a un <b>transistor o MOSFET</b> (j3, j6) o a un <b>ULN2003</b> (k9).', { svg: '<svg viewBox="0 0 300 110" class="viz"><rect x="20" y="30" width="60" height="50" rx="6" fill="var(--board)"/><text x="50" y="59" text-anchor="middle" style="font-size:10px;fill:#E8EDF5">pin</text><path d="M80 55H130" stroke="var(--led)" stroke-width="2" class="a-flow-slow"/><text x="105" y="47" text-anchor="middle" class="vizsm">orden</text><circle cx="150" cy="55" r="18" fill="none" stroke="currentColor" stroke-width="2"/><text x="150" y="59" text-anchor="middle" class="vizsm">NPN</text><path d="M168 55H210" stroke="var(--err)" stroke-width="4" class="a-flow"/><circle cx="235" cy="55" r="18" fill="none" stroke="currentColor" stroke-width="2"/><text x="235" y="60" text-anchor="middle" class="vizlab">M</text><text x="150" y="100" text-anchor="middle" class="vizsm">el pin manda; el transistor mueve la corriente grande</text></svg>' }),
      Q('¿Cuánta corriente conviene sacar como mucho de un pin de la Uno?', ['Unos 20 mA', '2 A', '200 mA', 'Ilimitada'], 'El máximo absoluto son 40 mA; 20 mA es lo cómodo.', { c: 'mc_pinmax', h: 'Lo justo para un LED.' }),
      Q('¿Por qué no encender 12 LEDs a 20 mA cada uno directamente desde pines de la Uno?', ['Se pasaría del límite total del chip, unos 200 mA', 'Porque solo hay 6 pines', 'Porque los LEDs se apagan entre sí', 'Sí se puede sin problema'], '12 × 20 = 240 mA. Además del límite por pin hay uno total.', { c: 'mc_pinmax', h: 'Suma las corrientes y compáralas con el límite del chip.' }),
      Q('¿Cómo controlas un motor de 500 mA desde un pin?', ['Con un transistor o MOSFET y un diodo de rueda libre', 'Directo al pin', 'Con una resistencia en serie', 'No se puede'], 'El pin da unos 20 mA: solo puede dar la orden (j7).', { c: 'mc_pinmax', h: 'Recuerda el módulo de transistores.' }),
      RES('<b>pinMode(pin, OUTPUT)</b>, luego <b>digitalWrite</b> HIGH (5 V) o LOW (0 V).', 'LED a GND: luce con HIGH. LED a 5V: luce con LOW.', '<b>R = (V − Vled) / I</b>; con 3,3 V, resistencias más pequeñas.', '~20 mA por pin y ~200 mA en total: cargas grandes con transistor.')
    ]),
    SIM('s7a', 'Reto: parpadeo', 'Conecta un LED al pin 13 para que parpadee.', { arduino: 'blink', parts: ['res', 'led'], code: true, hint: 'D13 → 220 Ω → ánodo; cátodo → GND.' }, 'blink'),
    L('n15', 'El monitor serie: depurar de verdad', 'bus', ['mc_serial', 'mc_print', 'mc_baud'], [
      Q('Tu programa no hace lo que esperas y no ves qué pasa dentro. ¿Cómo crees que podrías saber cuánto vale una variable mientras funciona?', ['Haciendo que la placa la envíe al ordenador por el USB', 'Mirando el chip con una lupa', 'No se puede', 'Midiendo con el multímetro cada pin'], 'La placa puede escribir texto en el ordenador por el mismo cable USB: es el puerto serie, tu ventana al interior del programa.', { predict: true, c: 'mc_print', h: 'Piensa en el cable que ya une la placa y el ordenador.' }),
      I('Por el cable USB, la placa puede enviar texto al ordenador: es el <b>puerto serie</b>, y en el IDE lo ves en el <b>Monitor serie</b>. Es tu ventana al interior del programa.', { code: 'void setup() {\n  Serial.begin(9600);          // abre el puerto a 9600 baudios\n  Serial.println("Arrancando");\n}' }),
      I('<b>Serial.begin(9600)</b> fija la velocidad en <b>baudios</b> (bits por segundo). Programa y monitor deben usar la misma; si no, salen símbolos raros. Cada carácter viaja como <b>10 bits</b> (8 de datos, uno de inicio y uno de parada): a 9600 baudios, unos 960 caracteres por segundo.'),
      { t: 'explore', text: 'Un carácter viajando por el cable y lo que tarda un mensaje entero.', viz: 'baud', params: { bd: LS('Baudios', 9600, [9600, 19200, 57600, 115200]), n: SL('Caracteres del mensaje', 20, 1, 200, 1) },
        tasks: [
          { q: 'ms', min: 0, max: 2, text: 'Envía 20 caracteres en menos de 2 ms', done: 'A 115 200 baudios, 20 caracteres tardan 1,7 ms.', hint: 'Sube los baudios.' },
          { q: 'ms', min: 100, max: 10000, text: 'Ahora haz que el mensaje tarde más de 100 ms', done: 'A 9600 baudios, unos 100 caracteres ya tardan más de 100 ms: imprimir mucho frena el programa.', hint: '9600 baudios y un mensaje largo.' }
        ] },
      Q('El Monitor serie muestra «⸮⸮x⸮⸮». ¿Causa más probable?', ['Velocidades distintas en el programa y en el monitor', 'La placa está rota', 'Falta un println', 'El cable USB es demasiado corto'], 'Elige en el monitor los mismos baudios que en Serial.begin().', { c: 'mc_serial', h: 'Los dos extremos tienen que hablar al mismo ritmo.' }),
      G('serialMs'),
      I('<b>Serial.print()</b> escribe sin saltar de línea; <b>Serial.println()</b> salta al final. Entre comillas, el texto tal cual; sin comillas, el <b>valor</b> de la variable.', { code: 'int t = 23;\nSerial.print("Temp: ");\nSerial.print(t);\nSerial.println(" C");   // Temp: 23 C' }),
      Q('¿Qué aparece en el monitor?', ['Temp: 23 C', 'Temp: t C', 'Temp:, 23 y C en tres líneas', 'Nada'], 'print no salta de línea; println salta al final. Sin comillas se imprime el valor.', { c: 'mc_print', code: 'int t = 23;\nSerial.print("Temp: ");\nSerial.print(t);\nSerial.println(" C");', h: 'Fíjate en qué va entre comillas y qué no.' }),
      { t: 'steps', text: 'Un LED debería encenderse cuando la variable nivel pasa de umbral, y no lo hace. Depura con el monitor.', code: 'if (nivel > umbral) {\n  Serial.println("dentro");\n  digitalWrite(LED, HIGH);\n}', steps: ['Pones Serial.println("dentro") dentro del if', 'No aparece nunca: la condición <b>no se cumple</b> (el LED no es el problema)', 'Imprimes los dos valores con etiqueta: «nivel=40 umbral=400»', 'Ves que el umbral está mal escrito (400 en vez de 40): <b>error encontrado</b>'], result: 'Observar, no adivinar: dos println bastaron.' },
      Q('Un LED no se enciende cuando debería. Pones Serial.println("dentro") dentro del if que lo enciende y nunca aparece. ¿Qué has aprendido?', ['Que la condición del if nunca se cumple: ahora imprime los valores que compara', 'Que el LED está fundido', 'Que Serial no funciona dentro de un if', 'Nada útil'], 'Has descartado medio problema en un minuto.', { c: 'mc_print', h: 'Si el mensaje no sale, ¿se ha ejecutado esa parte?' }),
      I('Dos detalles de la Uno y la Nano:\n· Los pines <b>0 (RX) y 1 (TX)</b> los usa el puerto serie: si usas Serial, no conectes nada en ellos.\n· Al abrir el monitor, la placa se <b>reinicia</b>: por eso vuelves a ver el mensaje de setup().'),
      { t: 'pin', q: 'Tu programa usa Serial. ¿Qué pin no deberías usar para un LED? (elige uno)', a: ['D0', 'D1'], e: 'D0 y D1 son RX y TX del puerto serie que va al USB.', c: 'mc_serial', h: 'Son los dos primeros pines digitales.' },
      Q('Abrir el Monitor serie con una Uno conectada…', ['Reinicia la placa: el programa empieza de nuevo', 'No le afecta', 'Borra el programa', 'Cambia los baudios del programa'], 'La Uno y la Nano se reinician al abrir el puerto.', { c: 'mc_serial', h: '¿Por qué vuelve a salir el mensaje de setup()?' }),
      RES('<b>Serial.begin(9600)</b> y el monitor a la misma velocidad.', '<b>print</b> sin salto, <b>println</b> con salto; sin comillas, el valor.', '10 bits por carácter: tiempo = caracteres × 10 / baudios.', 'Depurar = imprimir valores con etiqueta. Pines 0 y 1 reservados.')
    ]),
    L('n10', 'Variables y tipos', 'code', ['mc_vars', 'mc_typepick', 'mc_overflow', 'mc_varbytes'], [
      Q('Un contador de pulsaciones se guarda en una variable que solo admite de 0 a 255. Vale 255 y pulsas otra vez. ¿Qué crees que pasa?', ['Vuelve a 0', 'Se queda en 255', 'Pasa a 256', 'La placa se reinicia'], 'No cabe y da la vuelta, como un cuentakilómetros. No hay aviso: hay que elegir bien el tipo.', { predict: true, c: 'mc_overflow', h: 'Piensa en un cuentakilómetros que llega a su máximo.' }),
      I('Una <b>variable</b> es una cajita con nombre en la RAM donde el programa guarda un dato que puede cambiar. Al crearla indicas su <b>tipo</b> (qué guarda y cuánto ocupa), su nombre y, si quieres, un valor inicial.', { code: 'int contador = 0;         // tipo, nombre y valor inicial\ncontador = contador + 1;  // ahora vale 1' }),
      Q('¿Cuánto vale x después de estas líneas?', ['8', '5', '3', '53'], 'Primero vale 5; luego se calcula 5 + 3 y el resultado sustituye al valor anterior.', { c: 'mc_vars', code: 'int x = 5;\nx = x + 3;', h: 'El = guarda en la izquierda lo que vale la derecha.' }),
      I('Tipos más usados en la Uno y la Nano:\n<b>bool</b> · 1 byte · true o false\n<b>byte</b> · 1 byte · de 0 a 255\n<b>int</b> · 2 bytes · de −32 768 a 32 767\n<b>unsigned int</b> · 2 bytes · de 0 a 65 535\n<b>long</b> · 4 bytes · unos ±2100 millones\n<b>unsigned long</b> · 4 bytes · de 0 a 4 294 967 295\n<b>float</b> · 4 bytes · con decimales'),
      { t: 'match', q: 'Elige el tipo más ajustado para cada dato.', pairs: [['Si un LED está encendido', 'bool'], ['Número de pulsaciones, hasta 200', 'byte'], ['Temperatura en décimas de grado, de −400 a 1250', 'int'], ['Pasos de un motor, hasta 3 millones', 'long'], ['Temperatura con decimales', 'float']], c: 'mc_typepick', h: 'Busca el tipo más pequeño en el que quepa el dato, con o sin decimales.' },
      { t: 'explore', text: 'Un byte es un cuentakilómetros de 0 a 255. Intenta guardar valores y mira la aguja.', viz: 'mc_wrap', params: { v: SL('Valor que intentas guardar', 200, 0, 600, 1), bits: { val: 8, fixed: true } },
        tasks: [
          { q: 'laps', min: 1, max: 9, text: 'Intenta guardar algo que no quepa', done: 'Pasado 255, vuelve a empezar desde 0: se pierden 256.', hint: 'Más de 255.' },
          { q: 'trick', min: 1, max: 1, text: 'Haz que el byte acabe guardando 4 aunque intentes guardar más de 255', done: '260 = 256 + 4. Con dos vueltas, 516 también da 4.', hint: 'Una vuelta completa son 256.' }
        ] },
      { t: 'steps', text: 'byte b = 250; b = b + 10; ¿Qué guarda b?', steps: ['La cuenta da 250 + 10 = <b>260</b>', 'Un byte solo llega a 255: no cabe', 'Da la vuelta: se quitan 256 → 260 − 256 = <b>4</b>', 'Sin error ni aviso: el programa sigue con un 4'], result: 'b vale 4.' },
      Q('¿Qué imprime?', ['4', '260', '255', 'Da error al compilar'], 'Un byte solo llega a 255: 260 da la vuelta y queda 260 − 256 = 4.', { c: 'mc_overflow', code: 'byte b = 250;\nb = b + 10;\nSerial.println(b);', h: 'Si no cabe, quita 256.' }),
      G('byteWrap'),
      I('Cuidado con <b>int</b>: en la Uno ocupa 2 bytes, pero en el ESP32, la Pico o un STM32 ocupa 4. El mismo programa puede comportarse distinto según la placa. Por eso el código serio usa tipos de tamaño fijo: <b>uint8_t</b> (como byte), <b>int16_t</b>, <b>uint32_t</b>…'),
      Q('En una Uno, ¿qué problema tiene esta línea?', ['40 000 no cabe en un int de la Uno (máximo 32 767)', 'Ninguno', 'Falta el punto decimal', 'int no admite números de cinco cifras escritos así'], 'Usa long o unsigned int. En un ESP32 sí cabría: allí int ocupa 4 bytes.', { c: 'mc_typepick', code: 'int pasos = 40000;', h: 'Compara 40 000 con el máximo de un int de 2 bytes.' }),
      Q('Cuentas los pasos de un motor y pueden llegar a 100 000. ¿Qué tipo usas en la Uno?', ['long o unsigned long', 'int', 'byte', 'bool'], 'int llega a 32 767 y unsigned int a 65 535: hace falta uno de 4 bytes.', { c: 'mc_typepick', h: '¿Cuál es el primer tipo en el que caben 100 000?' }),
      Nm('¿Cuántos bytes ocupan juntos, en la Uno, un bool, dos int y un unsigned long?', 9, 'bytes', '1 + 2 × 2 + 4 = 9 bytes.', { c: 'mc_varbytes', h: 'Suma los tamaños de la tabla de tipos.' }),
      RES('Variable = tipo + nombre + valor; <b>=</b> guarda.', 'Elige el tipo por el dato más grande: bool, byte, int, long, float…', 'Si no cabe, <b>da la vuelta</b> sin avisar.', 'int: 2 bytes en la Uno, 4 en placas de 32 bits.')
    ]),
    L('n11', 'Cuentas en el microcontrolador', 'code', ['mc_intmath', 'mc_opertype', 'mc_bitops'], [
      Q('int x = 7 / 2; ¿cuánto crees que vale x?', ['3', '3,5', '4', '2'], 'Entre números enteros, la división descarta los decimales: 3. No redondea: corta.', { predict: true, c: 'mc_intmath', h: 'Una variable int no guarda decimales.' }),
      I('Operadores: <b>+ − * /</b> y <b>%</b> (resto). Entre enteros, <b>/ descarta los decimales</b>: 7 / 2 da 3. Y <b>%</b> da lo que sobra: 7 % 2 da 1.'),
      { t: 'explore', text: 'a / b son los grupos completos (azul) y a % b lo que sobra (naranja).', viz: 'intDiv', params: pDiv(17, 5),
        tasks: [
          { q: 'r', min: 0, max: 0, text: 'Busca una división exacta (resto 0)', done: 'Si a es múltiplo de b, no sobra nada.', hint: 'Prueba a = 20 con b = 5.' },
          { q: 'minsec', min: 1, max: 1, text: 'Divide 125 segundos entre 60', done: '125 / 60 = 2 minutos y 125 % 60 = 5 segundos.', hint: 'a = 125 y b = 60.' },
          { q: 'impar', min: 1, max: 1, text: 'Comprueba con % 2 si un número es impar', done: 'n % 2 vale 1 en los impares y 0 en los pares.', hint: 'b = 2 y un a impar.' }
        ] },
      Q('¿Cuánto vale x?', ['3', '3,8', '4', '0'], 'División entera: 19 / 5 = 3 y sobran 4. No se redondea a 4.', { c: 'mc_intmath', code: 'int x = 19 / 5;', h: '¿Cuántos grupos completos de 5 caben en 19?' }),
      Q('¿Y r?', ['4', '3', '0', '3,8'], '19 = 5 × 3 + 4: el resto es 4.', { c: 'mc_intmath', code: 'int r = 19 % 5;', h: 'Lo que sobra tras los grupos completos.' }),
      G('intDivMod'), G('intDivMod'),
      I('El resto es muy útil para lo que se repite en ciclo:\n· <b>n % 2</b> vale 0 si n es par.\n· <b>(paso + 1) % 4</b> recorre 0, 1, 2, 3, 0, 1…\n· <b>segundos % 60</b> da los segundos dentro del minuto.', { code: 'paso = (paso + 1) % 4;   // 0, 1, 2, 3, 0, 1, 2, 3...' }),
      { t: 'steps', text: 'La variable s vale 125 segundos. Escríbelo como minutos y segundos.', steps: ['Minutos: división entera, <b>s / 60</b> = 125 / 60 = <b>2</b>', 'Segundos que sobran: <b>s % 60</b> = 125 − 2 × 60 = <b>5</b>', 'Comprueba: 2 × 60 + 5 = 125 ✓'], result: '2 min 5 s.' },
      Q('La variable s vale 125 (segundos). ¿Qué dos expresiones dan «2 min 5 s»?', ['s / 60 y s % 60', 's % 60 y s / 60', 's / 60 y s - 60', 's * 60 y s % 60'], 'Minutos: división entera. Segundos sobrantes: el resto.', { c: 'mc_intmath', h: 'Primero los grupos completos de 60, luego lo que sobra.' }),
      I('Para tener decimales, al menos un número de la cuenta debe ser decimal. Guardar en un float no basta, porque la división entre enteros se hace <b>antes</b> de guardar.', { code: 'float a = 7 / 2;     // 3.0  (entera y luego a float)\nfloat b = 7.0 / 2;   // 3.5' }),
      Q('¿Qué guarda nota?', ['9,25', '9', '0', '10'], '37 × 10.0 / 40 = 9,25: el 10.0 hace que la cuenta tenga decimales. Con 10 en vez de 10.0 saldría 9.', { c: 'mc_opertype', code: 'int puntos = 37;\nfloat nota = puntos * 10.0 / 40;', h: '¿Hay algún número con decimales en la cuenta?' }),
      I('<b>Precedencia</b>: como en matemáticas, * / % van antes que + −. En caso de duda, paréntesis.\nY cuidado con los <b>resultados intermedios</b>: en la Uno, 60 * 1000 se calcula como int, y 60 000 no cabe en un int. Se escribe <b>60 * 1000UL</b> (UL: unsigned long).'),
      Q('En la Uno quieres esperar 2 minutos con delay(). ¿Qué línea es correcta?', ['delay(2 * 60 * 1000UL);', 'delay(2 * 60 * 1000);', 'delay(120);', 'delay(2 / 60);'], 'Sin UL, 120 000 se calcula como int en la Uno y sale un número absurdo. delay(120) son 0,12 s.', { c: 'mc_opertype', code: '// 2 min = 120 000 ms', h: '¿Cabe 120 000 en un int de la Uno?' }),
      I('Los <b>operadores de bits</b> trabajan con los unos y ceros de un número (l1): <b>1 &lt;&lt; k</b> es un 1 desplazado k posiciones (2ᵏ); <b>|</b> pone bits a 1, <b>&amp;</b> los filtra y <b>~</b> los invierte. Los usarás a fondo con los registros del chip.', { code: 'byte x = 0b00000100;\nx |= (1 << 0);    // x = 0b00000101 = 5\nx &= ~(1 << 2);   // x = 0b00000001 = 1' }),
      { t: 'bits', q: 'Enciende los bits de (1 << 6) | (1 << 1).', n: 8, target: 66, e: '64 + 2 = 66.', c: 'mc_bitops', h: '1 << 6 es el bit de peso 64; 1 << 1, el de peso 2.' },
      G('bitMask'),
      RES('Entre enteros, <b>/</b> corta los decimales y <b>%</b> da el resto.', '% para ciclos, pares e impares, minutos y segundos.', 'Un número con decimales (con punto en el código) para que la cuenta los tenga; <b>UL</b> para intermedios grandes.', '<b>1 &lt;&lt; k</b>, <b>|</b>, <b>&amp;</b>, <b>~</b>: bits a mano.')
    ]),
    L('n12', 'Decisiones y bucles', 'code', ['mc_if', 'mc_flow'], [
      Q('Un programa dice: si t > 30, enciende el ventilador. Con t = 30, ¿se enciende?', ['No: 30 no es mayor que 30', 'Sí', 'Depende de la placa', 'Da error'], '> es «estrictamente mayor». Para incluir el 30, hace falta >=. Los bordes son la fuente de muchos errores.', { predict: true, c: 'mc_if', h: '¿Es 30 mayor que 30?' }),
      I('<b>if</b> ejecuta un bloque solo si la condición es cierta; <b>else</b>, si no lo es. Comparadores: <b>==</b> igual, <b>!=</b> distinto, <b>&lt; &gt; &lt;= &gt;=</b>. Se combinan con <b>&amp;&amp;</b> (y), <b>||</b> (o) y <b>!</b> (no).', { code: 'if (temp > 30 && ventiladorLibre) {\n  digitalWrite(VENT, HIGH);\n} else {\n  digitalWrite(VENT, LOW);\n}' }),
      { t: 'explore', text: 'Una cadena if / else if / else que elige un LED según la temperatura t. Mueve t y mira qué rama se ejecuta.', viz: 'flowTrace', params: { t: SL('t', 10, 0, 40, 1) },
        tasks: [
          { q: 'branch', min: 0, max: 0, text: 'Haz que se encienda el rojo', done: 'Con t > 30 se cumple la primera condición y las demás ni se miran.', hint: 'Sube t por encima de 30.' },
          { q: 'branch', min: 1, max: 1, text: 'Ahora el amarillo', done: 'La primera es falsa y la segunda cierta.', hint: 't entre 21 y 30.' },
          { q: 't30', min: 1, max: 1, text: 'Pon t justo en 30', done: 'Amarillo: 30 no es mayor que 30. Si quisieras el rojo, harías falta t >= 30.', hint: 't = 30.' }
        ] },
      Q('¿Dónde está el fallo?', ['Usa = (asignar) en vez de == (comparar): x pasa a valer 5 y la condición siempre se cumple', 'Faltan llaves', 'x no puede compararse con 5', 'Falta un punto y coma tras el if'], 'Error clásico: compila y hace otra cosa.', { c: 'mc_if', code: 'if (x = 5) {\n  digitalWrite(13, HIGH);\n}', h: 'Cuenta los signos igual.' }),
      Q('Con t = 25, ¿qué LED se enciende?', ['El amarillo', 'El rojo', 'El verde', 'El amarillo y el verde'], '25 no es mayor que 30, pero sí que 20. En cuanto se cumple una rama, las demás se saltan.', { c: 'mc_if', code: 'if (t > 30) {\n  encender(ROJO);\n} else if (t > 20) {\n  encender(AMARILLO);\n} else {\n  encender(VERDE);\n}', h: 'Prueba las condiciones de arriba abajo.' }),
      Q('¿Cuándo se cumple esta condición?', ['Si t es menor que 5 o mayor que 35', 'Si t está entre 5 y 35', 'Nunca', 'Siempre'], '|| se cumple con que una de las dos sea cierta: fuera del rango.', { c: 'mc_if', code: 'if (t < 5 || t > 35)', h: '|| significa «o».' }),
      I('El bucle <b>for</b> repite algo un número de veces. Tiene tres partes: inicio, condición para seguir y qué hacer al final de cada vuelta. <b>while</b> repite mientras su condición sea cierta.', { code: 'for (int i = 0; i < 3; i++) {\n  Serial.println(i);\n}\n// imprime 0, 1 y 2' }),
      { t: 'explore', text: 'Un for y los valores que toma i. Cambia sus partes y cuenta las vueltas.', viz: 'forTrace', params: { i0: LS('Inicio', 0, [0, 1]), N: SL('Límite', 3, 1, 10, 1), op: LS('Comparación (0 <, 1 <=)', 0, [0, 1]), step: LS('Paso (1 i++, 2 i += 2)', 1, [1, 2]) },
        tasks: [
          { q: 'count', min: 5, max: 5, text: 'Que el bucle dé 5 vueltas', done: 'Desde 0 con i < 5: 0, 1, 2, 3 y 4.', hint: 'Inicio 0, límite 5 y <.' },
          { q: 'le6', min: 1, max: 1, text: 'Cambia < por <= con inicio 0 y límite 5', done: '¡6 vueltas! Con <= se incluye el 5. Es el error más típico.', hint: 'Comparación 1.' }
        ] },
      Q('¿Cuántas veces parpadea?', ['5', '4', '6', 'Sin parar'], 'i toma 0, 1, 2, 3 y 4: cinco vueltas. Con i <= 5 serían seis.', { c: 'mc_flow', code: 'for (int i = 0; i < 5; i++) {\n  digitalWrite(13, HIGH); delay(200);\n  digitalWrite(13, LOW);  delay(200);\n}', h: 'Escribe los valores de i que cumplen la condición.' }),
      Q('¿Qué imprime?', ['10 8 6 4 2', '10 8 6 4 2 0', '2 4 6 8 10', '10 9 8 7 6'], 'Empieza en 10, resta 2 en cada vuelta y para cuando i ya no es mayor que 0.', { c: 'mc_flow', code: 'for (int i = 10; i > 0; i -= 2) {\n  Serial.print(i);\n  Serial.print(" ");\n}', h: '¿Se cumple 0 > 0?' }),
      Q('¿Qué le pasa a este programa?', ['Se queda atrapado: n nunca cambia dentro del while', 'Imprime 0, 1, 2… hasta 9', 'No compila', 'Imprime una sola vez'], 'Algo dentro del while debe acabar haciendo falsa la condición.', { c: 'mc_flow', code: 'int n = 0;\nwhile (n < 10) {\n  Serial.println(n);\n}', h: '¿Cambia n dentro del bucle?' }),
      I('Recuerda que <b>loop()</b> ya es un bucle infinito. Un while que espera algo bloquea todo lo demás mientras espera, igual que delay(). Para esperar sin bloquear, usa un if y deja que loop() vuelva a pasar (lo trabajarás en el siguiente módulo).'),
      { t: 'order', q: 'Ordena las líneas: el LED del 13 parpadea 3 veces al arrancar y luego se queda apagado.', items: ['void setup() {', 'pinMode(13, OUTPUT);', 'for (int i = 0; i < 3; i++) {', 'digitalWrite(13, HIGH); delay(300);', 'digitalWrite(13, LOW); delay(300);', '}   // fin del for', '}   // fin de setup()'], e: 'Primero se configura el pin; luego el bucle con su cuerpo, encendiendo antes de apagar; y se cierran las llaves de dentro hacia fuera.', c: 'mc_flow', h: 'Al arrancar → setup(). Las llaves se cierran de dentro hacia fuera.' },
      RES('<b>==</b> compara, <b>=</b> guarda. &amp;&amp; (y), || (o).', 'En una cadena de else if solo actúa la primera rama cierta.', '<b>for</b>: inicio, condición, paso. i &lt; N da N vueltas; i &lt;= N, una más.', 'Un while sin salida cuelga el programa.')
    ]),
    L('n13', 'Funciones y parámetros', 'code', ['mc_func', 'mc_scope'], [
      Q('Tienes que hacer parpadear tres LEDs distintos, cada uno un número de veces. ¿Qué crees que es mejor?', ['Escribir el parpadeo una vez como función y llamarla con distintos datos', 'Copiar y pegar el código tres veces', 'Hacer tres programas', 'No se puede'], 'Una función se escribe una vez y se usa muchas. Si hay un fallo, se arregla en un solo sitio.', { predict: true, c: 'mc_func', h: 'Piensa en qué pasa si luego encuentras un fallo en el código copiado.' }),
      I('Una <b>función</b> es un trozo de programa con nombre que puedes usar muchas veces. setup() y loop() son funciones, y digitalWrite() también, solo que ya viene escrita.'),
      I('Partes: el tipo que devuelve (<b>void</b> si no devuelve nada), el nombre, los <b>parámetros</b> entre paréntesis y el cuerpo entre llaves.', { code: 'void parpadear(int pin, int veces) {\n  for (int i = 0; i < veces; i++) {\n    digitalWrite(pin, HIGH); delay(150);\n    digitalWrite(pin, LOW);  delay(150);\n  }\n}\n\n// uso:\nparpadear(13, 3);' }),
      { t: 'steps', text: 'Sigue la llamada parpadear(8, 2) desde loop().', code: 'void loop() {\n  parpadear(8, 2);\n  delay(1000);\n}', steps: ['loop() llega a parpadear(8, 2) y <b>salta a la función</b>', 'Los valores entran en orden: <b>pin = 8</b> y <b>veces = 2</b>', 'El for da 2 vueltas: dos destellos en el pin 8', 'La función termina y el programa <b>vuelve justo detrás</b> de la llamada: delay(1000)'], result: 'Dos destellos, un segundo de pausa, y vuelta a empezar.' },
      Q('¿Qué hace parpadear(8, 2)?', ['Dos destellos en el LED del pin 8', 'Ocho destellos en el pin 2', 'Nada: falta pinMode dentro de la función', 'Un destello de 8 ms'], 'Los valores se asignan en orden: pin = 8 y veces = 2. (pinMode se hace una vez en setup().)', { c: 'mc_func', h: 'El primer valor va al primer parámetro.' }),
      I('Una función puede <b>devolver</b> un resultado con <b>return</b>. El tipo escrito delante del nombre dice qué devuelve.', { code: 'float aFahrenheit(float c) {\n  return c * 1.8 + 32;\n}\n\nfloat f = aFahrenheit(25);   // 77.0' }),
      Q('¿Qué imprime?', ['10', '7', '25', '5'], 'doble(5) devuelve 5 × 2 = 10.', { c: 'mc_func', code: 'int doble(int x) {\n  return x * 2;\n}\n\nvoid loop() {\n  Serial.println(doble(5));\n}', h: 'Sustituye x por 5 dentro de la función.' }),
      Q('¿Dónde está el fallo?', ['Dice que devuelve int pero no tiene return', 'Sobran los paréntesis', 'Los parámetros no pueden llamarse a y b', 'Debería llamarse loop'], 'Sin return, lo que llega es basura. El compilador suele avisar: hazle caso.', { c: 'mc_func', code: 'int suma(int a, int b) {\n  int s = a + b;\n}', h: 'Mira qué promete la cabecera y qué hace el cuerpo.' }),
      I('<b>Ámbito</b>: una variable creada dentro de una función (<b>local</b>) solo existe ahí y se crea de nuevo en cada llamada. Una creada fuera de todas (<b>global</b>) existe siempre y la ven todas las funciones.'),
      Q('¿Qué imprime en la tercera vuelta de loop()?', ['1', '3', '0', '2'], 'n es local: se crea con 0 en cada vuelta, sube a 1 y desaparece.', { c: 'mc_scope', code: 'void loop() {\n  int n = 0;\n  n++;\n  Serial.println(n);\n}', h: '¿Dónde se crea n?' }),
      Q('¿Y ahora, en la tercera vuelta?', ['3', '1', '0', 'Error'], 'n es global: conserva su valor entre vueltas de loop().', { c: 'mc_scope', code: 'int n = 0;\n\nvoid loop() {\n  n++;\n  Serial.println(n);\n}', h: 'Ahora n vive fuera de loop().' }),
      I('Los parámetros se pasan <b>por valor</b>: la función recibe una copia. Si cambia su copia, la variable original sigue igual. Para obtener un resultado, usa return.'),
      Q('¿Qué imprime?', ['5', '6', '0', 'Error'], 'subir() cambia su copia de x, no la variable a.', { c: 'mc_func', code: 'void subir(int x) {\n  x = x + 1;\n}\n\nvoid loop() {\n  int a = 5;\n  subir(a);\n  Serial.println(a);\n}', h: 'La función trabaja con una copia.' }),
      { t: 'match', q: 'Une cada cabecera con lo que hace.', pairs: [['void encender(int pin)', 'Recibe un pin y no devuelve nada'], ['int leerMedia()', 'No recibe nada y devuelve un entero'], ['bool pulsado(int pin)', 'Devuelve verdadero o falso'], ['float aCelsius(int raw)', 'Recibe un entero y devuelve un número con decimales']], c: 'mc_func', h: 'Delante del nombre, lo que devuelve; entre paréntesis, lo que recibe.' },
      RES('Función = nombre + parámetros + cuerpo; se escribe una vez y se llama muchas.', '<b>void</b> no devuelve; si promete un tipo, necesita <b>return</b>.', 'Local: nace en cada llamada. Global: vive siempre.', 'Parámetros por valor: copias.')
    ]),
    L('n14', 'Arrays: muchos pines, un bucle', 'code', ['mc_array', 'mc_varbytes', 'mc_intmath'], [
      Q('Tienes 8 LEDs en 8 pines. ¿Cuántas líneas de pinMode crees que necesitas?', ['Una dentro de un bucle, si guardas los pines en una lista', '8, siempre', 'Una sin bucle', '16'], 'Con un array guardas los 8 pines y un for los recorre: el mismo código sirve para 8 o para 50.', { predict: true, c: 'mc_array', h: 'Recuerda que un for repite una línea las veces que quieras.' }),
      I('Un <b>array</b> es una fila de variables del mismo tipo bajo un solo nombre. Cada una se alcanza por su <b>índice</b>, que empieza en <b>0</b>.', { code: 'int leds[] = {8, 9, 10, 11, 12};\n// leds[0] es 8 y leds[4] es 12' }),
      { t: 'explore', text: 'Un array con los pines de 5 LEDs. Mueve el índice.', viz: 'arrayIdx', params: { i: SL('Índice i', 0, 0, 5, 1) },
        tasks: [
          { q: 'i', min: 2, max: 2, text: 'Enciende el LED de leds[2]', done: 'El tercer elemento (índices 0, 1, 2): el pin 10.', hint: 'Índice 2.' },
          { q: 'out', min: 1, max: 1, text: 'Prueba leds[5]', done: 'No existe: el último es leds[4]. C++ no avisa: lee lo que haya detrás en memoria.', hint: 'Índice 5.' }
        ] },
      Q('¿Cuánto vale leds[2]?', ['10', '9', '2', '11'], 'Índices 0, 1, 2: es el tercer elemento.', { c: 'mc_array', code: 'int leds[] = {8, 9, 10, 11, 12};', h: 'El primero es el índice 0.' }),
      I('Con un <b>for</b> recorres el array: el mismo código sirve para 5 LEDs o para 50. Así se hacen barridos, barras de nivel o secuencias.', { code: 'const int N = 5;\nint leds[N] = {8, 9, 10, 11, 12};\n\nvoid setup() {\n  for (int i = 0; i < N; i++) pinMode(leds[i], OUTPUT);\n}' }),
      { t: 'pin', q: '¿En qué pin está el último LED que se enciende?', code: 'int leds[] = {3, 5, 6, 9, 10};\nfor (int i = 0; i < 5; i++) {\n  digitalWrite(leds[i], HIGH);\n  delay(100);\n  digitalWrite(leds[i], LOW);\n}', a: 'D10', e: 'El índice 4 es el quinto elemento: el 10.', c: 'mc_array', h: 'La última vuelta usa i = 4.' },
      Q('¿Dónde está el fallo?', ['leds[5] no existe: el array va de 0 a 4 y se escribe en memoria ajena', 'Falta pinMode', 'El for debería empezar en 1', 'Ninguno'], 'Con <= se da una vuelta de más. C++ no comprueba los límites.', { c: 'mc_array', code: 'int leds[5] = {8, 9, 10, 11, 12};\nfor (int i = 0; i <= 5; i++) {\n  digitalWrite(leds[i], HIGH);\n}', h: '¿Cuál es el último valor de i?' }),
      I('Salirse de un array es de los errores más traicioneros: puede pisar otra variable y el fallo aparece lejos de su causa. Recorre siempre con <b>i &lt; N</b> y usa una constante N en vez de repetir el número a mano.'),
      Q('Un array de 20 int en la Uno, ¿cuánta RAM ocupa?', ['40 bytes', '20 bytes', '80 bytes', '2 bytes'], 'Cada int ocupa 2 bytes en la Uno: 20 × 2. Y la Uno solo tiene 2048 bytes de RAM en total.', { c: 'mc_varbytes', h: 'Elementos por bytes de cada uno.' }),
      G('arrayRam'),
      I('Los arrays también guardan datos: las últimas medidas, las notas de una melodía, los tiempos de un semáforo… Un truco clásico es el <b>buffer circular</b>: escribes en la posición i y avanzas con i = (i + 1) % N, sobrescribiendo lo más antiguo.', { code: 'datos[i] = nuevoDato;\ni = (i + 1) % N;' }),
      Q('Con N = 4 e i empezando en 0, ¿en qué posición se guarda el sexto dato?', ['1', '5', '2', '0'], 'Posiciones: 0, 1, 2, 3, 0, 1. El sexto sobrescribe el segundo.', { c: 'mc_intmath', h: 'Escribe las posiciones una a una: tras el 3 viene el 0.' }),
      Q('¿Qué imprime?', ['20', '4', '8', '0'], 'Suma 2 + 4 + 6 + 8 = 20.', { c: 'mc_array', code: 'int v[] = {2, 4, 6, 8};\nint s = 0;\nfor (int i = 0; i < 4; i++) s += v[i];\nSerial.println(s);', h: 's va acumulando cada elemento.' }),
      { t: 'steps', text: 'Barrido: los 5 LEDs se encienden uno tras otro.', code: 'for (int i = 0; i < N; i++) {\n  digitalWrite(leds[i], HIGH);\n  delay(120);\n  digitalWrite(leds[i], LOW);\n}', steps: ['i = 0: enciende leds[0] (pin 8), espera 120 ms, lo apaga', 'i = 1: lo mismo con el pin 9', '… y así hasta i = 4 (pin 12)', 'i = 5 ya no cumple i < 5: el for termina y loop() vuelve a empezar'], result: 'Una luz que corre de un lado a otro, con 5 líneas de código.' },
      { t: 'order', q: 'Ordena el cuerpo de loop() que enciende los LEDs uno tras otro (barrido).', items: ['for (int i = 0; i < N; i++) {', 'digitalWrite(leds[i], HIGH);', 'delay(120);', 'digitalWrite(leds[i], LOW);', '}'], e: 'Para cada LED: encender, esperar y apagar, todo dentro del bucle.', c: 'mc_array', h: 'Abre el bucle, haz las tres cosas y ciérralo.' },
      RES('Índices desde <b>0</b>: el último es N − 1.', 'Un <b>for con i &lt; N</b> recorre el array entero.', 'Salirse no avisa: pisa memoria ajena.', 'Memoria = elementos × tamaño; buffer circular con <b>% N</b>.')
    ]),
    SIM('s7b', 'Reto: semáforo', 'Monta las tres luces en los pines del programa.', { arduino: 'semaforo', parts: ['res', 'led'], code: true, hint: 'LEDs en 12, 11 y 10, cada uno con su resistencia a GND.' }, 'traffic'),
    PRJ('p7', 'Proyecto: semáforo real', 'traffic')
  ] });
})();
