/* Voltio · curso base, módulo 18: Microcontroladores III: tiempo y estados
   Lote 6. Visualizaciones propias: millisTimeline, fsm, isrTimeline, ramBar. Generadores mc2…
   y conceptos de sus lecciones (mc_millis, mc_elapsed, mc_ulong, mc_tasks, mc_debounce, mc_edge,
   mc_fsm, mc_switch, mc_isr, mc_isrrules, mc_memwhere, mc_ram, mc_eeprom). */
(() => {
  const { num, st } = Widgets.H;
  const tx = (x, y, s, cls = 'vizsm', extra = '') => `<text x="${x}" y="${y}" class="${cls}" ${extra}>${s}</text>`;

  /* ================= VISUALIZACIONES ================= */
  // Simula loop() durante 3 s: cada vuelta tarda 1 ms más el bloqueo (delay) y mira dos tareas con millis()
  const simTasks = p => {
    let t = 0, lA = 0, lB = 0, late = 0; const eA = [], eB = [];
    for (let k = 0; k < 4000 && t <= 3000; k++) {
      if (p.iA > 0 && t - lA >= p.iA) { late = Math.max(late, t - (lA + p.iA)); eA.push(t); lA = p.mode ? lA + p.iA : t; }
      if (p.iB > 0 && t - lB >= p.iB) { eB.push(t); lB = p.mode ? lB + p.iB : t; }
      t += 1 + p.blk;
    }
    return { eA, eB, late };
  };
  Object.assign(Widgets.VIZ, {
    millisTimeline: {
      calc: p => {
        const s = simTasks(p), nA = s.eA.length, nB = s.eB.length;
        return { nA, nB, late: s.late, eA: s.eA, eB: s.eB, clean500: p.blk === 0 && p.iA === 500 ? 1 : 0, ab: p.iA === 250 && p.iB === 1000 && p.blk === 0 ? 1 : 0,
          drift: p.mode === 0 && p.blk >= 30 && p.iA === 250 ? 1 : 0, fix: p.mode === 1 && p.blk >= 30 && p.iA === 250 ? 1 : 0 };
      },
      svg: (p, o) => {
        const X = t => (20 + t / 3000 * 268).toFixed(1);
        let ideal = ''; for (let t = p.iA; t <= 3000; t += p.iA) ideal += `<path d="M${X(t)} 30V62" stroke="var(--muted)" stroke-dasharray="2 3" opacity=".6"/>`;
        const tA = o.eA.map(t => `<path d="M${X(t)} 34V58" stroke="var(--led)" stroke-width="3"/>`).join('');
        const tB = o.eB.map(t => `<path d="M${X(t)} 84V108" stroke="var(--ice)" stroke-width="3"/>`).join('');
        const blk = p.blk > 0 ? `<rect x="20" y="124" width="268" height="12" rx="3" fill="var(--err)" opacity="${Math.min(0.8, 0.15 + p.blk / (p.blk + 1) * 0.6).toFixed(2)}"/>${tx(20, 150, `loop(): ${p.blk} ms parado en delay() de cada ${p.blk + 1} ms`, 'vizsm', 'style="fill:var(--err)"')}` : `<rect x="20" y="124" width="268" height="12" rx="3" fill="var(--ok)" opacity=".35"/>${tx(20, 150, 'loop() da una vuelta cada 1 ms: nada bloquea', 'vizsm')}`;
        return `<svg viewBox="0 0 300 180" class="viz">${[0, 1, 2, 3].map(s => `<path d="M${X(s * 1000)} 26V140" stroke="var(--line)"/>${tx(X(s * 1000), 176, s + ' s', 'vizsm', 'text-anchor="middle"')}`).join('')}
          ${ideal}${tA}${tx(20, 24, `A cada ${p.iA} ms: ${o.nA} veces${o.late > 0 ? ` · ${o.late} ms tarde` : ''}`, 'vizlab')}
          ${p.iB > 0 ? tB + tx(20, 80, `B cada ${p.iB} ms: ${o.nB} veces`, 'vizlab') : tx(20, 96, 'Tarea B: desactivada', 'vizsm')}${blk}
          ${p.mode ? tx(288, 80, 'antes += intervalo', 'vizsm', 'text-anchor="end"') : ''}</svg>`;
      }
    },
    // Semáforo con pulsador de peatón: VERDE → (pulsan) → ÁMBAR → (2 s) → ROJO → (3 s) → VERDE
    fsm: {
      calc: p => {
        let st = 0, tin = p.t, back = 0;
        if (p.tp > 0 && p.t >= p.tp) { const d = p.t - p.tp; if (d < 2) { st = 1; tin = d; } else if (d < 5) { st = 2; tin = d - 2; } else { st = 0; tin = d - 5; back = 1; } }
        return { st, tin, back, amb: st === 1 ? 1 : 0, red: st === 2 ? 1 : 0 };
      },
      svg: (p, o) => {
        const S = [['VERDE', 55, 62, 'var(--ok)'], ['ÁMBAR', 245, 62, 'var(--led)'], ['ROJO', 150, 130, 'var(--err)']];
        const nodes = S.map(([n, x, y, c], i) => `<circle cx="${x}" cy="${y}" r="27" fill="${o.st === i ? c : 'none'}" stroke="${c}" stroke-width="3" ${o.st === i ? 'class="a-pulse"' : ''}/><text x="${x}" y="${y + 4}" text-anchor="middle" class="vizlab" style="${o.st === i ? 'fill:#1B1300' : ''}">${n}</text>`).join('');
        const arr = `<path d="M84 56H214" ${st}/><path d="M214 56l-8 -5v10z" fill="currentColor"/>${tx(150, 48, 'pulsan', 'vizsm', 'text-anchor="middle"')}
          <path d="M228 86L180 118" ${st}/><path d="M180 118l9 -1l-4 -8z" fill="currentColor"/>${tx(222, 112, '2 s', 'vizsm')}
          <path d="M120 118L72 86" ${st}/><path d="M72 86l3 9l5 -7z" fill="currentColor"/>${tx(66, 112, '3 s', 'vizsm')}`;
        const X = t => (20 + t / 12 * 260).toFixed(1); let bar = '';
        const seg = (a, b, c) => b > a ? `<rect x="${X(a)}" y="178" width="${(X(b) - X(a)).toFixed(1)}" height="10" fill="${c}"/>` : '';
        if (p.tp > 0) bar = seg(0, p.tp, 'var(--ok)') + seg(p.tp, Math.min(12, p.tp + 2), 'var(--led)') + seg(Math.min(12, p.tp + 2), Math.min(12, p.tp + 5), 'var(--err)') + seg(Math.min(12, p.tp + 5), 12, 'var(--ok)'); else bar = seg(0, 12, 'var(--ok)');
        return `<svg viewBox="0 0 300 200" class="viz">${arr}${nodes}${bar}<path d="M${X(p.t)} 174V194" stroke="currentColor" stroke-width="2.5"/>
          ${tx(20, 170, `t = ${num(p.t, 1)} s · ${p.tp > 0 ? 'pulsan a los ' + num(p.tp, 1) + ' s' : 'nadie pulsa'} · lleva ${num(o.tin, 1)} s en ${S[o.st][0]}`, 'vizsm')}</svg>`;
      }
    },
    // Pulsos de un sensor durante 1 s: cuántos ve loop() mirando el pin y cuántos cuenta la interrupción
    isrTimeline: {
      calc: p => {
        const T = 1000 / p.f, w = Math.min(p.w, T * 0.5), pulses = []; for (let t = 0.37 * T; t < 1000; t += T) pulses.push([t, t + w]);
        const hi = t => pulses.some(([a, b]) => t >= a && t < b);
        let poll = 0, prev = false; const seen = new Set();
        for (let t = 0.5; t < 1000; t += p.L) { const h = hi(t); if (h && !prev) { poll++; const k = pulses.findIndex(([a, b]) => t >= a && t < b); seen.add(k); } prev = h; }
        const real = pulses.length, lost = real - poll;
        return { real, poll, lost, lostPct: lost / real * 100, pulses, seen: [...seen], ok2: p.w === 2 && lost === 0 ? 1 : 0, w };
      },
      svg: (p, o) => {
        const X = t => (20 + t / 1000 * 268), pw = Math.max(2, o.w / 1000 * 268);
        const pl = o.pulses.map(([a], i) => `<rect x="${X(a).toFixed(1)}" y="30" width="${pw.toFixed(1)}" height="22" fill="${o.seen.includes(i) ? 'var(--ok)' : 'var(--err)'}"/>`).join('');
        let samp = ''; if (p.L >= 5) for (let t = 0.5; t < 1000; t += p.L) samp += `<path d="M${X(t).toFixed(1)} 74V88" stroke="var(--muted)" stroke-width="1.2"/>`; else samp = `<rect x="20" y="74" width="268" height="14" fill="var(--muted)" opacity=".5"/>`;
        const isr = o.pulses.map(([a]) => `<rect x="${X(a).toFixed(1)}" y="110" width="3" height="18" fill="var(--led)"/>`).join('');
        return `<svg viewBox="0 0 300 175" class="viz">${tx(20, 24, `Pulsos del sensor (verde: vistos por loop(); rojo: perdidos)`)}${pl}
          ${tx(20, 70, `loop() mira el pin una vez cada ${p.L} ms`)}${samp}
          ${tx(20, 106, 'Interrupción: salta en cada flanco y corta a loop()')}<rect x="20" y="116" width="268" height="6" rx="3" fill="var(--line)"/>${isr}
          ${tx(20, 150, `Reales ${o.real} · loop() cuenta ${o.poll} · interrupción ${o.real}`, 'vizlab')}${tx(20, 168, o.lost ? `Sondeando se pierden ${o.lost} (${num(o.lostPct, 0)} %)` : 'Sondeando no se pierde ninguno', 'vizsm', `style="fill:${o.lost ? 'var(--err)' : 'var(--ok)'}"`)}</svg>`;
      }
    },
    // La SRAM de 2 KB de la Uno: lo fijo, las globales, los buffers, los textos y lo que queda para la pila
    ramBar: {
      calc: p => {
        const core = 200, txt = p.F ? 0 : p.txt, used = core + p.glob + p.buf + txt, free = 2048 - used;
        return { used, free, pct: used / 2048 * 100, freeF: p.F === 1 && free >= 500 ? 1 : 0, big: p.buf >= 600 && free >= 300 ? 1 : 0, risk: free < 300 ? 1 : 0 };
      },
      svg: (p, o) => {
        const H = 150, y0 = 165, sc = H / 2048, parts = [[200, 'var(--muted)', 'Arduino y Serial'], [p.glob, 'var(--ice)', 'Variables globales'], [p.buf, 'var(--gem)', 'Buffers (arrays)'], [p.F ? 0 : p.txt, 'var(--err)', 'Textos copiados a la RAM']];
        let y = y0, s = '', leg = '';
        parts.forEach(([b, c, l], i) => { const h = Math.max(0, Math.min(b, 2048)) * sc; y -= h; if (h > 0) s += `<rect x="40" y="${y.toFixed(1)}" width="60" height="${h.toFixed(1)}" fill="${c}" opacity=".8"/>`; leg += `<rect x="120" y="${30 + i * 20}" width="12" height="12" rx="2" fill="${c}"/>${tx(138, 40 + i * 20, `${l}: ${b} B`)}`; });
        const stack = 300 * sc, top = y0 - H;
        s += `<rect x="40" y="${top}" width="60" height="${stack.toFixed(1)}" fill="none" stroke="var(--led)" stroke-dasharray="4 3"/>${tx(70, top - 4, 'pila ↓', 'vizsm', 'text-anchor="middle"')}`;
        return `<svg viewBox="0 0 300 180" class="viz"><rect x="40" y="${top}" width="60" height="${H}" fill="none" stroke="currentColor" stroke-width="1.5"/>${s}${tx(36, y0, '0', 'vizsm', 'text-anchor="end"')}${tx(36, top + 8, '2 KB', 'vizsm', 'text-anchor="end"')}
          ${leg}${tx(120, 124, `Usado ${o.used} B (${num(o.pct, 0)} %)`, 'vizlab')}${tx(120, 144, o.free >= 0 ? `Libre para la pila: ${o.free} B` : 'No cabe: falta RAM', 'vizlab', `style="fill:${o.risk ? 'var(--err)' : 'var(--ok)'}"`)}
          ${o.risk ? tx(120, 162, '¡La pila puede pisar variables!', 'vizsm', 'style="fill:var(--err)"') : tx(120, 162, 'La pila tiene margen', 'vizsm')}</svg>`;
      }
    }
  });

  /* ================= GENERADORES ================= */
  const { pick, ri, fmt, MC, N } = Gen.helpers;
  Gen.add('mc2Elapsed', () => {
    const iv = pick([100, 250, 500, 1000, 2000]), antes = ri(10, 500) * 100, d = ri(Math.round(iv * 0.4), Math.round(iv * 1.6)), ahora = antes + d, ok = d >= iv;
    if (Math.random() < 0.4) return { ...N(`millis() vale ${ahora} y antes vale ${antes}. ¿Cuántos ms han pasado?`, d, 'ms', `${ahora} − ${antes} = ${d} ms.`), h: 'Tiempo pasado = ahora − antes.' };
    const si = `Sí: han pasado ${d} ms`, no = `No: solo han pasado ${d} ms`;
    return { ...MC(`antes = ${antes}, millis() = ${ahora} e intervalo = ${iv} ms. ¿Se ejecuta la tarea en esta vuelta?`, ok ? si : no, [ok ? no : si, `Sí: ${ahora} es mayor que ${iv}`, 'No se puede saber sin delay()'], `ahora − antes = ${d} ms, que ${ok ? 'llega' : 'no llega'} a ${iv} ms.`), h: 'Resta antes a millis() y compara con el intervalo usando >=.' };
  }, 'mc_elapsed');
  Gen.add('mc2Count', () => {
    if (Math.random() < 0.5) { const T = pick([20, 50, 100, 200, 250, 500, 1000, 2000]), S = pick([10, 30, 60]); return { ...N(`Una tarea usa if (millis() - t >= ${T}). ¿Cuántas veces se ejecuta en ${S} s?`, S * 1000 / T, 'veces', `${S * 1000} ms / ${T} ms = ${S * 1000 / T}.`), h: 'Pasa los segundos a milisegundos y divide entre el intervalo.' }; }
    const a = pick([100, 200, 250, 500]), b = pick([1000, 2000, 5000]), S = pick([10, 20, 60]), n = S * 1000 / a + S * 1000 / b;
    return { ...N(`Dos tareas con millis(): una cada ${a} ms y otra cada ${b} ms. ¿Cuántas ejecuciones hay en total en ${S} s?`, n, 'veces', `${S * 1000} / ${a} = ${S * 1000 / a} y ${S * 1000} / ${b} = ${S * 1000 / b}: ${n} en total.`), h: 'Cuenta cada tarea por separado y suma.' };
  }, 'mc_timecount');
  Gen.add('mc2Ulong', () => {
    const [t, max, ans, u, ex] = pick([['int', 32767, 32.767, 's', 'Un int de la Uno llega a 32 767: 32 767 ms ≈ 32,8 s.'], ['unsigned int', 65535, 65.535, 's', 'Un unsigned int de la Uno llega a 65 535: 65 535 ms ≈ 65,5 s.'], ['unsigned long', 4294967295, 49.71, 'días', '4 294 967 295 ms / 86 400 000 ms por día ≈ 49,7 días.'], ['long', 2147483647, 24.86, 'días', 'Un long llega a 2 147 483 647: unos 24,9 días; luego salta a negativo.']]);
    return { ...N(`Guardas millis() en una variable ${t} de la Uno. ¿A los cuántos ${u} deja de caber el valor?`, ans, u, ex, ans * 0.01), h: `Busca el valor máximo de un ${t} y pásalo de milisegundos a ${u}.` };
  }, 'mc_ulong');
  Gen.add('mc2Isr', () => {
    const ppv = pick([1, 2, 4, 20]), n = ppv * ri(3, 30), s = pick([1, 2, 5]), rps = n / ppv / s;
    if (Math.random() < 0.5) return { ...N(`Un sensor da ${ppv} pulso${ppv > 1 ? 's' : ''} por vuelta y la interrupción cuenta ${n} en ${s} s. ¿Cuántas vueltas por segundo?`, rps, 'vueltas/s', `${n} pulsos / ${ppv} = ${n / ppv} vueltas en ${s} s → ${fmt(rps, 2)} vueltas/s.`, 0.01), h: 'Primero pulsos → vueltas; luego divide entre el tiempo.' };
    return { ...N(`Un encoder da ${ppv} pulso${ppv > 1 ? 's' : ''} por vuelta y la interrupción cuenta ${n} en ${s} s. ¿Revoluciones por minuto (rpm)?`, rps * 60, 'rpm', `${fmt(rps, 2)} vueltas/s × 60 = ${fmt(rps * 60, 1)} rpm.`, 0.1), h: 'Saca las vueltas por segundo y multiplica por 60.' };
  }, 'mc_isr');
  Gen.add('mc2Eeprom', () => {
    if (Math.random() < 0.5) { const m = pick([1, 2, 5, 10, 30, 60]), d = 100000 * m / 1440; return { ...N(`Grabas en la misma celda de EEPROM cada ${m} min. ¿Cuántos días tardas en llegar a las 100 000 escrituras garantizadas?`, d, 'días', `100 000 × ${m} min = ${100000 * m} min; entre 1440 min por día: ${fmt(d, 1)} días.`, Math.max(0.5, d * 0.02)), h: 'Multiplica las escrituras por el tiempo entre ellas y pasa los minutos a días.' }; }
    const f = pick([1, 10, 100, 1000]), s = 100000 / f; return { ...N(`Escribes en la misma celda de EEPROM ${f} ${f === 1 ? 'vez' : 'veces'} por segundo. ¿Cuántos minutos aguanta hasta las 100 000 escrituras?`, s / 60, 'min', `100 000 / ${f} = ${fmt(s, 0)} s = ${fmt(s / 60, 1)} min.`, Math.max(0.05, s / 60 * 0.02)), h: 'Divide las escrituras entre las que haces por segundo y pasa a minutos.' };
  }, 'mc_eeprom');
  Gen.add('mc2RamBytes', () => {
    const [t, sz] = pick([['byte', 1], ['int', 2], ['long', 4], ['float', 4], ['char', 1], ['unsigned long', 4]]), n = pick([50, 64, 100, 128, 200, 250, 300, 500]), b = n * sz;
    if (Math.random() < 0.5) return { ...N(`¿Cuántos bytes de RAM ocupa ${t} datos[${n}]; en una Uno?`, b, 'bytes', `${n} × ${sz} = ${b} bytes.`), h: `Multiplica las casillas por lo que ocupa un ${t} en la Uno.` };
    return { ...N(`En una Uno (2048 bytes de RAM), ¿qué porcentaje ocupa ${t} datos[${n}];?`, b / 2048 * 100, '%', `${n} × ${sz} = ${b} bytes; ${b} / 2048 = ${fmt(b / 2048 * 100, 1)} %.`, 0.3), h: 'Calcula los bytes del array y divide entre 2048.' };
  }, 'mc_ram');

  /* ================= CONCEPTOS ================= */
  const TM = (iA, iB, blk, mode, fixB) => ({ viz: 'millisTimeline', params: { iA: { label: 'Intervalo de la tarea A', val: iA, min: 100, max: 1000, step: 50, unit: 'ms', dec: 0 }, iB: fixB ? { val: iB, fixed: true } : { label: 'Intervalo de la tarea B (0: no hay)', val: iB, min: 0, max: 2000, step: 250, unit: 'ms', dec: 0 }, blk: { label: 'delay() dentro de loop()', val: blk, min: 0, max: 600, step: 10, unit: 'ms', dec: 0 }, mode: fixB ? { val: mode, fixed: true } : { label: 'Actualizar (0: antes = ahora · 1: antes += intervalo)', val: mode, list: [0, 1], dec: 0 } } });
  const SV_BLOCK = `<svg viewBox="0 0 300 120" class="viz"><text x="10" y="16" class="vizsm">Una vuelta de loop() con dos delay(1000)</text><rect x="10" y="26" width="8" height="26" fill="var(--ok)"/><rect x="18" y="26" width="130" height="26" fill="var(--err)" opacity=".35"/><rect x="148" y="26" width="8" height="26" fill="var(--ok)"/><rect x="156" y="26" width="130" height="26" fill="var(--err)" opacity=".35"/><text x="83" y="44" text-anchor="middle" class="vizsm">delay(1000)</text><text x="221" y="44" text-anchor="middle" class="vizsm">delay(1000)</text><rect x="70" y="64" width="30" height="14" rx="3" fill="var(--led)"/><text x="105" y="76" class="vizsm">pulsas aquí: nadie mira el botón</text><path d="M85 64V54" stroke="var(--led)" stroke-width="2"/><text x="10" y="108" class="vizlab">Verde: instantes en que el programa trabaja</text></svg>`;
  const SV_ODO = `<svg viewBox="0 0 300 120" class="viz"><text x="10" y="16" class="vizsm">El cuentakilómetros de millis()</text>${['4', '2', '9', '4', '9', '6', '7', '2', '9', '5'].map((d, i) => `<rect x="${12 + i * 27}" y="26" width="24" height="34" rx="4" fill="var(--board)"/><text x="${24 + i * 27}" y="49" text-anchor="middle" class="vizbig" style="fill:#FFB000">${d}</text>`).join('')}<path d="M150 66V80" stroke="currentColor" stroke-width="2"/><path d="M150 80l-5 -6h10z" fill="currentColor"/>${['0', '0', '0', '0', '0', '0', '0', '0', '0', '0'].map((d, i) => `<rect x="${12 + i * 27}" y="84" width="24" height="26" rx="4" fill="var(--line)"/><text x="${24 + i * 27}" y="102" text-anchor="middle" class="vizlab">${d}</text>`).join('')}</svg>`;
  const SV_EDGE = `<svg viewBox="0 0 300 140" class="viz"><text x="10" y="16" class="vizsm">Pin con INPUT_PULLUP (pulsación larga)</text><path d="M20 36H80V76H220V36H280" fill="none" stroke="var(--led)" stroke-width="2.5"/><text x="10" y="40" class="vizsm">H</text><text x="10" y="80" class="vizsm">L</text><rect x="80" y="88" width="140" height="10" fill="var(--ice)" opacity=".5"/><text x="150" y="112" text-anchor="middle" class="vizsm">Nivel: «está pulsado» en cada vuelta (cientos de veces)</text><circle cx="80" cy="56" r="7" fill="var(--err)" class="a-pulse"/><text x="20" y="132" class="vizlab">Flanco de bajada: una sola vez</text><path d="M80 120V64" stroke="var(--err)" stroke-dasharray="3 3"/></svg>`;
  const SV_FALL = `<svg viewBox="0 0 300 150" class="viz">${[['case REPOSO:', 24], ['  …', 46], ['  break;', 68], ['case REGANDO:', 96], ['  …', 118]].map(([s, y], i) => `<text x="20" y="${y}" class="vizlab" style="font-family:ui-monospace,monospace;${i === 2 ? 'text-decoration:line-through;fill:var(--err)' : ''}">${s}</text>`).join('')}<path d="M170 30C220 40 220 90 170 100" fill="none" stroke="var(--err)" stroke-width="2.5" class="a-flow"/><path d="M170 100l9 -1l-5 -7z" fill="var(--err)"/><text x="196" y="66" class="vizsm" style="fill:var(--err)">sin break,</text><text x="196" y="80" class="vizsm" style="fill:var(--err)">sigue de largo</text><text x="20" y="144" class="vizsm">break sale del switch; sin él, se ejecuta también el case siguiente</text></svg>`;
  const SV_ISR = `<svg viewBox="0 0 300 120" class="viz"><text x="10" y="16" class="vizsm">loop() trabajando…</text><rect x="10" y="26" width="110" height="22" rx="4" fill="var(--ice)" opacity=".6"/><rect x="120" y="26" width="24" height="22" rx="4" fill="var(--led)" class="a-pulse"/><rect x="144" y="26" width="146" height="22" rx="4" fill="var(--ice)" opacity=".6"/><path d="M132 74V52" stroke="var(--led)" stroke-width="2.5"/><path d="M132 52l-5 7h10z" fill="var(--led)"/><text x="132" y="88" text-anchor="middle" class="vizlab">flanco en el pin → ISR</text><text x="10" y="112" class="vizsm">La ISR corta a loop(); luego loop() sigue donde iba</text></svg>`;
  const SV_VOLAT = `<svg viewBox="0 0 300 120" class="viz"><rect x="16" y="30" width="90" height="40" rx="6" fill="var(--board)"/><text x="61" y="48" text-anchor="middle" class="vizsm" style="fill:#E8EDF5">memoria</text><text x="61" y="62" text-anchor="middle" class="vizlab" style="fill:#FFB000">pulsos = 7</text><rect x="190" y="30" width="96" height="40" rx="6" fill="none" stroke="var(--err)" stroke-dasharray="4 3"/><text x="238" y="48" text-anchor="middle" class="vizsm">copia en registro</text><text x="238" y="62" text-anchor="middle" class="vizlab" style="fill:var(--err)">pulsos = 0</text><path d="M110 50H186" stroke="var(--muted)" stroke-dasharray="3 3"/><text x="148" y="44" text-anchor="middle" class="vizsm">la ISR</text><text x="16" y="90" class="vizsm">Sin volatile, loop() puede leer siempre la copia vieja.</text><text x="16" y="108" class="vizlab">volatile: «léela de la memoria cada vez»</text></svg>`;
  const SV_MEM = `<svg viewBox="0 0 300 130" class="viz">${[['Flash', '32 KB', 'el programa', 'se conserva', 'var(--ice)'], ['SRAM', '2 KB', 'las variables', 'se borra al apagar', 'var(--led)'], ['EEPROM', '1 KB', 'datos a guardar', 'se conserva', 'var(--ok)']].map(([n, s, a, b, c], i) => `<rect x="${8 + i * 98}" y="14" width="90" height="70" rx="8" fill="${c}" opacity=".25" stroke="${c}"/><text x="${53 + i * 98}" y="36" text-anchor="middle" class="vizlab">${n}</text><text x="${53 + i * 98}" y="56" text-anchor="middle" class="vizbig">${s}</text><text x="${53 + i * 98}" y="100" text-anchor="middle" class="vizsm">${a}</text><text x="${53 + i * 98}" y="116" text-anchor="middle" class="vizsm" style="fill:${i === 1 ? 'var(--err)' : 'var(--ok)'}">${b}</text>`).join('')}</svg>`;
  const SV_WEAR = `<svg viewBox="0 0 300 110" class="viz"><text x="10" y="16" class="vizsm">Vida de una celda de EEPROM</text><rect x="10" y="26" width="280" height="20" rx="6" fill="var(--line)"/><rect x="10" y="26" width="200" height="20" rx="6" fill="var(--led)" class="a-fade"/><text x="290" y="62" text-anchor="end" class="vizsm">100 000 escrituras</text><text x="10" y="80" class="vizlab">Leer: gratis · Escribir: gasta</text><text x="10" y="100" class="vizsm">Cada 60 min → 11 años · cada segundo → 28 horas</text></svg>`;
  const SV_DRIFT = `<svg viewBox="0 0 300 130" class="viz"><text x="10" y="16" class="vizsm">Intervalo 250 ms; cada ejecución llega 30 ms tarde</text>${[0, 1, 2, 3, 4].map(k => `<path d="M${20 + k * 62} 26V112" stroke="var(--line)"/>`).join('')}<text x="10" y="44" class="vizlab">antes = ahora</text>${[1, 2, 3].map(k => `<path d="M${20 + k * 69.4} 50V66" stroke="var(--err)" stroke-width="3"/>`).join('')}<text x="10" y="88" class="vizlab">antes += intervalo</text>${[1, 2, 3, 4].map(k => `<path d="M${20 + k * 62 + 7.4} 94V110" stroke="var(--ok)" stroke-width="3"/>`).join('')}<text x="10" y="126" class="vizsm">Rojo: el retraso se acumula. Verde: no se acumula.</text></svg>`;
  const SV_WRAPSUB = `<svg viewBox="0 0 300 130" class="viz"><circle cx="70" cy="66" r="48" fill="none" stroke="currentColor" stroke-width="2"/><text x="70" y="12" text-anchor="middle" class="vizsm">0 = 4 294 967 296</text><circle cx="58" cy="19" r="5" fill="var(--ice)"/><circle cx="82" cy="19" r="5" fill="var(--led)"/><path d="M58 19A48 48 0 0 1 82 19" stroke="var(--ok)" stroke-width="4" fill="none"/><text x="140" y="44" class="vizsm">antes = 4 294 967 290</text><text x="140" y="64" class="vizsm">ahora = 5 (ya dio la vuelta)</text><text x="140" y="90" class="vizlab">ahora − antes = 11 ✓</text><text x="140" y="112" class="vizsm">La resta sin signo también da la vuelta</text></svg>`;

  Object.assign(CONCEPTS, {
    mc_millis: { name: 'No bloquear: millis() en vez de delay()', alts: [
      { title: 'Mira qué pasa al bloquear', text: 'delay() deja al procesador contando sin hacer nada más. Con millis(), loop() da vueltas rapidísimas y cada vuelta mira si ya toca hacer algo. Mete un delay() en loop() y observa cómo la tarea llega tarde y se ejecuta menos veces.', tune: TM(250, 0, 0, 0, true), q: mcq('¿Qué hace delay(500) mientras espera?', ['Nada más: el programa se queda parado ahí', 'Sigue leyendo los botones', 'Duerme la placa para ahorrar', 'Ejecuta las demás tareas'], 'Por eso se usa millis() cuando hay que atender varias cosas.') },
      { title: 'El horno y el reloj', text: 'Con delay() te sientas delante del horno 20 minutos sin hacer nada. Con millis() apuntas la hora a la que lo encendiste y, mientras haces otras cosas, de vez en cuando miras el reloj: si ya han pasado 20 minutos, lo sacas. El patrón es siempre el mismo: <b>if (millis() − antes >= intervalo) { antes = millis(); …haz la tarea… }</b>.', svg: SV_BLOCK, q: mcq('¿Qué línea va dentro del if, además de la tarea?', ['antes = millis();', 'delay(intervalo);', 'millis() = 0;', 'intervalo = 0;'], 'Así la siguiente espera empieza a contar desde ahora.') }
    ] },
    mc_elapsed: { name: 'Cuánto ha pasado: millis() − antes', alts: [
      { title: 'Resta y compara con >=', text: 'Tiempo transcurrido = <b>ahora − antes</b>, en ms. Si millis() vale 12 500 y antes vale 12 000, han pasado 500 ms; con un intervalo de 500, toca (500 ≥ 500). Compara siempre con <b>>=</b>: si miras un poco tarde (502 ms), sigue cumpliéndose; con == te lo saltarías para siempre.', svg: `<svg viewBox="0 0 300 80" class="viz"><path d="M20 40H280" stroke="currentColor" stroke-width="2"/><circle cx="60" cy="40" r="6" fill="var(--ice)"/><circle cx="230" cy="40" r="6" fill="var(--led)"/><text x="60" y="26" text-anchor="middle" class="vizsm">antes 12 000</text><text x="230" y="26" text-anchor="middle" class="vizsm">ahora 12 500</text><path d="M66 56H224" stroke="var(--ok)" stroke-width="3"/><text x="145" y="74" text-anchor="middle" class="vizlab">ahora − antes = 500 ms</text></svg>`, q: mcq('antes = 3000 y millis() = 3600. Con intervalo 500, ¿toca?', ['Sí: han pasado 600 ms', 'No: 3600 no es 3500', 'No: han pasado 3600 ms', 'Solo con =='], '600 ≥ 500.') },
      { title: 'Cuando el contador da la vuelta', text: 'millis() vuelve a 0 a los 49,7 días. Si comparas <b>millis() − antes >= intervalo</b> con unsigned long, la resta también «da la vuelta» y el resultado sigue siendo correcto. Escrito como millis() >= antes + intervalo, falla justo en ese momento.', svg: SV_WRAPSUB, q: mcq('¿Qué forma sigue funcionando cuando millis() vuelve a 0?', ['millis() - antes >= intervalo', 'millis() >= antes + intervalo', 'millis() == antes + intervalo', 'millis() > intervalo'], 'La resta de unsigned long da la diferencia correcta.') },
      { title: 'El tiempo dentro de un estado', text: 'Si al entrar en un estado guardas <b>t0 = millis()</b>, entonces millis() − t0 es lo que lleva en ese estado. Así un estado puede decir «salgo a los 2 s» sin delay(): if (millis() − t0 >= 2000) cambia de estado.', q: mcq('t0 se guardó al entrar en ÁMBAR, con millis() = 8000. Ahora millis() = 9500. ¿Cuánto lleva en ÁMBAR?', ['1,5 s', '9,5 s', '8 s', '17,5 s'], '9500 − 8000 = 1500 ms.') }
    ] },
    mc_ulong: { name: 'unsigned long para guardar tiempos', alts: [
      { title: 'Un cuentakilómetros que se llena', text: 'millis() cuenta milisegundos sin parar desde que arranca la placa. Un <b>int</b> de la Uno llega a 32 767: a los 32,8 s ya no cabe y aparecen valores absurdos (incluso negativos). Un <b>unsigned long</b> (32 bits sin signo) llega a 4 294 967 295 ms, unos <b>49,7 días</b>, y entonces vuelve a 0 como un cuentakilómetros.', svg: SV_ODO, q: mcq('¿Qué tipo usas para guardar lo que devuelve millis()?', ['unsigned long', 'int', 'byte', 'float'], 'Es el tipo que devuelve millis().') },
      { title: 'Cuidado con las cuentas', text: 'Al escribir una espera larga, las cuentas también deben hacerse en unsigned long: 2 * 60 * 1000 se calcula como int en la Uno y se desborda (120 000 no cabe en 32 767). Con <b>UL</b> al final de un número (1000UL) obligas a usar unsigned long: const unsigned long ESPERA = 2 * 60 * 1000UL;', q: mcq('¿Qué línea guarda bien 5 minutos en ms en la Uno?', ['const unsigned long T = 5 * 60 * 1000UL;', 'const int T = 5 * 60 * 1000;', 'const byte T = 300000;', 'const unsigned long T = 5 * 60 * 1000;'], 'Sin UL, 5 * 60 * 1000 se calcula con int y se desborda antes de guardarse.') }
    ] },
    mc_tasks: { name: 'Varias tareas sin bloquear', alts: [
      { title: 'Cada tarea, su reloj', text: 'Cada tarea tiene su propia variable (el instante de la última vez) y su intervalo. En cada vuelta, loop() pregunta a todas: «¿te toca?». Ninguna espera. Activa la tarea B y mira cómo cada una lleva su ritmo; luego mete un delay() y mira cómo se estropean las dos.', tune: TM(500, 1000, 0, 0, false), q: mcq('Un programa tiene un delay(1000) al final de loop(). ¿A qué afecta?', ['A todas las tareas: ninguna puede ejecutarse durante ese segundo', 'Solo a la última tarea', 'A ninguna', 'Solo al LED del 13'], 'Una tarea que bloquea frena a todas.') },
      { title: 'Que el retraso no se acumule', text: 'Con <b>antes = millis()</b>, si una ejecución llega 30 ms tarde, la siguiente cuenta desde ahí y el retraso se suma una y otra vez. Con <b>antes += intervalo</b>, cada ejecución se programa respecto al ritmo ideal: puede llegar un poco tarde, pero el ritmo medio se mantiene.', svg: SV_DRIFT, q: mcq('Quieres un reloj que no se atrase con las horas. ¿Qué usas?', ['antes += intervalo', 'antes = millis()', 'delay(intervalo)', 'antes = 0'], 'Así los pequeños retrasos no se acumulan.') }
    ] },
    mc_debounce: { name: 'Antirrebote', alts: [
      { title: 'Ignora los rebotes', text: 'Al cerrarse, las láminas de un pulsador rebotan unos milisegundos y el pin cambia varias veces. El antirrebote acepta un cambio y luego <b>ignora</b> los que lleguen durante un tiempo, típicamente 20–50 ms. Ajústalo: si es corto, cuentas de más; si es largo, te comes pulsaciones rápidas.', tune: { viz: 'mc_bounce', params: { T: { label: 'Tiempo de antirrebote', val: 0, min: 0, max: 120, step: 1, unit: 'ms', dec: 0 } } }, q: mcq('Con 1 ms de antirrebote, un contador por flanco…', ['Sigue contando de más: los rebotes duran más de 1 ms', 'Cuenta perfecto', 'No cuenta nada', 'Se reinicia'], 'Hay que tapar toda la ráfaga de rebotes.') },
      { title: 'Una puerta que se cierra un rato', text: 'Piensa en una puerta que, cada vez que pasa alguien, se cierra 30 ms. Los rebotes llegan en esos 30 ms y se quedan fuera. En código: if (lectura != antes && millis() − tCambio > 30) { tCambio = millis(); … }. Y guarda antes = lectura solo cuando aceptas el cambio, para no colar los rebotes ignorados.', q: mcq('¿Para qué sirve millis() − tCambio > 30 en el antirrebote?', ['Para ignorar cambios que llegan menos de 30 ms después del último aceptado', 'Para esperar 30 ms bloqueando', 'Para contar 30 pulsaciones', 'Para encender el LED 30 ms'], 'Sin delay(): el resto del programa sigue.') }
    ] },
    mc_edge: { name: 'Nivel o flanco', alts: [
      { title: 'Un instante frente a un rato', text: 'Por <b>nivel</b>: «mientras esté pulsado, haz X», y se repite en cada vuelta de loop(), cientos de veces por segundo. Por <b>flanco</b>: «cuando se acaba de pulsar, haz X una vez». Con INPUT_PULLUP, la pulsación es el paso de HIGH a LOW: flanco de bajada.', svg: SV_EDGE, q: mcq('Con INPUT_PULLUP, ¿qué flanco aparece al soltar el botón?', ['De subida: de LOW a HIGH', 'De bajada: de HIGH a LOW', 'Ninguno', 'Los dos a la vez'], 'Suelto vuelve a HIGH.') },
      { title: 'Recordar la lectura anterior', text: 'Para detectar el flanco hay que comparar la lectura de ahora con la de antes: si antes era HIGH y ahora es LOW, se acaba de pulsar. Para acciones de «una vez» (encender y apagar, contar, cambiar de pantalla), flanco. Para acciones continuas (acelerar, subir el volumen mientras pulsas), nivel.', q: mcq('Para contar cuántas veces se pulsa un botón, ¿qué miras?', ['El flanco: el paso de suelto a pulsado', 'El nivel: si está pulsado', 'Solo el primer instante tras encender', 'El tiempo que está pulsado'], 'Cada pulsación da un único flanco.') }
    ] },
    mc_fsm: { name: 'Máquinas de estados', alts: [
      { title: 'Muévete por el diagrama', text: 'Una máquina de estados es una lista de <b>estados</b> y unas <b>transiciones</b> que dicen cuándo se pasa de uno a otro: por un evento (pulsan) o por tiempo (2 s). En cada momento solo hay un estado activo. Haz que el peatón pulse y avanza el tiempo.', tune: { viz: 'fsm', params: { tp: { label: 'El peatón pulsa en (0: nadie)', val: 2, min: 0, max: 8, step: 0.5, unit: 's', dec: 1 }, t: { label: 'Tiempo', val: 0, min: 0, max: 12, step: 0.1, unit: 's', dec: 1 } } }, q: mcq('En ese semáforo, ¿qué provoca el paso de ÁMBAR a ROJO?', ['Que pasen 2 s', 'Que pulsen otra vez', 'Que pase un coche', 'Nada: ÁMBAR es el final'], 'Esa transición es por tiempo.') },
      { title: 'Como una lavadora', text: 'Una lavadora no hace todo a la vez: llena, lava, aclara y centrifuga, y en cada fase sabe a cuál pasa y cuándo. Diseñar así un programa lo hace sencillo: cada estado es pequeño, nada bloquea (los tiempos se miden con millis()) y añadir un comportamiento nuevo es añadir un estado. Dibuja primero los círculos y las flechas.', q: mcq('¿Qué dos cosas definen una máquina de estados?', ['Sus estados y las transiciones entre ellos', 'Sus pines y sus delay()', 'El número de LEDs', 'El tipo de placa'], 'Estados y reglas para cambiar.') }
    ] },
    mc_switch: { name: 'enum y switch', alts: [
      { title: 'Cuidado con el break', text: '<b>enum</b> da nombres a los estados (REPOSO, REGANDO…). <b>switch (estado)</b> salta al <b>case</b> del estado actual y ejecuta hasta el <b>break</b>, que sale del switch. Si olvidas el break, sigue de largo y ejecuta también el case siguiente.', svg: SV_FALL, q: mcq('¿Qué hace break dentro de un case?', ['Sale del switch', 'Termina loop() para siempre', 'Vuelve al primer case', 'Reinicia la placa'], 'Sin él, el programa cae al case de abajo.') },
      { title: 'Un if largo, más ordenado', text: 'switch es una forma ordenada de escribir if (estado == A) {…} else if (estado == B) {…}. Cada case es una rama. Para cambiar de estado basta con asignar: estado = ROJO; y en la siguiente vuelta de loop() el switch entrará en case ROJO.', q: mcq('Escribes estado = ROJO; dentro de case AMBAR. ¿Cuándo se ejecuta el código de case ROJO?', ['En la siguiente vuelta de loop(), si hay break', 'Nunca', 'Antes que el de AMBAR', 'Solo si se pulsa'], 'El switch vuelve a mirar el estado en cada vuelta.') }
    ] },
    mc_isr: { name: 'Interrupciones: cuándo y cómo', alts: [
      { title: 'Sondeo frente a interrupción', text: 'Mirar el pin en cada vuelta de loop() se llama <b>sondeo</b>: si la vuelta es larga y el pulso corto, el pulso pasa sin que nadie lo vea. Una <b>interrupción</b> la dispara el propio hardware en el flanco y no se pierde ninguno. Haz loop() más lento y mira qué se pierde.', tune: { viz: 'isrTimeline', params: { f: { label: 'Pulsos por segundo', val: 10, min: 5, max: 40, step: 1, dec: 0 }, w: { label: 'Duración de cada pulso', val: 3, min: 1, max: 20, step: 1, unit: 'ms', dec: 0 }, L: { label: 'Duración de una vuelta de loop()', val: 20, min: 1, max: 200, step: 1, unit: 'ms', dec: 0 } } }, q: mcq('¿Cuándo compensa usar una interrupción?', ['Con pulsos cortos o que no te puedes perder', 'Para encender un LED', 'Para poder usar delay()', 'Siempre, para cualquier botón'], 'Si loop() es ágil, un botón normal se lee bien sondeando.') },
      { title: 'El timbre de casa', text: 'No vas a mirar por la ventana cada minuto por si llega alguien: el timbre te avisa. La interrupción es el timbre: dejas lo que estabas haciendo, abres (la <b>ISR</b>, una función cortita) y vuelves. En la Uno, attachInterrupt funciona en los pines <b>2 y 3</b>; en el ESP32, en casi cualquiera. Modos: RISING, FALLING, CHANGE y LOW.', svg: SV_ISR, q: mcq('En una Uno, ¿qué pines sirven para attachInterrupt?', ['El 2 y el 3', 'Todos', 'El 13', 'A0 a A5'], 'INT0 e INT1.') }
    ] },
    mc_isrrules: { name: 'Una buena ISR: corta y con volatile', alts: [
      { title: 'Por qué volatile', text: 'El compilador optimiza: si ve que loop() nunca cambia una variable, puede leerla una vez, guardarla en un registro del procesador y no volver a mirar la memoria. <b>volatile</b> le dice: «esta variable puede cambiar sola en cualquier momento; léela siempre de la memoria».', svg: SV_VOLAT, q: mcq('Una variable la cambia la ISR y la lee loop(). ¿Cómo la declaras?', ['volatile', 'const', 'static', 'Como cualquier otra'], 'Si no, loop() puede no ver nunca el cambio.') },
      { title: 'Entra, apunta y sal', text: 'Mientras corre una ISR, las demás interrupciones esperan, y de ellas dependen Serial y millis(). Por eso una ISR <b>no imprime ni usa delay()</b>: solo apunta lo que pasó (pulsos++, una bandera) y sale. El trabajo pesado, en loop(). Y para leer una variable de varios bytes que cambia la ISR, cópiala entre noInterrupts() e interrupts().', q: mcq('¿Qué debería hacer una ISR que cuenta pulsos?', ['pulsos++ y nada más', 'Imprimir el total por Serial', 'Esperar 50 ms con delay()', 'Calcular la velocidad y mostrarla'], 'Lo demás, en loop().') }
    ] },
    mc_memwhere: { name: 'Flash, SRAM y EEPROM', alts: [
      { title: 'Tres cajones', text: 'El ATmega328P tiene tres memorias. <b>Flash</b> (32 KB): el programa y los textos con F(); se conserva sin corriente. <b>SRAM</b> (2 KB): las variables mientras funciona; se borra al apagar. <b>EEPROM</b> (1 KB): datos que quieres conservar, como un récord o una calibración.', svg: SV_MEM, q: mcq('¿Dónde guardas un récord que debe sobrevivir a un apagado?', ['En la EEPROM', 'En una variable global', 'En una variable local', 'En la pila'], 'Las variables viven en la SRAM y se pierden.') },
      { title: 'Pregúntate dos cosas', text: '¿Cambia mientras funciona? ¿Debe sobrevivir a un apagado? Si cambia y no hace falta conservarlo: SRAM (una variable). Si no cambia nunca: Flash (el código, F("texto"), PROGMEM). Si cambia de vez en cuando y hay que conservarlo: EEPROM, escribiendo poco.', q: mcq('Una tabla de 500 valores constantes de calibración, ¿dónde la pones en una Uno?', ['En la Flash, con PROGMEM', 'En la SRAM', 'En la EEPROM, escribiéndola en cada arranque', 'En un String'], 'Es constante: no tiene por qué ocupar la poca RAM.') }
    ] },
    mc_ram: { name: 'RAM escasa: que no se acabe', alts: [
      { title: 'Llena la barra', text: 'La SRAM de la Uno son 2048 bytes. Las variables globales, los buffers y los textos entre comillas ocupan su sitio fijo; lo que queda es para la <b>pila</b> (variables locales y llamadas a funciones). Si la pila no cabe, pisa otras variables y aparecen cuelgues sin ningún aviso. Prueba a llenarla y a usar F().', tune: { viz: 'ramBar', params: { glob: { label: 'Variables globales', val: 700, min: 100, max: 1500, step: 50, unit: 'B', dec: 0 }, buf: { label: 'Buffers (arrays)', val: 200, min: 0, max: 800, step: 50, unit: 'B', dec: 0 }, txt: { label: 'Textos entre comillas', val: 400, min: 0, max: 600, step: 50, unit: 'B', dec: 0 }, F: { label: 'Textos con F() (0 no · 1 sí)', val: 0, list: [0, 1], dec: 0 } } }, q: mcq('El IDE dice que las globales usan el 95 % de la memoria dinámica. ¿Qué esperas?', ['Cuelgues o valores raros: queda muy poca RAM para la pila', 'Nada: el 5 % sobra', 'Un error al compilar', 'Que la Flash se llene'], 'Unos 100 bytes no dan para casi nada.') },
      { title: 'Saca lo constante de la RAM', text: 'Cada texto entre comillas se copia en la RAM al arrancar; con <b>F("…")</b> se queda en la Flash. Las tablas constantes, con <b>PROGMEM</b>. Y la clase String, al crear y destruir textos en cada vuelta, deja huecos (fragmentación): tras horas puede no quedar un hueco del tamaño necesario. Si el IDE avisa de que la memoria dinámica pasa del 75 %, revisa.', q: mcq('¿Qué línea ahorra RAM en la Uno?', ['Serial.println(F("Sensor listo"));', 'Serial.println("Sensor listo");', 'String s = "Sensor listo";', 'char s[] = "Sensor listo";'], 'F() deja el texto en la Flash.') }
    ] },
    mc_eeprom: { name: 'EEPROM: guardar sin gastarla', alts: [
      { title: 'Una libreta que se gasta', text: 'La EEPROM guarda datos sin corriente, pero cada celda aguanta unas <b>100 000 escrituras</b> garantizadas; leer no la gasta. Duración = 100 000 × tiempo entre escrituras. Escribe solo cuando el dato cambie (EEPROM.put() ya se salta los bytes que no cambian).', svg: SV_WEAR, q: mcq('Grabas la misma celda cada 10 segundos. ¿Cuánto dura, aproximadamente?', ['Unos 11,6 días', 'Unos 100 años', 'Unos 10 minutos', 'Para siempre'], '100 000 × 10 s = 1 000 000 s ≈ 11,6 días.') },
      { title: 'Bytes de fábrica', text: 'Una EEPROM sin estrenar tiene todos sus bytes a 255 (0xFF). EEPROM.get() de un unsigned int (2 bytes) devuelve 0xFFFF = 65 535: compruébalo al arrancar para saber que aún no hay nada guardado. Capacidad en la Uno: 1024 bytes; caben 1024 / tamaño de cada dato (256 float, 512 int).', q: mcq('¿Qué devuelve EEPROM.read(0) en una EEPROM nueva?', ['255', '0', '-1', 'Un error'], 'De fábrica, cada byte vale 0xFF.') }
    ] }
  });

  /* ================= LECCIONES ================= */
  const MT3 = (iA, blk) => ({ iA: { label: 'Intervalo de la tarea', val: iA, min: 100, max: 1000, step: 50, unit: 'ms', dec: 0 }, iB: { val: 0, fixed: true }, blk: { label: 'delay() dentro de loop()', val: blk, min: 0, max: 600, step: 50, unit: 'ms', dec: 0 }, mode: { val: 0, fixed: true } });
  const BLINK = 'unsigned long antes = 0;\nbool encendido = false;\n\nvoid setup() {\n  pinMode(13, OUTPUT);\n}\n\nvoid loop() {\n  if (millis() - antes >= 500) {   // ¿han pasado 500 ms?\n    antes = millis();               // apunta cuándo\n    encendido = !encendido;\n    digitalWrite(13, encendido);\n  }\n  // aquí cabe todo lo demás: botones, sensores…\n}';

  /* ===================== EXAMEN DE NIVEL (banco propio) ===================== */
  const exam = [
    // n7 · millis()
    Q('Este parpadeo sin delay() no parpadea: el LED no cambia nunca. ¿Por qué?', ['antes se actualiza en cada vuelta, fuera del if: la diferencia nunca llega a 500', 'millis() no funciona dentro de un if', 'Falta un delay() al final', 'antes debería ser un int'], 'antes = millis() debe ir dentro del if, solo cuando toca. Así, millis() − antes mide el tiempo desde el último cambio; si lo actualizas siempre, mide solo lo que tarda una vuelta.', { c: 'mc_elapsed', l: 'n7', h: '¿Cuánto vale millis() − antes si antes se pone al día en cada vuelta?', code: 'void loop() {\n  if (millis() - antes >= 500) {\n    encendido = !encendido;\n    digitalWrite(13, encendido);\n  }\n  antes = millis();\n}' }),
    Nm('Si guardaras millis() en un unsigned int de la Uno (de 0 a 65 535), ¿a los cuántos segundos daría la vuelta?', 65.5, 's', '65 535 ms ≈ 65,5 s. Por eso millis() devuelve un unsigned long, que aguanta unos 49,7 días.', { tol: 0.2, c: 'mc_ulong', l: 'n7', h: 'El máximo de un unsigned int son milisegundos: pásalo a segundos.' }),
    Q('Quieres un destello de 50 ms cada 2 s, sin delay(). ¿Qué intervalo debe comprobar el if?', ['50 ms si el LED está encendido y 1950 ms si está apagado', '2000 ms siempre', '50 ms siempre', '1000 ms siempre'], 'El intervalo depende del estado: encendido espera 50 ms para apagar; apagado espera el resto del ciclo, 2000 − 50 = 1950 ms.', { c: 'mc_millis', l: 'n7', h: 'Cada estado del LED dura un tiempo distinto.' }),
    // n17 · rebotes y flancos
    Q('Un contador de visitantes usa if (digitalRead(2) == LOW) cuenta++; con el pulsador en pull-up. Al pasar una persona, el contacto queda pulsado unos 300 ms. ¿Qué pasa?', ['La cuenta sube muchísimo: suma en cada vuelta de loop() mientras está pulsado', 'Cuenta 1, perfecto', 'No cuenta nada', 'Cuenta 2, por los rebotes'], 'Mira el nivel, no el flanco. loop() da miles de vueltas en 300 ms y cada una suma. Hay que detectar el cambio de HIGH a LOW.', { c: 'mc_edge', l: 'n17', h: '¿Detecta el momento de pulsar o el estado de estar pulsado?' }),
    Q('Los rebotes de tu pulsador duran unos 5 ms y alguien puede pulsar, como mucho, 8 veces por segundo. ¿Qué tiempo de antirrebote eliges?', ['Unos 30 ms', '2 ms', '200 ms', '1 s'], 'Debe tapar los rebotes (más de 5 ms) sin llegar al hueco entre pulsaciones (125 ms). Unos 20–50 ms cumplen las dos cosas.', { c: 'mc_debounce', l: 'n17', h: 'Más largo que los rebotes y más corto que el tiempo entre dos pulsaciones.' }),
    Q('Con INPUT_PULLUP, quieres que algo pase justo al soltar el botón. ¿Qué cambio de la lectura buscas?', ['De LOW a HIGH: el flanco de subida', 'De HIGH a LOW: el flanco de bajada', 'Que esté en HIGH', 'Que esté en LOW'], 'Pulsado lee LOW y suelto, HIGH. Soltar es pasar de LOW a HIGH.', { c: 'mc_edge', l: 'n17', h: 'Con pull-up, ¿qué se lee pulsado y qué suelto?' }),
    // n18 · varias tareas
    Nm('Tres tareas con millis(): una cada 200 ms, otra cada 750 ms y otra cada 3 s. ¿Cuántas ejecuciones hay en total en 30 s?', 200, 'veces', '30 000 / 200 = 150; 30 000 / 750 = 40; 30 000 / 3000 = 10. Total: 200.', { tol: 0, c: 'mc_timecount', l: 'n18', h: 'Pasa los 30 s a ms y divide entre el intervalo de cada tarea.' }),
    Q('Un programa tiene una tarea con millis() cada 100 ms y otra que, cada vez que imprime, hace delay(300). ¿Qué le pasa a la de 100 ms?', ['Se retrasa hasta 300 ms en esos momentos y pierde ejecuciones', 'Nada: cada tarea va a su ritmo', 'Se ejecuta tres veces seguidas', 'La placa se reinicia'], 'Una sola tarea que bloquea frena a todas: mientras dura el delay(), loop() no pasa por las demás.', { c: 'mc_tasks', l: 'n18', h: '¿Qué hace loop() mientras está dentro de un delay()?' }),
    Q('Un registrador debe guardar un dato cada minuto durante semanas, y cada vuelta de loop() tarda unos 3 ms. ¿Cómo actualizas el instante?', ['tDato += 60000, para que los pequeños retrasos no se acumulen', 'tDato = millis(), que es lo más exacto', 'Con delay(60000)', 'No hace falta actualizarlo'], 'Con tDato = millis(), cada pequeño retraso se suma al siguiente y el ritmo se va estirando. Sumando el intervalo, cada dato llega algo tarde pero el ritmo medio se mantiene.', { c: 'mc_tasks', l: 'n18', h: 'Piensa qué pasa con los milisegundos de retraso de cada ejecución a lo largo de semanas.' }),
    Nm('antes vale 4 294 967 000 y, tras dar la vuelta, millis() vale 200. ¿Cuánto da millis() − antes con unsigned long, en ms?', 496, 'ms', 'Hasta el máximo (4 294 967 295) faltaban 295 ms; uno más para pasar por 0 y luego 200: 295 + 1 + 200 = 496 ms. La resta sin signo da justo el tiempo real.', { tol: 0, c: 'mc_elapsed', l: 'n18', h: 'Cuenta lo que faltaba hasta el máximo, el paso por 0 y lo que ha contado después.' }),
    // n19 · máquinas de estados
    Q('La alarma está en ARMADA. Se abre la puerta y nadie mete el código. ¿Qué pasa?', ['Pasa a AVISO y, a los 10 s, a SIRENA', 'Pasa directamente a SIRENA', 'Se queda en ARMADA', 'Pasa a DESARMADA'], 'La puerta provoca ARMADA → AVISO (evento). En AVISO, si no llega el código en 10 s, el tiempo provoca AVISO → SIRENA.', { c: 'mc_fsm', l: 'n19', h: 'Sigue el código desde case ARMADA, mirando qué condición se cumple en cada estado.', code: 'switch (estado) {\n  case DESARMADA:\n    if (codigoOk()) estado = ARMADA;\n    break;\n  case ARMADA:\n    if (puertaAbierta()) { t0 = millis(); estado = AVISO; }\n    break;\n  case AVISO:\n    if (codigoOk()) estado = DESARMADA;\n    else if (millis() - t0 >= 10000) estado = SIRENA;\n    break;\n  case SIRENA:\n    digitalWrite(ZUMB, HIGH);\n    if (codigoOk()) { digitalWrite(ZUMB, LOW); estado = DESARMADA; }\n    break;\n}' }),
    Q('En ese estado AVISO, ¿por qué se mide la espera con t0 y millis() en vez de un delay(10000)?', ['Para que durante la espera se siga mirando si meten el código', 'Porque delay() no admite 10 000', 'Para gastar menos memoria', 'Da igual: harían lo mismo'], 'Con delay(10000) el programa no podría leer el teclado durante esos 10 s: nadie podría desarmar la alarma a tiempo.', { c: 'mc_millis', l: 'n19', h: '¿Qué deja de hacer el programa mientras está dentro de un delay()?' }),
    Q('¿Para qué se nombran los estados con enum (DESARMADA, ARMADA…) en vez de usar 0, 1, 2?', ['Para que el código se lea solo; el compilador los convierte en números igualmente', 'Porque switch no admite números', 'Para que el programa vaya más rápido', 'Para ahorrar RAM'], 'enum es una lista de nombres que el compilador traduce a números. case ARMADA se entiende; case 1, no.', { c: 'mc_switch', l: 'n19', h: '¿Qué hace el compilador con los nombres de un enum?' }),
    { t: 'order', q: 'Ordena los estados de la barrera de un garaje, empezando por la barrera bajada.', items: ['CERRADA: espera la orden del mando', 'SUBIENDO: el motor sube hasta el final de carrera', 'ABIERTA: espera 10 s', 'BAJANDO: el motor baja hasta el final de carrera'], e: 'Cada estado sabe qué espera: un evento (el mando, los finales de carrera) o un tiempo (los 10 s). Al terminar de bajar vuelve a CERRADA.', c: 'mc_fsm', l: 'n19', h: 'Piensa qué hace la barrera desde que pulsas el mando hasta que vuelve a estar bajada.' },
    // n20 · interrupciones
    Nm('Un encoder da 20 pulsos por vuelta. La ISR cuenta 300 pulsos en 2 s. ¿A cuántas vueltas por minuto gira?', 450, 'rpm', '300 / 20 = 15 vueltas en 2 s = 7,5 vueltas/s. Por minuto: 7,5 × 60 = 450 rpm.', { tol: 1, c: 'mc_isr', l: 'n20', h: 'Pasa los pulsos a vueltas, luego a vueltas por segundo y por último por minuto.' }),
    Q('Este programa se queda colgado en el while aunque lleguen pulsos. ¿Qué le falta?', ['volatile en cuenta: sin él, el compilador puede no volver a leerla en el while', 'Un delay() dentro del while', 'Que la ISR devuelva un valor', 'Nada: el sensor está roto'], 'cuenta la cambia la ISR y la lee loop(). Sin volatile, el compilador puede guardar una copia y no ver nunca el cambio.', { c: 'mc_isrrules', l: 'n20', h: '¿Cómo se marca una variable que cambia una ISR?', code: 'int cuenta = 0;\n\nvoid pulso() {          // ISR\n  cuenta++;\n}\n\nvoid loop() {\n  while (cuenta < 10) { }\n  Serial.println("Diez pulsos");\n}' }),
    Q('Dentro de una ISR que tarda 3 ms, quieres medir cuánto pasa entre dos puntos con millis(). ¿Qué problema hay?', ['Dentro de la ISR millis() no avanza; además, una ISR debe ser cortísima', 'Ninguno', 'millis() reinicia la placa', 'Solo funciona con FALLING'], 'millis() se apoya en otra interrupción, que está en pausa mientras corre la tuya. Apunta el evento y mide en loop().', { c: 'mc_isrrules', l: 'n20', h: 'Recuerda las reglas de una buena ISR y qué pasa con otras interrupciones mientras corre.' }),
    Q('Cuentas pulsos con attachInterrupt(…, contar, RISING). Cambias RISING por CHANGE. ¿Qué pasa con la cuenta?', ['Se duplica: la ISR salta en la subida y en la bajada de cada pulso', 'No cambia', 'Se reduce a la mitad', 'Deja de contar'], 'RISING salta solo al pasar de LOW a HIGH; CHANGE, en cualquier cambio: dos por pulso.', { c: 'mc_isr', l: 'n20', h: '¿Cuántos cambios tiene un pulso completo?' }),
    TU('Un sensor da 20 pulsos por segundo de 4 ms cada uno, y loop() solo mira el pin una vez por vuelta. Ajusta lo que tarda una vuelta para que el sondeo no pierda ningún pulso.', 'isrTimeline', { f: { val: 20, fixed: true }, w: { val: 4, fixed: true }, L: { label: 'Duración de una vuelta de loop()', val: 60, min: 1, max: 200, step: 1, unit: 'ms', dec: 0 } }, { q: 'lost', min: 0, max: 0, text: 'Objetivo: que el sondeo no pierda ningún pulso', hint: 'Compara lo que dura una vuelta con lo que dura un pulso.' }, 'Hace falta que loop() mire el pin al menos una vez mientras dura cada pulso: vueltas de unos pocos milisegundos, del orden de los 4 ms del pulso. Con un loop() que hace muchas cosas es difícil; por eso, para pulsos cortos, interrupciones.', { c: 'mc_isr', l: 'n20', h: 'Si una vuelta dura más que un pulso, alguno puede caer entre dos miradas.' }),
    // n21 · memoria
    Nm('Guardas un dato en la misma celda de EEPROM cada 5 minutos. Con 100 000 escrituras por celda, ¿cuántos días dura, más o menos?', 347, 'días', '100 000 × 5 min = 500 000 min = 8333 h ≈ 347 días: menos de un año. Mejor grabar solo cuando el dato cambie, o repartir las escrituras entre varias celdas.', { tol: 5, c: 'mc_eeprom', l: 'n21', h: 'Multiplica escrituras por el tiempo entre ellas y pásalo a días.' }),
    Q('Al compilar para la Uno, el IDE dice que las variables globales usan 1200 bytes (58 %). Añades un array global de 300 int. ¿Cómo queda?', ['Unos 1800 bytes (88 %): queda muy poca RAM para la pila', '1500 bytes: va sobrado', 'No cambia: los arrays van a la Flash', 'No compila nunca'], 'Cada int ocupa 2 bytes en la Uno: 300 × 2 = 600 bytes más. 1800 de 2048 es un 88 %, por encima del 75 % en que el IDE ya avisa.', { c: 'mc_ram', l: 'n21', h: 'Calcula lo que ocupa el array y súmalo a lo que ya había.' }),
    { t: 'match', q: '¿Dónde acaba cada cosa en una Uno?', pairs: [['Una melodía constante declarada con PROGMEM', 'Flash'], ['La lectura actual de un sensor', 'SRAM'], ['Un ajuste que el usuario cambia de vez en cuando y debe conservarse', 'EEPROM'], ['Un texto en Serial.print() sin F()', 'SRAM ']], e: 'PROGMEM y F() dejan las constantes en la Flash. Las variables viven en la SRAM, y los textos sin F() se copian también en ella al arrancar. Lo que debe sobrevivir a un apagado y cambia, en la EEPROM.', c: 'mc_memwhere', l: 'n21', h: 'Pregúntate si cambia mientras funciona y si debe conservarse sin corriente.' },
    Q('Quieres conservar un ajuste en la EEPROM sin gastarla. ¿Qué código es el adecuado?', ['if (nuevo != guardado) { EEPROM.put(0, nuevo); guardado = nuevo; }', 'EEPROM.put(0, nuevo); en cada vuelta de loop()', 'EEPROM.get(0, nuevo); en cada vuelta de loop()', 'EEPROM.put(0, nuevo); dentro de un delay()'], 'Leer no desgasta; escribir sí. Solo se graba cuando el valor cambia de verdad.', { c: 'mc_eeprom', l: 'n21', h: '¿Qué operación desgasta la EEPROM y cuándo hace falta de verdad?' })
  ];
  /* ===================== FIN DEL EXAMEN ===================== */
  UNITS.push({ id: 'm11d', title: 'Microcontroladores III: tiempo y estados', desc: 'millis(), rebotes y flancos, varias tareas a la vez, máquinas de estados, interrupciones y memoria.', exam, nodes: [
    /* n7 · Enseña: por qué delay() bloquea, millis(), unsigned long (49,7 días; int a los 32,8 s), «ahora − antes ≥ intervalo», UL, parpadeo asimétrico.
       Usa: n10, n11, n12, n15, n4. Recibe n10#10–#11 y n11#10. */
    L('n7', 'Tiempo sin bloquear: millis()', 'timer', ['mc_millis', 'mc_elapsed', 'mc_ulong', 'mc_timecount'], [
      Q('Tu programa hace parpadear un LED con dos delay(1000) y, además, debe encender otro LED al pulsar un botón. Si das un toque rápido al botón, ¿qué crees que pasa?', ['Muchas veces no se entera: estaba esperando dentro de un delay()', 'Lo detecta siempre al momento', 'Se reinicia la placa', 'El LED parpadea más deprisa'], 'Durante un delay() el programa no hace nada más: si pulsas en ese momento, nadie mira el botón.', { predict: true, c: 'mc_millis', h: '¿Qué hace el programa mientras está dentro de delay()?' }),
      I('<b>delay()</b> deja el procesador contando sin hacer nada más. Mientras espera, no lee botones, no mira sensores, no atiende el monitor serie. Con una sola tarea no importa; con varias, sí.', { svg: SV_BLOCK }),
      I('<b>millis()</b> devuelve los milisegundos que han pasado desde que arrancó la placa. Es un reloj que nunca se para: no espera, solo te dice la hora.', { code: 'void loop() {\n  Serial.println(millis());   // 0, 1, 3, 5… y no para de crecer\n}', more: 'La Uno lo lleva con un temporizador interno que interrumpe al procesador cada poco más de 1 ms para sumar. Por eso millis() sigue avanzando aunque tu programa esté ocupado (salvo dentro de una interrupción, como verás).' }),
      { t: 'explore', text: 'Línea de tiempo de 3 s. Cada raya naranja es una vez que la tarea se ejecuta; las grises discontinuas, cuándo debería.', viz: 'millisTimeline', params: MT3(1000, 0),
        tasks: [
          { q: 'nA', min: 12, max: 12, text: 'Haz que la tarea se ejecute 12 veces en 3 s', done: 'Cada 250 ms: 3000 / 250 = 12.', hint: '3000 ms entre 12.' },
          { q: 'late', min: 100, max: 99999, text: 'Ahora mete un delay() de 400 ms en loop()', done: 'Mientras delay() espera, nadie mira el reloj: la tarea llega tarde y se ejecuta menos veces.', hint: 'Sube el delay() hasta 400 ms.' },
          { q: 'clean500', min: 1, max: 1, text: 'Quita el bloqueo y pon la tarea cada 500 ms', done: 'Sin bloqueos, cada ejecución llega a su hora.', hint: 'delay() a 0 e intervalo a 500 ms.' }
        ] },
      I('El patrón para no bloquear: apunta <b>cuándo</b> hiciste algo y, en cada vuelta de loop(), mira si ya ha pasado el intervalo: <b>if (millis() − antes >= intervalo)</b>. Si toca, lo haces y apuntas la nueva hora; si no, sigues con lo demás.', { code: BLINK }),
      { t: 'steps', text: 'Sigue el parpadeo sin delay() durante el primer segundo. loop() da miles de vueltas por segundo.', code: BLINK, steps: ['Arranca: antes = 0, LED apagado.', 'Vueltas con millis() = 1, 2… 499: 499 − 0 = 499 < 500 → no toca. Se salta el if y el resto de loop() sigue funcionando.', 'millis() = 500: 500 − 0 = 500 ≥ 500 → toca: antes = 500 y el LED se <b>enciende</b>.', 'millis() = 501… 999: menos de 500 desde antes → no toca.', 'millis() = 1000: 1000 − 500 = 500 → toca: antes = 1000 y el LED se <b>apaga</b>.'], result: 'Un cambio cada 500 ms y loop() libre todo el tiempo' },
      Nm('millis() vale 12 500 y antes vale 12 000. ¿Cuántos ms han pasado?', 500, 'ms', '12 500 − 12 000 = 500 ms: justo el intervalo, así que toca cambiar.', { c: 'mc_elapsed', h: 'Tiempo pasado = ahora − antes.' }),
      G('mc2Elapsed'),
      Q('Un programa tiene delay(5000) en loop() y debe reaccionar a un botón. ¿Qué problema hay?', ['Durante 5 s no se lee el botón', 'Ninguno', 'Quema el LED', 'Reinicia la placa'], 'Por eso se usa millis().', { c: 'mc_millis', h: 'Piensa en qué hace el programa durante esos 5 s.' }),
      I('¿De qué tipo es lo que devuelve millis()? Un número que crece sin parar: un <b>int</b> de la Uno (hasta 32 767) se desbordaría a los <b>32,8 s</b>. Por eso es un <b>unsigned long</b>: 32 bits sin signo, hasta 4 294 967 295 ms, unos <b>49,7 días</b>. Después vuelve a 0.', { svg: SV_ODO }),
      Q('Guardas millis() en un int de la Uno. ¿Qué pasa al rato?', ['A los 32,8 s ya no cabe y aparecen valores absurdos, incluso negativos', 'Nada: millis() siempre cabe', 'La placa se reinicia', 'millis() se detiene'], 'Un int llega a 32 767. Para tiempos, siempre unsigned long.', { c: 'mc_ulong', h: '¿Cuál es el mayor número que cabe en un int de la Uno?' }),
      Q('¿De qué tipo debe ser la variable antes?', ['unsigned long, el mismo que devuelve millis()', 'int', 'byte', 'float'], 'Si no, la resta y la comparación fallan cuando el número crece.', { c: 'mc_ulong', h: 'Usa el mismo tipo que millis().' }),
      Q('En la Uno quieres una espera de 2 minutos para usar con millis(). ¿Qué línea es correcta?', ['const unsigned long ESPERA = 2 * 60 * 1000UL;', 'const int ESPERA = 2 * 60 * 1000;', 'const byte ESPERA = 120000;', 'const float ESPERA = 2 / 60;'], 'UL obliga a hacer la multiplicación en unsigned long. 120 000 no cabe en un int ni en un byte.', { c: 'mc_ulong', h: '2 min son 120 000 ms: ¿en qué tipo cabe, y en qué tipo se hace la cuenta?', code: '// 2 min = 120 000 ms' }),
      Q('Quieres el LED 100 ms encendido y 900 ms apagado, sin delay(). ¿Qué cambia respecto al parpadeo simétrico?', ['El intervalo depende de si el LED está encendido o apagado', 'Nada: basta un intervalo de 500 ms', 'Hacen falta dos placas', 'No se puede con millis()'], 'Por ejemplo: unsigned long intervalo = encendido ? 100 : 900;', { c: 'mc_millis', h: 'El tiempo de espera ya no es siempre el mismo.' }),
      G('mc2Count'),
      I('<b>Resumen</b>\n· delay() <b>bloquea</b>: el programa no hace nada más mientras espera.\n· millis() dice cuántos ms han pasado desde el arranque.\n· Patrón: <b>if (millis() − antes >= intervalo) { antes = millis(); … }</b>\n· Tiempos en <b>unsigned long</b> (49,7 días); un int de la Uno se desborda a los 32,8 s.')
    ]),
    /* n17 · Enseña: rebotes, antirrebote por software con millis(), nivel frente a flanco, flanco de bajada con INPUT_PULLUP, antirrebote por hardware.
       Usa: n7, n4, l7, k14, g4. */
    L('n17', 'Rebotes y flancos', 'chip', ['mc_debounce', 'mc_edge'], [
      Q('Un contador sube cada vez que digitalRead pasa de HIGH a LOW. Pulsas el botón una sola vez. ¿Qué crees que marcará?', ['A veces 2, 3 o más', 'Siempre 1', 'Siempre 0', 'Un número negativo'], 'Los contactos rebotan: para el microcontrolador, que lee miles de veces por segundo, una pulsación pueden ser varias.', { predict: true, c: 'mc_debounce', h: 'Recuerda lo que hacen las láminas metálicas de un pulsador al cerrarse.' }),
      I('Ya lo viste con los contadores: un pulsador son dos láminas de metal que, al cerrarse, <b>rebotan</b> varias veces durante unos milisegundos. Para ti es un clic; para un programa que lee el pin miles de veces por segundo, son varios.', { svg: `<svg viewBox="0 0 300 110" class="viz"><text x="10" y="16" class="vizsm">Tensión del pin al pulsar (con pull-up)</text><path d="M10 30H90V80H96V34H100V80H106V40H109V80H112V48H114V80H290" fill="none" stroke="var(--led)" stroke-width="2.5"/><rect x="90" y="88" width="26" height="10" fill="var(--err)" opacity=".5"/><text x="122" y="98" class="vizsm" style="fill:var(--err)">rebotes: unos pocos ms</text><text x="10" y="40" class="vizsm">H</text><text x="10" y="84" class="vizsm">L</text></svg>` }),
      { t: 'explore', text: 'Arriba, lo que lee el pin en dos pulsaciones reales. Abajo, lo que acepta el programa si ignora los cambios durante un tiempo tras cada uno.', viz: 'mc_bounce', params: { T: { label: 'Tiempo de antirrebote', val: 0, min: 0, max: 120, step: 1, unit: 'ms', dec: 0 } },
        tasks: [
          { q: 'n', min: 2, max: 2, text: 'Ajusta el antirrebote para detectar exactamente las 2 pulsaciones', done: 'Aquí vale de 8 a 58 ms. En la práctica se usan 20–50 ms.', hint: 'Más largo que los rebotes, pero no tanto como para tragarse la siguiente pulsación.' },
          { q: 'n', min: 0, max: 1, text: 'Ahora pásate: pon tanto tiempo que se pierda una pulsación', done: 'Si el antirrebote dura más que el hueco entre pulsaciones, te comes las rápidas.', hint: 'Sube el tiempo por encima de 60 ms.' }
        ] },
      I('<b>Antirrebote por software</b>: cuando aceptas un cambio, apuntas la hora con millis() y <b>ignoras</b> los cambios que lleguen durante 20–50 ms. Sin delay(): el resto del programa sigue funcionando.', { code: 'if (lectura != antes && millis() - tCambio > 30) {\n  tCambio = millis();   // acepto el cambio y apunto la hora\n  antes = lectura;\n  // … aquí, lo que haya que hacer\n}' }),
      I('Dos formas de usar un botón:\n· Por <b>nivel</b>: «mientras esté pulsado, haz X» (un acelerador).\n· Por <b>flanco</b>: «cuando se acaba de pulsar, haz X una vez» (encender y apagar, contar, cambiar de pantalla).\nPara el flanco hay que <b>recordar la lectura anterior</b> y compararla con la actual.', { svg: SV_EDGE }),
      Q('¿Qué hace este programa si mantienes el botón pulsado 2 segundos?', ['Cambia el LED cientos de veces: al soltar queda al azar', 'Lo cambia una sola vez', 'Lo deja encendido 2 s', 'Nada'], 'Mira el nivel, no el flanco: invierte el LED en cada vuelta de loop() mientras sigue pulsado.', { c: 'mc_edge', h: '¿Cuántas vueltas da loop() en 2 s? ¿En cuántas se cumple el if?', code: 'void loop() {\n  if (digitalRead(2) == LOW) {\n    led = !led;\n    digitalWrite(13, led);\n  }\n}' }),
      { t: 'steps', text: 'El interruptor de un solo botón: flanco con antirrebote, sin bloquear. Así funciona, línea a línea:', code: 'bool antes = HIGH;\nunsigned long tCambio = 0;\nbool led = false;\n\nvoid loop() {\n  bool ahora = digitalRead(2);\n  if (ahora != antes && millis() - tCambio > 30) {\n    tCambio = millis();\n    if (ahora == LOW) {        // flanco de bajada: se acaba de pulsar\n      led = !led;\n      digitalWrite(13, led);\n    }\n    antes = ahora;\n  }\n}', steps: ['Se lee el pin en <b>ahora</b> (con INPUT_PULLUP: suelto HIGH, pulsado LOW).', '¿Ha cambiado respecto a <b>antes</b> y han pasado más de 30 ms desde el último cambio aceptado? Si no, se ignora: es un rebote o no ha pasado nada.', 'Si sí: se apunta la hora en <b>tCambio</b>.', 'Si el cambio es a LOW, es un <b>flanco de bajada</b>: se acaba de pulsar → se invierte el LED una vez.', 'Se guarda <b>antes = ahora</b> para la próxima comparación. Al soltar habrá otro cambio (a HIGH), que se acepta pero no hace nada.'], result: 'Una pulsación = un cambio del LED, sin delay() y sin rebotes' },
      Q('Con INPUT_PULLUP, «se acaba de pulsar» es el paso de…', ['HIGH a LOW (flanco de bajada)', 'LOW a HIGH (flanco de subida)', 'LOW a LOW', 'HIGH a HIGH'], 'Suelto lee HIGH y pulsado, LOW. Al soltar hay un flanco de subida.', { c: 'mc_edge', h: '¿Qué lee el pin suelto y qué lee pulsado?' }),
      Q('En ese código, ¿para qué sirve millis() - tCambio > 30?', ['Ignora los cambios que llegan menos de 30 ms después del último aceptado: los rebotes', 'Espera 30 ms bloqueando el programa', 'Limita el brillo del LED', 'Cuenta 30 pulsaciones'], 'Sin delay(): el resto del programa sigue funcionando.', { c: 'mc_debounce', h: 'tCambio es la hora del último cambio aceptado.' }),
      Q('¿Por qué antes = ahora; va dentro del if y no fuera?', ['Para que la siguiente comparación sea con el último cambio aceptado', 'Es indiferente dónde vaya', 'Para borrar la lectura', 'Porque si no, no compila'], 'Si guardaras cada lectura cruda, los rebotes ignorados se colarían en la siguiente comparación.', { c: 'mc_debounce', h: 'Piensa qué pasaría con un rebote ignorado si se guardara igualmente.' }),
      Q('Con un antirrebote de 100 ms y dos pulsaciones separadas por 70 ms, ¿qué pasa?', ['La segunda se pierde: el programa sigue ignorando cambios cuando llega', 'Cuenta de más', 'La placa se reinicia', 'Nada: cuanto más, mejor'], 'Lo justo para tapar los rebotes, sin perder pulsaciones rápidas.', { c: 'mc_debounce', h: 'Compara el hueco entre pulsaciones con el tiempo que se ignoran cambios.' }),
      { t: 'match', q: '¿Por nivel o por flanco?', pairs: [['Pedal de un coche de juguete', 'Nivel'], ['Encender y apagar una lámpara', 'Flanco'], ['Contar personas que pasan', 'Flanco '], ['Mantener pulsado para subir el volumen', 'Nivel ']], c: 'mc_edge', h: '¿La acción dura mientras pulsas o pasa una sola vez?' },
      Q('Un contador por flanco tiene un antirrebote de 1 ms y sigue contando de más. ¿Qué cambias?', ['Subir el antirrebote a unos 20–50 ms', 'Bajarlo a 0', 'Quitar la pull-up', 'Usar delay(1)'], 'Los rebotes duran varios ms: 1 ms no los tapa.', { c: 'mc_debounce', h: '¿Cuánto duran los rebotes de un pulsador?' }),
      I('También hay antirrebote por <b>hardware</b>, como viste con los contadores: un condensador pequeño (por ejemplo, 100 nF) entre el pin y masa, junto a la pull-up, forma un RC que suaviza los rebotes, y un disparador Schmitt deja la señal limpia. Por software sale gratis, así que es lo más habitual.', { svg: `<svg viewBox="0 0 300 110" class="viz"><text x="40" y="16" class="vizsm">5 V</text><path d="M50 22V30M50 62V72H130M90 72V80M78 80H102M78 86H102M90 86V96M82 96H98M50 72V80M50 92V100M42 100H58" ${st}/><g transform="translate(50 46) rotate(90)">${Widgets.H.resBody()}</g><path d="M40 90L60 82" stroke="currentColor" stroke-width="3"/><text x="104" y="86" class="vizsm">100 nF</text><path d="M130 56V88L160 72Z" fill="none" stroke="currentColor" stroke-width="2"/><text x="132" y="104" class="vizsm">Schmitt</text><path d="M160 72H200V40H220V72H290" fill="none" stroke="var(--ok)" stroke-width="2.5"/><text x="200" y="100" class="vizsm">señal limpia</text></svg>` }),
      I('<b>Resumen</b>\n· Los pulsadores <b>rebotan</b> unos ms: ignora los cambios 20–50 ms tras aceptar uno.\n· <b>Nivel</b>: mientras esté pulsado. <b>Flanco</b>: una vez al pulsar.\n· Con INPUT_PULLUP, pulsar es el flanco de <b>bajada</b> (HIGH → LOW).\n· Guarda la lectura anterior solo cuando aceptas el cambio.')
    ]),
    SIM('s7f', 'Reto: interruptor con un pulsador (ESP32)', 'Ahora con un ESP32, que trabaja a 3,3 V. Cada pulsación del botón del GPIO4 enciende o apaga el LED del GPIO23, y se queda así al soltar: flanco con antirrebote.', { arduino: 'mc_toggle', board: 'esp32', parts: ['push', 'res', 'led'], code: true, hint: 'Pulsador entre D4 y GND. D23 → 220 Ω → ánodo; cátodo a GND. Con 3,3 V, una de 470 Ω deja el LED muy tenue. Pulsa, suelta y vuelve a pulsar.' }, 'mc_toggle'),
    /* n18 · Enseña: varias tareas con su instante e intervalo, nada bloquea, desbordamiento con resta sin signo, antes += intervalo.
       Usa: n7, n17. */
    L('n18', 'Varias tareas a la vez', 'timer', ['mc_tasks', 'mc_elapsed', 'mc_timecount'], [
      Q('Un programa debe hacer parpadear un LED cada 500 ms y leer un sensor cada 2 s. Si las dos cosas usan delay(), ¿qué crees que pasa?', ['Los ritmos se mezclan: cada delay() retrasa a la otra tarea', 'Funciona perfecto', 'La placa elige una de las dos', 'Se ejecutan en paralelo'], 'Mientras una espera, la otra no puede hacer nada. Vamos a arreglarlo.', { predict: true, c: 'mc_tasks', h: 'Durante un delay() de una tarea, ¿quién atiende a la otra?' }),
      I('Un microcontrolador sencillo hace una sola cosa cada vez, pero muy deprisa. El truco para que parezca que hace varias: que <b>ninguna tarea bloquee</b>. loop() pasa por todas en cada vuelta; cada una mira el reloj, hace su parte si le toca y devuelve el control enseguida.', { svg: `<svg viewBox="0 0 300 130" class="viz"><circle cx="150" cy="66" r="44" fill="none" stroke="var(--line)" stroke-width="2"/><path d="M150 22A44 44 0 0 1 194 66" fill="none" stroke="var(--led)" stroke-width="4" class="a-spin" style="transform-origin:150px 66px"/>${[['LED', 150, 14], ['Sensor', 232, 70], ['Botón', 150, 126], ['Serie', 68, 70]].map(([s, x, y]) => `<rect x="${x - 30}" y="${y - 12}" width="60" height="22" rx="5" fill="var(--board)"/><text x="${x}" y="${y + 3}" text-anchor="middle" class="vizsm" style="fill:#E8EDF5">${s}</text>`).join('')}<text x="150" y="70" text-anchor="middle" class="vizlab">loop()</text></svg>` }),
      I('Patrón: cada tarea tiene <b>su propia variable</b> con el instante de la última vez y su propio intervalo.', { code: 'unsigned long tLed = 0, tSensor = 0;\nbool led = false;\n\nvoid loop() {\n  unsigned long ahora = millis();\n  if (ahora - tLed >= 500) {       // tarea 1: cada 500 ms\n    tLed = ahora;\n    led = !led;\n    digitalWrite(13, led);\n  }\n  if (ahora - tSensor >= 2000) {   // tarea 2: cada 2 s\n    tSensor = ahora;\n    Serial.println(analogRead(A0));\n  }\n  // tarea 3: leer el botón, en cada vuelta\n}' }),
      { t: 'explore', text: 'Dos tareas con millis() en 3 s. También puedes simular un loop() lento (un delay() o trabajo que tarda) y cambiar cómo se actualiza el instante.', viz: 'millisTimeline', params: { iA: { label: 'Intervalo de la tarea A', val: 500, min: 100, max: 1000, step: 50, unit: 'ms', dec: 0 }, iB: { label: 'Intervalo de la tarea B (0: no hay)', val: 0, min: 0, max: 2000, step: 250, unit: 'ms', dec: 0 }, blk: { label: 'Tiempo parado en cada vuelta', val: 0, min: 0, max: 600, step: 10, unit: 'ms', dec: 0 }, mode: { label: 'Actualizar (0: antes = ahora · 1: antes += intervalo)', val: 0, list: [0, 1], dec: 0 } },
        tasks: [
          { q: 'ab', min: 1, max: 1, text: 'Tarea A cada 250 ms y tarea B cada 1000 ms, sin bloqueos', done: '12 y 3 ejecuciones: cada una lleva su ritmo y ninguna estorba a la otra.', hint: 'A a 250, B a 1000 y el tiempo parado a 0.' },
          { q: 'drift', min: 1, max: 1, text: 'Simula 30 ms parados en cada vuelta (A a 250 ms)', done: 'Con antes = ahora, cada retraso se suma al siguiente: el ritmo se estira y en 3 s hay menos ejecuciones.', hint: 'Sube el tiempo parado hasta 30 ms.' },
          { q: 'fix', min: 1, max: 1, text: 'Cambia a antes += intervalo', done: 'Los retrasos ya no se acumulan: cada ejecución llega un poco tarde, pero el ritmo medio se mantiene.', hint: 'Pon «Actualizar» en 1.' }
        ] },
      { t: 'steps', text: 'Una tarea va cada 250 ms y otra cada 1000 ms. ¿Cuántas ejecuciones hay en total en 10 s?', steps: ['Pasa a ms: 10 s = 10 000 ms.', 'Tarea rápida: 10 000 / 250 = <b>40</b>.', 'Tarea lenta: 10 000 / 1000 = <b>10</b>.', 'Total: 40 + 10 = <b>50</b>. Y entre ejecución y ejecución, loop() sigue libre para lo demás.'], result: '50 ejecuciones' },
      Q('Con el programa del patrón, ¿cuántas veces se imprime el sensor en un minuto?', ['30', '120', '60', '2'], '60 000 ms / 2000 ms = 30.', { c: 'mc_timecount', h: 'Pasa el minuto a ms y divide entre el intervalo de esa tarea.' }),
      G('mc2Count'),
      Q('¿Cuánto tarda en reaccionar al botón (tarea 3) si ninguna tarea usa delay()?', ['Casi nada: loop() da miles de vueltas por segundo', 'Hasta 2 s', 'Hasta 500 ms', 'Nunca reacciona'], 'Cada vuelta de loop() es rapidísima porque ninguna tarea se queda esperando.', { c: 'mc_tasks', h: '¿Cuánto dura una vuelta de loop() si nadie espera?' }),
      Q('¿Dónde está el fallo?', ['delay(1000) bloquea: el LED ya no puede cambiar cada 200 ms', 'tLed debería ser int', 'millis() no puede usarse dos veces', 'Ninguno'], 'Una sola tarea con delay() estropea el ritmo de todas las demás.', { c: 'mc_tasks', h: 'Busca lo que hace esperar al programa.', code: 'void loop() {\n  if (millis() - tLed >= 200) {\n    tLed = millis();\n    led = !led;\n    digitalWrite(13, led);\n  }\n  Serial.println(analogRead(A0));\n  delay(1000);\n}' }),
      I('¿Y cuando millis() llegue a su máximo y vuelva a 0, a los 49,7 días? Si comparas como <b>ahora − antes >= intervalo</b> con unsigned long, la resta sin signo también da la vuelta y el resultado sigue siendo correcto. Escrito como ahora >= antes + intervalo, falla justo en ese momento.', { svg: SV_WRAPSUB }),
      Q('¿Qué comparación sigue funcionando cuando millis() se desborda?', ['millis() - antes >= 1000', 'millis() >= antes + 1000', 'millis() > 1000', 'millis() == antes + 1000'], 'La resta de unsigned long da la diferencia correcta aunque el contador haya pasado por cero.', { c: 'mc_elapsed', h: 'Busca la forma «ahora menos antes».' }),
      Q('¿Qué problema tiene if (millis() == antes + 1000)?', ['Si una vuelta de loop() tarda más de 1 ms, se salta ese milisegundo exacto y no se cumple nunca', 'Ninguno', 'No compila', 'Gasta más RAM'], 'Usa siempre >=.', { c: 'mc_elapsed', h: '¿Qué pasa si justo en ese milisegundo el programa estaba haciendo otra cosa?' }),
      I('Si necesitas un ritmo exacto a largo plazo (un reloj, un registro cada minuto), avanza el instante con <b>tLed += 500</b> en vez de tLed = ahora: así los pequeños retrasos de cada vuelta no se acumulan.', { svg: SV_DRIFT }),
      Nm('Tres tareas con millis(): cada 100 ms, cada 500 ms y cada 2000 ms. ¿Cuántas ejecuciones hay en total en 1 minuto?', 750, 'veces', '60 000 / 100 = 600; 60 000 / 500 = 120; 60 000 / 2000 = 30. Total: 750.', { c: 'mc_timecount', h: 'Cuenta cada tarea por separado y suma.' }),
      Q('Quieres que el LED parpadee cada 100 ms solo mientras el botón esté pulsado, y que se apague al soltarlo. ¿Qué estructura?', ['Un if que mira el botón en cada vuelta y, dentro, la tarea de parpadeo con millis()', 'Un while que espera al botón', 'Un for con delay(100)', 'Muchos delay() cortos'], 'Comprobar y seguir, nunca esperar.', { c: 'mc_tasks', h: 'Nada de esperar: en cada vuelta, mira y decide.' }),
      I('<b>Resumen</b>\n· Varias tareas: cada una con <b>su instante y su intervalo</b>; ninguna bloquea.\n· <b>ahora − antes >= intervalo</b> sigue funcionando cuando millis() vuelve a 0.\n· Nunca ==: si te saltas el milisegundo exacto, no se cumple jamás.\n· <b>antes += intervalo</b> para que los retrasos no se acumulen.')
    ]),
    SIM('s7g', 'Reto: dos ritmos a la vez (ESP32)', 'Dos tareas con millis() y sin delay(): el LED del GPIO25 cambia cada 250 ms y el del GPIO26, cada segundo. Conéctalos y comprueba que cada uno lleva su ritmo.', { arduino: 'mc_multi', board: 'esp32', parts: ['res', 'led'], code: true, hint: 'D25 → 220 Ω → LED → GND, y D26 → 220 Ω → otro LED → GND. Déjalo correr unos segundos.' }, 'mc_multi'),
    /* n19 · Enseña: estados y transiciones, diagrama, enum, switch, case, break, t0 al entrar en un estado.
       Usa: n18, n12, n13, n17. */
    L('n19', 'Máquinas de estados', 'code', ['mc_fsm', 'mc_switch', 'mc_elapsed', 'mc_millis'], [
      Q('Una lavadora llena, lava, aclara y centrifuga. Si pulsas «pausa» y luego «seguir», ¿de qué depende lo que haga?', ['De en qué fase estaba', 'De nada: siempre empieza de cero', 'De la hora', 'Del agua que quede'], 'La lavadora recuerda en qué fase está: es una máquina de estados.', { predict: true, c: 'mc_fsm', h: 'Piensa en qué tiene que recordar la lavadora para seguir.' }),
      I('Muchos aparatos se comportan según <b>en qué fase están</b>. Eso es una <b>máquina de estados</b>: una lista de <b>estados</b> y unas reglas, las <b>transiciones</b>, que dicen cuándo se pasa de uno a otro. Las transiciones pueden ser un <b>evento</b> (pulsan un botón) o un <b>tiempo</b> (han pasado 2 s).', { svg: `<svg viewBox="0 0 300 100" class="viz">${[['LLENAR', 40], ['LAVAR', 115], ['ACLARAR', 190], ['CENTRIF.', 262]].map(([s, x], i) => `<circle cx="${x}" cy="44" r="30" fill="${i === 1 ? 'var(--led)' : 'none'}" stroke="var(--ice)" stroke-width="2.5" ${i === 1 ? 'class="a-pulse"' : ''}/><text x="${x}" y="48" text-anchor="middle" class="vizsm" style="${i === 1 ? 'fill:#1B1300' : ''}">${s}</text>${i < 3 ? `<path d="M${x + 31} 44H${x + 44}" stroke="currentColor" stroke-width="2"/><path d="M${x + 44} 44l-6 -4v8z" fill="currentColor"/>` : ''}`).join('')}<text x="10" y="94" class="vizsm">Un solo estado activo cada vez; las flechas, cuándo se cambia</text></svg>` }),
      { t: 'explore', text: 'Semáforo con pulsador de peatón. Elige cuándo pulsa el peatón y avanza el tiempo: mira qué estado está activo.', viz: 'fsm', params: { tp: { label: 'El peatón pulsa en (0: nadie)', val: 0, min: 0, max: 8, step: 0.5, unit: 's', dec: 1 }, t: { label: 'Tiempo', val: 0, min: 0, max: 12, step: 0.1, unit: 's', dec: 1 } },
        tasks: [
          { q: 'amb', min: 1, max: 1, text: 'Haz que el peatón pulse y busca un instante en ÁMBAR', done: 'Pulsar provoca la transición VERDE → ÁMBAR: un evento.', hint: 'Pon la pulsación a los 2 s y avanza el tiempo un poco más.' },
          { q: 'red', min: 1, max: 1, text: 'Avanza hasta el ROJO', done: 'Tras 2 s en ÁMBAR pasa a ROJO: esta transición la provoca el tiempo.', hint: 'Dos segundos después de la pulsación.' },
          { q: 'back', min: 1, max: 1, text: 'Sigue hasta que vuelva a VERDE', done: 'Tras 3 s en ROJO vuelve al estado inicial y espera otra pulsación.', hint: 'Cinco segundos después de la pulsación.' }
        ] },
      I('En C++ los estados se nombran con <b>enum</b>: una lista de nombres que el compilador convierte en números (REPOSO = 0, REGANDO = 1…). Así el código se lee solo.', { code: 'enum Estado { REPOSO, REGANDO, ESPERA };\nEstado estado = REPOSO;        // estado inicial\nunsigned long t0 = 0;          // cuándo se entró en el estado' }),
      I('<b>switch (estado)</b> salta directamente al <b>case</b> del estado actual. Cada case acaba en <b>break</b>, que sale del switch. En cada vuelta de loop() solo se ejecuta el trozo del estado activo; para cambiar de estado, basta con asignar uno nuevo.', { code: 'void loop() {\n  switch (estado) {\n    case REPOSO:\n      if (sueloSeco()) { abrirValvula(); t0 = millis(); estado = REGANDO; }\n      break;\n    case REGANDO:\n      if (millis() - t0 >= 10000) { cerrarValvula(); t0 = millis(); estado = ESPERA; }\n      break;\n    case ESPERA:\n      if (millis() - t0 >= 60000) estado = REPOSO;\n      break;\n  }\n}', more: 'sueloSeco(), abrirValvula() y cerrarValvula() serían funciones tuyas, como las que ya sabes escribir. Fíjate en que t0 = millis() se guarda justo al cambiar de estado: así millis() − t0 dice cuánto lleva en el estado actual.' }),
      { t: 'steps', text: 'El semáforo con peatón escrito como máquina de estados. Síguelo cuando el peatón pulsa:', code: 'switch (estado) {\n  case VERDE:\n    if (digitalRead(BOTON) == LOW) { t0 = millis(); estado = AMBAR; }\n    break;\n  case AMBAR:\n    if (millis() - t0 >= 2000) { t0 = millis(); estado = ROJO; }\n    break;\n  case ROJO:\n    if (millis() - t0 >= 3000) estado = VERDE;\n    break;\n}', steps: ['Estado <b>VERDE</b>: en cada vuelta mira el botón. Nadie pulsa → no cambia nada.', 'El peatón pulsa: se apunta <b>t0</b> y el estado pasa a <b>AMBAR</b>.', 'En las vueltas siguientes se ejecuta case AMBAR: cuando millis() − t0 llega a 2000, nuevo t0 y estado <b>ROJO</b>.', 'En ROJO, a los 3000 ms vuelve a <b>VERDE</b> y espera otra pulsación.', 'Nada bloquea: entre medias, loop() puede atender más cosas.'], result: 'Cada estado sabe qué mira y a cuál pasa' },
      Q('En el riego, con el suelo siempre seco, ¿cuánto tiempo pasa entre el inicio de un riego y el del siguiente?', ['Unos 70 s', '10 s', '60 s', '0 s'], '10 s regando más 60 s de espera antes de volver a mirar el suelo.', { c: 'mc_fsm', h: 'Suma lo que dura cada estado antes de volver a REPOSO.' }),
      Q('¿Qué pasa si olvidas el break de case REPOSO y se cumple su if?', ['También se ejecuta el código de case REGANDO en la misma vuelta', 'No compila', 'Nada', 'Se reinicia la placa'], 'Sin break, el switch «se cae» al case siguiente. A veces se hace a propósito; casi siempre es un fallo.', { c: 'mc_switch', h: '¿Qué hace break dentro de un switch?' }),
      { t: 'order', q: 'Ordena los estados de un microondas sencillo.', items: ['REPOSO: puerta cerrada y nada elegido', 'PROGRAMANDO: eliges el tiempo', 'CALENTANDO: cuenta atrás', 'AVISO: pita y vuelve a reposo'], e: 'Cada estado sabe a cuál pasa y cuándo.', c: 'mc_fsm', h: 'Sigue lo que haces tú al usarlo, de principio a fin.' },
      Q('Semáforo con peatón: VERDE → (pulsan) → ÁMBAR → (2 s) → ROJO → (?) → VERDE. ¿Qué provoca la última transición?', ['Que pase el tiempo del paso de peatones', 'Que vuelvan a pulsar', 'Nada: ROJO es el final', 'Que se apague la placa'], 'Las transiciones pueden ser eventos (pulsar) o tiempos.', { c: 'mc_fsm', h: 'Recuerda lo que has visto al mover el tiempo en el diagrama.' }),
      Q('Estado inicial APAGADO. ¿Qué imprime la primera llamada a alPulsar()?', ['ENCENDIDO', 'APAGADO', 'Nada', 'Las dos palabras'], 'Mira el estado actual (APAGADO), pasa al otro y lo anuncia.', { c: 'mc_fsm', h: 'Sigue el if con el estado que tiene al empezar.', code: 'enum Modo { APAGADO, ENCENDIDO };\nModo modo = APAGADO;\n\nvoid alPulsar() {\n  if (modo == APAGADO) {\n    modo = ENCENDIDO;\n    Serial.println("ENCENDIDO");\n  } else {\n    modo = APAGADO;\n    Serial.println("APAGADO");\n  }\n}' }),
      Q('Un temporizador de cocina con botón de parar. ¿Dónde está el fallo?', ['delay(5000) bloquea: durante esos 5 s el botón de parar no responde', 'digitalWrite no puede ir dentro de un switch', 'Falta un break en CONTANDO', 'duracion debería ser byte'], 'Mide el tiempo del aviso con millis() en el propio estado SONANDO.', { c: 'mc_millis', h: 'Busca lo que deja al programa sin mirar el botón.', code: 'case CONTANDO:\n  if (millis() - t0 >= duracion) estado = SONANDO;\n  break;\ncase SONANDO:\n  digitalWrite(ZUMBADOR, HIGH);\n  delay(5000);\n  digitalWrite(ZUMBADOR, LOW);\n  estado = REPOSO;\n  break;' }),
      { t: 'match', q: 'Une cada estado de un ascensor con lo que lo hace salir de él.', pairs: [['PARADO', 'Alguien llama desde otra planta'], ['SUBIENDO', 'El sensor detecta la planta destino'], ['PUERTAS_ABIERTAS', 'Pasan 5 s sin nadie en la puerta']], c: 'mc_fsm', h: 'Piensa en qué espera cada estado para terminar.' },
      Q('¿Para qué guardar t0 = millis() justo al cambiar de estado?', ['Para saber cuánto tiempo lleva en el estado actual', 'Para gastar menos energía', 'Porque switch lo exige', 'Para poner millis() a cero'], 'millis() − t0 es el tiempo dentro del estado.', { c: 'mc_elapsed', h: '¿Qué te dice millis() − t0?' }),
      I('<b>Resumen</b>\n· Máquina de estados: <b>estados</b> + <b>transiciones</b> (por evento o por tiempo).\n· <b>enum</b> nombra los estados; <b>switch/case</b> ejecuta solo el estado activo; <b>break</b> sale del switch.\n· Guarda <b>t0 = millis()</b> al entrar en un estado para medir cuánto lleva.\n· Dibuja el diagrama antes de programar.')
    ]),
    SIM('s7h', 'Reto: semáforo con peatón (ESP32)', 'Una máquina de estados: verde fijo hasta que un peatón pulsa; entonces ámbar 2 s, rojo 3 s y vuelta al verde. Monta las tres luces y el pulsador.', { arduino: 'mc_fsm', board: 'esp32', parts: ['push', 'res', 'led'], code: true, hint: 'Rojo en D25, ámbar en D26 y verde en D27, cada uno con 220 Ω a GND. Pulsador entre D4 y GND. Espera unos 5 s sin pulsar y luego pulsa.' }, 'mc_fsm'),
    /* n20 · Enseña: interrupción e ISR, attachInterrupt y modos, pines 2 y 3, volatile, ISR corta, noInterrupts para variables multibyte, rebotes.
       Usa: n17, n18, n10, n13. */
    L('n20', 'Interrupciones', 'bolt', ['mc_isr', 'mc_isrrules', 'mc_debounce'], [
      Q('Un sensor da pulsos de 1 ms y tu loop() tarda 50 ms en dar una vuelta (lee sensores, imprime…). Si miras el pin una vez por vuelta, ¿cuántos pulsos crees que verás?', ['Muy pocos: la mayoría ocurren mientras haces otra cosa', 'Todos', 'Exactamente la mitad', 'Ninguno, nunca'], 'Un pulso de 1 ms tiene que caer justo en el instante en que miras: casi nunca pasa.', { predict: true, c: 'mc_isr', h: 'Compara lo que dura un pulso con lo que tardas en volver a mirar.' }),
      I('Una <b>interrupción</b> es un aviso del hardware: el procesador deja lo que esté haciendo, ejecuta una función corta (la <b>ISR</b>, rutina de servicio) y vuelve justo donde estaba. Como el timbre de casa: no miras por la ventana cada minuto; suena y vas.', { svg: SV_ISR }),
      { t: 'explore', text: 'Un segundo de pulsos de un sensor. loop() mira el pin una vez por vuelta (sondeo); la interrupción salta sola en cada flanco.', viz: 'isrTimeline', params: { f: { label: 'Pulsos por segundo', val: 10, min: 5, max: 40, step: 1, dec: 0 }, w: { label: 'Duración de cada pulso', val: 5, min: 1, max: 20, step: 1, unit: 'ms', dec: 0 }, L: { label: 'Duración de una vuelta de loop()', val: 1, min: 1, max: 200, step: 1, unit: 'ms', dec: 0 } },
        tasks: [
          { q: 'lost', min: 1, max: 999, text: 'Haz más lento loop() hasta que el sondeo pierda pulsos', done: 'Si loop() tarda más que un pulso, algunos pasan entre dos miradas.', hint: 'Sube la duración de una vuelta de loop().' },
          { q: 'lostPct', min: 50, max: 100, text: 'Consigue que el sondeo pierda más de la mitad', done: 'La interrupción, en cambio, los ha contado todos.', hint: 'Pulsos más cortos o un loop() aún más lento.' },
          { q: 'ok2', min: 1, max: 1, text: 'Con pulsos de 2 ms, consigue que el sondeo no pierda ninguno', done: 'Hace falta que loop() mire el pin más a menudo de lo que dura un pulso: difícil si loop() hace muchas cosas.', hint: 'Pulso de 2 ms y vueltas de loop() de 1 ms.' }
        ] },
      I('En la Uno y la Nano, las interrupciones externas están en los pines <b>2 y 3</b>. En el ESP32, casi cualquier GPIO sirve. <b>attachInterrupt</b> une un pin, una función y un modo.', { code: 'volatile unsigned long pulsos = 0;\n\nvoid contar() {        // la ISR: corta, sin parámetros, sin return\n  pulsos++;\n}\n\nvoid setup() {\n  pinMode(2, INPUT_PULLUP);\n  attachInterrupt(digitalPinToInterrupt(2), contar, FALLING);\n}' }),
      { t: 'pin', q: 'En una Uno, ¿qué pin elegirías para un sensor de pulsos con attachInterrupt? (elige uno)', a: ['D2', 'D3'], e: 'INT0 está en el 2 e INT1 en el 3. Los demás pines tienen interrupciones por cambio de pin, que se configuran de otra forma.', c: 'mc_isr', h: 'Solo dos pines de la Uno tienen interrupción externa propia.' },
      { t: 'match', q: 'Une cada modo de attachInterrupt.', pairs: [['RISING', 'Al pasar de LOW a HIGH'], ['FALLING', 'Al pasar de HIGH a LOW'], ['CHANGE', 'En cualquier cambio'], ['LOW', 'Mientras esté en LOW']], c: 'mc_isr', h: 'RISING sube, FALLING cae.' },
      I('<b>volatile</b> avisa al compilador de que la variable puede cambiar «por sorpresa» en cualquier momento. Sin él, el compilador puede guardar una copia en un registro del procesador y loop() no vería nunca el cambio.', { svg: SV_VOLAT }),
      Q('¿Por qué pulsos lleva volatile?', ['Porque la cambia la ISR y la lee loop(): el compilador no debe dar su valor por sabido', 'Para que ocupe menos', 'Para que sea más rápida', 'Porque es unsigned long'], 'Toda variable compartida entre una ISR y el resto del programa debe ser volatile.', { c: 'mc_isrrules', h: '¿Quién cambia esa variable y quién la lee?' }),
      I('Reglas de una buena ISR:\n· <b>Corta</b>: apunta lo que ha pasado y sal. El trabajo pesado, en loop().\n· Sin <b>delay()</b> ni <b>Serial.print</b>: se apoyan en otras interrupciones, que están en pausa mientras corre la tuya.\n· Dentro de la ISR, millis() no avanza.', { svg: `<svg viewBox="0 0 300 80" class="viz"><rect x="10" y="14" width="130" height="40" rx="8" fill="var(--ok)" opacity=".3"/><text x="75" y="38" text-anchor="middle" class="vizlab">pulsos++;</text><rect x="160" y="14" width="130" height="40" rx="8" fill="var(--err)" opacity=".25"/><text x="225" y="31" text-anchor="middle" class="vizsm" style="text-decoration:line-through">delay(50);</text><text x="225" y="47" text-anchor="middle" class="vizsm" style="text-decoration:line-through">Serial.print(…);</text><text x="75" y="72" text-anchor="middle" class="vizsm">en la ISR, sí</text><text x="225" y="72" text-anchor="middle" class="vizsm">en la ISR, no</text></svg>` }),
      Q('¿Dónde está el fallo?', ['La ISR imprime por Serial y espera 50 ms: debe ser cortísima', 'Falta volatile en el nombre de la función', 'FALLING no existe', 'Ninguno'], 'Anota el evento en una variable volatile y deja que loop() imprima.', { c: 'mc_isrrules', h: 'Repasa las reglas de una ISR.', code: 'void alPulsar() {     // ISR del pin 2\n  Serial.println("¡Pulsado!");\n  delay(50);\n}' }),
      I('Un detalle más: en la Uno, un unsigned long son 4 bytes y leerlo son 4 pasos. Si la ISR lo cambia justo a mitad, lees un valor mezclado. Copia la variable con las interrupciones en pausa un instante.', { code: 'noInterrupts();\nunsigned long copia = pulsos;\ninterrupts();\nSerial.println(copia);' }),
      { t: 'steps', text: 'Un anemómetro da 2 pulsos por vuelta. La ISR cuenta pulsos y loop() calcula la velocidad cada segundo. En un segundo se han contado 30.', code: 'if (millis() - tCalc >= 1000) {\n  tCalc = millis();\n  noInterrupts();\n  unsigned long n = pulsos;\n  pulsos = 0;\n  interrupts();\n  Serial.println(n / 2.0);   // vueltas por segundo\n}', steps: ['Cada segundo (millis()), loop() copia el contador con las interrupciones en pausa y lo pone a cero.', 'n = 30 pulsos en 1 s.', 'Vueltas = pulsos / pulsos por vuelta = 30 / 2 = <b>15 vueltas/s</b>.', 'Por minuto: 15 × 60 = <b>900 rpm</b>.'], result: '15 vueltas por segundo' },
      G('mc2Isr'),
      Q('Un pulsador con rebotes, conectado a una interrupción FALLING…', ['Puede disparar la ISR varias veces por pulsación: también necesita antirrebote', 'Solo la dispara una vez', 'No la dispara nunca', 'Reinicia la placa'], 'Para el hardware, cada rebote es un flanco real.', { c: 'mc_debounce', h: '¿Cuántos flancos de bajada tiene una pulsación con rebotes?' }),
      Q('¿Cuándo compensa una interrupción frente a leer el pin en loop()?', ['Con pulsos muy cortos o que no te puedes perder, como los de un encoder', 'Siempre, para cualquier botón', 'Para encender un LED', 'Para poder usar delay()'], 'Si loop() es ágil, un botón normal se lee bien sin interrupciones. Un pulso de microsegundos, no.', { c: 'mc_isr', h: 'Recuerda lo que pasaba en el dibujo con pulsos cortos.' }),
      I('<b>Resumen</b>\n· Una interrupción corta a loop(), ejecuta la <b>ISR</b> y vuelve. No pierde pulsos cortos.\n· Uno: pines <b>2 y 3</b>; attachInterrupt(digitalPinToInterrupt(pin), funcion, modo).\n· Variables compartidas: <b>volatile</b>. ISR <b>cortísima</b>: sin delay() ni Serial.\n· Copia las variables de varios bytes entre noInterrupts() e interrupts().')
    ]),
    /* n21 · Enseña: Flash, SRAM y EEPROM del ATmega328P, pila, RAM agotada sin aviso, F() y PROGMEM, EEPROM (100 000 escrituras, put/get), 32 bits.
       Usa: n1, n10, n14, n16. */
    L('n21', 'Memoria: Flash, RAM y EEPROM', 'memory', ['mc_memwhere', 'mc_ram', 'mc_eeprom'], [
      Q('Guardas el récord de un juego en una variable. Desenchufas la placa y la vuelves a enchufar. ¿Qué crees que pasa con el récord?', ['Se pierde: las variables viven en una memoria que se borra al apagar', 'Se conserva siempre', 'Se duplica', 'Depende del cable USB'], 'Las variables están en la SRAM, que se borra sin corriente. Para conservarlo hay otra memoria.', { predict: true, c: 'mc_memwhere', h: 'Piensa en dónde viven las variables mientras el programa funciona.' }),
      I('El ATmega328P de la Uno tiene <b>tres memorias</b>:\n· <b>Flash</b> (32 KB): el programa. No se borra al quitar la corriente.\n· <b>SRAM</b> (2 KB): las variables mientras funciona. Se pierde al apagar.\n· <b>EEPROM</b> (1 KB): datos que quieres conservar, como un récord o una calibración.', { svg: SV_MEM }),
      { t: 'match', q: '¿Dónde se guarda cada cosa?', pairs: [['El código de loop()', 'Flash'], ['Un contador que cambia cada segundo', 'SRAM'], ['La puntuación máxima de un juego', 'EEPROM'], ['Un texto constante escrito con F()', 'Flash ']], c: 'mc_memwhere', h: '¿Cambia mientras funciona? ¿Debe sobrevivir a un apagado?' },
      { t: 'explore', text: 'La SRAM de 2 KB de la Uno. Lo que no ocupan las variables queda para la pila (variables locales y llamadas a funciones), que necesita unos 300 bytes en este programa.', viz: 'ramBar', params: { glob: { label: 'Variables globales', val: 700, min: 100, max: 1500, step: 50, unit: 'B', dec: 0 }, buf: { label: 'Buffers (arrays)', val: 200, min: 0, max: 800, step: 50, unit: 'B', dec: 0 }, txt: { label: 'Textos entre comillas', val: 400, min: 0, max: 600, step: 50, unit: 'B', dec: 0 }, F: { label: 'Textos con F() (0 no · 1 sí)', val: 0, list: [0, 1], dec: 0 } },
        tasks: [
          { q: 'pct', min: 90, max: 1000, text: 'Llena la RAM por encima del 90 %', done: 'Queda muy poco para la pila: el programa compila, pero puede colgarse en marcha.', hint: 'Sube las variables globales o los buffers.' },
          { q: 'freeF', min: 1, max: 1, text: 'Usa F() y deja al menos 500 bytes libres', done: 'Con F(), los textos se quedan en la Flash y no ocupan RAM.', hint: 'Pon F en 1 y baja lo que haga falta.' },
          { q: 'big', min: 1, max: 1, text: 'Haz sitio para un buffer de 600 bytes dejando 300 para la pila', done: 'Hay que repartir: cada byte de buffer sale de algún sitio.', hint: 'Buffer a 600, textos con F() y menos globales.' }
        ] },
      I('Cuando se acaba la RAM <b>no hay mensaje de error</b>: la pila (variables locales y direcciones de vuelta de las funciones) crece y pisa otras variables. Síntomas: reinicios, valores absurdos y cuelgues que pasan «a veces». El IDE avisa al compilar si la memoria dinámica pasa del 75 %.', { svg: `<svg viewBox="0 0 300 100" class="viz"><rect x="20" y="14" width="260" height="30" rx="6" fill="var(--line)"/><rect x="20" y="14" width="190" height="30" rx="6" fill="var(--ice)" opacity=".8"/><rect x="190" y="14" width="90" height="30" rx="6" fill="var(--err)" opacity=".5" class="a-fade"/><text x="100" y="34" text-anchor="middle" class="vizsm">variables</text><text x="250" y="34" text-anchor="middle" class="vizsm">← pila</text><text x="20" y="66" class="vizlab" style="fill:var(--err)">Si se tocan, la pila pisa variables</text><text x="20" y="88" class="vizsm">Y nadie te avisa: el programa sigue con datos corruptos</text></svg>` }),
      Q('Al compilar, el IDE dice que las variables globales usan 1890 bytes (92 %) de la memoria dinámica. ¿Qué significa?', ['Quedan unos 150 bytes de RAM para la pila y las variables locales: riesgo de cuelgues', 'El programa ocupa casi toda la Flash', 'Todo va bien', 'Hay que borrar la EEPROM'], 'La memoria dinámica es la SRAM. Las funciones necesitan RAM libre mientras se ejecutan.', { c: 'mc_ram', h: '«Memoria dinámica» es la SRAM: ¿cuánto queda de 2048?' }),
      I('Truco barato: cada texto entre comillas se copia en la RAM al arrancar. Con <b>F()</b> se queda en la Flash y se lee desde allí. Para tablas grandes y constantes (una melodía, una curva de calibración) está <b>PROGMEM</b>, que también las deja en la Flash.', { code: 'Serial.println(F("Sistema listo. Pulsa A para empezar."));\n\nconst byte curva[] PROGMEM = { 0, 3, 9, 20, 36, 56 };   // en la Flash\nbyte v = pgm_read_byte(&curva[3]);                      // se lee así' }),
      Q('¿Qué línea ahorra RAM en la Uno?', ['Serial.println(F("Error de sensor"));', 'Serial.println("Error de sensor");', 'String s = "Error de sensor"; Serial.println(s);', 'char s[] = "Error de sensor"; Serial.println(s);'], 'F() deja el texto en la Flash. Las otras tres lo copian en la RAM.', { c: 'mc_ram', h: 'Busca la que deja el texto en la memoria del programa.' }),
      Q('Este programa funciona horas y luego se cuelga. ¿Sospechoso principal?', ['Crear y destruir Strings en cada vuelta puede fragmentar la poca RAM de la Uno', 'millis() se desborda a las 2 horas', 'La EEPROM se llena', 'El LED se gasta'], 'Con 2 KB, los huecos que dejan los Strings acaban impidiendo reservar memoria. Mejor arrays de char de tamaño fijo, o imprimir los datos uno a uno.', { c: 'mc_ram', h: 'Recuerda qué pasaba con los String en placas pequeñas.', code: 'void loop() {\n  String linea = "T=" + String(leerTemp()) + " H=" + String(leerHum());\n  Serial.println(linea);\n  delay(1000);\n}' }),
      G('mc2RamBytes'),
      I('La <b>EEPROM</b> conserva los datos sin corriente, pero cada celda aguanta unas <b>100 000 escrituras</b>. Lee todo lo que quieras; escribe solo cuando cambie algo. <b>EEPROM.put()</b> y <b>EEPROM.get()</b> guardan y leen variables de cualquier tipo.', { code: '#include <EEPROM.h>\n\nunsigned int record;\n\nvoid setup() {\n  EEPROM.get(0, record);     // lee 2 bytes desde la dirección 0\n}\n\nvoid nuevoRecord(unsigned int ms) {\n  record = ms;\n  EEPROM.put(0, record);     // solo reescribe los bytes que cambian\n}', svg: SV_WEAR }),
      { t: 'steps', text: '¿Cuánto dura una celda de EEPROM si la grabas cada hora? ¿Y cada segundo?', steps: ['Cada hora: 100 000 escrituras × 1 h = <b>100 000 h</b>.', '100 000 h / 24 = 4167 días ≈ <b>11 años</b>: de sobra.', 'Cada segundo: 100 000 × 1 s = 100 000 s.', '100 000 s / 3600 ≈ <b>28 horas</b>: se gasta en poco más de un día.'], result: 'Grabar poco: horas o cambios reales, nunca en cada vuelta' },
      Q('Guardas una lectura en la misma celda en cada vuelta de loop(), unas 1000 veces por segundo. ¿Qué pasa?', ['En menos de dos minutos superas las 100 000 escrituras de esa celda', 'Nada: la EEPROM es eterna', 'Se llena y deja de grabar', 'Se borra la Flash'], '100 000 / 1000 = 100 s. Graba solo cuando haga falta.', { c: 'mc_eeprom', h: 'Divide las escrituras que aguanta entre las que haces por segundo.' }),
      G('mc2Eeprom'),
      Q('Una EEPROM sin estrenar tiene todos sus bytes a 255. ¿Qué devuelve EEPROM.get() en un unsigned int la primera vez?', ['65 535', '0', '255', 'Un error'], 'Dos bytes a 0xFF forman 0xFFFF = 65 535. Compruébalo en setup() para saber que aún no hay nada guardado.', { c: 'mc_eeprom', h: 'Un unsigned int son dos bytes: ¿qué número forman dos bytes a 0xFF?' }),
      Nm('¿Cuántos float (4 bytes cada uno) caben en la EEPROM de 1 KB (1024 bytes) de la Uno?', 256, 'float', '1024 / 4 = 256.', { c: 'mc_eeprom', h: 'Divide la capacidad entre lo que ocupa cada dato.' }),
      I('En el ESP32, la Pico o los STM32 la RAM es mucho mayor (cientos de KB) y la EEPROM se imita guardando en la Flash (en el ESP32, por ejemplo, con la librería Preferences). Las ideas son las mismas: la RAM se pierde al apagar y la memoria permanente se desgasta al escribir.', { svg: `<svg viewBox="0 0 300 80" class="viz"><rect x="10" y="20" width="16" height="30" fill="var(--led)"/><text x="18" y="66" text-anchor="middle" class="vizsm">Uno</text><text x="18" y="14" text-anchor="middle" class="vizsm">2 KB</text><rect x="60" y="20" width="230" height="30" fill="var(--ice)" opacity=".7"/><text x="175" y="66" text-anchor="middle" class="vizsm">ESP32 (modelo clásico)</text><text x="175" y="14" text-anchor="middle" class="vizsm">520 KB de RAM</text></svg>` }),
      I('<b>Resumen</b>\n· <b>Flash</b>: el programa (se conserva). <b>SRAM</b>: las variables (se borra). <b>EEPROM</b>: datos a conservar.\n· Sin RAM libre, la pila pisa variables <b>sin avisar</b>: textos con F(), tablas con PROGMEM, pocos String.\n· EEPROM: <b>100 000 escrituras</b> por celda; lee libremente, escribe solo si cambia.')
    ]),
    PRJ('p20', 'Proyecto: duelo de reflejos', 'mc_reflex')
  ] });
})();
